#!/usr/bin/env python3
"""
Backfill Tier 1 locales with the 146 keys recently added to en.json.
Translations done by Claude in-conversation, not via API.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TR = ROOT / 'public' / 'translations'

# Per-locale dotted-key → translated string.
# Placeholders {temp} {humidity} {n} {days} {count} {avg} {score} {seconds}
# {ml} {kg} {delta} {unit} {value} {tail} {label} {mins} {primary} are
# preserved verbatim.

TRANSLATIONS = {
'es': {
  'common.save': 'Guardar',
  'common.close': 'Cerrar',
  'common.cancel': 'Cancelar',
  'footer.poweredBy': 'Impulsado por',
  'footer.shotsGlobally': 'shots en todo el mundo',
  'header.home': 'Inicio',
  'hero.brewFirst': 'Saca el primero.',
  'hero.shotN': 'Hora del shot {n}.',
  'hero.dayN': 'Día {n}.',
  'hero.statusLastShot': 'Último shot: {score}. {tail}',
  'hero.statusNailed': 'Clavado.',
  'hero.statusClose': 'Cerca.',
  'hero.statusOneTweak': 'A un ajuste.',
  'hero.statusKeepGoing': 'Reinicia y otra vez.',
  'hero.statusReady': 'Pon la receta. Saca lo que cuenta.',
  'hero.statusKeepPulling': 'Sigue extrayendo. Estamos aprendiendo.',
  'hero.beanResting': 'Día {days} · descansando',
  'hero.beanDay': 'Día {days} · en la ventana',
  'hero.beanUseSoon': 'Día {days} · úsalo pronto',
  'hero.beanStale': 'Día {days} · pasado',
  'hero.beanRestingShort': 'Descansando',
  'hero.beanDayShort': 'En la ventana',
  'hero.beanUseSoonShort': 'Úsalo pronto',
  'hero.beanStaleShort': 'Pasado',
  'hero.weatherHumid': '{temp}°C · {humidity}% humedad',
  'hero.weatherDry': '{temp}°C · {humidity}% humedad',
  'hero.weatherNeutral': '{temp}°C · {humidity}% humedad',
  'hero.setupYourKit': 'Tu equipo.',
  'hero.setupKitOnFile': 'Tu equipo.',
  'hero.setupAllSetBig': 'Tu equipo.',
  'hero.setupAllSet': 'Listo cuando quieras.',
  'hero.setupAddBeans': 'Añade tus granos para ajustar.',
  'hero.setupEmpty': 'Configura tu equipo.',
  'hero.setupEmptySub': 'Cinco minutos. Mejores shots después.',
  'hero.setupSectionsToGo': 'Queda {count} sección.',
  'hero.setupSectionsToGoPlural': 'Quedan {count} secciones.',
  'hero.insightsBig': 'Cada shot, registrado.',
  'hero.insightsEmpty': 'Saca uno. Empezamos a registrar.',
  'hero.insightsEmptySub': 'Tu puntuación, tu molienda, tu deriva.',
  'hero.insightsCount': '{count} shot. Sigue sacando.',
  'hero.insightsCountPlural': '{count} shots. Sigue sacando.',
  'hero.insightsAvg': '{count} shots. Promedio de 5: {avg}.',
  'auth.providerSub': 'Un toque. Sin contraseñas que recordar.',
  'auth.continueMeta': 'Continuar con Meta',
  'auth.continueGitHub': 'Continuar con GitHub',
  'auth.privacyNote': 'Solo un apodo. Sin contraseñas que recordar.',
  'auth.nicknameTitle': 'Elige un apodo.',
  'auth.nicknameSub': 'A tu gusto. Es lo único que guardamos.',
  'auth.nicknamePlaceholder': 'p. ej., billy_bean',
  'auth.nicknameSubmit': 'Guardar',
  'brew.decreaseFine': 'Disminuir {label} (fino)',
  'brew.increaseFine': 'Aumentar {label} (fino)',
  'brew.coachPreviewBadge': 'Después de tu primer shot',
  'brew.coachPreviewDirection': 'Más grueso',
  'brew.coachPreviewReason': '3s largo. Más grueso.',
  'brew.coachPreviewCaption': 'Saca. Registra. Te decimos qué cambiar.',
  'brew.coachLine': 'Saca. Registra. Te decimos qué cambiar.',
  'brew.outcomeShort': '{delta} {unit} corto',
  'brew.outcomeLong': '{delta} {unit} largo',
  'brew.holdAtTarget': 'Mantén',
  'brew.targetWas': 'objetivo {value} {unit}',
  'brew.sectionChange': 'Cambios para el próximo shot',
  'brew.sectionHold': 'Mantén para el próximo shot',
  'brew.sectionShot': 'Este shot',
  'brew.scoreBest': 'Récord personal. Tómalo despacio.',
  'brew.scoreUp': '+{delta} sobre el anterior. Construyendo.',
  'brew.scoreDown': '-{delta} desde el anterior. Reinicia.',
  'brew.scoreSame': 'Igual que el anterior. Mano firme.',
  'brew.scoreFirst': 'El primero, hecho. Ahora aprendemos.',
  'brew.stop': 'PARAR',
  'brew.saveShot': 'GUARDAR SHOT',
  'brew.timingRunning': 'Extrayendo',
  'brew.timingStopped': 'Captura el shot',
  'brew.countdownSub': 'Prepárate',
  'brew.reasonRanFastBoth': 'Salió {seconds}s corto y {ml}ml de más. Más fino.',
  'brew.reasonRanSlowBoth': 'Salió {seconds}s largo y {ml}ml de menos. Más grueso.',
  'brew.reasonGrindAtMin': '{primary} El molinillo está en su mínimo — sube la dosis.',
  'brew.reasonGrindAtMax': '{primary} El molinillo está en su máximo — baja la dosis.',
  'brew.doseTrendUp': 'Has ido más fino 3 shots seguidos. Prueba +0,5g.',
  'brew.doseTrendDown': 'Has ido más grueso 3 shots seguidos. Prueba −0,5g.',
  'brew.doseGrindAtMin': 'El molinillo está en su mínimo. +0,5g para más resistencia.',
  'brew.doseGrindAtMax': 'El molinillo está en su máximo. −0,5g para menos resistencia.',
  'crema.thin': 'Fina',
  'crema.normal': 'Normal',
  'crema.thick': 'Espesa',
  'rating.crema': 'Crema',
  'rating.flavour': 'Sabor',
  'rating.strength': 'Intensidad',
  'rating.later': 'Valorar luego',
  'rating.save': 'Guardar valoración',
  'barista.toggleOn': 'Modo barista',
  'barista.toggleOff': 'Desactivar modo barista',
  'barista.active': 'Modo barista',
  'barista.sessionMeta': '{count} shots · {mins} min',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Brewmie, hecho a tu medida.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'Añade tu molinillo y las recomendaciones salen en tus unidades.',
  'premium.triggerTamper': 'Tampers de muelle y automáticos suman al modelo.',
  'premium.triggerBeans': 'Guarda tus granos. Cambia de bolsa, retoma donde lo dejaste.',
  'premium.triggerHistory': 'Desbloquea historial completo y tendencias.',
  'premium.triggerBenchmarks': 'Compara cada shot con tu propio récord.',
  'premium.feature1Head': 'Tu equipo',
  'premium.feature1Sub': 'Añade tu molinillo, tamper y granos. Las recomendaciones salen en tus unidades.',
  'premium.feature2Head': 'Historial completo',
  'premium.feature2Sub': 'Cada shot guardado. Exporta cuando quieras.',
  'premium.feature3Head': 'Récords personales',
  'premium.feature3Sub': 'Compara cada shot con tu propio récord.',
  'premium.ctaBrewmie': 'Solo Brewmie',
  'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Pack con Lazy Sous',
  'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev: se desbloquea desde el dev pill. No es una compra real.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'Los shots antiguos siguen guardados. Desbloquea el historial con Premium.',
  'tierLock.benchmarksLocked': 'Desbloquea Récords Personales con Premium.',
  'tierLock.genericGrinder': 'Estás con un molinillo genérico. Premium afina los cálculos al tuyo.',
  'tierLock.genericTamper': 'Estás con tamp manual. Premium suma muelle y automático.',
  'tierLock.genericBeans': 'Estás con un grano tostado medio genérico. Premium sigue tus granos.',
  'setup.profileCtaReset': 'Volver a configurar',
  'setup.bannerEyebrow': 'Asistente',
  'setup.bannerCta': 'Continuar →',
  'setup.cardLanguage': 'Idioma',
  'setup.languageLabel': 'Idioma de pantalla',
  'setup.languageMajor': 'Frecuentes',
  'setup.languageMore': 'Otros idiomas',
  'setup.languageHint': 'Brewmie detecta tu idioma automáticamente. Elige otro aquí. Las traducciones fuera de los frecuentes pueden estar incompletas y volverán al inglés.',
  'setup.maintLastDone': 'Último mantenimiento',
  'setup.privacyPolicyLink': 'Ver política de privacidad',
  'insights.viewAll': 'Ver los {count}',
  'insights.allShotsTitle': 'Todos los shots ({count})',
  'insights.editShot': 'Editar shot',
  'insights.editTime': 'Tiempo',
  'insights.editVolume': 'Volumen',
  'insights.editTaste': 'Sabor',
  'insights.editStrength': 'Intensidad',
  'insights.deleteShot': 'Eliminar',
  'insights.confirmDeleteShot': '¿Eliminar este shot? No se puede deshacer.',
  'insights.sweetSpotEyebrow': 'Tu punto dulce',
  'insights.bestGrindLabel': 'molienda',
  'insights.ratioLabel': 'ratio',
  'insights.fromNShots': 'de tus {n} mejores shots',
  'insights.noTopShots': 'Registra un shot de 85+ para fijar tu punto dulce.',
  'insights.personalBest': 'Récord personal',
  'insights.thisWeek': 'Esta semana',
  'insights.timeWindow': 'Ventana de tiempo',
  'insights.avgScore': 'media {score}',
  'insights.noShotsYet': 'aún sin datos',
  'insights.daysActive': 'Activo {count} días',
  'insights.exportCsv': 'Exportar CSV',
  'insights.deleteAccountEmail': 'Para borrar tu cuenta, escribe a chef@lazysous.app',
},

'fr': {
  'common.save': 'Enregistrer',
  'common.close': 'Fermer',
  'common.cancel': 'Annuler',
  'footer.poweredBy': 'Propulsé par',
  'footer.shotsGlobally': 'shots dans le monde',
  'header.home': 'Accueil',
  'hero.brewFirst': 'Tire le premier.',
  'hero.shotN': 'Shot n°{n}.',
  'hero.dayN': 'Jour {n}.',
  'hero.statusLastShot': 'Dernier shot : {score}. {tail}',
  'hero.statusNailed': 'Parfait.',
  'hero.statusClose': 'Tout proche.',
  'hero.statusOneTweak': 'Un réglage et c\'est fait.',
  'hero.statusKeepGoing': 'Repars de zéro.',
  'hero.statusReady': 'Pose la recette. Tire ce qui compte.',
  'hero.statusKeepPulling': 'Continue. On apprend.',
  'hero.beanResting': 'Jour {days} · encore en repos',
  'hero.beanDay': 'Jour {days} · dans la fenêtre',
  'hero.beanUseSoon': 'Jour {days} · à finir',
  'hero.beanStale': 'Jour {days} · passé',
  'hero.beanRestingShort': 'En repos',
  'hero.beanDayShort': 'Dans la fenêtre',
  'hero.beanUseSoonShort': 'À finir',
  'hero.beanStaleShort': 'Passé',
  'hero.weatherHumid': '{temp}°C · {humidity}% humidité',
  'hero.weatherDry': '{temp}°C · {humidity}% humidité',
  'hero.weatherNeutral': '{temp}°C · {humidity}% humidité',
  'hero.setupYourKit': 'Ton matériel.',
  'hero.setupKitOnFile': 'Ton matériel.',
  'hero.setupAllSetBig': 'Ton matériel.',
  'hero.setupAllSet': 'Prêt quand tu l\'es.',
  'hero.setupAddBeans': 'Ajoute tes grains pour caler.',
  'hero.setupEmpty': 'Configure ton matériel.',
  'hero.setupEmptySub': 'Cinq minutes. Meilleurs shots après.',
  'hero.setupSectionsToGo': '{count} section à finir.',
  'hero.setupSectionsToGoPlural': '{count} sections à finir.',
  'hero.insightsBig': 'Chaque shot, tracé.',
  'hero.insightsEmpty': 'Tire-en un. On commence à tracer.',
  'hero.insightsEmptySub': 'Ton score, ta mouture, ta dérive.',
  'hero.insightsCount': '{count} shot. Continue.',
  'hero.insightsCountPlural': '{count} shots. Continue.',
  'hero.insightsAvg': '{count} shots. Moyenne sur 5 : {avg}.',
  'auth.providerSub': 'Un tap. Pas de mot de passe à retenir.',
  'auth.continueMeta': 'Continuer avec Meta',
  'auth.continueGitHub': 'Continuer avec GitHub',
  'auth.privacyNote': 'Juste un pseudo. Pas de mot de passe à retenir.',
  'auth.nicknameTitle': 'Choisis un pseudo.',
  'auth.nicknameSub': 'Comme tu veux. C\'est tout ce qu\'on garde.',
  'auth.nicknamePlaceholder': 'ex. billy_bean',
  'auth.nicknameSubmit': 'Enregistrer',
  'brew.decreaseFine': 'Diminuer {label} (fin)',
  'brew.increaseFine': 'Augmenter {label} (fin)',
  'brew.coachPreviewBadge': 'Après ton premier shot',
  'brew.coachPreviewDirection': 'Plus gros',
  'brew.coachPreviewReason': '3s trop long. Mouture plus grosse.',
  'brew.coachPreviewCaption': 'Tire. Note. On te dit quoi changer.',
  'brew.coachLine': 'Tire. Note. On te dit quoi changer.',
  'brew.outcomeShort': '{delta} {unit} en moins',
  'brew.outcomeLong': '{delta} {unit} en plus',
  'brew.holdAtTarget': 'Garde tel quel',
  'brew.targetWas': 'objectif {value} {unit}',
  'brew.sectionChange': 'À changer au prochain shot',
  'brew.sectionHold': 'Garder pour le prochain shot',
  'brew.sectionShot': 'Ce shot',
  'brew.scoreBest': 'Record perso. Savoure.',
  'brew.scoreUp': '+{delta} sur le précédent. Tu montes.',
  'brew.scoreDown': '−{delta} sur le précédent. Recadre.',
  'brew.scoreSame': 'Même score. Main stable.',
  'brew.scoreFirst': 'Premier fait. On apprend.',
  'brew.stop': 'STOP',
  'brew.saveShot': 'ENREGISTRER',
  'brew.timingRunning': 'Extraction',
  'brew.timingStopped': 'Capture le shot',
  'brew.countdownSub': 'Prêt',
  'brew.reasonRanFastBoth': '{seconds}s trop court et {ml}ml en trop. Mouture plus fine.',
  'brew.reasonRanSlowBoth': '{seconds}s trop long et {ml}ml en moins. Mouture plus grosse.',
  'brew.reasonGrindAtMin': '{primary} Le moulin est au plus fin — augmente la dose.',
  'brew.reasonGrindAtMax': '{primary} Le moulin est au plus gros — baisse la dose.',
  'brew.doseTrendUp': 'Mouture plus fine 3 shots de suite. Essaie +0,5g.',
  'brew.doseTrendDown': 'Mouture plus grosse 3 shots de suite. Essaie −0,5g.',
  'brew.doseGrindAtMin': 'Moulin au plus fin. +0,5g pour plus de résistance.',
  'brew.doseGrindAtMax': 'Moulin au plus gros. −0,5g pour moins de résistance.',
  'crema.thin': 'Fine',
  'crema.normal': 'Normale',
  'crema.thick': 'Épaisse',
  'rating.crema': 'Crème',
  'rating.flavour': 'Saveur',
  'rating.strength': 'Intensité',
  'rating.later': 'Plus tard',
  'rating.save': 'Enregistrer',
  'barista.toggleOn': 'Mode barista',
  'barista.toggleOff': 'Désactiver mode barista',
  'barista.active': 'Mode barista',
  'barista.sessionMeta': '{count} shots · {mins} min',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Brewmie, calé pour toi.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'Ajoute ton moulin et les recommandations sortent dans tes unités.',
  'premium.triggerTamper': 'Tampers à ressort et auto enrichissent le modèle.',
  'premium.triggerBeans': 'Garde tes grains. Change de paquet, reprends là où tu étais.',
  'premium.triggerHistory': 'Débloque historique complet et tendances.',
  'premium.triggerBenchmarks': 'Compare chaque shot à ton meilleur.',
  'premium.feature1Head': 'Ton matériel',
  'premium.feature1Sub': 'Ajoute ton moulin, tamper et grains. Les recommandations sortent dans tes unités.',
  'premium.feature2Head': 'Historique complet',
  'premium.feature2Sub': 'Chaque shot conservé. Exporte quand tu veux.',
  'premium.feature3Head': 'Records personnels',
  'premium.feature3Sub': 'Compare chaque shot à ton meilleur.',
  'premium.ctaBrewmie': 'Brewmie seul',
  'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Pack avec Lazy Sous',
  'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev : déblocage via le dev pill. Ce n\'est pas un vrai achat.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'Les anciens shots sont gardés. Historique complet avec Premium.',
  'tierLock.benchmarksLocked': 'Débloque les Records personnels avec Premium.',
  'tierLock.genericGrinder': 'Moulin générique. Premium cale les calculs sur le tien.',
  'tierLock.genericTamper': 'Tamp manuel. Premium ajoute ressort et automatique.',
  'tierLock.genericBeans': 'Grain torréfaction moyenne générique. Premium suit tes grains.',
  'setup.profileCtaReset': 'Relancer l\'assistant',
  'setup.bannerEyebrow': 'Assistant',
  'setup.bannerCta': 'Continuer →',
  'setup.cardLanguage': 'Langue',
  'setup.languageLabel': 'Langue d\'affichage',
  'setup.languageMajor': 'Courantes',
  'setup.languageMore': 'Autres langues',
  'setup.languageHint': 'Brewmie détecte ta langue automatiquement. Choisis-en une autre ici. Les traductions hors liste courante peuvent être incomplètes et basculer en anglais.',
  'setup.maintLastDone': 'Dernière fois',
  'setup.privacyPolicyLink': 'Lire la politique de confidentialité',
  'insights.viewAll': 'Voir les {count}',
  'insights.allShotsTitle': 'Tous les shots ({count})',
  'insights.editShot': 'Modifier le shot',
  'insights.editTime': 'Temps',
  'insights.editVolume': 'Volume',
  'insights.editTaste': 'Saveur',
  'insights.editStrength': 'Intensité',
  'insights.deleteShot': 'Supprimer',
  'insights.confirmDeleteShot': 'Supprimer ce shot ? Action irréversible.',
  'insights.sweetSpotEyebrow': 'Ton sweet spot',
  'insights.bestGrindLabel': 'mouture',
  'insights.ratioLabel': 'ratio',
  'insights.fromNShots': 'sur tes {n} meilleurs shots',
  'insights.noTopShots': 'Note un shot à 85+ pour fixer ton sweet spot.',
  'insights.personalBest': 'Record personnel',
  'insights.thisWeek': 'Cette semaine',
  'insights.timeWindow': 'Fenêtre de temps',
  'insights.avgScore': 'moy. {score}',
  'insights.noShotsYet': 'pas encore de données',
  'insights.daysActive': '{count} jours actifs',
  'insights.exportCsv': 'Exporter CSV',
  'insights.deleteAccountEmail': 'Pour supprimer ton compte, écris à chef@lazysous.app',
},

'de': {
  'common.save': 'Speichern',
  'common.close': 'Schließen',
  'common.cancel': 'Abbrechen',
  'footer.poweredBy': 'Angetrieben von',
  'footer.shotsGlobally': 'Shots weltweit',
  'header.home': 'Start',
  'hero.brewFirst': 'Zieh den ersten.',
  'hero.shotN': 'Shot {n}.',
  'hero.dayN': 'Tag {n}.',
  'hero.statusLastShot': 'Letzter Shot: {score}. {tail}',
  'hero.statusNailed': 'Sitzt.',
  'hero.statusClose': 'Knapp dran.',
  'hero.statusOneTweak': 'Eine Anpassung.',
  'hero.statusKeepGoing': 'Reset und nochmal.',
  'hero.statusReady': 'Setz das Rezept. Zieh, was zählt.',
  'hero.statusKeepPulling': 'Weiter ziehen. Wir lernen.',
  'hero.beanResting': 'Tag {days} · noch am ruhen',
  'hero.beanDay': 'Tag {days} · im Fenster',
  'hero.beanUseSoon': 'Tag {days} · bald aufbrauchen',
  'hero.beanStale': 'Tag {days} · überständig',
  'hero.beanRestingShort': 'Ruht noch',
  'hero.beanDayShort': 'Im Fenster',
  'hero.beanUseSoonShort': 'Bald aufbrauchen',
  'hero.beanStaleShort': 'Überständig',
  'hero.weatherHumid': '{temp}°C · {humidity}% Luftfeuchte',
  'hero.weatherDry': '{temp}°C · {humidity}% Luftfeuchte',
  'hero.weatherNeutral': '{temp}°C · {humidity}% Luftfeuchte',
  'hero.setupYourKit': 'Dein Setup.',
  'hero.setupKitOnFile': 'Dein Setup.',
  'hero.setupAllSetBig': 'Dein Setup.',
  'hero.setupAllSet': 'Bereit, wann du es bist.',
  'hero.setupAddBeans': 'Bohnen hinzufügen zum Einstellen.',
  'hero.setupEmpty': 'Richte dein Setup ein.',
  'hero.setupEmptySub': 'Fünf Minuten. Bessere Shots danach.',
  'hero.setupSectionsToGo': 'Noch {count} Abschnitt.',
  'hero.setupSectionsToGoPlural': 'Noch {count} Abschnitte.',
  'hero.insightsBig': 'Jeder Shot, getrackt.',
  'hero.insightsEmpty': 'Zieh einen. Wir tracken.',
  'hero.insightsEmptySub': 'Dein Score, dein Mahlgrad, dein Drift.',
  'hero.insightsCount': '{count} Shot. Weiter ziehen.',
  'hero.insightsCountPlural': '{count} Shots. Weiter ziehen.',
  'hero.insightsAvg': '{count} Shots. 5-Shot-Schnitt {avg}.',
  'auth.providerSub': 'Ein Tipp. Kein Passwort merken.',
  'auth.continueMeta': 'Weiter mit Meta',
  'auth.continueGitHub': 'Weiter mit GitHub',
  'auth.privacyNote': 'Nur ein Nickname. Kein Passwort merken.',
  'auth.nicknameTitle': 'Wähl einen Nickname.',
  'auth.nicknameSub': 'Wie du magst. Mehr speichern wir nicht.',
  'auth.nicknamePlaceholder': 'z. B. billy_bean',
  'auth.nicknameSubmit': 'Speichern',
  'brew.decreaseFine': '{label} verringern (fein)',
  'brew.increaseFine': '{label} erhöhen (fein)',
  'brew.coachPreviewBadge': 'Nach deinem ersten Shot',
  'brew.coachPreviewDirection': 'Gröber',
  'brew.coachPreviewReason': '3s zu lang. Gröber mahlen.',
  'brew.coachPreviewCaption': 'Zieh. Notier. Wir sagen, was zu ändern ist.',
  'brew.coachLine': 'Zieh. Notier. Wir sagen, was als Nächstes zu ändern ist.',
  'brew.outcomeShort': '{delta} {unit} zu wenig',
  'brew.outcomeLong': '{delta} {unit} zu viel',
  'brew.holdAtTarget': 'So lassen',
  'brew.targetWas': 'Ziel {value} {unit}',
  'brew.sectionChange': 'Für den nächsten Shot ändern',
  'brew.sectionHold': 'Für den nächsten Shot halten',
  'brew.sectionShot': 'Dieser Shot',
  'brew.scoreBest': 'Bestleistung. Genieße langsam.',
  'brew.scoreUp': '+{delta} zum letzten. Geht aufwärts.',
  'brew.scoreDown': '−{delta} zum letzten. Zurücksetzen.',
  'brew.scoreSame': 'Gleich wie letzter. Ruhige Hand.',
  'brew.scoreFirst': 'Erster im Kasten. Jetzt lernen wir.',
  'brew.stop': 'STOPP',
  'brew.saveShot': 'SHOT SPEICHERN',
  'brew.timingRunning': 'Extraktion',
  'brew.timingStopped': 'Shot erfassen',
  'brew.countdownSub': 'Mach dich bereit',
  'brew.reasonRanFastBoth': '{seconds}s zu kurz und {ml}ml zu viel. Feiner mahlen.',
  'brew.reasonRanSlowBoth': '{seconds}s zu lang und {ml}ml zu wenig. Gröber mahlen.',
  'brew.reasonGrindAtMin': '{primary} Mühle am Anschlag fein — Dose erhöhen.',
  'brew.reasonGrindAtMax': '{primary} Mühle am Anschlag grob — Dose senken.',
  'brew.doseTrendUp': 'Mahlgrad 3 Shots feiner geworden. Versuch +0,5g.',
  'brew.doseTrendDown': 'Mahlgrad 3 Shots gröber geworden. Versuch −0,5g.',
  'brew.doseGrindAtMin': 'Mühle am Anschlag fein. +0,5g für mehr Widerstand.',
  'brew.doseGrindAtMax': 'Mühle am Anschlag grob. −0,5g für weniger Widerstand.',
  'crema.thin': 'Dünn',
  'crema.normal': 'Normal',
  'crema.thick': 'Dick',
  'rating.crema': 'Crema',
  'rating.flavour': 'Geschmack',
  'rating.strength': 'Stärke',
  'rating.later': 'Später bewerten',
  'rating.save': 'Bewertung speichern',
  'barista.toggleOn': 'Barista-Modus',
  'barista.toggleOff': 'Barista-Modus aus',
  'barista.active': 'Barista-Modus',
  'barista.sessionMeta': '{count} Shots · {mins} Min',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Brewmie, auf dich abgestimmt.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'Trag deine Mühle ein und Empfehlungen kommen in deinen Einheiten.',
  'premium.triggerTamper': 'Feder- und Auto-Tamper kommen ins Modell.',
  'premium.triggerBeans': 'Bohnen speichern. Tüten wechseln, da weitermachen, wo du warst.',
  'premium.triggerHistory': 'Komplette Historie und Trends freischalten.',
  'premium.triggerBenchmarks': 'Jeden Shot gegen deinen besten vergleichen.',
  'premium.feature1Head': 'Dein Setup',
  'premium.feature1Sub': 'Mühle, Tamper, Bohnen. Empfehlungen kommen in deinen Einheiten.',
  'premium.feature2Head': 'Komplette Historie',
  'premium.feature2Sub': 'Jeder Shot bleibt. Exportier jederzeit.',
  'premium.feature3Head': 'Persönliche Bestwerte',
  'premium.feature3Sub': 'Jeden Shot gegen deinen besten vergleichen.',
  'premium.ctaBrewmie': 'Nur Brewmie',
  'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Bundle mit Lazy Sous',
  'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev: über den Dev-Pill freischaltbar. Kein echter Kauf.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'Ältere Shots sind gespeichert. Volle Historie mit Premium.',
  'tierLock.benchmarksLocked': 'Persönliche Bestwerte mit Premium freischalten.',
  'tierLock.genericGrinder': 'Generische Mühle. Premium stimmt die Mathematik auf deine ab.',
  'tierLock.genericTamper': 'Manuelles Tampen. Premium ergänzt Feder und Auto.',
  'tierLock.genericBeans': 'Generische mittlere Röstung. Premium trackt deine Bohnen.',
  'setup.profileCtaReset': 'Setup neu starten',
  'setup.bannerEyebrow': 'Setup-Assistent',
  'setup.bannerCta': 'Weiter →',
  'setup.cardLanguage': 'Sprache',
  'setup.languageLabel': 'Anzeigesprache',
  'setup.languageMajor': 'Häufig',
  'setup.languageMore': 'Weitere Sprachen',
  'setup.languageHint': 'Brewmie erkennt deine Sprache automatisch. Hier kannst du eine andere wählen. Übersetzungen außerhalb der häufigen Liste können unvollständig sein und fallen auf Englisch zurück.',
  'setup.maintLastDone': 'Zuletzt erledigt',
  'setup.privacyPolicyLink': 'Datenschutzerklärung lesen',
  'insights.viewAll': 'Alle {count} anzeigen',
  'insights.allShotsTitle': 'Alle Shots ({count})',
  'insights.editShot': 'Shot bearbeiten',
  'insights.editTime': 'Zeit',
  'insights.editVolume': 'Volumen',
  'insights.editTaste': 'Geschmack',
  'insights.editStrength': 'Stärke',
  'insights.deleteShot': 'Löschen',
  'insights.confirmDeleteShot': 'Diesen Shot löschen? Nicht rückgängig zu machen.',
  'insights.sweetSpotEyebrow': 'Dein Sweet Spot',
  'insights.bestGrindLabel': 'Mahlgrad',
  'insights.ratioLabel': 'Verhältnis',
  'insights.fromNShots': 'aus deinen {n} besten Shots',
  'insights.noTopShots': 'Notier einen Shot mit 85+, um deinen Sweet Spot zu setzen.',
  'insights.personalBest': 'Persönlicher Rekord',
  'insights.thisWeek': 'Diese Woche',
  'insights.timeWindow': 'Zeitfenster',
  'insights.avgScore': 'Ø {score}',
  'insights.noShotsYet': 'noch keine Daten',
  'insights.daysActive': '{count} Tage aktiv',
  'insights.exportCsv': 'CSV exportieren',
  'insights.deleteAccountEmail': 'Konto löschen? Mail an chef@lazysous.app',
},

# Tier 1 continued: it, pt, ja, zh, ko, hi, nl, sv, tr, pl. Same structure.
# Translations done in-conversation, no API.
'it': {
  'common.save': 'Salva', 'common.close': 'Chiudi', 'common.cancel': 'Annulla',
  'footer.poweredBy': 'Powered by', 'footer.shotsGlobally': 'shot nel mondo',
  'header.home': 'Home',
  'hero.brewFirst': 'Tira il primo.', 'hero.shotN': 'Shot {n}.', 'hero.dayN': 'Giorno {n}.',
  'hero.statusLastShot': 'Ultimo shot: {score}. {tail}',
  'hero.statusNailed': 'Centrato.', 'hero.statusClose': 'Quasi.',
  'hero.statusOneTweak': 'Un ritocco e ci sei.', 'hero.statusKeepGoing': 'Resetta e riparti.',
  'hero.statusReady': 'Imposta la ricetta. Tira quel che conta.',
  'hero.statusKeepPulling': 'Continua. Stiamo imparando.',
  'hero.beanResting': 'Giorno {days} · ancora in riposo',
  'hero.beanDay': 'Giorno {days} · nella finestra',
  'hero.beanUseSoon': 'Giorno {days} · da finire',
  'hero.beanStale': 'Giorno {days} · passato',
  'hero.beanRestingShort': 'In riposo', 'hero.beanDayShort': 'Nella finestra',
  'hero.beanUseSoonShort': 'Da finire', 'hero.beanStaleShort': 'Passato',
  'hero.weatherHumid': '{temp}°C · {humidity}% umidità',
  'hero.weatherDry': '{temp}°C · {humidity}% umidità',
  'hero.weatherNeutral': '{temp}°C · {humidity}% umidità',
  'hero.setupYourKit': 'La tua attrezzatura.',
  'hero.setupKitOnFile': 'La tua attrezzatura.',
  'hero.setupAllSetBig': 'La tua attrezzatura.',
  'hero.setupAllSet': 'Pronto quando vuoi.',
  'hero.setupAddBeans': 'Aggiungi i grani per tarare.',
  'hero.setupEmpty': 'Imposta l\'attrezzatura.',
  'hero.setupEmptySub': 'Cinque minuti. Shot migliori dopo.',
  'hero.setupSectionsToGo': '{count} sezione rimasta.',
  'hero.setupSectionsToGoPlural': '{count} sezioni rimaste.',
  'hero.insightsBig': 'Ogni shot, tracciato.',
  'hero.insightsEmpty': 'Tirane uno. Iniziamo a tracciare.',
  'hero.insightsEmptySub': 'Il tuo punteggio, la tua macinatura, la tua deriva.',
  'hero.insightsCount': '{count} shot. Continua.',
  'hero.insightsCountPlural': '{count} shot. Continua.',
  'hero.insightsAvg': '{count} shot. Media su 5: {avg}.',
  'auth.providerSub': 'Un tap. Niente password da ricordare.',
  'auth.continueMeta': 'Continua con Meta',
  'auth.continueGitHub': 'Continua con GitHub',
  'auth.privacyNote': 'Solo un nickname. Niente password da ricordare.',
  'auth.nicknameTitle': 'Scegli un nickname.',
  'auth.nicknameSub': 'A piacere. È l\'unica cosa che salviamo.',
  'auth.nicknamePlaceholder': 'es. billy_bean',
  'auth.nicknameSubmit': 'Salva',
  'brew.decreaseFine': 'Riduci {label} (fine)',
  'brew.increaseFine': 'Aumenta {label} (fine)',
  'brew.coachPreviewBadge': 'Dopo il primo shot',
  'brew.coachPreviewDirection': 'Più grossa',
  'brew.coachPreviewReason': '3s troppo. Macina più grosso.',
  'brew.coachPreviewCaption': 'Tira. Registra. Ti diciamo cosa cambiare.',
  'brew.coachLine': 'Tira. Registra. Ti diciamo cosa cambiare dopo.',
  'brew.outcomeShort': '{delta} {unit} in meno',
  'brew.outcomeLong': '{delta} {unit} in più',
  'brew.holdAtTarget': 'Lascia così',
  'brew.targetWas': 'obiettivo {value} {unit}',
  'brew.sectionChange': 'Da cambiare al prossimo shot',
  'brew.sectionHold': 'Da tenere al prossimo shot',
  'brew.sectionShot': 'Questo shot',
  'brew.scoreBest': 'Record personale. Goditelo.',
  'brew.scoreUp': '+{delta} sull\'ultimo. Stai salendo.',
  'brew.scoreDown': '−{delta} sull\'ultimo. Resetta.',
  'brew.scoreSame': 'Stesso dell\'ultimo. Mano ferma.',
  'brew.scoreFirst': 'Primo fatto. Adesso impariamo.',
  'brew.stop': 'STOP', 'brew.saveShot': 'SALVA SHOT',
  'brew.timingRunning': 'In estrazione', 'brew.timingStopped': 'Cattura lo shot',
  'brew.countdownSub': 'Pronti',
  'brew.reasonRanFastBoth': '{seconds}s corto e {ml}ml in più. Macina più fine.',
  'brew.reasonRanSlowBoth': '{seconds}s lungo e {ml}ml in meno. Macina più grosso.',
  'brew.reasonGrindAtMin': '{primary} Macinino al minimo — aumenta la dose.',
  'brew.reasonGrindAtMax': '{primary} Macinino al massimo — riduci la dose.',
  'brew.doseTrendUp': 'Macinatura più fine per 3 shot. Prova +0,5g.',
  'brew.doseTrendDown': 'Macinatura più grossa per 3 shot. Prova −0,5g.',
  'brew.doseGrindAtMin': 'Macinino al minimo. +0,5g per più resistenza.',
  'brew.doseGrindAtMax': 'Macinino al massimo. −0,5g per meno resistenza.',
  'crema.thin': 'Sottile', 'crema.normal': 'Normale', 'crema.thick': 'Densa',
  'rating.crema': 'Crema', 'rating.flavour': 'Sapore', 'rating.strength': 'Intensità',
  'rating.later': 'Valuta dopo', 'rating.save': 'Salva valutazione',
  'barista.toggleOn': 'Modalità barista', 'barista.toggleOff': 'Disattiva modalità barista',
  'barista.active': 'Modalità barista', 'barista.sessionMeta': '{count} shot · {mins} min',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Brewmie, tarato per te.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'Aggiungi il macinino e le raccomandazioni escono nelle tue unità.',
  'premium.triggerTamper': 'Tamper a molla e automatici entrano nel modello.',
  'premium.triggerBeans': 'Salva i tuoi grani. Cambia busta, riprendi da dove eri.',
  'premium.triggerHistory': 'Sblocca lo storico completo e i trend.',
  'premium.triggerBenchmarks': 'Confronta ogni shot col tuo migliore.',
  'premium.feature1Head': 'La tua attrezzatura',
  'premium.feature1Sub': 'Aggiungi macinino, tamper e grani. Raccomandazioni nelle tue unità.',
  'premium.feature2Head': 'Storico completo',
  'premium.feature2Sub': 'Ogni shot salvato. Esporta quando vuoi.',
  'premium.feature3Head': 'Record personali',
  'premium.feature3Sub': 'Confronta ogni shot col tuo migliore.',
  'premium.ctaBrewmie': 'Solo Brewmie',
  'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Pacchetto con Lazy Sous',
  'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev: sblocco tramite dev pill. Non è un acquisto reale.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'Gli shot più vecchi sono salvati. Storico completo con Premium.',
  'tierLock.benchmarksLocked': 'Sblocca i Record personali con Premium.',
  'tierLock.genericGrinder': 'Macinino generico. Premium calibra sulla tua macchina.',
  'tierLock.genericTamper': 'Tamp manuale. Premium aggiunge molla e automatico.',
  'tierLock.genericBeans': 'Tostatura media generica. Premium traccia i tuoi grani.',
  'setup.profileCtaReset': 'Riavvia configurazione',
  'setup.bannerEyebrow': 'Configurazione',
  'setup.bannerCta': 'Continua →',
  'setup.cardLanguage': 'Lingua',
  'setup.languageLabel': 'Lingua di visualizzazione',
  'setup.languageMajor': 'Comuni', 'setup.languageMore': 'Altre lingue',
  'setup.languageHint': 'Brewmie rileva la tua lingua. Sceglila qui. Le traduzioni fuori dall\'elenco comune possono essere incomplete e tornare all\'inglese.',
  'setup.maintLastDone': 'Ultima volta',
  'setup.privacyPolicyLink': 'Leggi l\'informativa privacy',
  'insights.viewAll': 'Vedi tutti ({count})',
  'insights.allShotsTitle': 'Tutti gli shot ({count})',
  'insights.editShot': 'Modifica shot',
  'insights.editTime': 'Tempo', 'insights.editVolume': 'Volume',
  'insights.editTaste': 'Sapore', 'insights.editStrength': 'Intensità',
  'insights.deleteShot': 'Elimina',
  'insights.confirmDeleteShot': 'Eliminare questo shot? Non si può annullare.',
  'insights.sweetSpotEyebrow': 'Il tuo sweet spot',
  'insights.bestGrindLabel': 'macinatura', 'insights.ratioLabel': 'rapporto',
  'insights.fromNShots': 'sui tuoi {n} shot migliori',
  'insights.noTopShots': 'Registra uno shot 85+ per fissare il tuo sweet spot.',
  'insights.personalBest': 'Record personale',
  'insights.thisWeek': 'Questa settimana',
  'insights.timeWindow': 'Finestra di tempo',
  'insights.avgScore': 'media {score}',
  'insights.noShotsYet': 'ancora nessun dato',
  'insights.daysActive': 'Attivo {count} giorni',
  'insights.exportCsv': 'Esporta CSV',
  'insights.deleteAccountEmail': 'Per eliminare l\'account scrivi a chef@lazysous.app',
},
}


def set_nested(d, key, value):
    parts = key.split('.')
    cur = d
    for p in parts[:-1]:
        if p not in cur or not isinstance(cur[p], dict):
            cur[p] = {}
        cur = cur[p]
    cur[parts[-1]] = value


def main():
    for locale, kvs in TRANSLATIONS.items():
        path = TR / f'{locale}.json'
        existing = json.loads(path.read_text(encoding='utf-8'))
        for k, v in kvs.items():
            set_nested(existing, k, v)
        path.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        print(f'{locale}: filled {len(kvs)} keys')


if __name__ == '__main__':
    main()
