#!/usr/bin/env python3
"""Tier 1 batch B: pt, ja, zh, ko, hi, nl, sv, tr, pl."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TR = ROOT / 'public' / 'translations'

TRANSLATIONS = {
'pt': {
  'common.save': 'Guardar', 'common.close': 'Fechar', 'common.cancel': 'Cancelar',
  'footer.poweredBy': 'Powered by', 'footer.shotsGlobally': 'shots em todo o mundo',
  'header.home': 'Início',
  'hero.brewFirst': 'Tira o primeiro.', 'hero.shotN': 'Hora do shot {n}.', 'hero.dayN': 'Dia {n}.',
  'hero.statusLastShot': 'Último shot: {score}. {tail}',
  'hero.statusNailed': 'Acertaste.', 'hero.statusClose': 'Quase.',
  'hero.statusOneTweak': 'Um ajuste e está.', 'hero.statusKeepGoing': 'Recomeça e vai.',
  'hero.statusReady': 'Define a receita. Tira o que conta.',
  'hero.statusKeepPulling': 'Continua. Estamos a aprender.',
  'hero.beanResting': 'Dia {days} · ainda a descansar',
  'hero.beanDay': 'Dia {days} · na janela',
  'hero.beanUseSoon': 'Dia {days} · usa em breve',
  'hero.beanStale': 'Dia {days} · passou do ponto',
  'hero.beanRestingShort': 'A descansar', 'hero.beanDayShort': 'Na janela',
  'hero.beanUseSoonShort': 'Usa em breve', 'hero.beanStaleShort': 'Passou do ponto',
  'hero.weatherHumid': '{temp}°C · {humidity}% humidade',
  'hero.weatherDry': '{temp}°C · {humidity}% humidade',
  'hero.weatherNeutral': '{temp}°C · {humidity}% humidade',
  'hero.setupYourKit': 'O teu equipamento.', 'hero.setupKitOnFile': 'O teu equipamento.',
  'hero.setupAllSetBig': 'O teu equipamento.', 'hero.setupAllSet': 'Pronto quando quiseres.',
  'hero.setupAddBeans': 'Adiciona os grãos para calibrar.',
  'hero.setupEmpty': 'Configura o equipamento.',
  'hero.setupEmptySub': 'Cinco minutos. Shots melhores a seguir.',
  'hero.setupSectionsToGo': 'Falta {count} secção.',
  'hero.setupSectionsToGoPlural': 'Faltam {count} secções.',
  'hero.insightsBig': 'Cada shot, registado.',
  'hero.insightsEmpty': 'Tira um. Começamos a registar.',
  'hero.insightsEmptySub': 'A tua pontuação, a tua moagem, o teu desvio.',
  'hero.insightsCount': '{count} shot. Continua a tirar.',
  'hero.insightsCountPlural': '{count} shots. Continua a tirar.',
  'hero.insightsAvg': '{count} shots. Média 5: {avg}.',
  'auth.providerSub': 'Um toque. Sem palavras-passe.',
  'auth.continueMeta': 'Continuar com Meta',
  'auth.continueGitHub': 'Continuar com GitHub',
  'auth.privacyNote': 'Só um nickname. Sem palavras-passe.',
  'auth.nicknameTitle': 'Escolhe um nickname.',
  'auth.nicknameSub': 'Como quiseres. É a única coisa que guardamos.',
  'auth.nicknamePlaceholder': 'ex. billy_bean', 'auth.nicknameSubmit': 'Guardar',
  'brew.decreaseFine': 'Reduzir {label} (fino)',
  'brew.increaseFine': 'Aumentar {label} (fino)',
  'brew.coachPreviewBadge': 'Após o teu primeiro shot',
  'brew.coachPreviewDirection': 'Mais grosso',
  'brew.coachPreviewReason': '3s a mais. Moe mais grosso.',
  'brew.coachPreviewCaption': 'Tira. Regista. Dizemos-te o que mudar.',
  'brew.coachLine': 'Tira. Regista. Dizemos-te o que mudar a seguir.',
  'brew.outcomeShort': '{delta} {unit} a menos',
  'brew.outcomeLong': '{delta} {unit} a mais',
  'brew.holdAtTarget': 'Mantém',
  'brew.targetWas': 'objetivo {value} {unit}',
  'brew.sectionChange': 'Mudar para o próximo shot',
  'brew.sectionHold': 'Manter para o próximo shot',
  'brew.sectionShot': 'Este shot',
  'brew.scoreBest': 'Recorde pessoal. Saboreia.',
  'brew.scoreUp': '+{delta} ao último. A subir.',
  'brew.scoreDown': '−{delta} ao último. Recomeça.',
  'brew.scoreSame': 'Igual ao último. Mão firme.',
  'brew.scoreFirst': 'Primeiro feito. Agora aprendemos.',
  'brew.stop': 'PARAR', 'brew.saveShot': 'GUARDAR SHOT',
  'brew.timingRunning': 'A extrair', 'brew.timingStopped': 'Captura o shot',
  'brew.countdownSub': 'Prepara-te',
  'brew.reasonRanFastBoth': '{seconds}s curto e {ml}ml a mais. Moe mais fino.',
  'brew.reasonRanSlowBoth': '{seconds}s longo e {ml}ml a menos. Moe mais grosso.',
  'brew.reasonGrindAtMin': '{primary} Moinho no mínimo — aumenta a dose.',
  'brew.reasonGrindAtMax': '{primary} Moinho no máximo — reduz a dose.',
  'brew.doseTrendUp': 'Moeste mais fino 3 shots seguidos. Tenta +0,5g.',
  'brew.doseTrendDown': 'Moeste mais grosso 3 shots seguidos. Tenta −0,5g.',
  'brew.doseGrindAtMin': 'Moinho no mínimo. +0,5g para mais resistência.',
  'brew.doseGrindAtMax': 'Moinho no máximo. −0,5g para menos resistência.',
  'crema.thin': 'Fina', 'crema.normal': 'Normal', 'crema.thick': 'Densa',
  'rating.crema': 'Crema', 'rating.flavour': 'Sabor', 'rating.strength': 'Intensidade',
  'rating.later': 'Avaliar depois', 'rating.save': 'Guardar avaliação',
  'barista.toggleOn': 'Modo barista', 'barista.toggleOff': 'Desligar modo barista',
  'barista.active': 'Modo barista', 'barista.sessionMeta': '{count} shots · {mins} min',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Brewmie, à tua medida.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'Adiciona o moinho e as recomendações saem nas tuas unidades.',
  'premium.triggerTamper': 'Tampers de mola e automáticos entram no modelo.',
  'premium.triggerBeans': 'Guarda os teus grãos. Muda de saco, retoma onde estavas.',
  'premium.triggerHistory': 'Desbloqueia histórico completo e tendências.',
  'premium.triggerBenchmarks': 'Compara cada shot com o teu melhor.',
  'premium.feature1Head': 'O teu equipamento',
  'premium.feature1Sub': 'Moinho, tamper, grãos. Recomendações nas tuas unidades.',
  'premium.feature2Head': 'Histórico completo',
  'premium.feature2Sub': 'Cada shot guardado. Exporta quando quiseres.',
  'premium.feature3Head': 'Recordes pessoais',
  'premium.feature3Sub': 'Compara cada shot com o teu melhor.',
  'premium.ctaBrewmie': 'Só Brewmie', 'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Pacote com Lazy Sous', 'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev: desbloqueio pelo dev pill. Não é compra real.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'Shots antigos ficam guardados. Histórico completo com Premium.',
  'tierLock.benchmarksLocked': 'Desbloqueia Recordes Pessoais com Premium.',
  'tierLock.genericGrinder': 'Moinho genérico. Premium ajusta a matemática ao teu.',
  'tierLock.genericTamper': 'Tamp manual. Premium adiciona mola e automático.',
  'tierLock.genericBeans': 'Torra média genérica. Premium segue os teus grãos.',
  'setup.profileCtaReset': 'Reiniciar configuração',
  'setup.bannerEyebrow': 'Configuração', 'setup.bannerCta': 'Continuar →',
  'setup.cardLanguage': 'Idioma', 'setup.languageLabel': 'Idioma do ecrã',
  'setup.languageMajor': 'Comuns', 'setup.languageMore': 'Outros idiomas',
  'setup.languageHint': 'A Brewmie deteta o teu idioma. Escolhe outro aqui. Traduções fora dos comuns podem estar incompletas e voltam ao inglês.',
  'setup.maintLastDone': 'Última vez',
  'setup.privacyPolicyLink': 'Ler política de privacidade',
  'insights.viewAll': 'Ver todos ({count})',
  'insights.allShotsTitle': 'Todos os shots ({count})',
  'insights.editShot': 'Editar shot',
  'insights.editTime': 'Tempo', 'insights.editVolume': 'Volume',
  'insights.editTaste': 'Sabor', 'insights.editStrength': 'Intensidade',
  'insights.deleteShot': 'Eliminar',
  'insights.confirmDeleteShot': 'Eliminar este shot? Não tem volta.',
  'insights.sweetSpotEyebrow': 'O teu sweet spot',
  'insights.bestGrindLabel': 'moagem', 'insights.ratioLabel': 'rácio',
  'insights.fromNShots': 'dos teus {n} melhores shots',
  'insights.noTopShots': 'Regista um shot 85+ para definir o teu sweet spot.',
  'insights.personalBest': 'Recorde pessoal',
  'insights.thisWeek': 'Esta semana', 'insights.timeWindow': 'Janela de tempo',
  'insights.avgScore': 'média {score}', 'insights.noShotsYet': 'ainda sem dados',
  'insights.daysActive': 'Ativo {count} dias',
  'insights.exportCsv': 'Exportar CSV',
  'insights.deleteAccountEmail': 'Para apagar a tua conta, escreve para chef@lazysous.app',
},

'ja': {
  'common.save': '保存', 'common.close': '閉じる', 'common.cancel': 'キャンセル',
  'footer.poweredBy': 'Powered by', 'footer.shotsGlobally': 'ショット（世界全体）',
  'header.home': 'ホーム',
  'hero.brewFirst': '一杯目を抽出。', 'hero.shotN': 'ショット{n}の時間。', 'hero.dayN': '{n}日目。',
  'hero.statusLastShot': '直近スコア{score}。{tail}',
  'hero.statusNailed': '完璧。', 'hero.statusClose': 'もう少し。',
  'hero.statusOneTweak': '微調整で決まり。', 'hero.statusKeepGoing': 'リセットしてもう一杯。',
  'hero.statusReady': 'レシピをセット。狙って抽出。',
  'hero.statusKeepPulling': '抽出を続けよう。学習中。',
  'hero.beanResting': '{days}日目 · 休ませ中',
  'hero.beanDay': '{days}日目 · ベスト域',
  'hero.beanUseSoon': '{days}日目 · 早めに使い切ろう',
  'hero.beanStale': '{days}日目 · 鮮度切れ',
  'hero.beanRestingShort': '休ませ中', 'hero.beanDayShort': 'ベスト域',
  'hero.beanUseSoonShort': '早めに', 'hero.beanStaleShort': '鮮度切れ',
  'hero.weatherHumid': '{temp}°C · 湿度{humidity}%',
  'hero.weatherDry': '{temp}°C · 湿度{humidity}%',
  'hero.weatherNeutral': '{temp}°C · 湿度{humidity}%',
  'hero.setupYourKit': 'あなたの機材。', 'hero.setupKitOnFile': 'あなたの機材。',
  'hero.setupAllSetBig': 'あなたの機材。', 'hero.setupAllSet': 'いつでも開始OK。',
  'hero.setupAddBeans': '豆を登録してダイヤルイン。',
  'hero.setupEmpty': '機材を設定。',
  'hero.setupEmptySub': '5分でOK。次のショットから違う。',
  'hero.setupSectionsToGo': 'あと{count}項目。',
  'hero.setupSectionsToGoPlural': 'あと{count}項目。',
  'hero.insightsBig': 'すべてのショットを記録。',
  'hero.insightsEmpty': '一杯抽出。記録を始めよう。',
  'hero.insightsEmptySub': 'スコア、挽き目、ドリフト。',
  'hero.insightsCount': '{count}ショット。続けよう。',
  'hero.insightsCountPlural': '{count}ショット。続けよう。',
  'hero.insightsAvg': '{count}ショット。直近5ショット平均{avg}。',
  'auth.providerSub': 'タップ一回。パスワード不要。',
  'auth.continueMeta': 'Metaで続行',
  'auth.continueGitHub': 'GitHubで続行',
  'auth.privacyNote': 'ニックネームだけ。パスワード不要。',
  'auth.nicknameTitle': 'ニックネームを決めよう。',
  'auth.nicknameSub': 'お好みで。保存するのはこれだけ。',
  'auth.nicknamePlaceholder': '例：billy_bean', 'auth.nicknameSubmit': '保存',
  'brew.decreaseFine': '{label}を細かく減らす',
  'brew.increaseFine': '{label}を細かく増やす',
  'brew.coachPreviewBadge': '初回ショット後に',
  'brew.coachPreviewDirection': '粗く',
  'brew.coachPreviewReason': '3秒長い。挽き目を粗く。',
  'brew.coachPreviewCaption': '抽出して記録。次の調整を提案します。',
  'brew.coachLine': '抽出して記録。次の調整を提案します。',
  'brew.outcomeShort': '{delta}{unit}不足',
  'brew.outcomeLong': '{delta}{unit}超過',
  'brew.holdAtTarget': 'そのまま',
  'brew.targetWas': '目標{value}{unit}',
  'brew.sectionChange': '次のショット用に調整',
  'brew.sectionHold': '次のショットも同じで',
  'brew.sectionShot': '今のショット',
  'brew.scoreBest': '自己ベスト。じっくり味わって。',
  'brew.scoreUp': '前回より+{delta}。良くなってる。',
  'brew.scoreDown': '前回より−{delta}。やり直し。',
  'brew.scoreSame': '前回と同じ。手堅い。',
  'brew.scoreFirst': '一杯目完了。ここから学習。',
  'brew.stop': 'ストップ', 'brew.saveShot': 'ショット保存',
  'brew.timingRunning': '抽出中', 'brew.timingStopped': 'ショットを記録',
  'brew.countdownSub': '準備',
  'brew.reasonRanFastBoth': '{seconds}秒短く{ml}ml超過。挽き目を細かく。',
  'brew.reasonRanSlowBoth': '{seconds}秒長く{ml}ml不足。挽き目を粗く。',
  'brew.reasonGrindAtMin': '{primary} グラインダーが最細 — ドースを増やそう。',
  'brew.reasonGrindAtMax': '{primary} グラインダーが最粗 — ドースを減らそう。',
  'brew.doseTrendUp': '3ショット連続で細挽き。+0.5gを試そう。',
  'brew.doseTrendDown': '3ショット連続で粗挽き。−0.5gを試そう。',
  'brew.doseGrindAtMin': 'グラインダー最細。抵抗を増やすため+0.5g。',
  'brew.doseGrindAtMax': 'グラインダー最粗。抵抗を減らすため−0.5g。',
  'crema.thin': '薄い', 'crema.normal': '普通', 'crema.thick': '濃い',
  'rating.crema': 'クレマ', 'rating.flavour': 'フレーバー', 'rating.strength': '濃度',
  'rating.later': '後で評価', 'rating.save': '評価を保存',
  'barista.toggleOn': 'バリスタモード', 'barista.toggleOff': 'バリスタモードオフ',
  'barista.active': 'バリスタモード', 'barista.sessionMeta': '{count}ショット · {mins}分',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Brewmieをあなた仕様に。',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'グラインダーを登録すれば、推奨値があなたの単位で出ます。',
  'premium.triggerTamper': 'スプリング/自動タンパーをモデルに反映。',
  'premium.triggerBeans': '豆を保存。袋を変えても続きから。',
  'premium.triggerHistory': '全履歴とトレンドを解放。',
  'premium.triggerBenchmarks': '毎ショットを自己ベストと比較。',
  'premium.feature1Head': 'あなたの機材',
  'premium.feature1Sub': 'グラインダー、タンパー、豆を登録。推奨値はあなたの単位で。',
  'premium.feature2Head': '全履歴',
  'premium.feature2Sub': '全ショットを保存。いつでもエクスポート。',
  'premium.feature3Head': '自己ベンチマーク',
  'premium.feature3Sub': '毎ショットを自己ベストと比較。',
  'premium.ctaBrewmie': 'Brewmieのみ', 'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Lazy Sous同梱', 'premium.priceBundle': '$9.99',
  'premium.devNote': '開発: dev pillで解放。実際の購入ではありません。',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': '古いショットは保存済み。Premiumで全履歴解放。',
  'tierLock.benchmarksLocked': 'Premiumで自己ベンチマーク解放。',
  'tierLock.genericGrinder': '汎用グラインダー使用中。Premiumであなたの機材に最適化。',
  'tierLock.genericTamper': '手動タンプ使用中。Premiumでスプリング/自動も対応。',
  'tierLock.genericBeans': '汎用ミディアムロースト。Premiumで豆を追跡。',
  'setup.profileCtaReset': 'セットアップをやり直す',
  'setup.bannerEyebrow': 'セットアップ', 'setup.bannerCta': '次へ →',
  'setup.cardLanguage': '言語', 'setup.languageLabel': '表示言語',
  'setup.languageMajor': '主要言語', 'setup.languageMore': 'その他の言語',
  'setup.languageHint': 'Brewmieは言語を自動検出します。ここで切り替え可能。主要言語以外は未訳部分が英語表示になる場合があります。',
  'setup.maintLastDone': '最終実施日',
  'setup.privacyPolicyLink': 'プライバシーポリシーを読む',
  'insights.viewAll': 'すべて表示（{count}）',
  'insights.allShotsTitle': '全ショット（{count}）',
  'insights.editShot': 'ショットを編集',
  'insights.editTime': '時間', 'insights.editVolume': '量',
  'insights.editTaste': '味', 'insights.editStrength': '濃度',
  'insights.deleteShot': '削除',
  'insights.confirmDeleteShot': 'このショットを削除しますか？元に戻せません。',
  'insights.sweetSpotEyebrow': 'あなたのスイートスポット',
  'insights.bestGrindLabel': '挽き目', 'insights.ratioLabel': '比率',
  'insights.fromNShots': '上位{n}ショットから',
  'insights.noTopShots': '85+のショットを記録するとスイートスポットが決まります。',
  'insights.personalBest': '自己ベスト',
  'insights.thisWeek': '今週', 'insights.timeWindow': '時間ウィンドウ',
  'insights.avgScore': '平均{score}', 'insights.noShotsYet': 'データなし',
  'insights.daysActive': '{count}日アクティブ',
  'insights.exportCsv': 'CSVエクスポート',
  'insights.deleteAccountEmail': 'アカウント削除はchef@lazysous.appまで',
},

'zh': {
  'common.save': '保存', 'common.close': '关闭', 'common.cancel': '取消',
  'footer.poweredBy': '由', 'footer.shotsGlobally': '杯全球萃取数据驱动',
  'header.home': '首页',
  'hero.brewFirst': '萃取你的第一杯。', 'hero.shotN': '第{n}杯萃取。', 'hero.dayN': '第{n}天。',
  'hero.statusLastShot': '上一杯：{score}。{tail}',
  'hero.statusNailed': '完美。', 'hero.statusClose': '接近了。',
  'hero.statusOneTweak': '再微调一下。', 'hero.statusKeepGoing': '重置再来。',
  'hero.statusReady': '设好配方。萃取要紧的。',
  'hero.statusKeepPulling': '继续萃取。我们在学习。',
  'hero.beanResting': '第{days}天 · 还在休养',
  'hero.beanDay': '第{days}天 · 最佳窗口',
  'hero.beanUseSoon': '第{days}天 · 尽快用完',
  'hero.beanStale': '第{days}天 · 已过期',
  'hero.beanRestingShort': '休养中', 'hero.beanDayShort': '最佳窗口',
  'hero.beanUseSoonShort': '尽快用完', 'hero.beanStaleShort': '已过期',
  'hero.weatherHumid': '{temp}°C · 湿度{humidity}%',
  'hero.weatherDry': '{temp}°C · 湿度{humidity}%',
  'hero.weatherNeutral': '{temp}°C · 湿度{humidity}%',
  'hero.setupYourKit': '你的器材。', 'hero.setupKitOnFile': '你的器材。',
  'hero.setupAllSetBig': '你的器材。', 'hero.setupAllSet': '随时开始。',
  'hero.setupAddBeans': '添加咖啡豆开始调试。',
  'hero.setupEmpty': '配置你的器材。',
  'hero.setupEmptySub': '五分钟搞定。之后每杯更好。',
  'hero.setupSectionsToGo': '还差{count}项。',
  'hero.setupSectionsToGoPlural': '还差{count}项。',
  'hero.insightsBig': '每一杯都被记录。',
  'hero.insightsEmpty': '萃取一杯，开始记录。',
  'hero.insightsEmptySub': '你的分数、研磨度、偏移。',
  'hero.insightsCount': '{count}杯。继续。',
  'hero.insightsCountPlural': '{count}杯。继续。',
  'hero.insightsAvg': '{count}杯。近5杯平均{avg}。',
  'auth.providerSub': '一键登录，无需密码。',
  'auth.continueMeta': '使用Meta继续',
  'auth.continueGitHub': '使用GitHub继续',
  'auth.privacyNote': '只是昵称。无需密码。',
  'auth.nicknameTitle': '取个昵称。',
  'auth.nicknameSub': '随你定。这是我们唯一保存的信息。',
  'auth.nicknamePlaceholder': '例如：billy_bean', 'auth.nicknameSubmit': '保存',
  'brew.decreaseFine': '微减 {label}',
  'brew.increaseFine': '微增 {label}',
  'brew.coachPreviewBadge': '第一杯之后',
  'brew.coachPreviewDirection': '更粗',
  'brew.coachPreviewReason': '长了3秒。磨粗一些。',
  'brew.coachPreviewCaption': '萃取，记录。我们告诉你下次怎么调。',
  'brew.coachLine': '萃取，记录。我们告诉你下次怎么调。',
  'brew.outcomeShort': '少 {delta}{unit}',
  'brew.outcomeLong': '多 {delta}{unit}',
  'brew.holdAtTarget': '保持',
  'brew.targetWas': '目标 {value}{unit}',
  'brew.sectionChange': '下杯调整',
  'brew.sectionHold': '下杯保持',
  'brew.sectionShot': '这一杯',
  'brew.scoreBest': '个人最佳。慢慢品。',
  'brew.scoreUp': '比上次+{delta}。在进步。',
  'brew.scoreDown': '比上次−{delta}。归零重来。',
  'brew.scoreSame': '和上次相同。手稳。',
  'brew.scoreFirst': '第一杯完成。开始学习。',
  'brew.stop': '停止', 'brew.saveShot': '保存咖啡',
  'brew.timingRunning': '萃取中', 'brew.timingStopped': '记录这一杯',
  'brew.countdownSub': '准备',
  'brew.reasonRanFastBoth': '短了{seconds}秒，多了{ml}ml。磨细一些。',
  'brew.reasonRanSlowBoth': '长了{seconds}秒，少了{ml}ml。磨粗一些。',
  'brew.reasonGrindAtMin': '{primary} 磨豆机已到最细 — 增加咖啡量。',
  'brew.reasonGrindAtMax': '{primary} 磨豆机已到最粗 — 减少咖啡量。',
  'brew.doseTrendUp': '连续3杯磨更细了。试试+0.5g。',
  'brew.doseTrendDown': '连续3杯磨更粗了。试试−0.5g。',
  'brew.doseGrindAtMin': '磨豆机已到最细。+0.5g增加阻力。',
  'brew.doseGrindAtMax': '磨豆机已到最粗。−0.5g降低阻力。',
  'crema.thin': '薄', 'crema.normal': '正常', 'crema.thick': '厚',
  'rating.crema': '油脂', 'rating.flavour': '风味', 'rating.strength': '浓度',
  'rating.later': '稍后评分', 'rating.save': '保存评分',
  'barista.toggleOn': '咖啡师模式', 'barista.toggleOff': '关闭咖啡师模式',
  'barista.active': '咖啡师模式', 'barista.sessionMeta': '{count}杯 · {mins}分钟',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': '为你定制的Brewmie。',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': '添加你的磨豆机，建议会按你的刻度给出。',
  'premium.triggerTamper': '弹簧和自动压粉器会进入模型。',
  'premium.triggerBeans': '保存你的咖啡豆。换袋后接着用。',
  'premium.triggerHistory': '解锁全部历史和趋势。',
  'premium.triggerBenchmarks': '每杯和你的最佳对比。',
  'premium.feature1Head': '你的器材',
  'premium.feature1Sub': '添加磨豆机、压粉器、豆子。建议按你的单位给出。',
  'premium.feature2Head': '全部历史',
  'premium.feature2Sub': '每杯都保存。随时导出。',
  'premium.feature3Head': '个人基准',
  'premium.feature3Sub': '每杯和你的最佳对比。',
  'premium.ctaBrewmie': '仅Brewmie', 'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': '与Lazy Sous组合', 'premium.priceBundle': '$9.99',
  'premium.devNote': '开发：通过dev pill解锁，非实际购买。',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': '旧咖啡仍有保存。Premium解锁全历史。',
  'tierLock.benchmarksLocked': '使用Premium解锁个人基准。',
  'tierLock.genericGrinder': '使用通用磨豆机。Premium按你的型号调整算法。',
  'tierLock.genericTamper': '使用手动压粉。Premium支持弹簧和自动。',
  'tierLock.genericBeans': '使用通用中度烘焙。Premium追踪你的豆。',
  'setup.profileCtaReset': '重新运行设置向导',
  'setup.bannerEyebrow': '设置', 'setup.bannerCta': '继续 →',
  'setup.cardLanguage': '语言', 'setup.languageLabel': '显示语言',
  'setup.languageMajor': '常用', 'setup.languageMore': '其他语言',
  'setup.languageHint': 'Brewmie自动检测你的语言。在此切换。常用语言之外的翻译可能不完整，会回退到英语。',
  'setup.maintLastDone': '上次完成',
  'setup.privacyPolicyLink': '阅读完整隐私政策',
  'insights.viewAll': '查看全部 {count}',
  'insights.allShotsTitle': '所有咖啡（{count}）',
  'insights.editShot': '编辑咖啡',
  'insights.editTime': '时间', 'insights.editVolume': '容量',
  'insights.editTaste': '风味', 'insights.editStrength': '浓度',
  'insights.deleteShot': '删除',
  'insights.confirmDeleteShot': '确认删除这杯？操作不可撤销。',
  'insights.sweetSpotEyebrow': '你的甜蜜点',
  'insights.bestGrindLabel': '研磨度', 'insights.ratioLabel': '比例',
  'insights.fromNShots': '基于你最好的{n}杯',
  'insights.noTopShots': '记录一杯85+分的咖啡来确定你的甜蜜点。',
  'insights.personalBest': '个人最佳',
  'insights.thisWeek': '本周', 'insights.timeWindow': '时间窗口',
  'insights.avgScore': '均分{score}', 'insights.noShotsYet': '暂无数据',
  'insights.daysActive': '活跃{count}天',
  'insights.exportCsv': '导出CSV',
  'insights.deleteAccountEmail': '删除账户请发邮件至chef@lazysous.app',
},

'ko': {
  'common.save': '저장', 'common.close': '닫기', 'common.cancel': '취소',
  'footer.poweredBy': '데이터 기반', 'footer.shotsGlobally': '잔의 전 세계 데이터',
  'header.home': '홈',
  'hero.brewFirst': '첫 잔을 내려보자.', 'hero.shotN': '{n}번째 샷.', 'hero.dayN': '{n}일째.',
  'hero.statusLastShot': '직전 점수: {score}. {tail}',
  'hero.statusNailed': '완벽.', 'hero.statusClose': '거의 다 왔어.',
  'hero.statusOneTweak': '한 번만 더 조정.', 'hero.statusKeepGoing': '리셋하고 다시.',
  'hero.statusReady': '레시피 설정. 한 잔 내리자.',
  'hero.statusKeepPulling': '계속 내리자. 학습 중.',
  'hero.beanResting': '{days}일째 · 아직 디게싱',
  'hero.beanDay': '{days}일째 · 최적 구간',
  'hero.beanUseSoon': '{days}일째 · 곧 다 써야 함',
  'hero.beanStale': '{days}일째 · 신선도 떨어짐',
  'hero.beanRestingShort': '디게싱 중', 'hero.beanDayShort': '최적 구간',
  'hero.beanUseSoonShort': '곧 소진', 'hero.beanStaleShort': '신선도 저하',
  'hero.weatherHumid': '{temp}°C · 습도 {humidity}%',
  'hero.weatherDry': '{temp}°C · 습도 {humidity}%',
  'hero.weatherNeutral': '{temp}°C · 습도 {humidity}%',
  'hero.setupYourKit': '내 장비.', 'hero.setupKitOnFile': '내 장비.',
  'hero.setupAllSetBig': '내 장비.', 'hero.setupAllSet': '준비 완료.',
  'hero.setupAddBeans': '원두를 추가해 다이얼인.',
  'hero.setupEmpty': '장비 설정.',
  'hero.setupEmptySub': '5분이면 끝. 다음 샷부터 다름.',
  'hero.setupSectionsToGo': '{count}개 남음.',
  'hero.setupSectionsToGoPlural': '{count}개 남음.',
  'hero.insightsBig': '모든 샷, 기록.',
  'hero.insightsEmpty': '한 잔 내려. 기록 시작.',
  'hero.insightsEmptySub': '점수, 분쇄, 편차.',
  'hero.insightsCount': '{count}잔. 계속.',
  'hero.insightsCountPlural': '{count}잔. 계속.',
  'hero.insightsAvg': '{count}잔. 최근 5잔 평균 {avg}.',
  'auth.providerSub': '원탭. 비밀번호 없이.',
  'auth.continueMeta': 'Meta로 계속',
  'auth.continueGitHub': 'GitHub로 계속',
  'auth.privacyNote': '닉네임만. 비밀번호 없이.',
  'auth.nicknameTitle': '닉네임을 고르세요.',
  'auth.nicknameSub': '원하시는 대로. 저장하는 건 이것뿐.',
  'auth.nicknamePlaceholder': '예: billy_bean', 'auth.nicknameSubmit': '저장',
  'brew.decreaseFine': '{label} 미세 감소',
  'brew.increaseFine': '{label} 미세 증가',
  'brew.coachPreviewBadge': '첫 샷 이후',
  'brew.coachPreviewDirection': '굵게',
  'brew.coachPreviewReason': '3초 길어. 굵게 갈자.',
  'brew.coachPreviewCaption': '내리고 기록. 다음 조정은 우리가.',
  'brew.coachLine': '내리고 기록. 다음 조정은 우리가.',
  'brew.outcomeShort': '{delta}{unit} 부족',
  'brew.outcomeLong': '{delta}{unit} 초과',
  'brew.holdAtTarget': '유지',
  'brew.targetWas': '목표 {value}{unit}',
  'brew.sectionChange': '다음 샷 조정',
  'brew.sectionHold': '다음 샷 유지',
  'brew.sectionShot': '이번 샷',
  'brew.scoreBest': '개인 최고점. 천천히.',
  'brew.scoreUp': '이전보다 +{delta}. 상승세.',
  'brew.scoreDown': '이전보다 −{delta}. 리셋.',
  'brew.scoreSame': '이전과 같음. 손 안정.',
  'brew.scoreFirst': '첫 잔 완료. 이제 학습.',
  'brew.stop': '중지', 'brew.saveShot': '샷 저장',
  'brew.timingRunning': '추출 중', 'brew.timingStopped': '샷 캡처',
  'brew.countdownSub': '준비',
  'brew.reasonRanFastBoth': '{seconds}초 짧고 {ml}ml 초과. 곱게 갈자.',
  'brew.reasonRanSlowBoth': '{seconds}초 길고 {ml}ml 부족. 굵게 갈자.',
  'brew.reasonGrindAtMin': '{primary} 그라인더 최세 — 도즈 증가.',
  'brew.reasonGrindAtMax': '{primary} 그라인더 최대 — 도즈 감소.',
  'brew.doseTrendUp': '3잔 연속 곱게 갔어. +0.5g 시도.',
  'brew.doseTrendDown': '3잔 연속 굵게 갔어. −0.5g 시도.',
  'brew.doseGrindAtMin': '그라인더 최세. +0.5g로 저항 추가.',
  'brew.doseGrindAtMax': '그라인더 최대. −0.5g로 저항 감소.',
  'crema.thin': '얇음', 'crema.normal': '보통', 'crema.thick': '두꺼움',
  'rating.crema': '크레마', 'rating.flavour': '풍미', 'rating.strength': '농도',
  'rating.later': '나중에 평가', 'rating.save': '평가 저장',
  'barista.toggleOn': '바리스타 모드', 'barista.toggleOff': '바리스타 모드 끄기',
  'barista.active': '바리스타 모드', 'barista.sessionMeta': '{count}샷 · {mins}분',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': '나만의 Brewmie.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': '그라인더 등록 시 권장값이 내 단위로 나옵니다.',
  'premium.triggerTamper': '스프링/오토 탬퍼가 모델에 반영됩니다.',
  'premium.triggerBeans': '원두 저장. 봉지 바꿔도 이어서.',
  'premium.triggerHistory': '전체 히스토리와 트렌드 해제.',
  'premium.triggerBenchmarks': '매 샷을 내 최고와 비교.',
  'premium.feature1Head': '내 장비',
  'premium.feature1Sub': '그라인더, 탬퍼, 원두. 권장값이 내 단위로.',
  'premium.feature2Head': '전체 히스토리',
  'premium.feature2Sub': '모든 샷 저장. 언제든 내보내기.',
  'premium.feature3Head': '개인 벤치마크',
  'premium.feature3Sub': '매 샷을 내 최고와 비교.',
  'premium.ctaBrewmie': 'Brewmie만', 'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Lazy Sous 번들', 'premium.priceBundle': '$9.99',
  'premium.devNote': '개발: dev pill로 해제. 실제 구매 아님.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': '이전 샷은 저장돼 있어요. Premium으로 전체 해제.',
  'tierLock.benchmarksLocked': 'Premium으로 개인 벤치마크 해제.',
  'tierLock.genericGrinder': '일반 그라인더 사용 중. Premium은 내 장비에 맞춰 조정.',
  'tierLock.genericTamper': '수동 탬프 사용 중. Premium은 스프링/오토도 지원.',
  'tierLock.genericBeans': '일반 미디엄 로스트. Premium은 내 원두 추적.',
  'setup.profileCtaReset': '설정 마법사 다시 실행',
  'setup.bannerEyebrow': '설정', 'setup.bannerCta': '계속 →',
  'setup.cardLanguage': '언어', 'setup.languageLabel': '표시 언어',
  'setup.languageMajor': '주요', 'setup.languageMore': '기타 언어',
  'setup.languageHint': 'Brewmie가 언어를 자동 감지합니다. 여기서 변경 가능. 주요 언어 외에는 번역이 불완전할 수 있고 영어로 표시됩니다.',
  'setup.maintLastDone': '마지막 실행',
  'setup.privacyPolicyLink': '전체 개인정보 처리방침 보기',
  'insights.viewAll': '전체 보기 ({count})',
  'insights.allShotsTitle': '전체 샷 ({count})',
  'insights.editShot': '샷 편집',
  'insights.editTime': '시간', 'insights.editVolume': '용량',
  'insights.editTaste': '풍미', 'insights.editStrength': '농도',
  'insights.deleteShot': '삭제',
  'insights.confirmDeleteShot': '이 샷을 삭제할까요? 되돌릴 수 없습니다.',
  'insights.sweetSpotEyebrow': '내 스위트 스팟',
  'insights.bestGrindLabel': '분쇄도', 'insights.ratioLabel': '비율',
  'insights.fromNShots': '상위 {n}잔 기준',
  'insights.noTopShots': '85+점 샷을 기록하면 스위트 스팟이 설정됩니다.',
  'insights.personalBest': '개인 최고',
  'insights.thisWeek': '이번 주', 'insights.timeWindow': '시간 범위',
  'insights.avgScore': '평균 {score}', 'insights.noShotsYet': '데이터 없음',
  'insights.daysActive': '{count}일 활동',
  'insights.exportCsv': 'CSV 내보내기',
  'insights.deleteAccountEmail': '계정 삭제는 chef@lazysous.app로',
},

'hi': {
  'common.save': 'सहेजें', 'common.close': 'बंद करें', 'common.cancel': 'रद्द',
  'footer.poweredBy': 'द्वारा संचालित', 'footer.shotsGlobally': 'शॉट वैश्विक रूप से',
  'header.home': 'होम',
  'hero.brewFirst': 'पहला निकालें।', 'hero.shotN': 'शॉट {n} का समय।', 'hero.dayN': 'दिन {n}।',
  'hero.statusLastShot': 'पिछला शॉट: {score}। {tail}',
  'hero.statusNailed': 'बिल्कुल सही।', 'hero.statusClose': 'क़रीब।',
  'hero.statusOneTweak': 'बस एक और ट्वीक।', 'hero.statusKeepGoing': 'रीसेट करें और फिर से।',
  'hero.statusReady': 'रेसिपी सेट करें। ज़रूरी निकालें।',
  'hero.statusKeepPulling': 'खींचते रहें। हम सीख रहे हैं।',
  'hero.beanResting': 'दिन {days} · अभी आराम पर',
  'hero.beanDay': 'दिन {days} · सर्वोत्तम विंडो',
  'hero.beanUseSoon': 'दिन {days} · जल्द उपयोग करें',
  'hero.beanStale': 'दिन {days} · पुराने',
  'hero.beanRestingShort': 'आराम पर', 'hero.beanDayShort': 'सर्वोत्तम विंडो',
  'hero.beanUseSoonShort': 'जल्द उपयोग', 'hero.beanStaleShort': 'पुराने',
  'hero.weatherHumid': '{temp}°C · {humidity}% आर्द्रता',
  'hero.weatherDry': '{temp}°C · {humidity}% आर्द्रता',
  'hero.weatherNeutral': '{temp}°C · {humidity}% आर्द्रता',
  'hero.setupYourKit': 'आपका सेटअप।', 'hero.setupKitOnFile': 'आपका सेटअप।',
  'hero.setupAllSetBig': 'आपका सेटअप।', 'hero.setupAllSet': 'तैयार है।',
  'hero.setupAddBeans': 'बीन्स जोड़कर ट्यून करें।',
  'hero.setupEmpty': 'अपना सेटअप करें।',
  'hero.setupEmptySub': 'पाँच मिनट। बाद के शॉट बेहतर।',
  'hero.setupSectionsToGo': '{count} सेक्शन बाक़ी।',
  'hero.setupSectionsToGoPlural': '{count} सेक्शन बाक़ी।',
  'hero.insightsBig': 'हर शॉट, ट्रैक्ड।',
  'hero.insightsEmpty': 'एक निकालें। ट्रैक करना शुरू करें।',
  'hero.insightsEmptySub': 'आपका स्कोर, ग्राइंड, ड्रिफ्ट।',
  'hero.insightsCount': '{count} शॉट। जारी रखें।',
  'hero.insightsCountPlural': '{count} शॉट। जारी रखें।',
  'hero.insightsAvg': '{count} शॉट। 5-शॉट औसत {avg}।',
  'auth.providerSub': 'एक टैप। पासवर्ड याद रखने की ज़रूरत नहीं।',
  'auth.continueMeta': 'Meta से जारी रखें',
  'auth.continueGitHub': 'GitHub से जारी रखें',
  'auth.privacyNote': 'सिर्फ़ निकनेम। पासवर्ड नहीं।',
  'auth.nicknameTitle': 'निकनेम चुनें।',
  'auth.nicknameSub': 'आपकी मर्ज़ी। हम बस यही सहेजते हैं।',
  'auth.nicknamePlaceholder': 'जैसे billy_bean', 'auth.nicknameSubmit': 'सहेजें',
  'brew.decreaseFine': '{label} थोड़ा घटाएँ',
  'brew.increaseFine': '{label} थोड़ा बढ़ाएँ',
  'brew.coachPreviewBadge': 'पहले शॉट के बाद',
  'brew.coachPreviewDirection': 'मोटा',
  'brew.coachPreviewReason': '3 सेकंड लंबा। मोटा पीसें।',
  'brew.coachPreviewCaption': 'निकालें। लॉग करें। अगला बदलाव हम बताएँगे।',
  'brew.coachLine': 'निकालें। लॉग करें। अगला बदलाव हम बताएँगे।',
  'brew.outcomeShort': '{delta} {unit} कम',
  'brew.outcomeLong': '{delta} {unit} ज़्यादा',
  'brew.holdAtTarget': 'जैसा है रखें',
  'brew.targetWas': 'लक्ष्य {value} {unit}',
  'brew.sectionChange': 'अगले शॉट के लिए बदलें',
  'brew.sectionHold': 'अगले शॉट के लिए रखें',
  'brew.sectionShot': 'यह शॉट',
  'brew.scoreBest': 'व्यक्तिगत बेस्ट। धीरे पिएँ।',
  'brew.scoreUp': 'पिछले से +{delta}। बढ़त।',
  'brew.scoreDown': 'पिछले से −{delta}। रीसेट।',
  'brew.scoreSame': 'पिछले जैसा। हाथ स्थिर।',
  'brew.scoreFirst': 'पहला हो गया। अब सीखेंगे।',
  'brew.stop': 'रोकें', 'brew.saveShot': 'शॉट सहेजें',
  'brew.timingRunning': 'निकल रहा है', 'brew.timingStopped': 'शॉट कैप्चर करें',
  'brew.countdownSub': 'तैयार',
  'brew.reasonRanFastBoth': '{seconds}s कम और {ml}ml ज़्यादा। बारीक पीसें।',
  'brew.reasonRanSlowBoth': '{seconds}s ज़्यादा और {ml}ml कम। मोटा पीसें।',
  'brew.reasonGrindAtMin': '{primary} ग्राइंडर सबसे बारीक — डोज़ बढ़ाएँ।',
  'brew.reasonGrindAtMax': '{primary} ग्राइंडर सबसे मोटा — डोज़ कम करें।',
  'brew.doseTrendUp': '3 शॉट से बारीक हो रहा है। +0.5g आज़माएँ।',
  'brew.doseTrendDown': '3 शॉट से मोटा हो रहा है। −0.5g आज़माएँ।',
  'brew.doseGrindAtMin': 'ग्राइंडर सबसे बारीक। +0.5g प्रतिरोध बढ़ाने को।',
  'brew.doseGrindAtMax': 'ग्राइंडर सबसे मोटा। −0.5g प्रतिरोध कम करने को।',
  'crema.thin': 'पतली', 'crema.normal': 'सामान्य', 'crema.thick': 'गाढ़ी',
  'rating.crema': 'क्रेमा', 'rating.flavour': 'स्वाद', 'rating.strength': 'तीव्रता',
  'rating.later': 'बाद में रेट करें', 'rating.save': 'रेटिंग सहेजें',
  'barista.toggleOn': 'बरिस्ता मोड', 'barista.toggleOff': 'बरिस्ता मोड बंद',
  'barista.active': 'बरिस्ता मोड', 'barista.sessionMeta': '{count} शॉट · {mins} मिनट',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'आपके लिए ट्यून्ड Brewmie।',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'अपना ग्राइंडर जोड़ें — सुझाव आपकी यूनिट में।',
  'premium.triggerTamper': 'स्प्रिंग/ऑटो टैम्पर मॉडल में जुड़ते हैं।',
  'premium.triggerBeans': 'अपने बीन्स सेव करें। बैग बदलें, जहाँ छोड़ा था वहीं से।',
  'premium.triggerHistory': 'पूरा इतिहास और ट्रेंड अनलॉक करें।',
  'premium.triggerBenchmarks': 'हर शॉट को अपने बेस्ट से तुलना करें।',
  'premium.feature1Head': 'आपका सेटअप',
  'premium.feature1Sub': 'ग्राइंडर, टैम्पर, बीन्स। सुझाव आपकी यूनिट में।',
  'premium.feature2Head': 'पूरा इतिहास',
  'premium.feature2Sub': 'हर शॉट सहेजा। कभी भी एक्सपोर्ट।',
  'premium.feature3Head': 'व्यक्तिगत बेंचमार्क',
  'premium.feature3Sub': 'हर शॉट को अपने बेस्ट से तुलना करें।',
  'premium.ctaBrewmie': 'सिर्फ़ Brewmie', 'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Lazy Sous बंडल', 'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev: dev pill से अनलॉक। यह असली खरीद नहीं।',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'पुराने शॉट सहेजे हैं। Premium से पूरा इतिहास।',
  'tierLock.benchmarksLocked': 'Premium से व्यक्तिगत बेंचमार्क अनलॉक करें।',
  'tierLock.genericGrinder': 'जेनेरिक ग्राइंडर। Premium आपके पर गणना तैयार करता है।',
  'tierLock.genericTamper': 'मैनुअल टैम्प। Premium स्प्रिंग/ऑटो भी जोड़ता है।',
  'tierLock.genericBeans': 'जेनेरिक मीडियम रोस्ट। Premium आपके बीन्स ट्रैक करता है।',
  'setup.profileCtaReset': 'सेटअप विज़ार्ड दोबारा चलाएँ',
  'setup.bannerEyebrow': 'सेटअप', 'setup.bannerCta': 'जारी रखें →',
  'setup.cardLanguage': 'भाषा', 'setup.languageLabel': 'डिस्प्ले भाषा',
  'setup.languageMajor': 'सामान्य', 'setup.languageMore': 'अन्य भाषाएँ',
  'setup.languageHint': 'Brewmie आपकी भाषा अपने आप पहचानता है। यहाँ से बदलें। सामान्य सूची के बाहर अनुवाद अधूरे हो सकते हैं और अंग्रेज़ी में वापस आ सकते हैं।',
  'setup.maintLastDone': 'आख़िरी बार',
  'setup.privacyPolicyLink': 'पूरी गोपनीयता नीति पढ़ें',
  'insights.viewAll': 'सभी देखें ({count})',
  'insights.allShotsTitle': 'सभी शॉट ({count})',
  'insights.editShot': 'शॉट संपादित करें',
  'insights.editTime': 'समय', 'insights.editVolume': 'मात्रा',
  'insights.editTaste': 'स्वाद', 'insights.editStrength': 'तीव्रता',
  'insights.deleteShot': 'हटाएँ',
  'insights.confirmDeleteShot': 'इस शॉट को हटाएँ? वापस नहीं आएगा।',
  'insights.sweetSpotEyebrow': 'आपका स्वीट स्पॉट',
  'insights.bestGrindLabel': 'ग्राइंड', 'insights.ratioLabel': 'अनुपात',
  'insights.fromNShots': 'आपके टॉप {n} शॉट से',
  'insights.noTopShots': 'अपना स्वीट स्पॉट तय करने के लिए 85+ का शॉट रिकॉर्ड करें।',
  'insights.personalBest': 'व्यक्तिगत बेस्ट',
  'insights.thisWeek': 'इस हफ़्ते', 'insights.timeWindow': 'समय विंडो',
  'insights.avgScore': 'औसत {score}', 'insights.noShotsYet': 'अभी डेटा नहीं',
  'insights.daysActive': '{count} दिन सक्रिय',
  'insights.exportCsv': 'CSV एक्सपोर्ट',
  'insights.deleteAccountEmail': 'अकाउंट डिलीट के लिए chef@lazysous.app पर लिखें',
},

'nl': {
  'common.save': 'Opslaan', 'common.close': 'Sluiten', 'common.cancel': 'Annuleren',
  'footer.poweredBy': 'Aangedreven door', 'footer.shotsGlobally': 'shots wereldwijd',
  'header.home': 'Home',
  'hero.brewFirst': 'Trek je eerste.', 'hero.shotN': 'Shot {n}.', 'hero.dayN': 'Dag {n}.',
  'hero.statusLastShot': 'Vorige shot: {score}. {tail}',
  'hero.statusNailed': 'Perfect.', 'hero.statusClose': 'Bijna.',
  'hero.statusOneTweak': 'Eén tweak weg.', 'hero.statusKeepGoing': 'Reset en opnieuw.',
  'hero.statusReady': 'Stel het recept in. Trek wat telt.',
  'hero.statusKeepPulling': 'Blijf trekken. We leren.',
  'hero.beanResting': 'Dag {days} · nog aan het rusten',
  'hero.beanDay': 'Dag {days} · in het venster',
  'hero.beanUseSoon': 'Dag {days} · snel opgebruiken',
  'hero.beanStale': 'Dag {days} · over de top',
  'hero.beanRestingShort': 'Aan het rusten', 'hero.beanDayShort': 'In het venster',
  'hero.beanUseSoonShort': 'Snel opgebruiken', 'hero.beanStaleShort': 'Over de top',
  'hero.weatherHumid': '{temp}°C · {humidity}% vocht',
  'hero.weatherDry': '{temp}°C · {humidity}% vocht',
  'hero.weatherNeutral': '{temp}°C · {humidity}% vocht',
  'hero.setupYourKit': 'Je setup.', 'hero.setupKitOnFile': 'Je setup.',
  'hero.setupAllSetBig': 'Je setup.', 'hero.setupAllSet': 'Klaar wanneer jij dat bent.',
  'hero.setupAddBeans': 'Voeg bonen toe om te dialen.',
  'hero.setupEmpty': 'Stel je setup in.',
  'hero.setupEmptySub': 'Vijf minuten. Betere shots daarna.',
  'hero.setupSectionsToGo': '{count} sectie te gaan.',
  'hero.setupSectionsToGoPlural': '{count} secties te gaan.',
  'hero.insightsBig': 'Elke shot, vastgelegd.',
  'hero.insightsEmpty': 'Trek er een. We beginnen met loggen.',
  'hero.insightsEmptySub': 'Je score, je maling, je drift.',
  'hero.insightsCount': '{count} shot. Blijf trekken.',
  'hero.insightsCountPlural': '{count} shots. Blijf trekken.',
  'hero.insightsAvg': '{count} shots. 5-shot gemiddelde {avg}.',
  'auth.providerSub': 'Eén tik. Geen wachtwoord nodig.',
  'auth.continueMeta': 'Doorgaan met Meta',
  'auth.continueGitHub': 'Doorgaan met GitHub',
  'auth.privacyNote': 'Alleen een nickname. Geen wachtwoord.',
  'auth.nicknameTitle': 'Kies een nickname.',
  'auth.nicknameSub': 'Aan jou. Dit is het enige wat we opslaan.',
  'auth.nicknamePlaceholder': 'bijv. billy_bean', 'auth.nicknameSubmit': 'Opslaan',
  'brew.decreaseFine': '{label} fijn verlagen',
  'brew.increaseFine': '{label} fijn verhogen',
  'brew.coachPreviewBadge': 'Na je eerste shot',
  'brew.coachPreviewDirection': 'Grover',
  'brew.coachPreviewReason': '3s te lang. Grover malen.',
  'brew.coachPreviewCaption': 'Trek. Log. We vertellen wat je moet aanpassen.',
  'brew.coachLine': 'Trek. Log. We vertellen wat je hierna moet aanpassen.',
  'brew.outcomeShort': '{delta} {unit} te weinig',
  'brew.outcomeLong': '{delta} {unit} te veel',
  'brew.holdAtTarget': 'Behoud',
  'brew.targetWas': 'doel {value} {unit}',
  'brew.sectionChange': 'Aanpassen voor volgende shot',
  'brew.sectionHold': 'Behouden voor volgende shot',
  'brew.sectionShot': 'Deze shot',
  'brew.scoreBest': 'Persoonlijk record. Drink hem traag.',
  'brew.scoreUp': '+{delta} op de vorige. Stijgt.',
  'brew.scoreDown': '−{delta} op de vorige. Reset.',
  'brew.scoreSame': 'Zelfde als vorige. Stevige hand.',
  'brew.scoreFirst': 'Eerste binnen. Nu leren we.',
  'brew.stop': 'STOP', 'brew.saveShot': 'SHOT OPSLAAN',
  'brew.timingRunning': 'Aan het trekken', 'brew.timingStopped': 'Shot vastleggen',
  'brew.countdownSub': 'Maak je klaar',
  'brew.reasonRanFastBoth': '{seconds}s te kort en {ml}ml te veel. Fijner malen.',
  'brew.reasonRanSlowBoth': '{seconds}s te lang en {ml}ml te weinig. Grover malen.',
  'brew.reasonGrindAtMin': '{primary} Molen op fijnste — verhoog de dosis.',
  'brew.reasonGrindAtMax': '{primary} Molen op grofste — verlaag de dosis.',
  'brew.doseTrendUp': '3 shots fijner gegaan. Probeer +0,5g.',
  'brew.doseTrendDown': '3 shots grover gegaan. Probeer −0,5g.',
  'brew.doseGrindAtMin': 'Molen op fijnste. +0,5g voor meer weerstand.',
  'brew.doseGrindAtMax': 'Molen op grofste. −0,5g voor minder weerstand.',
  'crema.thin': 'Dun', 'crema.normal': 'Normaal', 'crema.thick': 'Dik',
  'rating.crema': 'Crema', 'rating.flavour': 'Smaak', 'rating.strength': 'Sterkte',
  'rating.later': 'Later beoordelen', 'rating.save': 'Beoordeling opslaan',
  'barista.toggleOn': 'Barista-modus', 'barista.toggleOff': 'Barista-modus uit',
  'barista.active': 'Barista-modus', 'barista.sessionMeta': '{count} shots · {mins} min',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Brewmie, afgesteld op jou.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'Voeg je molen toe; aanbevelingen komen in jouw eenheden.',
  'premium.triggerTamper': 'Veer- en auto-tampers gaan in het model.',
  'premium.triggerBeans': 'Bewaar je bonen. Ander zakje, pak je draad weer op.',
  'premium.triggerHistory': 'Ontgrendel volledige historie en trends.',
  'premium.triggerBenchmarks': 'Vergelijk elke shot met je eigen beste.',
  'premium.feature1Head': 'Je setup',
  'premium.feature1Sub': 'Molen, tamper, bonen. Aanbevelingen in jouw eenheden.',
  'premium.feature2Head': 'Volledige historie',
  'premium.feature2Sub': 'Elke shot bewaard. Exporteren wanneer je wil.',
  'premium.feature3Head': 'Persoonlijke benchmarks',
  'premium.feature3Sub': 'Vergelijk elke shot met je eigen beste.',
  'premium.ctaBrewmie': 'Alleen Brewmie', 'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Bundel met Lazy Sous', 'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev: ontgrendel via dev pill. Geen echte aankoop.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'Oudere shots zijn bewaard. Volledige historie met Premium.',
  'tierLock.benchmarksLocked': 'Ontgrendel persoonlijke benchmarks met Premium.',
  'tierLock.genericGrinder': 'Generieke molen. Premium stemt de berekening af op de jouwe.',
  'tierLock.genericTamper': 'Handmatig tampen. Premium voegt veer en auto toe.',
  'tierLock.genericBeans': 'Generieke medium roast. Premium volgt je bonen.',
  'setup.profileCtaReset': 'Setup opnieuw doorlopen',
  'setup.bannerEyebrow': 'Setup', 'setup.bannerCta': 'Doorgaan →',
  'setup.cardLanguage': 'Taal', 'setup.languageLabel': 'Weergavetaal',
  'setup.languageMajor': 'Veelvoorkomend', 'setup.languageMore': 'Andere talen',
  'setup.languageHint': 'Brewmie detecteert je taal automatisch. Kies hier een andere. Vertalingen buiten de veelvoorkomende lijst kunnen onvolledig zijn en vallen terug op Engels.',
  'setup.maintLastDone': 'Laatst gedaan',
  'setup.privacyPolicyLink': 'Volledig privacybeleid lezen',
  'insights.viewAll': 'Alle {count} bekijken',
  'insights.allShotsTitle': 'Alle shots ({count})',
  'insights.editShot': 'Shot bewerken',
  'insights.editTime': 'Tijd', 'insights.editVolume': 'Volume',
  'insights.editTaste': 'Smaak', 'insights.editStrength': 'Sterkte',
  'insights.deleteShot': 'Verwijderen',
  'insights.confirmDeleteShot': 'Deze shot verwijderen? Niet ongedaan te maken.',
  'insights.sweetSpotEyebrow': 'Jouw sweet spot',
  'insights.bestGrindLabel': 'maling', 'insights.ratioLabel': 'ratio',
  'insights.fromNShots': 'uit je top {n} shots',
  'insights.noTopShots': 'Log een shot met 85+ om je sweet spot in te stellen.',
  'insights.personalBest': 'Persoonlijk record',
  'insights.thisWeek': 'Deze week', 'insights.timeWindow': 'Tijdsvenster',
  'insights.avgScore': 'gem. {score}', 'insights.noShotsYet': 'nog geen data',
  'insights.daysActive': '{count} dagen actief',
  'insights.exportCsv': 'CSV exporteren',
  'insights.deleteAccountEmail': 'Account verwijderen? Mail chef@lazysous.app',
},

'sv': {
  'common.save': 'Spara', 'common.close': 'Stäng', 'common.cancel': 'Avbryt',
  'footer.poweredBy': 'Drivs av', 'footer.shotsGlobally': 'shots globalt',
  'header.home': 'Hem',
  'hero.brewFirst': 'Dra din första.', 'hero.shotN': 'Shot {n}.', 'hero.dayN': 'Dag {n}.',
  'hero.statusLastShot': 'Senaste shot: {score}. {tail}',
  'hero.statusNailed': 'Pricksäkert.', 'hero.statusClose': 'Nära.',
  'hero.statusOneTweak': 'En justering bort.', 'hero.statusKeepGoing': 'Återställ och kör igen.',
  'hero.statusReady': 'Sätt receptet. Dra det som räknas.',
  'hero.statusKeepPulling': 'Fortsätt dra. Vi lär oss.',
  'hero.beanResting': 'Dag {days} · vilar än',
  'hero.beanDay': 'Dag {days} · i fönstret',
  'hero.beanUseSoon': 'Dag {days} · använd snart',
  'hero.beanStale': 'Dag {days} · över bästa tid',
  'hero.beanRestingShort': 'Vilar', 'hero.beanDayShort': 'I fönstret',
  'hero.beanUseSoonShort': 'Använd snart', 'hero.beanStaleShort': 'Över bästa tid',
  'hero.weatherHumid': '{temp}°C · {humidity}% luftfuktighet',
  'hero.weatherDry': '{temp}°C · {humidity}% luftfuktighet',
  'hero.weatherNeutral': '{temp}°C · {humidity}% luftfuktighet',
  'hero.setupYourKit': 'Din utrustning.', 'hero.setupKitOnFile': 'Din utrustning.',
  'hero.setupAllSetBig': 'Din utrustning.', 'hero.setupAllSet': 'Redo när du är.',
  'hero.setupAddBeans': 'Lägg till bönor för att kalibrera.',
  'hero.setupEmpty': 'Ställ in din utrustning.',
  'hero.setupEmptySub': 'Fem minuter. Bättre shots efter.',
  'hero.setupSectionsToGo': '{count} avsnitt kvar.',
  'hero.setupSectionsToGoPlural': '{count} avsnitt kvar.',
  'hero.insightsBig': 'Varje shot, loggad.',
  'hero.insightsEmpty': 'Dra en. Vi börjar logga.',
  'hero.insightsEmptySub': 'Din poäng, din malning, din drift.',
  'hero.insightsCount': '{count} shot. Fortsätt.',
  'hero.insightsCountPlural': '{count} shots. Fortsätt.',
  'hero.insightsAvg': '{count} shots. 5-shot snitt {avg}.',
  'auth.providerSub': 'Ett tryck. Inget lösenord att komma ihåg.',
  'auth.continueMeta': 'Fortsätt med Meta',
  'auth.continueGitHub': 'Fortsätt med GitHub',
  'auth.privacyNote': 'Bara ett smeknamn. Inget lösenord.',
  'auth.nicknameTitle': 'Välj ett smeknamn.',
  'auth.nicknameSub': 'Upp till dig. Det är allt vi sparar.',
  'auth.nicknamePlaceholder': 't.ex. billy_bean', 'auth.nicknameSubmit': 'Spara',
  'brew.decreaseFine': 'Minska {label} fint',
  'brew.increaseFine': 'Öka {label} fint',
  'brew.coachPreviewBadge': 'Efter din första shot',
  'brew.coachPreviewDirection': 'Grövre',
  'brew.coachPreviewReason': '3s för lång. Mal grövre.',
  'brew.coachPreviewCaption': 'Dra. Logga. Vi säger vad du ska ändra.',
  'brew.coachLine': 'Dra. Logga. Vi säger vad du ska ändra härnäst.',
  'brew.outcomeShort': '{delta} {unit} för lite',
  'brew.outcomeLong': '{delta} {unit} för mycket',
  'brew.holdAtTarget': 'Behåll',
  'brew.targetWas': 'mål {value} {unit}',
  'brew.sectionChange': 'Ändra till nästa shot',
  'brew.sectionHold': 'Behåll till nästa shot',
  'brew.sectionShot': 'Den här shoten',
  'brew.scoreBest': 'Personbästa. Smaka långsamt.',
  'brew.scoreUp': '+{delta} mot förra. Bygger.',
  'brew.scoreDown': '−{delta} mot förra. Återställ.',
  'brew.scoreSame': 'Samma som förra. Stadig hand.',
  'brew.scoreFirst': 'Första klar. Nu lär vi oss.',
  'brew.stop': 'STOPP', 'brew.saveShot': 'SPARA SHOT',
  'brew.timingRunning': 'Drar', 'brew.timingStopped': 'Fånga shoten',
  'brew.countdownSub': 'Gör dig redo',
  'brew.reasonRanFastBoth': '{seconds}s för kort och {ml}ml för mycket. Mal finare.',
  'brew.reasonRanSlowBoth': '{seconds}s för lång och {ml}ml för lite. Mal grövre.',
  'brew.reasonGrindAtMin': '{primary} Kvarn på finaste — höj dosen.',
  'brew.reasonGrindAtMax': '{primary} Kvarn på grövsta — sänk dosen.',
  'brew.doseTrendUp': 'Finare i 3 shots i rad. Testa +0,5g.',
  'brew.doseTrendDown': 'Grövre i 3 shots i rad. Testa −0,5g.',
  'brew.doseGrindAtMin': 'Kvarn på finaste. +0,5g för mer motstånd.',
  'brew.doseGrindAtMax': 'Kvarn på grövsta. −0,5g för mindre motstånd.',
  'crema.thin': 'Tunn', 'crema.normal': 'Normal', 'crema.thick': 'Tjock',
  'rating.crema': 'Crema', 'rating.flavour': 'Smak', 'rating.strength': 'Styrka',
  'rating.later': 'Betygsätt senare', 'rating.save': 'Spara betyg',
  'barista.toggleOn': 'Baristaläge', 'barista.toggleOff': 'Stäng av baristaläge',
  'barista.active': 'Baristaläge', 'barista.sessionMeta': '{count} shots · {mins} min',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Brewmie, inställd för dig.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'Lägg in din kvarn så kommer rekommendationer i dina enheter.',
  'premium.triggerTamper': 'Fjäder- och autotampers går in i modellen.',
  'premium.triggerBeans': 'Spara dina bönor. Byt påse, fortsätt där du var.',
  'premium.triggerHistory': 'Lås upp full historik och trender.',
  'premium.triggerBenchmarks': 'Jämför varje shot med ditt bästa.',
  'premium.feature1Head': 'Din utrustning',
  'premium.feature1Sub': 'Kvarn, tamper, bönor. Rekommendationer i dina enheter.',
  'premium.feature2Head': 'Full historik',
  'premium.feature2Sub': 'Varje shot sparad. Exportera när du vill.',
  'premium.feature3Head': 'Personliga riktmärken',
  'premium.feature3Sub': 'Jämför varje shot med ditt bästa.',
  'premium.ctaBrewmie': 'Bara Brewmie', 'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Paket med Lazy Sous', 'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev: lås upp via dev pill. Inget riktigt köp.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'Äldre shots är sparade. Full historik med Premium.',
  'tierLock.benchmarksLocked': 'Lås upp personliga riktmärken med Premium.',
  'tierLock.genericGrinder': 'Generisk kvarn. Premium kalibrerar mot din.',
  'tierLock.genericTamper': 'Manuell tamp. Premium lägger till fjäder och auto.',
  'tierLock.genericBeans': 'Generisk medelrostad. Premium spårar dina bönor.',
  'setup.profileCtaReset': 'Kör guiden igen',
  'setup.bannerEyebrow': 'Inställningar', 'setup.bannerCta': 'Fortsätt →',
  'setup.cardLanguage': 'Språk', 'setup.languageLabel': 'Visningsspråk',
  'setup.languageMajor': 'Vanliga', 'setup.languageMore': 'Andra språk',
  'setup.languageHint': 'Brewmie upptäcker ditt språk automatiskt. Välj ett annat här. Översättningar utanför vanliga listan kan vara ofullständiga och falla tillbaka på engelska.',
  'setup.maintLastDone': 'Senast gjort',
  'setup.privacyPolicyLink': 'Läs hela integritetspolicyn',
  'insights.viewAll': 'Visa alla {count}',
  'insights.allShotsTitle': 'Alla shots ({count})',
  'insights.editShot': 'Redigera shot',
  'insights.editTime': 'Tid', 'insights.editVolume': 'Volym',
  'insights.editTaste': 'Smak', 'insights.editStrength': 'Styrka',
  'insights.deleteShot': 'Radera',
  'insights.confirmDeleteShot': 'Radera denna shot? Går inte att ångra.',
  'insights.sweetSpotEyebrow': 'Din sweet spot',
  'insights.bestGrindLabel': 'malning', 'insights.ratioLabel': 'ratio',
  'insights.fromNShots': 'från dina topp {n} shots',
  'insights.noTopShots': 'Logga en shot med 85+ för att sätta din sweet spot.',
  'insights.personalBest': 'Personbästa',
  'insights.thisWeek': 'Denna vecka', 'insights.timeWindow': 'Tidsfönster',
  'insights.avgScore': 'snitt {score}', 'insights.noShotsYet': 'ingen data än',
  'insights.daysActive': 'Aktiv {count} dagar',
  'insights.exportCsv': 'Exportera CSV',
  'insights.deleteAccountEmail': 'Radera konto? Mejla chef@lazysous.app',
},

'tr': {
  'common.save': 'Kaydet', 'common.close': 'Kapat', 'common.cancel': 'İptal',
  'footer.poweredBy': 'Destek veren:', 'footer.shotsGlobally': 'shot dünya genelinde',
  'header.home': 'Ana sayfa',
  'hero.brewFirst': 'İlkini çek.', 'hero.shotN': 'Shot {n}.', 'hero.dayN': '{n}. gün.',
  'hero.statusLastShot': 'Son shot: {score}. {tail}',
  'hero.statusNailed': 'Tam isabet.', 'hero.statusClose': 'Yaklaştın.',
  'hero.statusOneTweak': 'Bir ayar uzakta.', 'hero.statusKeepGoing': 'Sıfırla, baştan başla.',
  'hero.statusReady': 'Tarifi ayarla. Önemli olanı çek.',
  'hero.statusKeepPulling': 'Çekmeye devam. Öğreniyoruz.',
  'hero.beanResting': '{days}. gün · hâlâ dinleniyor',
  'hero.beanDay': '{days}. gün · ideal aralıkta',
  'hero.beanUseSoon': '{days}. gün · yakında bitir',
  'hero.beanStale': '{days}. gün · tazeliğini yitirdi',
  'hero.beanRestingShort': 'Dinleniyor', 'hero.beanDayShort': 'İdeal aralıkta',
  'hero.beanUseSoonShort': 'Yakında bitir', 'hero.beanStaleShort': 'Tazeliği yitti',
  'hero.weatherHumid': '{temp}°C · %{humidity} nem',
  'hero.weatherDry': '{temp}°C · %{humidity} nem',
  'hero.weatherNeutral': '{temp}°C · %{humidity} nem',
  'hero.setupYourKit': 'Senin ekipmanın.', 'hero.setupKitOnFile': 'Senin ekipmanın.',
  'hero.setupAllSetBig': 'Senin ekipmanın.', 'hero.setupAllSet': 'Hazırsın istediğinde.',
  'hero.setupAddBeans': 'Çekirdek ekle, ayarlamaya başla.',
  'hero.setupEmpty': 'Ekipmanını kur.',
  'hero.setupEmptySub': 'Beş dakika. Sonraki shotlar daha iyi.',
  'hero.setupSectionsToGo': '{count} bölüm kaldı.',
  'hero.setupSectionsToGoPlural': '{count} bölüm kaldı.',
  'hero.insightsBig': 'Her shot kayıtta.',
  'hero.insightsEmpty': 'Bir tane çek. Kaydetmeye başlıyoruz.',
  'hero.insightsEmptySub': 'Puanın, öğütümün, sapman.',
  'hero.insightsCount': '{count} shot. Devam et.',
  'hero.insightsCountPlural': '{count} shot. Devam et.',
  'hero.insightsAvg': '{count} shot. Son 5 ortalama {avg}.',
  'auth.providerSub': 'Tek dokunuş. Şifre ezberlemeye gerek yok.',
  'auth.continueMeta': 'Meta ile devam et',
  'auth.continueGitHub': 'GitHub ile devam et',
  'auth.privacyNote': 'Sadece bir takma ad. Şifre yok.',
  'auth.nicknameTitle': 'Bir takma ad seç.',
  'auth.nicknameSub': 'Sen bilirsin. Sakladığımız tek şey bu.',
  'auth.nicknamePlaceholder': 'örn. billy_bean', 'auth.nicknameSubmit': 'Kaydet',
  'brew.decreaseFine': '{label} ince azalt',
  'brew.increaseFine': '{label} ince artır',
  'brew.coachPreviewBadge': 'İlk shottan sonra',
  'brew.coachPreviewDirection': 'Daha iri',
  'brew.coachPreviewReason': '3s uzun. Daha iri öğüt.',
  'brew.coachPreviewCaption': 'Çek. Kaydet. Ne değişeceğini söyleriz.',
  'brew.coachLine': 'Çek. Kaydet. Bir sonrakinde ne değişeceğini söyleriz.',
  'brew.outcomeShort': '{delta} {unit} eksik',
  'brew.outcomeLong': '{delta} {unit} fazla',
  'brew.holdAtTarget': 'Olduğu gibi',
  'brew.targetWas': 'hedef {value} {unit}',
  'brew.sectionChange': 'Sonraki shot için değişiklik',
  'brew.sectionHold': 'Sonraki shot için koru',
  'brew.sectionShot': 'Bu shot',
  'brew.scoreBest': 'Kişisel rekor. Yavaş tat.',
  'brew.scoreUp': 'Öncekine göre +{delta}. Yükseliyor.',
  'brew.scoreDown': 'Öncekine göre −{delta}. Sıfırla.',
  'brew.scoreSame': 'Öncekiyle aynı. Stabil el.',
  'brew.scoreFirst': 'İlk tamam. Öğrenmeye başlıyoruz.',
  'brew.stop': 'DURDUR', 'brew.saveShot': 'SHOTU KAYDET',
  'brew.timingRunning': 'Çekiyor', 'brew.timingStopped': 'Shotu yakala',
  'brew.countdownSub': 'Hazırlan',
  'brew.reasonRanFastBoth': '{seconds}s kısa ve {ml}ml fazla. Daha ince öğüt.',
  'brew.reasonRanSlowBoth': '{seconds}s uzun ve {ml}ml eksik. Daha iri öğüt.',
  'brew.reasonGrindAtMin': '{primary} Değirmen en incede — dozu artır.',
  'brew.reasonGrindAtMax': '{primary} Değirmen en iride — dozu azalt.',
  'brew.doseTrendUp': '3 shottur daha ince gidiyorsun. +0,5g dene.',
  'brew.doseTrendDown': '3 shottur daha iri gidiyorsun. −0,5g dene.',
  'brew.doseGrindAtMin': 'Değirmen en incede. Direnç için +0,5g.',
  'brew.doseGrindAtMax': 'Değirmen en iride. Direnci düşürmek için −0,5g.',
  'crema.thin': 'İnce', 'crema.normal': 'Normal', 'crema.thick': 'Kalın',
  'rating.crema': 'Krema', 'rating.flavour': 'Tat', 'rating.strength': 'Yoğunluk',
  'rating.later': 'Sonra puanla', 'rating.save': 'Puanı kaydet',
  'barista.toggleOn': 'Barista modu', 'barista.toggleOff': 'Barista modunu kapat',
  'barista.active': 'Barista modu', 'barista.sessionMeta': '{count} shot · {mins} dk',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Sana göre ayarlanmış Brewmie.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'Değirmenini ekle; öneriler senin birimlerinde gelir.',
  'premium.triggerTamper': 'Yaylı ve otomatik tamperler modele girer.',
  'premium.triggerBeans': 'Çekirdeklerini kaydet. Paket değiştir, kaldığın yerden devam et.',
  'premium.triggerHistory': 'Tüm geçmişi ve trendleri aç.',
  'premium.triggerBenchmarks': 'Her shotu kendi rekorunla karşılaştır.',
  'premium.feature1Head': 'Senin ekipmanın',
  'premium.feature1Sub': 'Değirmen, tamper, çekirdek. Öneriler senin birimlerinde.',
  'premium.feature2Head': 'Tüm geçmiş',
  'premium.feature2Sub': 'Her shot kayıtta. İstediğinde dışa aktar.',
  'premium.feature3Head': 'Kişisel rekorlar',
  'premium.feature3Sub': 'Her shotu kendi rekorunla karşılaştır.',
  'premium.ctaBrewmie': 'Sadece Brewmie', 'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Lazy Sous paketi', 'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev: dev pill ile açılır. Gerçek satın alma değil.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'Eski shotlar kayıtta. Tam geçmiş Premium ile.',
  'tierLock.benchmarksLocked': 'Kişisel rekorları Premium ile aç.',
  'tierLock.genericGrinder': 'Genel değirmen kullanılıyor. Premium senin için kalibre eder.',
  'tierLock.genericTamper': 'Manuel tamp. Premium yaylı ve otomatik de ekler.',
  'tierLock.genericBeans': 'Genel orta kavurma. Premium çekirdeklerini takip eder.',
  'setup.profileCtaReset': 'Kurulum sihirbazını yeniden çalıştır',
  'setup.bannerEyebrow': 'Kurulum', 'setup.bannerCta': 'Devam →',
  'setup.cardLanguage': 'Dil', 'setup.languageLabel': 'Görünüm dili',
  'setup.languageMajor': 'Sık kullanılan', 'setup.languageMore': 'Diğer diller',
  'setup.languageHint': 'Brewmie dilini otomatik algılar. Buradan değiştir. Sık kullanılan listenin dışındaki çeviriler eksik olabilir, İngilizceye döner.',
  'setup.maintLastDone': 'Son yapılan',
  'setup.privacyPolicyLink': 'Tüm gizlilik politikasını oku',
  'insights.viewAll': 'Tümünü gör ({count})',
  'insights.allShotsTitle': 'Tüm shotlar ({count})',
  'insights.editShot': 'Shotu düzenle',
  'insights.editTime': 'Süre', 'insights.editVolume': 'Hacim',
  'insights.editTaste': 'Tat', 'insights.editStrength': 'Yoğunluk',
  'insights.deleteShot': 'Sil',
  'insights.confirmDeleteShot': 'Bu shotu silelim mi? Geri alınmaz.',
  'insights.sweetSpotEyebrow': 'Senin sweet spotun',
  'insights.bestGrindLabel': 'öğütüm', 'insights.ratioLabel': 'oran',
  'insights.fromNShots': 'en iyi {n} shotundan',
  'insights.noTopShots': 'Sweet spotu belirlemek için 85+ puanlı bir shot kaydet.',
  'insights.personalBest': 'Kişisel rekor',
  'insights.thisWeek': 'Bu hafta', 'insights.timeWindow': 'Süre aralığı',
  'insights.avgScore': 'ort. {score}', 'insights.noShotsYet': 'henüz veri yok',
  'insights.daysActive': '{count} gün aktif',
  'insights.exportCsv': 'CSV dışa aktar',
  'insights.deleteAccountEmail': 'Hesabı silmek için chef@lazysous.app',
},

'pl': {
  'common.save': 'Zapisz', 'common.close': 'Zamknij', 'common.cancel': 'Anuluj',
  'footer.poweredBy': 'Napędzane przez', 'footer.shotsGlobally': 'shotów na świecie',
  'header.home': 'Strona główna',
  'hero.brewFirst': 'Wyciągnij pierwszego.', 'hero.shotN': 'Shot {n}.', 'hero.dayN': 'Dzień {n}.',
  'hero.statusLastShot': 'Ostatni shot: {score}. {tail}',
  'hero.statusNailed': 'Trafione.', 'hero.statusClose': 'Blisko.',
  'hero.statusOneTweak': 'Jeszcze jedna poprawka.', 'hero.statusKeepGoing': 'Reset i jeszcze raz.',
  'hero.statusReady': 'Ustaw przepis. Wyciągnij to, co liczy.',
  'hero.statusKeepPulling': 'Ciągnij dalej. Uczymy się.',
  'hero.beanResting': 'Dzień {days} · jeszcze odpoczywa',
  'hero.beanDay': 'Dzień {days} · w oknie',
  'hero.beanUseSoon': 'Dzień {days} · wykorzystaj wkrótce',
  'hero.beanStale': 'Dzień {days} · przeszły',
  'hero.beanRestingShort': 'Odpoczywa', 'hero.beanDayShort': 'W oknie',
  'hero.beanUseSoonShort': 'Wykorzystaj wkrótce', 'hero.beanStaleShort': 'Przeszły',
  'hero.weatherHumid': '{temp}°C · {humidity}% wilgotność',
  'hero.weatherDry': '{temp}°C · {humidity}% wilgotność',
  'hero.weatherNeutral': '{temp}°C · {humidity}% wilgotność',
  'hero.setupYourKit': 'Twój sprzęt.', 'hero.setupKitOnFile': 'Twój sprzęt.',
  'hero.setupAllSetBig': 'Twój sprzęt.', 'hero.setupAllSet': 'Gotowe gdy jesteś.',
  'hero.setupAddBeans': 'Dodaj ziarna, by skalibrować.',
  'hero.setupEmpty': 'Skonfiguruj sprzęt.',
  'hero.setupEmptySub': 'Pięć minut. Lepsze shoty potem.',
  'hero.setupSectionsToGo': 'Została {count} sekcja.',
  'hero.setupSectionsToGoPlural': 'Zostało {count} sekcji.',
  'hero.insightsBig': 'Każdy shot zapisany.',
  'hero.insightsEmpty': 'Wyciągnij jednego. Zaczynamy logować.',
  'hero.insightsEmptySub': 'Twój wynik, mielenie, dryf.',
  'hero.insightsCount': '{count} shot. Kontynuuj.',
  'hero.insightsCountPlural': '{count} shotów. Kontynuuj.',
  'hero.insightsAvg': '{count} shotów. Średnia z 5: {avg}.',
  'auth.providerSub': 'Jeden dotyk. Bez haseł.',
  'auth.continueMeta': 'Kontynuuj z Meta',
  'auth.continueGitHub': 'Kontynuuj z GitHub',
  'auth.privacyNote': 'Tylko nick. Bez haseł.',
  'auth.nicknameTitle': 'Wybierz nick.',
  'auth.nicknameSub': 'Jak chcesz. To jedyne, co zapisujemy.',
  'auth.nicknamePlaceholder': 'np. billy_bean', 'auth.nicknameSubmit': 'Zapisz',
  'brew.decreaseFine': 'Zmniejsz {label} (drobno)',
  'brew.increaseFine': 'Zwiększ {label} (drobno)',
  'brew.coachPreviewBadge': 'Po pierwszym shocie',
  'brew.coachPreviewDirection': 'Grubiej',
  'brew.coachPreviewReason': '3s za długo. Miel grubiej.',
  'brew.coachPreviewCaption': 'Wyciągnij. Zaloguj. Powiemy co zmienić.',
  'brew.coachLine': 'Wyciągnij. Zaloguj. Powiemy co zmienić następnym razem.',
  'brew.outcomeShort': '{delta} {unit} za mało',
  'brew.outcomeLong': '{delta} {unit} za dużo',
  'brew.holdAtTarget': 'Bez zmian',
  'brew.targetWas': 'cel {value} {unit}',
  'brew.sectionChange': 'Zmień na następny shot',
  'brew.sectionHold': 'Zostaw na następny shot',
  'brew.sectionShot': 'Ten shot',
  'brew.scoreBest': 'Rekord osobisty. Smakuj powoli.',
  'brew.scoreUp': '+{delta} do poprzedniego. Idzie w górę.',
  'brew.scoreDown': '−{delta} do poprzedniego. Reset.',
  'brew.scoreSame': 'Tak jak poprzedni. Pewna ręka.',
  'brew.scoreFirst': 'Pierwszy w kasie. Teraz się uczymy.',
  'brew.stop': 'STOP', 'brew.saveShot': 'ZAPISZ SHOT',
  'brew.timingRunning': 'Wyciąganie', 'brew.timingStopped': 'Zapisz shot',
  'brew.countdownSub': 'Gotowy',
  'brew.reasonRanFastBoth': '{seconds}s za krótko i {ml}ml za dużo. Miel drobniej.',
  'brew.reasonRanSlowBoth': '{seconds}s za długo i {ml}ml za mało. Miel grubiej.',
  'brew.reasonGrindAtMin': '{primary} Młynek na min — zwiększ dawkę.',
  'brew.reasonGrindAtMax': '{primary} Młynek na max — zmniejsz dawkę.',
  'brew.doseTrendUp': '3 shoty drobniej. Spróbuj +0,5g.',
  'brew.doseTrendDown': '3 shoty grubiej. Spróbuj −0,5g.',
  'brew.doseGrindAtMin': 'Młynek na min. +0,5g dla większego oporu.',
  'brew.doseGrindAtMax': 'Młynek na max. −0,5g dla mniejszego oporu.',
  'crema.thin': 'Cienka', 'crema.normal': 'Normalna', 'crema.thick': 'Gęsta',
  'rating.crema': 'Crema', 'rating.flavour': 'Smak', 'rating.strength': 'Moc',
  'rating.later': 'Oceń później', 'rating.save': 'Zapisz ocenę',
  'barista.toggleOn': 'Tryb baristy', 'barista.toggleOff': 'Wyłącz tryb baristy',
  'barista.active': 'Tryb baristy', 'barista.sessionMeta': '{count} shotów · {mins} min',
  'premium.eyebrow': 'Brewmie Premium',
  'premium.title': 'Brewmie dopasowany do Ciebie.',
  'premium.lockBadge': 'Premium',
  'premium.triggerGrinder': 'Dodaj młynek — rekomendacje w Twoich jednostkach.',
  'premium.triggerTamper': 'Tampery sprężynowe i auto wchodzą do modelu.',
  'premium.triggerBeans': 'Zapisuj ziarna. Zmień paczkę, kontynuuj.',
  'premium.triggerHistory': 'Odblokuj pełną historię i trendy.',
  'premium.triggerBenchmarks': 'Porównuj każdy shot z własnym rekordem.',
  'premium.feature1Head': 'Twój sprzęt',
  'premium.feature1Sub': 'Młynek, tamper, ziarna. Rekomendacje w Twoich jednostkach.',
  'premium.feature2Head': 'Pełna historia',
  'premium.feature2Sub': 'Każdy shot zapisany. Eksport kiedy chcesz.',
  'premium.feature3Head': 'Rekordy osobiste',
  'premium.feature3Sub': 'Porównuj każdy shot z własnym rekordem.',
  'premium.ctaBrewmie': 'Tylko Brewmie', 'premium.priceBrewmie': '$6.99',
  'premium.ctaBundle': 'Pakiet z Lazy Sous', 'premium.priceBundle': '$9.99',
  'premium.devNote': 'Dev: odblokowanie przez dev pill. To nie prawdziwy zakup.',
  'tierLock.badge': 'Premium',
  'tierLock.historyMore': 'Starsze shoty są zapisane. Pełna historia z Premium.',
  'tierLock.benchmarksLocked': 'Odblokuj rekordy osobiste z Premium.',
  'tierLock.genericGrinder': 'Generyczny młynek. Premium kalibruje pod Twój.',
  'tierLock.genericTamper': 'Ręczny tamp. Premium dodaje sprężynowy i auto.',
  'tierLock.genericBeans': 'Generyczne średnie palenie. Premium śledzi Twoje ziarna.',
  'setup.profileCtaReset': 'Uruchom kreator ponownie',
  'setup.bannerEyebrow': 'Kreator', 'setup.bannerCta': 'Dalej →',
  'setup.cardLanguage': 'Język', 'setup.languageLabel': 'Język wyświetlania',
  'setup.languageMajor': 'Popularne', 'setup.languageMore': 'Inne języki',
  'setup.languageHint': 'Brewmie wykrywa język automatycznie. Wybierz inny tutaj. Tłumaczenia poza popularnymi mogą być niepełne i wrócić do angielskiego.',
  'setup.maintLastDone': 'Ostatnio',
  'setup.privacyPolicyLink': 'Przeczytaj politykę prywatności',
  'insights.viewAll': 'Pokaż wszystkie ({count})',
  'insights.allShotsTitle': 'Wszystkie shoty ({count})',
  'insights.editShot': 'Edytuj shot',
  'insights.editTime': 'Czas', 'insights.editVolume': 'Objętość',
  'insights.editTaste': 'Smak', 'insights.editStrength': 'Moc',
  'insights.deleteShot': 'Usuń',
  'insights.confirmDeleteShot': 'Usunąć ten shot? Nieodwracalne.',
  'insights.sweetSpotEyebrow': 'Twój sweet spot',
  'insights.bestGrindLabel': 'mielenie', 'insights.ratioLabel': 'ratio',
  'insights.fromNShots': 'z {n} najlepszych shotów',
  'insights.noTopShots': 'Zaloguj shot z 85+ by ustawić sweet spot.',
  'insights.personalBest': 'Rekord osobisty',
  'insights.thisWeek': 'Ten tydzień', 'insights.timeWindow': 'Okno czasu',
  'insights.avgScore': 'śr. {score}', 'insights.noShotsYet': 'brak danych',
  'insights.daysActive': 'Aktywny {count} dni',
  'insights.exportCsv': 'Eksport CSV',
  'insights.deleteAccountEmail': 'Usunięcie konta: chef@lazysous.app',
},
}


def set_nested(d, key, value):
    parts = key.split('.')
    cur = d
    for p in parts[:-1]:
        if p not in cur or not isinstance(cur[p], dict):
            cur[p] = {}
        cur = cur[p]
    cur[parts[-1]] = value


def main():
    for locale, kvs in TRANSLATIONS.items():
        path = TR / f'{locale}.json'
        existing = json.loads(path.read_text(encoding='utf-8'))
        for k, v in kvs.items():
            set_nested(existing, k, v)
        path.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        print(f'{locale}: filled {len(kvs)} keys')


if __name__ == '__main__':
    main()
