#!/usr/bin/env python3
"""Fill all remaining 44 Tier 2 locales. Compact format, in-conversation translations."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TR = ROOT / 'public' / 'translations'

# Shared key list — values are per-locale strings in the same order.
KEYS = [
    'common.save', 'common.close', 'common.cancel',
    'footer.poweredBy', 'footer.shotsGlobally', 'header.home',
    'hero.brewFirst', 'hero.shotN', 'hero.dayN',
    'hero.statusLastShot', 'hero.statusNailed', 'hero.statusClose',
    'hero.statusOneTweak', 'hero.statusKeepGoing', 'hero.statusReady',
    'hero.statusKeepPulling',
    'hero.beanResting', 'hero.beanDay', 'hero.beanUseSoon', 'hero.beanStale',
    'hero.beanRestingShort', 'hero.beanDayShort', 'hero.beanUseSoonShort', 'hero.beanStaleShort',
    'hero.weatherHumid', 'hero.weatherDry', 'hero.weatherNeutral',
    'hero.setupYourKit', 'hero.setupKitOnFile', 'hero.setupAllSetBig',
    'hero.setupAllSet', 'hero.setupAddBeans', 'hero.setupEmpty', 'hero.setupEmptySub',
    'hero.setupSectionsToGo', 'hero.setupSectionsToGoPlural',
    'hero.insightsBig', 'hero.insightsEmpty', 'hero.insightsEmptySub',
    'hero.insightsCount', 'hero.insightsCountPlural', 'hero.insightsAvg',
    'auth.providerSub', 'auth.continueMeta', 'auth.continueGitHub',
    'auth.privacyNote', 'auth.nicknameTitle', 'auth.nicknameSub',
    'auth.nicknamePlaceholder', 'auth.nicknameSubmit',
    'brew.decreaseFine', 'brew.increaseFine',
    'brew.coachPreviewBadge', 'brew.coachPreviewDirection', 'brew.coachPreviewReason',
    'brew.coachPreviewCaption', 'brew.coachLine',
    'brew.outcomeShort', 'brew.outcomeLong', 'brew.holdAtTarget', 'brew.targetWas',
    'brew.sectionChange', 'brew.sectionHold', 'brew.sectionShot',
    'brew.scoreBest', 'brew.scoreUp', 'brew.scoreDown', 'brew.scoreSame', 'brew.scoreFirst',
    'brew.stop', 'brew.saveShot', 'brew.timingRunning', 'brew.timingStopped', 'brew.countdownSub',
    'brew.reasonRanFastBoth', 'brew.reasonRanSlowBoth',
    'brew.reasonGrindAtMin', 'brew.reasonGrindAtMax',
    'brew.doseTrendUp', 'brew.doseTrendDown', 'brew.doseGrindAtMin', 'brew.doseGrindAtMax',
    'crema.thin', 'crema.normal', 'crema.thick',
    'rating.crema', 'rating.flavour', 'rating.strength', 'rating.later', 'rating.save',
    'barista.toggleOn', 'barista.toggleOff', 'barista.active', 'barista.sessionMeta',
    'premium.eyebrow', 'premium.title', 'premium.lockBadge',
    'premium.triggerGrinder', 'premium.triggerTamper', 'premium.triggerBeans',
    'premium.triggerHistory', 'premium.triggerBenchmarks',
    'premium.feature1Head', 'premium.feature1Sub',
    'premium.feature2Head', 'premium.feature2Sub',
    'premium.feature3Head', 'premium.feature3Sub',
    'premium.ctaBrewmie', 'premium.priceBrewmie',
    'premium.ctaBundle', 'premium.priceBundle', 'premium.devNote',
    'tierLock.badge', 'tierLock.historyMore', 'tierLock.benchmarksLocked',
    'tierLock.genericGrinder', 'tierLock.genericTamper', 'tierLock.genericBeans',
    'setup.profileCtaReset', 'setup.bannerEyebrow', 'setup.bannerCta',
    'setup.cardLanguage', 'setup.languageLabel', 'setup.languageMajor', 'setup.languageMore',
    'setup.languageHint', 'setup.maintLastDone', 'setup.privacyPolicyLink',
    'insights.viewAll', 'insights.allShotsTitle', 'insights.editShot',
    'insights.editTime', 'insights.editVolume', 'insights.editTaste', 'insights.editStrength',
    'insights.deleteShot', 'insights.confirmDeleteShot',
    'insights.sweetSpotEyebrow', 'insights.bestGrindLabel', 'insights.ratioLabel',
    'insights.fromNShots', 'insights.noTopShots',
    'insights.personalBest', 'insights.thisWeek', 'insights.timeWindow',
    'insights.avgScore', 'insights.noShotsYet', 'insights.daysActive',
    'insights.exportCsv', 'insights.deleteAccountEmail',
]

# Per-locale: list of 146 strings in the same order as KEYS above.
# Tier 2 — varying depth of fluency; functional translations throughout.
# Espresso loanwords kept ("crema", "shot", "barista") where they're already
# the standard term in the target language.

LOCALES = {
'af': ['Stoor','Sluit','Kanselleer','Aangedryf deur','shots wêreldwyd','Tuis',
'Trek jou eerste.','Shot {n}.','Dag {n}.','Laaste shot: {score}. {tail}','Perfek.','Naby.','Een tweak weg.','Begin oor.','Stel die resep. Trek wat tel.','Hou aan trek. Ons leer.',
'Dag {days} · rus nog','Dag {days} · in die venster','Dag {days} · gebruik gou','Dag {days} · oud',
'Rus nog','In die venster','Gebruik gou','Oud',
'{temp}°C · {humidity}% humiditeit','{temp}°C · {humidity}% humiditeit','{temp}°C · {humidity}% humiditeit',
'Jou toerusting.','Jou toerusting.','Jou toerusting.','Reg wanneer jy is.','Voeg bone by om te kalibreer.','Stel jou toerusting op.','Vyf minute. Beter shots daarna.',
'{count} afdeling oor.','{count} afdelings oor.',
'Elke shot, opgeneem.','Trek een. Ons begin opneem.','Jou telling, maalsel, dryf.','{count} shot. Hou aan.','{count} shots. Hou aan.','{count} shots. 5-shot gemiddeld {avg}.',
'Een tik. Geen wagwoord nodig.','Gaan voort met Meta','Gaan voort met GitHub','Net \'n bynaam. Geen wagwoord.','Kies \'n bynaam.','Jou keuse. Dit is al wat ons stoor.','bv. billy_bean','Stoor',
'Verminder {label} (fyn)','Vermeerder {label} (fyn)',
'Na jou eerste shot','Growwer','3s te lank. Maal growwer.','Trek. Log. Ons sê wat om te verander.','Trek. Log. Ons sê wat om volgende te verander.',
'{delta} {unit} te min','{delta} {unit} te veel','Hou','teiken {value} {unit}',
'Verander vir volgende shot','Hou vir volgende shot','Hierdie shot',
'Persoonlike rekord. Geniet dit stadig.','+{delta} op die vorige. Bou.','−{delta} op die vorige. Begin oor.','Selfde as vorige. Vaste hand.','Eerste klaar. Nou leer ons.',
'STOP','STOOR SHOT','Trek','Vang die shot','Maak gereed',
'{seconds}s kort en {ml}ml te veel. Maal fyner.','{seconds}s lank en {ml}ml te min. Maal growwer.',
'{primary} Meul op fynste — verhoog dosis.','{primary} Meul op growwes — verlaag dosis.',
'3 shots fyner. Probeer +0,5g.','3 shots growwer. Probeer −0,5g.',
'Meul op fynste. +0,5g vir meer weerstand.','Meul op growwes. −0,5g vir minder weerstand.',
'Dun','Normaal','Dik','Crema','Geur','Sterkte','Beoordeel later','Stoor beoordeling',
'Barista-modus','Skakel barista-modus af','Barista-modus','{count} shots · {mins} min',
'Brewmie Premium','Brewmie, vir jou ingestel.','Premium',
'Voeg jou meul by — aanbevelings in jou eenhede.','Veer- en outomatiese tampers kom in die model.','Stoor jou bone. Verander sak, gaan voort.','Ontsluit volle geskiedenis en tendense.','Vergelyk elke shot met jou beste.',
'Jou toerusting','Meul, tamper, bone. Aanbevelings in jou eenhede.','Volle geskiedenis','Elke shot gestoor. Voer uit wanneer jy wil.','Persoonlike maatstawwe','Vergelyk elke shot met jou beste.',
'Net Brewmie','$6.99','Bundel met Lazy Sous','$9.99','Dev: ontsluit via dev pill. Nie \'n regte aankoop nie.',
'Premium','Ouer shots is gestoor. Volle geskiedenis met Premium.','Ontsluit Persoonlike Maatstawwe met Premium.','Generiese meul. Premium kalibreer vir joune.','Handmatige tamp. Premium voeg veer en outo by.','Generiese mediumbraai. Premium volg jou bone.',
'Hardloop opstelling weer','Opstelling','Gaan voort →',
'Taal','Vertoontaal','Algemeen','Ander tale','Brewmie speur jou taal outomaties op. Kies hier \'n ander. Vertalings buite die algemene lys kan onvolledig wees en val terug op Engels.','Laaste keer','Lees volle privaatheidsbeleid',
'Bekyk al {count}','Alle shots ({count})','Wysig shot',
'Tyd','Volume','Geur','Sterkte','Verwyder','Verwyder hierdie shot? Kan nie ongedaan word nie.',
'Jou sweet spot','maalsel','verhouding','uit jou top {n} shots','Log \'n shot met 85+ om jou sweet spot vas te stel.',
'Persoonlike beste','Hierdie week','Tydvenster','gem. {score}','nog geen data','Aktief vir {count} dae','Voer CSV uit','Verwyder rekening: stuur e-pos na chef@lazysous.app'],

'am': ['አስቀምጥ','ዝጋ','ሰርዝ','የተጎላበተ በ','ሾቶች በዓለም ዙሪያ','ቤት',
'የመጀመሪያህን አውጣ።','ሾት {n}።','ቀን {n}።','የመጨረሻ ሾት: {score}። {tail}','ግሩም።','ቅርብ።','አንድ ለውጥ ብቻ።','እንደገና ጀምር።','የምግብ አሰራሩን አስቀምጥ። ጠቃሚውን አውጣ።','ማውጣት ቀጥል። እየተማርን ነው።',
'ቀን {days} · እያረፈ','ቀን {days} · በምርጥ ጊዜ','ቀን {days} · በቅርቡ ጨርስ','ቀን {days} · የበረታ',
'እያረፈ','በምርጥ ጊዜ','በቅርቡ ጨርስ','የበረታ',
'{temp}°C · {humidity}% እርጥበት','{temp}°C · {humidity}% እርጥበት','{temp}°C · {humidity}% እርጥበት',
'መሣሪያህ።','መሣሪያህ።','መሣሪያህ።','በማንኛውም ጊዜ ዝግጁ።','ለማስተካከል ሥር ጨምር።','መሣሪያህን አዘጋጅ።','አምስት ደቂቃ። በኋላ የተሻሉ ሾቶች።',
'{count} ክፍል ቀርቷል።','{count} ክፍሎች ቀርተዋል።',
'እያንዳንዱ ሾት፣ ተመዝግቦ።','አንድ አውጣ። መመዝገብ እንጀምራለን።','ነጥብህ፣ ዱቄትህ፣ ለውጥህ።','{count} ሾት። ቀጥል።','{count} ሾቶች። ቀጥል።','{count} ሾቶች። የ5-ሾት አማካይ {avg}።',
'አንድ ጠቅ። የይለፍ ቃል ማስታወስ አያስፈልግም።','በ Meta ቀጥል','በ GitHub ቀጥል','የቅጽል ስም ብቻ። የይለፍ ቃል የለም።','ቅጽል ስም ምረጥ።','እንዳሻህ። የምናስቀምጥው ይህ ብቻ ነው።','ምሳሌ: billy_bean','አስቀምጥ',
'{label} በትንሹ ቀንስ','{label} በትንሹ ጨምር',
'ከመጀመሪያ ሾትህ በኋላ','ጥቅጥቅ ያለ','3s ረዥም። ጥቅጥቅ ያለ ፍጨ።','አውጣ። መዝግብ። ምን መለወጥ እንዳለብህ እንነግርሃለን።','አውጣ። መዝግብ። በቀጣይ ምን መለወጥ እንዳለብህ እንነግርሃለን።',
'{delta} {unit} አጭር','{delta} {unit} ረዥም','እንዳለ ተወው','ዒላማ {value} {unit}',
'ለቀጣይ ሾት ለውጥ','ለቀጣይ ሾት ጠብቅ','ይህ ሾት',
'የግል ምርጥ። በዝግታ ጠጣ።','ከመጨረሻው +{delta}። እያደገ።','ከመጨረሻው −{delta}። እንደገና ጀምር።','እንደ መጨረሻው። የተረጋጋ እጅ።','የመጀመሪያው ሆኗል። አሁን እንማራለን።',
'አቁም','ሾትን አስቀምጥ','በማውጣት ላይ','ሾትን ቅረጽ','ተዘጋጅ',
'{seconds}s አጭር እና {ml}ml ተጨማሪ። ቀጭን ፍጨ።','{seconds}s ረዥም እና {ml}ml ጎደሎ። ጥቅጥቅ ፍጨ።',
'{primary} ፍጪ ጫፍ ላይ ቀጭን — ዶዝ ጨምር።','{primary} ፍጪ ጫፍ ላይ ጥቅጥቅ — ዶዝ ቀንስ።',
'3 ሾቶች ቀጭን ሆነዋል። +0.5g ሞክር።','3 ሾቶች ጥቅጥቅ ሆነዋል። −0.5g ሞክር።',
'ፍጪ ጫፍ ላይ ቀጭን። +0.5g ለበለጠ ተቃውሞ።','ፍጪ ጫፍ ላይ ጥቅጥቅ። −0.5g ለትንሽ ተቃውሞ።',
'ቀጭን','መደበኛ','ጥቅጥቅ','ክሬማ','ጣዕም','ጥንካሬ','በኋላ ገምግም','ግምገማ አስቀምጥ',
'የባሪስታ ሁነታ','የባሪስታ ሁነታ አጥፋ','የባሪስታ ሁነታ','{count} ሾቶች · {mins} ደቂቃ',
'Brewmie Premium','Brewmie፣ ለአንተ የተስተካከለ።','Premium',
'ፍጪህን አክል — ምክሮች በአንተ መለኪያ ይመጣሉ።','የስፕሪንግ እና ኦቶ ታምፐሮች ወደ ሞዴል ይገባሉ።','ሥሮችህን አስቀምጥ። ቦርሳ ለውጥ፣ ከነበርክበት ቀጥል።','ሙሉ ታሪክ እና አዝማሚያዎች ክፈት።','እያንዳንዱን ሾት ከራስህ ምርጥ ጋር አወዳድር።',
'መሣሪያህ','ፍጪ፣ ታምፐር፣ ሥሮች። ምክሮች በአንተ መለኪያ።','ሙሉ ታሪክ','እያንዳንዱ ሾት ተቀምጧል። በፈለግክ ጊዜ ላክ።','የግል መለኪያዎች','እያንዳንዱን ሾት ከራስህ ምርጥ ጋር አወዳድር።',
'Brewmie ብቻ','$6.99','ከ Lazy Sous ጋር ጥቅል','$9.99','Dev: በ dev pill ይከፈታል። እውነተኛ ግዥ አይደለም።',
'Premium','የቆዩ ሾቶች ተቀምጠዋል። ሙሉ ታሪክ ከ Premium ጋር።','የግል መለኪያዎችን በ Premium ክፈት።','አጠቃላይ ፍጪ። Premium ለፍጪህ ያስተካክላል።','የእጅ ታምፕ። Premium ስፕሪንግ እና ኦቶ ይጨምራል።','አጠቃላይ መካከለኛ የተጠበሰ። Premium ሥሮችህን ይከታተላል።',
'የማዋቀር አዋጅ እንደገና አሂድ','የማዋቀር አዋጅ','ቀጥል →',
'ቋንቋ','የማሳያ ቋንቋ','የተለመዱ','ሌሎች ቋንቋዎች','Brewmie ቋንቋህን በራስ-ሰር ይለያል። እዚህ ሌላ ምረጥ። ከተለመዱት ውጭ ያሉ ትርጉሞች ሙሉ ላይሆኑ ይችላሉ እና ወደ እንግሊዝኛ ይመለሳሉ።','የመጨረሻ ጊዜ','ሙሉ የግላዊነት ፖሊሲ አንብብ',
'ሁሉንም {count} አሳይ','ሁሉም ሾቶች ({count})','ሾት አስተካክል',
'ጊዜ','መጠን','ጣዕም','ጥንካሬ','ሰርዝ','ይህን ሾት ሰርዝ? መልሶ ማግኘት አይቻልም።',
'የእርስዎ ስዊት ስፖት','ፍጪ','ጥምርታ','ከእርስዎ ምርጥ {n} ሾቶች','ስዊት ስፖትዎን ለማዘጋጀት 85+ ሾት መዝግብ።',
'የግል ምርጥ','በዚህ ሳምንት','የጊዜ መስኮት','አማካይ {score}','ምንም ውሂብ የለም','ለ {count} ቀናት ንቁ','CSV ላክ','መለያ ለመሰረዝ ኢሜል: chef@lazysous.app'],

'ar': ['حفظ','إغلاق','إلغاء','مدعوم بـ','شوت حول العالم','الرئيسية',
'اسحب أول شوت.','شوت {n}.','اليوم {n}.','آخر شوت: {score}. {tail}','ممتاز.','قريب.','تعديل واحد فقط.','أعد البدء.','اضبط الوصفة. اسحب ما يهم.','استمر في السحب. نحن نتعلم.',
'اليوم {days} · لا يزال يرتاح','اليوم {days} · في النافذة','اليوم {days} · استخدم قريباً','اليوم {days} · فات أوانه',
'يرتاح','في النافذة','استخدم قريباً','فات أوانه',
'{temp}°C · {humidity}% رطوبة','{temp}°C · {humidity}% رطوبة','{temp}°C · {humidity}% رطوبة',
'معداتك.','معداتك.','معداتك.','جاهز متى أردت.','أضف حبوبك للضبط.','جهز معداتك.','خمس دقائق. شوتات أفضل بعدها.',
'بقي قسم {count}.','بقيت {count} أقسام.',
'كل شوت مسجّل.','اسحب واحداً. نبدأ التسجيل.','نقاطك، طحنك، انحرافك.','{count} شوت. استمر.','{count} شوتات. استمر.','{count} شوتات. متوسط 5 شوتات: {avg}.',
'لمسة واحدة. لا كلمات مرور.','تابع مع Meta','تابع مع GitHub','اسم مستعار فقط. لا كلمات مرور.','اختر اسماً مستعاراً.','كما تشاء. هذا كل ما نحفظه.','مثال: billy_bean','حفظ',
'تقليل {label} (دقيق)','زيادة {label} (دقيق)',
'بعد أول شوت','أخشن','3 ث طويل. اطحن أخشن.','اسحب. سجّل. سنخبرك بما تغيّر.','اسحب. سجّل. سنخبرك بما تغيّر تالياً.',
'{delta} {unit} ناقص','{delta} {unit} زيادة','احتفظ','الهدف {value} {unit}',
'غيّر للشوت التالي','احتفظ للشوت التالي','هذا الشوت',
'أفضل رقم شخصي. تذوقه ببطء.','+{delta} عن السابق. تتحسّن.','−{delta} عن السابق. أعد البدء.','مثل السابق. يد ثابتة.','الأول انتهى. الآن نتعلم.',
'إيقاف','حفظ الشوت','جاري السحب','التقط الشوت','استعد',
'{seconds}ث قصير و {ml}مل زائد. اطحن أنعم.','{seconds}ث طويل و {ml}مل ناقص. اطحن أخشن.',
'{primary} المطحنة في أنعم درجة — زد الجرعة.','{primary} المطحنة في أخشن درجة — قلّل الجرعة.',
'3 شوتات أنعم. جرّب +0.5غ.','3 شوتات أخشن. جرّب −0.5غ.',
'المطحنة في أنعم درجة. +0.5غ لمقاومة أكثر.','المطحنة في أخشن درجة. −0.5غ لمقاومة أقل.',
'رقيقة','عادية','كثيفة','كريمة','نكهة','قوة','تقييم لاحقاً','حفظ التقييم',
'وضع باريستا','إيقاف وضع باريستا','وضع باريستا','{count} شوت · {mins} د',
'Brewmie Premium','Brewmie المضبوط لك.','Premium',
'أضف مطحنتك — التوصيات بوحداتك.','تامبر النابض والآلي يدخل النموذج.','احفظ حبوبك. غيّر الكيس، تابع من حيث انتهيت.','افتح السجل الكامل والاتجاهات.','قارن كل شوت بأفضل لديك.',
'معداتك','مطحنة، تامبر، حبوب. التوصيات بوحداتك.','السجل الكامل','كل شوت محفوظ. صدّر متى تشاء.','معاييرك الشخصية','قارن كل شوت بأفضل لديك.',
'Brewmie فقط','$6.99','حزمة مع Lazy Sous','$9.99','Dev: يُفتح عبر dev pill. ليس شراء حقيقي.',
'Premium','الشوتات القديمة محفوظة. السجل الكامل مع Premium.','افتح المعايير الشخصية مع Premium.','مطحنة عامة. Premium يعاير على مطحنتك.','تمب يدوي. Premium يضيف النابض والآلي.','تحميص متوسط عام. Premium يتتبع حبوبك.',
'إعادة تشغيل المعالج','المعالج','تابع →',
'اللغة','لغة العرض','الشائعة','لغات أخرى','يكتشف Brewmie لغتك تلقائياً. اختر أخرى هنا. الترجمات خارج القائمة الشائعة قد تكون ناقصة وتعود للإنجليزية.','آخر مرة','اقرأ سياسة الخصوصية كاملةً',
'عرض الكل ({count})','جميع الشوتات ({count})','تعديل الشوت',
'الوقت','الحجم','النكهة','القوة','حذف','حذف هذا الشوت؟ لا يمكن التراجع.',
'نقطتك المثالية','الطحن','النسبة','من أفضل {n} شوتات','سجّل شوتاً بـ 85+ لتحديد نقطتك المثالية.',
'أفضل رقم شخصي','هذا الأسبوع','نافذة الوقت','متوسط {score}','لا بيانات بعد','نشط لـ {count} أيام','تصدير CSV','لحذف الحساب راسل chef@lazysous.app'],

'as': ['সংৰক্ষণ','বন্ধ','বাতিল','চলোৱা হৈছে','বিশ্বব্যাপী শ্বট','গৃহ',
'প্ৰথমটো উলিয়াওক।','শ্বট {n}।','দিন {n}।','শেষ শ্বট: {score}। {tail}','সঠিক।','ওচৰ।','এটা সলনি বাকী।','ৰিচেট কৰি পুনৰ।','ৰেচিপি নিৰ্ধাৰণ কৰক। গুৰুত্বপূৰ্ণ উলিয়াওক।','উলিয়াই থাকক। আমি শিকিছোঁ।',
'দিন {days} · এতিয়াও বিশ্ৰাম','দিন {days} · ভাল উইণ্ডোত','দিন {days} · সোনকালে ব্যৱহাৰ','দিন {days} · পুৰণা হৈছে',
'বিশ্ৰাম লৈ আছে','ভাল উইণ্ডোত','সোনকালে ব্যৱহাৰ','পুৰণা',
'{temp}°C · {humidity}% আৰ্দ্ৰতা','{temp}°C · {humidity}% আৰ্দ্ৰতা','{temp}°C · {humidity}% আৰ্দ্ৰতা',
'আপোনাৰ যন্ত্ৰ।','আপোনাৰ যন্ত্ৰ।','আপোনাৰ যন্ত্ৰ।','যেতিয়া আপুনি প্ৰস্তুত।','গুটি যোগ কৰি ডায়েল ইন কৰক।','আপোনাৰ যন্ত্ৰ সেট কৰক।','পাঁচ মিনিট। পিছত উন্নত শ্বট।',
'{count} খণ্ড বাকী।','{count} খণ্ড বাকী।',
'প্ৰতিটো শ্বট সংৰক্ষিত।','এটা উলিয়াওক। ট্ৰেকিং আৰম্ভ।','আপোনাৰ স্কোৰ, গ্ৰাইণ্ড, ড্ৰিফ্ট।','{count} শ্বট। অব্যাহত ৰাখক।','{count} শ্বট। অব্যাহত ৰাখক।','{count} শ্বট। 5-শ্বট গড় {avg}।',
'এটা টেপ। পাছৱৰ্ডৰ প্ৰয়োজন নাই।','Meta-ৰে অব্যাহত','GitHub-ৰে অব্যাহত','মাত্ৰ এটা ডাকনাম। পাছৱৰ্ড নাই।','এটা ডাকনাম বাছনি।','আপোনাৰ ইচ্ছা। ই একমাত্ৰ সংৰক্ষণ।','উদাহৰণ: billy_bean','সংৰক্ষণ',
'{label} সূক্ষ্মভাৱে কম','{label} সূক্ষ্মভাৱে বেছি',
'আপোনাৰ প্ৰথম শ্বটৰ পিছত','মোটা','3s দীঘল। মোটা পিহিব।','উলিয়াওক। লগ কৰক। কি সলনি কৰিব ক\'ম।','উলিয়াওক। লগ কৰক। পিছত কি সলনি কৰিব ক\'ম।',
'{delta} {unit} কম','{delta} {unit} বেছি','একে ৰাখক','লক্ষ্য {value} {unit}',
'পৰৱৰ্তী শ্বটৰ বাবে সলনি','পৰৱৰ্তী শ্বটৰ বাবে ৰখা','এই শ্বট',
'ব্যক্তিগত ৰেকৰ্ড। লাহে লাহে উপভোগ।','আগৰটোৰ পৰা +{delta}। বৃদ্ধি।','আগৰটোৰ পৰা −{delta}। ৰিচেট।','আগৰটোৰ দৰে। স্থিৰ হাত।','প্ৰথমটো হৈছে। এতিয়া শিকিম।',
'বন্ধ','শ্বট সংৰক্ষণ','উলিয়াই আছে','শ্বট ক্যাপচাৰ','প্ৰস্তুত হওক',
'{seconds}s চুটি আৰু {ml}ml বেছি। বহুত পিহিব।','{seconds}s দীঘল আৰু {ml}ml কম। মোটা পিহিব।',
'{primary} গ্ৰাইণ্ডাৰ আটাইতকৈ মিহি — ডোজ বঢ়াওক।','{primary} গ্ৰাইণ্ডাৰ আটাইতকৈ মোটা — ডোজ কমাওক।',
'3 শ্বট মিহি হৈছে। +0.5g চেষ্টা।','3 শ্বট মোটা হৈছে। −0.5g চেষ্টা।',
'গ্ৰাইণ্ডাৰ আটাইতকৈ মিহি। +0.5g অধিক ৰোধৰ বাবে।','গ্ৰাইণ্ডাৰ আটাইতকৈ মোটা। −0.5g কম ৰোধৰ বাবে।',
'পাতল','সাধাৰণ','ঘন','ক্ৰেমা','সোৱাদ','তীব্ৰতা','পিছত ৰেট','ৰেটিং সংৰক্ষণ',
'বাৰিষ্টা মোড','বাৰিষ্টা মোড বন্ধ','বাৰিষ্টা মোড','{count} শ্বট · {mins} মিনিট',
'Brewmie Premium','Brewmie, আপোনাৰ বাবে।','Premium',
'গ্ৰাইণ্ডাৰ যোগ কৰক — পৰামৰ্শ আপোনাৰ এককত।','স্প্ৰিং আৰু অটো টেম্পাৰ মডেলত যোগ।','গুটি সংৰক্ষণ। বেগ সলনি, একেই ঠাইৰ পৰা।','সম্পূৰ্ণ ইতিহাস আৰু প্ৰৱণতা।','প্ৰতিটো শ্বট আপোনাৰ শ্ৰেষ্ঠৰ সৈতে তুলনা।',
'আপোনাৰ যন্ত্ৰ','গ্ৰাইণ্ডাৰ, টেম্পাৰ, গুটি। পৰামৰ্শ আপোনাৰ এককত।','সম্পূৰ্ণ ইতিহাস','প্ৰতিটো শ্বট সংৰক্ষিত। যেতিয়া ইচ্ছা ৰপ্তানি।','ব্যক্তিগত মাপদণ্ড','প্ৰতিটো শ্বট আপোনাৰ শ্ৰেষ্ঠৰ সৈতে তুলনা।',
'কেৱল Brewmie','$6.99','Lazy Sous-ৰ সৈতে বাণ্ডল','$9.99','Dev: dev pill-ৰে আনলক। প্ৰকৃত ক্ৰয় নহয়।',
'Premium','পুৰণা শ্বট সংৰক্ষিত। Premium-ৰ সৈতে সম্পূৰ্ণ ইতিহাস।','Premium-ৰ সৈতে ব্যক্তিগত মাপদণ্ড আনলক।','সাধাৰণ গ্ৰাইণ্ডাৰ। Premium আপোনাৰটোৰ বাবে কেলিব্ৰেট।','মেনুৱেল টেম্প। Premium স্প্ৰিং আৰু অটো যোগ।','সাধাৰণ মধ্যম ৰোষ্ট। Premium আপোনাৰ গুটি ট্ৰেক।',
'ছেটআপ পুনৰ চলাওক','ছেটআপ','অব্যাহত →',
'ভাষা','প্ৰদৰ্শন ভাষা','সাধাৰণ','অন্য ভাষা','Brewmie-এ ভাষা স্বয়ংক্ৰিয়ভাৱে চিনাক্ত কৰে। ইয়াত অন্য বাছনি। সাধাৰণ তালিকাৰ বাহিৰৰ অনুবাদ অসম্পূৰ্ণ হ\'ব পাৰে আৰু ইংৰাজীলৈ ঘূৰি যায়।','শেষ কৰিছিল','গোপনীয়তা নীতি পঢ়ক',
'সকলো {count}','সকলো শ্বট ({count})','শ্বট সম্পাদনা',
'সময়','আয়তন','সোৱাদ','তীব্ৰতা','মচক','এই শ্বট মচিব? উভতাব নোৱাৰে।',
'আপোনাৰ স্ৱিট স্পট','গ্ৰাইণ্ড','অনুপাত','আপোনাৰ শীৰ্ষ {n} শ্বটৰ পৰা','স্ৱিট স্পট সেট কৰিবলৈ 85+ স্কোৰৰ শ্বট লগ।',
'ব্যক্তিগত শ্ৰেষ্ঠ','এই সপ্তাহ','সময় উইণ্ডো','গড় {score}','এতিয়াও তথ্য নাই','{count} দিন সক্ৰিয়','CSV ৰপ্তানি','একাউণ্ট মচিবলৈ chef@lazysous.app-লৈ ইমেইল'],

'az': ['Saxla','Bağla','Ləğv et','Tərəfindən təmin edilir','şot dünyada','Ana səhifə',
'İlkini çək.','Şot {n}.','Gün {n}.','Son şot: {score}. {tail}','Mükəmməl.','Yaxın.','Bir tənzimləmə.','Sıfırla və yenidən.','Reseptləri qur. Vacibi çək.','Çəkməyə davam et. Öyrənirik.',
'Gün {days} · hələ dincəlir','Gün {days} · ideal aralıqda','Gün {days} · tezliklə istifadə','Gün {days} · təravətsiz',
'Dincəlir','İdeal aralıqda','Tezliklə istifadə','Təravətsiz',
'{temp}°C · {humidity}% rütubət','{temp}°C · {humidity}% rütubət','{temp}°C · {humidity}% rütubət',
'Avadanlığın.','Avadanlığın.','Avadanlığın.','İstədiyin zaman hazır.','Tənzim üçün dən əlavə et.','Avadanlığını qur.','Beş dəqiqə. Sonra daha yaxşı şotlar.',
'{count} bölmə qalıb.','{count} bölmə qalıb.',
'Hər şot qeyd olunur.','Bir çək. Qeyd etməyə başlayırıq.','Xalın, üyüdün, sapması.','{count} şot. Davam.','{count} şot. Davam.','{count} şot. 5-şot orta: {avg}.',
'Bir toxunuş. Şifrə yoxdur.','Meta ilə davam','GitHub ilə davam','Yalnız ləqəb. Şifrə yox.','Bir ləqəb seç.','Sənə bağlı. Saxladığımız yeganə şey.','məs. billy_bean','Saxla',
'{label}-ı dəqiq azalt','{label}-ı dəqiq artır',
'İlk şotundan sonra','Daha kobud','3s uzun. Daha kobud üyüt.','Çək. Qeyd. Nə dəyişdirməyini deyirik.','Çək. Qeyd. Növbəti dəfə nə dəyişdirməyini deyirik.',
'{delta} {unit} az','{delta} {unit} çox','Olduğu kimi','hədəf {value} {unit}',
'Növbəti şot üçün dəyiş','Növbəti şot üçün saxla','Bu şot',
'Şəxsi rekord. Yavaş dad.','Əvvəlkindən +{delta}. Yüksəlir.','Əvvəlkindən −{delta}. Sıfırla.','Əvvəlki ilə eyni. Sabit əl.','Birinci tamam. İndi öyrənirik.',
'DAYAN','ŞOTU SAXLA','Çəkilir','Şotu yaxala','Hazırlaş',
'{seconds}s qısa və {ml}ml çox. Daha ince üyüt.','{seconds}s uzun və {ml}ml az. Daha kobud üyüt.',
'{primary} Üyüdücü ən incədə — dozu artır.','{primary} Üyüdücü ən kobudda — dozu azalt.',
'3 şot daha ince getdin. +0,5g yoxla.','3 şot daha kobud getdin. −0,5g yoxla.',
'Üyüdücü ən incədə. +0,5g daha çox müqavimət.','Üyüdücü ən kobudda. −0,5g daha az müqavimət.',
'İncə','Normal','Qalın','Krema','Dad','Sıxlıq','Sonra qiymətləndir','Qiymətləndirməni saxla',
'Barista rejimi','Barista rejimini söndür','Barista rejimi','{count} şot · {mins} dəq',
'Brewmie Premium','Brewmie sənə görə.','Premium',
'Üyüdücünü əlavə et — tövsiyələr sənin vahidlərində.','Yaylı və avtomatik tamperlər modelə daxil.','Dənlərini saxla. Paket dəyiş, qaldığın yerdən.','Tam tarixi və trendləri aç.','Hər şotu öz rekordunla müqayisə.',
'Avadanlığın','Üyüdücü, tamper, dən. Tövsiyələr sənin vahidlərində.','Tam tarix','Hər şot saxlanılır. İstədiyin vaxt ixrac.','Şəxsi göstəricilər','Hər şotu öz rekordunla müqayisə.',
'Yalnız Brewmie','$6.99','Lazy Sous paketi','$9.99','Dev: dev pill ilə açılır. Real alış deyil.',
'Premium','Köhnə şotlar saxlanılır. Tam tarix Premium ilə.','Şəxsi göstəriciləri Premium ilə aç.','Ümumi üyüdücü. Premium sənin üçün kalibrləyir.','Əl tampı. Premium yaylı və avtomatik əlavə edir.','Ümumi orta qovurma. Premium dənlərini izləyir.',
'Quraşdırma sehrbazını yenidən aç','Quraşdırma','Davam →',
'Dil','Görünüş dili','Geniş yayılmış','Digər dillər','Brewmie dilini avtomatik tapır. Burada dəyişdir. Geniş yayılmış xaricindəki tərcümələr natamam ola bilər və ingiliscəyə qayıdır.','Son dəfə','Tam məxfilik siyasətini oxu',
'Hamısını gör ({count})','Bütün şotlar ({count})','Şotu redaktə',
'Vaxt','Həcm','Dad','Sıxlıq','Sil','Bu şotu silək? Geri qaytarmaq olmaz.',
'Sənin şirin nöqtən','üyütmə','nisbət','ən yaxşı {n} şotdan','Şirin nöqtəni təyin etmək üçün 85+ şot qeyd et.',
'Şəxsi rekord','Bu həftə','Vaxt aralığı','orta {score}','hələ məlumat yox','{count} gün aktiv','CSV ixrac','Hesabı silmək üçün chef@lazysous.app'],

'be': ['Захаваць','Закрыць','Скасаваць','Працуе на','шотаў па ўсім свеце','Галоўная',
'Выцягні першы.','Шот {n}.','Дзень {n}.','Апошні шот: {score}. {tail}','Цэль.','Блізка.','Адна налада.','Скінь і яшчэ раз.','Налад рэцэпт. Выцягні важнае.','Працягвай выцягваць. Мы вучымся.',
'Дзень {days} · яшчэ адпачывае','Дзень {days} · у акне','Дзень {days} · хутка скончыць','Дзень {days} · састарэў',
'Адпачывае','У акне','Хутка скончыць','Састарэў',
'{temp}°C · {humidity}% вільготнасць','{temp}°C · {humidity}% вільготнасць','{temp}°C · {humidity}% вільготнасць',
'Тваё абсталяванне.','Тваё абсталяванне.','Тваё абсталяванне.','Гатова калі ты гатоў.','Дадай зерні для наладкі.','Налад абсталяванне.','Пяць хвілін. Лепшыя шоты пасля.',
'Засталася {count} секцыя.','Засталося {count} секцый.',
'Кожны шот запісаны.','Выцягні адзін. Пачынаем запісваць.','Твой бал, памол, дрэйф.','{count} шот. Працягвай.','{count} шотаў. Працягвай.','{count} шотаў. Сярэдні з 5: {avg}.',
'Адзін дотык. Без пароляў.','Працягнуць з Meta','Працягнуць з GitHub','Толькі мянушка. Без пароляў.','Выберы мянушку.','Як хочаш. Гэта адзінае што мы захоўваем.','напр. billy_bean','Захаваць',
'Паменшыць {label} (дакладна)','Павялічыць {label} (дакладна)',
'Пасля першага шота','Грубей','3с задоўга. Малі грубей.','Выцягні. Запішы. Скажам што змяніць.','Выцягні. Запішы. Скажам што змяніць далей.',
'{delta} {unit} мала','{delta} {unit} шмат','Пакінь так','мэта {value} {unit}',
'Змяніць на наступны шот','Захаваць на наступны шот','Гэты шот',
'Асабісты рэкорд. Смакуй павольна.','+{delta} да папярэдняга. Расцеш.','−{delta} да папярэдняга. Скінь.','Як папярэдні. Цвёрдая рука.','Першы зроблены. Цяпер вучымся.',
'СПЫНІЦЬ','ЗАХАВАЦЬ ШОТ','Выцягваецца','Захапіць шот','Падрыхтуйся',
'{seconds}с коратка і {ml}мл лішне. Малі дробней.','{seconds}с задоўга і {ml}мл недахоп. Малі грубей.',
'{primary} Млынок на самым дробным — павялічце дозу.','{primary} Млынок на самым грубым — паменшце дозу.',
'3 шоты дробней. Паспрабуй +0,5г.','3 шоты грубей. Паспрабуй −0,5г.',
'Млынок на самым дробным. +0,5г для большага супраціву.','Млынок на самым грубым. −0,5г для меншага супраціву.',
'Тонкая','Звычайная','Густая','Крэма','Смак','Моц','Ацаніць пазней','Захаваць ацэнку',
'Рэжым барысты','Выключыць рэжым барысты','Рэжым барысты','{count} шотаў · {mins} мін',
'Brewmie Premium','Brewmie настроены пад цябе.','Premium',
'Дадай млынок — рэкамендацыі ў тваіх адзінках.','Спружынныя і аўтаматычныя тамперы ў мадэль.','Захавай зерні. Пакет змяніў — працягни.','Адкрыйце ўвесь архіў і трэнды.','Параўнай кожны шот са сваім лепшым.',
'Тваё абсталяванне','Млынок, тампер, зерні. Рэкамендацыі ў тваіх адзінках.','Поўны архіў','Кожны шот захоўваецца. Экспартуй калі захочаш.','Асабістыя рэкорды','Параўнай кожны шот са сваім лепшым.',
'Толькі Brewmie','$6.99','Пакет з Lazy Sous','$9.99','Dev: разблакіроўка праз dev pill. Не сапраўдная пакупка.',
'Premium','Старыя шоты захаваны. Поўны архіў з Premium.','Адкрыйце асабістыя рэкорды з Premium.','Агульны млынок. Premium налад пад твой.','Ручны тамп. Premium дадае спружынны і аўтаматычны.','Агульная сярэдняя смажка. Premium адсочвае твае зерні.',
'Запусціць майстар нанова','Майстар','Далей →',
'Мова','Мова інтэрфейсу','Распаўсюджаныя','Іншыя мовы','Brewmie вызначае мову аўтаматычна. Выберы тут іншую. Пераклады па-за распаўсюджанымі могуць быць няпоўнымі і вярнуцца да англійскай.','Апошні раз','Прачытаць палітыку прыватнасці',
'Паказаць усе ({count})','Усе шоты ({count})','Рэдагаваць шот',
'Час','Аб\'ём','Смак','Моц','Выдаліць','Выдаліць гэты шот? Не атрымаецца вярнуць.',
'Твая ідэальная кропка','памол','суадносіны','з лепшых {n} шотаў','Запішы шот з 85+ каб задаць ідэальную кропку.',
'Асабісты рэкорд','Гэты тыдзень','Часовае акно','сярэдні {score}','пакуль няма даных','{count} дзён актыўны','Экспарт CSV','Для выдалення акаунта пішыце chef@lazysous.app'],

'cs': ['Uložit','Zavřít','Zrušit','Poháněno','shotů celosvětově','Domů',
'Vytáhni první.','Shot {n}.','Den {n}.','Poslední shot: {score}. {tail}','Trefa.','Blízko.','Jeden zásah.','Resetuj a znovu.','Nastav recept. Vytáhni co je třeba.','Pokračuj. Učíme se.',
'Den {days} · ještě odpočívá','Den {days} · v okně','Den {days} · využij brzy','Den {days} · zvětralá',
'Odpočívá','V okně','Využij brzy','Zvětralá',
'{temp}°C · vlhkost {humidity}%','{temp}°C · vlhkost {humidity}%','{temp}°C · vlhkost {humidity}%',
'Tvoje vybavení.','Tvoje vybavení.','Tvoje vybavení.','Kdykoliv jsi připraven.','Přidej zrna pro doladění.','Nastav vybavení.','Pět minut. Lepší shoty potom.',
'Zbývá {count} sekce.','Zbývají {count} sekce.',
'Každý shot zaznamenán.','Vytáhni jeden. Začínáme zaznamenávat.','Tvoje skóre, mletí, drift.','{count} shot. Pokračuj.','{count} shotů. Pokračuj.','{count} shotů. Průměr z 5: {avg}.',
'Jedno klepnutí. Žádná hesla.','Pokračovat s Meta','Pokračovat s GitHub','Jen přezdívka. Žádná hesla.','Vyber přezdívku.','Jak chceš. To je jediné co ukládáme.','např. billy_bean','Uložit',
'Snížit {label} (jemně)','Zvýšit {label} (jemně)',
'Po prvním shotu','Hruběji','3s dlouhé. Mel hruběji.','Vytáhni. Zapiš. Řekneme co změnit.','Vytáhni. Zapiš. Řekneme co změnit příště.',
'{delta} {unit} méně','{delta} {unit} více','Nech tak','cíl {value} {unit}',
'Změnit pro další shot','Ponechat pro další shot','Tento shot',
'Osobní rekord. Vychutnej si ho.','+{delta} oproti minulému. Roste to.','−{delta} oproti minulému. Reset.','Stejně jako minulý. Pevná ruka.','První hotový. Teď se učíme.',
'STOP','ULOŽIT SHOT','Vytahuji','Zachyť shot','Připrav se',
'{seconds}s krátký a {ml}ml moc. Mel jemněji.','{seconds}s dlouhý a {ml}ml málo. Mel hruběji.',
'{primary} Mlýnek na nejjemnější — zvyš dávku.','{primary} Mlýnek na nejhrubší — sniž dávku.',
'3 shoty jemněji. Zkus +0,5g.','3 shoty hruběji. Zkus −0,5g.',
'Mlýnek na nejjemnější. +0,5g pro větší odpor.','Mlýnek na nejhrubší. −0,5g pro menší odpor.',
'Tenká','Normální','Hustá','Crema','Chuť','Intenzita','Ohodnotit později','Uložit hodnocení',
'Režim barista','Vypnout režim barista','Režim barista','{count} shotů · {mins} min',
'Brewmie Premium','Brewmie naladěný pro tebe.','Premium',
'Přidej mlýnek — doporučení v tvých jednotkách.','Pružinové a auto tampery do modelu.','Ulož svá zrna. Vyměň sáček, pokračuj.','Odemkni celou historii a trendy.','Porovnej každý shot se svým nejlepším.',
'Tvoje vybavení','Mlýnek, tamper, zrna. Doporučení v tvých jednotkách.','Celá historie','Každý shot uložen. Exportuj kdykoliv.','Osobní rekordy','Porovnej každý shot se svým nejlepším.',
'Jen Brewmie','$6.99','Balíček s Lazy Sous','$9.99','Dev: odemčení přes dev pill. Není to skutečný nákup.',
'Premium','Starší shoty jsou uloženy. Celá historie s Premium.','Odemkni osobní rekordy s Premium.','Generický mlýnek. Premium ladí pro tvůj.','Manuální tamp. Premium přidá pružinový a auto.','Generické střední pražení. Premium sleduje tvá zrna.',
'Spustit průvodce znovu','Průvodce','Pokračovat →',
'Jazyk','Jazyk zobrazení','Běžné','Další jazyky','Brewmie detekuje jazyk automaticky. Vyber tu jiný. Překlady mimo běžný seznam můžou být neúplné a vrátí se k angličtině.','Naposledy','Přečíst celé zásady ochrany',
'Zobrazit všech {count}','Všechny shoty ({count})','Upravit shot',
'Čas','Objem','Chuť','Intenzita','Smazat','Smazat tento shot? Nelze vrátit.',
'Tvůj sweet spot','mletí','poměr','z tvých {n} nejlepších shotů','Zaznamenej shot s 85+ pro nastavení sweet spotu.',
'Osobní rekord','Tento týden','Časové okno','prům. {score}','zatím bez dat','Aktivní {count} dní','Exportovat CSV','Pro smazání účtu napiš chef@lazysous.app'],

'cy': ['Cadw','Cau','Canslo','Wedi\'i bweru gan','sied yn fyd-eang','Cartref',
'Tynna dy gyntaf.','Sied {n}.','Diwrnod {n}.','Sied diwethaf: {score}. {tail}','Perffaith.','Agos.','Un tweak i ffwrdd.','Ailosod a thro arall.','Gosod y rysáit. Tynna\'r hyn sy\'n cyfri.','Daliwch i dynnu. Rydyn ni\'n dysgu.',
'Diwrnod {days} · yn dal i orffwys','Diwrnod {days} · yn y ffenestr','Diwrnod {days} · defnyddio cyn bo hir','Diwrnod {days} · hen',
'Yn gorffwys','Yn y ffenestr','Defnyddio cyn bo hir','Hen',
'{temp}°C · {humidity}% lleithder','{temp}°C · {humidity}% lleithder','{temp}°C · {humidity}% lleithder',
'Dy git.','Dy git.','Dy git.','Pan wyt ti\'n barod.','Ychwanega ffa i ddialio i mewn.','Gosod dy git.','Pum munud. Sieds gwell wedyn.',
'{count} adran ar ôl.','{count} adran ar ôl.',
'Pob sied wedi\'i gofnodi.','Tynna un. Dechreuwn gofnodi.','Dy sgôr, malu, drifft.','{count} sied. Dali ati.','{count} sied. Dali ati.','{count} sied. Cyfartaledd 5: {avg}.',
'Un tap. Dim cyfrineiriau.','Parhau gyda Meta','Parhau gyda GitHub','Dim ond ffugenw. Dim cyfrineiriau.','Dewisa ffugenw.','Fyny i ti. Dyna\'r unig beth a gadwn.','e.e. billy_bean','Cadw',
'Lleihau {label} (mân)','Cynyddu {label} (mân)',
'Ar ôl dy sied gyntaf','Trwchach','3s yn rhy hir. Mal yn drwchach.','Tynna. Cofnoda. Dywedwn beth i\'w newid.','Tynna. Cofnoda. Dywedwn beth i\'w newid nesaf.',
'{delta} {unit} yn rhy fyr','{delta} {unit} yn rhy hir','Cadw','targed {value} {unit}',
'Newid ar gyfer y sied nesaf','Cadw ar gyfer y sied nesaf','Y sied hwn',
'Record bersonol. Mwynha\'n araf.','+{delta} ar y diwethaf. Codi.','−{delta} ar y diwethaf. Ailosod.','Yr un â\'r diwethaf. Llaw gadarn.','Cyntaf wedi\'i wneud. Nawr rydyn ni\'n dysgu.',
'STOPIO','CADW SIED','Tynnu','Daliwch y sied','Bydd yn barod',
'{seconds}s yn fyr a {ml}ml dros ben. Mal yn finach.','{seconds}s yn hir a {ml}ml yn brin. Mal yn drwchach.',
'{primary} Melin ar ei mân — codwch y ddos.','{primary} Melin ar ei thrwchaf — gostyngwch y ddos.',
'3 sied yn finach. Triwch +0.5g.','3 sied yn drwchach. Triwch −0.5g.',
'Melin ar ei mân. +0.5g am fwy o wrthwynebiad.','Melin ar ei thrwchaf. −0.5g am lai o wrthwynebiad.',
'Tenau','Arferol','Trwchog','Crema','Blas','Cryfder','Graddio\'n hwyrach','Cadw graddio',
'Modd barista','Diffodd modd barista','Modd barista','{count} sied · {mins} mun',
'Brewmie Premium','Brewmie, wedi\'i diwnio i ti.','Premium',
'Ychwanega dy felin — argymhellion yn dy unedau.','Mae tamperi sbring ac awto yn ymuno â\'r model.','Cadw dy ffa. Newid bag, parhau o\'r un lle.','Datgloi hanes llawn a thueddiadau.','Cymharu pob sied â\'th orau.',
'Dy git','Melin, tamper, ffa. Argymhellion yn dy unedau.','Hanes llawn','Pob sied wedi\'i gadw. Allforio pryd bynnag.','Meincnodau personol','Cymharu pob sied â\'th orau.',
'Brewmie yn unig','$6.99','Bwndel gyda Lazy Sous','$9.99','Dev: datgloi drwy dev pill. Nid pryniant go iawn.',
'Premium','Sieds hŷn wedi\'u cadw. Hanes llawn gyda Premium.','Datgloi meincnodau personol gyda Premium.','Melin generig. Premium yn calibrio i\'th un di.','Tamp llaw. Premium yn ychwanegu sbring ac awto.','Rhostiad canolig generig. Premium yn olrhain dy ffa.',
'Ailgynnal y dewin gosod','Dewin gosod','Parhau →',
'Iaith','Iaith dangos','Cyffredin','Ieithoedd eraill','Mae Brewmie yn canfod dy iaith yn awtomatig. Dewisa un arall yma. Gall cyfieithiadau y tu allan i\'r rhestr gyffredin fod yn anghyflawn ac yn dychwelyd i Saesneg.','Tro diwethaf','Darllen polisi preifatrwydd llawn',
'Gweld pob {count}','Pob sied ({count})','Golygu sied',
'Amser','Cyfaint','Blas','Cryfder','Dileu','Dileu\'r sied hwn? Methu dad-wneud.',
'Dy sweet spot','malu','cymhareb','o\'th {n} sied uchaf','Cofnoda sied 85+ i osod dy sweet spot.',
'Record bersonol','Yr wythnos hon','Ffenestr amser','cyfart. {score}','dim data eto','Yn weithgar {count} dydd','Allforio CSV','I ddileu cyfrif e-bostia chef@lazysous.app'],

'da': ['Gem','Luk','Annullér','Drevet af','shots globalt','Hjem',
'Træk din første.','Shot {n}.','Dag {n}.','Sidste shot: {score}. {tail}','Perfekt.','Tæt på.','Én justering.','Nulstil og igen.','Sæt opskriften. Træk det der tæller.','Bliv ved. Vi lærer.',
'Dag {days} · hviler stadig','Dag {days} · i vinduet','Dag {days} · brug snart','Dag {days} · over toppen',
'Hviler','I vinduet','Brug snart','Over toppen',
'{temp}°C · {humidity}% luftfugtighed','{temp}°C · {humidity}% luftfugtighed','{temp}°C · {humidity}% luftfugtighed',
'Dit udstyr.','Dit udstyr.','Dit udstyr.','Klar når du er.','Tilføj bønner for at dialere.','Sæt dit udstyr op.','Fem minutter. Bedre shots bagefter.',
'{count} sektion tilbage.','{count} sektioner tilbage.',
'Hvert shot, logget.','Træk én. Vi begynder at logge.','Din score, dit maleri, din drift.','{count} shot. Fortsæt.','{count} shots. Fortsæt.','{count} shots. 5-shot gennemsnit {avg}.',
'Et tryk. Ingen kodeord.','Fortsæt med Meta','Fortsæt med GitHub','Bare et kælenavn. Ingen kodeord.','Vælg et kælenavn.','Op til dig. Det er det eneste vi gemmer.','f.eks. billy_bean','Gem',
'Mindsk {label} (fint)','Forøg {label} (fint)',
'Efter dit første shot','Grovere','3s for langt. Mal grovere.','Træk. Log. Vi siger hvad du skal ændre.','Træk. Log. Vi siger hvad du skal ændre næste gang.',
'{delta} {unit} for lidt','{delta} {unit} for meget','Behold','mål {value} {unit}',
'Ændre til næste shot','Behold til næste shot','Dette shot',
'Personlig rekord. Nyd den langsomt.','+{delta} fra forrige. Stigende.','−{delta} fra forrige. Nulstil.','Samme som forrige. Stabil hånd.','Første klar. Nu lærer vi.',
'STOP','GEM SHOT','Trækker','Indfang shotet','Gør dig klar',
'{seconds}s for kort og {ml}ml for meget. Mal finere.','{seconds}s for langt og {ml}ml for lidt. Mal grovere.',
'{primary} Kværn på fineste — øg dosis.','{primary} Kværn på groveste — sænk dosis.',
'3 shots finere. Prøv +0,5g.','3 shots grovere. Prøv −0,5g.',
'Kværn på fineste. +0,5g for mere modstand.','Kværn på groveste. −0,5g for mindre modstand.',
'Tynd','Normal','Tyk','Crema','Smag','Styrke','Bedøm senere','Gem bedømmelse',
'Barista-tilstand','Slå barista-tilstand fra','Barista-tilstand','{count} shots · {mins} min',
'Brewmie Premium','Brewmie, indstillet til dig.','Premium',
'Tilføj din kværn — anbefalinger i dine enheder.','Fjeder- og auto-tampere indgår i modellen.','Gem dine bønner. Skift pose, fortsæt hvor du var.','Lås fuld historik og trends op.','Sammenlign hvert shot med din bedste.',
'Dit udstyr','Kværn, tamper, bønner. Anbefalinger i dine enheder.','Fuld historik','Hvert shot gemt. Eksportér når du vil.','Personlige rekorder','Sammenlign hvert shot med din bedste.',
'Kun Brewmie','$6.99','Bundle med Lazy Sous','$9.99','Dev: lås op via dev pill. Ikke et rigtigt køb.',
'Premium','Ældre shots er gemt. Fuld historik med Premium.','Lås personlige rekorder op med Premium.','Generisk kværn. Premium kalibrerer til din.','Manuel tamp. Premium tilføjer fjeder og auto.','Generisk medium ristning. Premium følger dine bønner.',
'Kør guide igen','Guide','Fortsæt →',
'Sprog','Visningssprog','Almindelige','Andre sprog','Brewmie registrerer dit sprog automatisk. Vælg et andet her. Oversættelser uden for almindelige sprog kan være ufuldstændige og falde tilbage på engelsk.','Sidst udført','Læs hele privatlivspolitikken',
'Vis alle {count}','Alle shots ({count})','Rediger shot',
'Tid','Volumen','Smag','Styrke','Slet','Slet dette shot? Kan ikke fortrydes.',
'Dit sweet spot','maleri','forhold','fra dine {n} bedste shots','Log et shot med 85+ for at sætte dit sweet spot.',
'Personlig rekord','Denne uge','Tidsvindue','gns. {score}','ingen data endnu','Aktiv {count} dage','Eksportér CSV','Slet konto: skriv til chef@lazysous.app'],

'el': ['Αποθήκευση','Κλείσιμο','Άκυρο','Powered by','shots παγκόσμια','Αρχική',
'Τράβα το πρώτο.','Shot {n}.','Ημέρα {n}.','Τελευταίο shot: {score}. {tail}','Τέλειο.','Κοντά.','Μία ρύθμιση.','Reset και ξανά.','Σετ συνταγή. Τράβα ό,τι μετράει.','Συνέχισε. Μαθαίνουμε.',
'Ημέρα {days} · ξεκουράζεται ακόμα','Ημέρα {days} · στο παράθυρο','Ημέρα {days} · χρησιμοποίησε σύντομα','Ημέρα {days} · έχει περάσει',
'Ξεκουράζεται','Στο παράθυρο','Χρησιμοποίησε σύντομα','Έχει περάσει',
'{temp}°C · υγρασία {humidity}%','{temp}°C · υγρασία {humidity}%','{temp}°C · υγρασία {humidity}%',
'Ο εξοπλισμός σου.','Ο εξοπλισμός σου.','Ο εξοπλισμός σου.','Έτοιμο όποτε εσύ.','Πρόσθεσε κόκκους για ρύθμιση.','Ρύθμισε τον εξοπλισμό σου.','Πέντε λεπτά. Καλύτερα shots μετά.',
'Έμεινε {count} ενότητα.','Έμειναν {count} ενότητες.',
'Κάθε shot, καταγεγραμμένο.','Τράβα ένα. Ξεκινάμε καταγραφή.','Σκορ, άλεσμα, drift σου.','{count} shot. Συνέχισε.','{count} shots. Συνέχισε.','{count} shots. Μ.Ο. 5: {avg}.',
'Ένα tap. Χωρίς κωδικούς.','Συνέχεια με Meta','Συνέχεια με GitHub','Μόνο ψευδώνυμο. Χωρίς κωδικούς.','Διάλεξε ψευδώνυμο.','Όπως θες. Είναι το μόνο που αποθηκεύουμε.','π.χ. billy_bean','Αποθήκευση',
'Μείωση {label} (λεπτή)','Αύξηση {label} (λεπτή)',
'Μετά το πρώτο shot','Πιο χοντρό','3s μακρύ. Άλεσε πιο χοντρά.','Τράβα. Κατάγραψε. Λέμε τι να αλλάξεις.','Τράβα. Κατάγραψε. Λέμε τι να αλλάξεις την επόμενη φορά.',
'{delta} {unit} λιγότερο','{delta} {unit} περισσότερο','Κράτα','στόχος {value} {unit}',
'Άλλαξε για το επόμενο shot','Κράτα για το επόμενο shot','Αυτό το shot',
'Προσωπικό ρεκόρ. Γεύσου το αργά.','+{delta} από το προηγούμενο. Ανεβαίνει.','−{delta} από το προηγούμενο. Reset.','Ίδιο με το προηγούμενο. Σταθερό χέρι.','Πρώτο έγινε. Τώρα μαθαίνουμε.',
'ΣΤΑΜΑΤΑ','ΑΠΟΘΗΚΕΥΣΗ SHOT','Εκχύλιση','Κατάγραψε το shot','Ετοιμάσου',
'{seconds}s κοντό και {ml}ml παραπάνω. Άλεσε πιο λεπτά.','{seconds}s μακρύ και {ml}ml λιγότερο. Άλεσε πιο χοντρά.',
'{primary} Μύλος στο ψιλότερο — αύξησε τη δόση.','{primary} Μύλος στο χοντρότερο — μείωσε τη δόση.',
'3 shots πιο λεπτά. Δοκίμασε +0,5γρ.','3 shots πιο χοντρά. Δοκίμασε −0,5γρ.',
'Μύλος στο ψιλότερο. +0,5γρ για περισσότερη αντίσταση.','Μύλος στο χοντρότερο. −0,5γρ για λιγότερη αντίσταση.',
'Λεπτή','Κανονική','Πυκνή','Κρέμα','Γεύση','Ένταση','Αξιολόγηση αργότερα','Αποθήκευση αξιολόγησης',
'Λειτουργία barista','Απενεργοποίηση barista','Λειτουργία barista','{count} shots · {mins} λεπτά',
'Brewmie Premium','Brewmie ρυθμισμένο για σένα.','Premium',
'Πρόσθεσε τον μύλο σου — οι συστάσεις βγαίνουν στις δικές σου μονάδες.','Tamper ελατηρίου και αυτόματα μπαίνουν στο μοντέλο.','Αποθήκευσε τους κόκκους σου. Άλλαξε σακούλα, συνέχισε.','Ξεκλείδωσε όλο το ιστορικό και τάσεις.','Σύγκρινε κάθε shot με το καλύτερό σου.',
'Ο εξοπλισμός σου','Μύλος, tamper, κόκκοι. Συστάσεις στις δικές σου μονάδες.','Πλήρες ιστορικό','Κάθε shot αποθηκευμένο. Εξαγωγή όποτε θες.','Προσωπικές μετρήσεις','Σύγκρινε κάθε shot με το καλύτερό σου.',
'Μόνο Brewmie','$6.99','Πακέτο με Lazy Sous','$9.99','Dev: ξεκλείδωμα μέσω dev pill. Δεν είναι πραγματική αγορά.',
'Premium','Παλιά shots είναι αποθηκευμένα. Πλήρες ιστορικό με Premium.','Ξεκλείδωσε προσωπικές μετρήσεις με Premium.','Γενικός μύλος. Το Premium ρυθμίζει στον δικό σου.','Χειροκίνητο tamp. Premium προσθέτει ελατηρίου και αυτόματο.','Γενικό μέτριο καβούρδισμα. Premium παρακολουθεί τους κόκκους σου.',
'Ξανά οδηγός εγκατάστασης','Οδηγός','Συνέχεια →',
'Γλώσσα','Γλώσσα οθόνης','Κοινές','Άλλες γλώσσες','Το Brewmie εντοπίζει αυτόματα τη γλώσσα. Επίλεξε άλλη εδώ. Μεταφράσεις εκτός κοινής λίστας μπορεί να είναι ατελείς και επιστρέφουν στα αγγλικά.','Τελευταία φορά','Διάβασε την πλήρη πολιτική απορρήτου',
'Δες όλα τα {count}','Όλα τα shots ({count})','Επεξεργασία shot',
'Χρόνος','Όγκος','Γεύση','Ένταση','Διαγραφή','Διαγραφή αυτού του shot; Δεν αναιρείται.',
'Το sweet spot σου','άλεσμα','αναλογία','από τα {n} καλύτερα shots','Κατάγραψε ένα shot 85+ για να ορίσεις το sweet spot.',
'Προσωπικό ρεκόρ','Αυτή την εβδομάδα','Παράθυρο χρόνου','μ.ο. {score}','δεν υπάρχουν δεδομένα','Ενεργός {count} ημέρες','Εξαγωγή CSV','Διαγραφή λογαριασμού: chef@lazysous.app'],

'et': ['Salvesta','Sulge','Tühista','Käivitab','shotti üle maailma','Avaleht',
'Tõmba esimene.','Shot {n}.','Päev {n}.','Viimane shot: {score}. {tail}','Täpselt.','Lähedal.','Üks parandus.','Lähtesta ja uuesti.','Sea retsept. Tõmba see mis loeb.','Jätka tõmbamist. Õpime.',
'Päev {days} · puhkab veel','Päev {days} · aknas','Päev {days} · kasuta varsti','Päev {days} · vananenud',
'Puhkab','Aknas','Kasuta varsti','Vananenud',
'{temp}°C · {humidity}% niiskus','{temp}°C · {humidity}% niiskus','{temp}°C · {humidity}% niiskus',
'Sinu varustus.','Sinu varustus.','Sinu varustus.','Valmis kui sina oled.','Lisa oad häälestamiseks.','Sea varustus.','Viis minutit. Paremad shotid pärast.',
'{count} sektsioon jäänud.','{count} sektsiooni jäänud.',
'Iga shot salvestatud.','Tõmba üks. Hakkame salvestama.','Sinu skoor, jahvatus, triiv.','{count} shot. Jätka.','{count} shotti. Jätka.','{count} shotti. 5-shoti keskmine {avg}.',
'Üks puudutus. Paroole pole.','Jätka Metaga','Jätka GitHubiga','Ainult hüüdnimi. Paroole pole.','Vali hüüdnimi.','Sinu valik. Ainus mida salvestame.','nt billy_bean','Salvesta',
'Vähenda {label} (täpne)','Suurenda {label} (täpne)',
'Pärast esimest shotti','Jämedam','3s liiga pikk. Jahvata jämedamalt.','Tõmba. Salvesta. Ütleme mida muuta.','Tõmba. Salvesta. Ütleme mida järgmisel korral muuta.',
'{delta} {unit} vähem','{delta} {unit} rohkem','Jäta nii','siht {value} {unit}',
'Muuda järgmise shoti jaoks','Säilita järgmise shoti jaoks','See shot',
'Isiklik rekord. Naudi aeglaselt.','+{delta} eelmisest. Tõuseb.','−{delta} eelmisest. Lähtesta.','Sama mis eelmine. Kindel käsi.','Esimene tehtud. Nüüd õpime.',
'PEATA','SALVESTA SHOT','Tõmban','Salvesta shot','Valmistu',
'{seconds}s lühike ja {ml}ml üle. Jahvata peenemalt.','{seconds}s pikk ja {ml}ml puudu. Jahvata jämedamalt.',
'{primary} Veski peenimal — suurenda doosi.','{primary} Veski jämedaimal — vähenda doosi.',
'3 shotti peenemalt. Proovi +0,5g.','3 shotti jämedamalt. Proovi −0,5g.',
'Veski peenimal. +0,5g rohkem takistust.','Veski jämedaimal. −0,5g vähem takistust.',
'Õhuke','Tavaline','Paks','Crema','Maitse','Tugevus','Hinda hiljem','Salvesta hinnang',
'Barista režiim','Lülita barista režiim välja','Barista režiim','{count} shotti · {mins} min',
'Brewmie Premium','Brewmie sinule häälestatud.','Premium',
'Lisa veski — soovitused sinu ühikutes.','Vedru- ja autotamprid mudelisse.','Salvesta oad. Vaheta kott, jätka samast kohast.','Ava terve ajalugu ja trendid.','Võrdle iga shotti enda parimaga.',
'Sinu varustus','Veski, tamper, oad. Soovitused sinu ühikutes.','Terve ajalugu','Iga shot salvestatud. Ekspordi millal tahad.','Isiklikud rekordid','Võrdle iga shotti enda parimaga.',
'Ainult Brewmie','$6.99','Komplekt Lazy Sousiga','$9.99','Dev: avab dev pill kaudu. Pole päris ost.',
'Premium','Vanemad shotid on salvestatud. Terve ajalugu Premiumiga.','Ava isiklikud rekordid Premiumiga.','Üldine veski. Premium kalibreerib sinu omale.','Käsitsi tamp. Premium lisab vedru ja auto.','Üldine keskmine röst. Premium jälgib sinu ube.',
'Käivita seadistus uuesti','Seadistus','Jätka →',
'Keel','Kuvakeel','Tavalised','Muud keeled','Brewmie tuvastab keele automaatselt. Vali teine siin. Tõlked väljaspool tavaliste loendit võivad olla mittetäielikud ja taanduda inglise keelele.','Viimati tehtud','Loe tervet privaatsuspoliitikat',
'Vaata kõik {count}','Kõik shotid ({count})','Muuda shotti',
'Aeg','Maht','Maitse','Tugevus','Kustuta','Kustuta see shot? Ei saa tagasi võtta.',
'Sinu sweet spot','jahvatus','suhe','sinu {n} parimast shotist','Salvesta 85+ shot et seada sweet spot.',
'Isiklik rekord','See nädal','Ajaaken','keskm. {score}','andmeid pole veel','Aktiivne {count} päeva','Ekspordi CSV','Konto kustutamiseks kirjuta chef@lazysous.app'],

'eu': ['Gorde','Itxi','Utzi','Honek elikatua:','shot mundu osoan','Hasiera',
'Atera lehenengoa.','{n}. shota.','{n}. eguna.','Azken shota: {score}. {tail}','Ezin hobeto.','Hurbil.','Doikuntza bat.','Berrezarri eta berriz.','Errezeta ezarri. Atera garrantzitsuena.','Jarraitu ateratzen. Ikasten ari gara.',
'{days}. eguna · oraindik atseden hartzen','{days}. eguna · leihoan','{days}. eguna · laster erabili','{days}. eguna · iraungita',
'Atseden hartzen','Leihoan','Laster erabili','Iraungita',
'{temp}°C · {humidity}% hezetasuna','{temp}°C · {humidity}% hezetasuna','{temp}°C · {humidity}% hezetasuna',
'Zure ekipamendua.','Zure ekipamendua.','Zure ekipamendua.','Prest zaudenean.','Aleak gehitu doitzeko.','Konfiguratu ekipamendua.','Bost minutu. Shot hobeak gero.',
'{count} atal falta.','{count} atal falta.',
'Shot bakoitza, jasota.','Atera bat. Hasiko gara jasotzen.','Zure puntuazioa, ehotzea, deriba.','{count} shot. Jarraitu.','{count} shot. Jarraitu.','{count} shot. 5eko batezbestekoa {avg}.',
'Ukitu bat. Pasahitzik gabe.','Jarraitu Metarekin','Jarraitu GitHubekin','Goitizena soilik. Pasahitzik gabe.','Aukeratu goitizen bat.','Nahi duzun bezala. Hori da gordetzen dugun gauza bakarra.','adib. billy_bean','Gorde',
'{label} fin gutxitu','{label} fin handitu',
'Lehen shotaren ondoren','Lodiagoa','3s luze. Lodiago ehotu.','Atera. Erregistratu. Esango dizugu zer aldatu.','Atera. Erregistratu. Esango dizugu hurrengoan zer aldatu.',
'{delta} {unit} gutxiago','{delta} {unit} gehiago','Mantendu','helburua {value} {unit}',
'Hurrengo shotrako aldatu','Hurrengo shotrako mantendu','Shot hau',
'Errekor pertsonala. Dastatu mantso.','+{delta} aurrekoaren gainetik. Igotzen.','−{delta} aurrekoaren azpitik. Berrezarri.','Aurrekoaren berdina. Esku finkoa.','Lehena egina. Orain ikasiko dugu.',
'GELDITU','SHOT GORDE','Ateratzen','Shot hau jaso','Prest egon',
'{seconds}s laburrak eta {ml}ml gehiago. Finago ehotu.','{seconds}s luzeak eta {ml}ml gutxiago. Lodiago ehotu.',
'{primary} Errota finenean — dosi handitu.','{primary} Errota lodienean — dosi gutxitu.',
'3 shot finagoak izan dira. Saiatu +0,5g.','3 shot lodiagoak izan dira. Saiatu −0,5g.',
'Errota finenean. +0,5g erresistentzia gehiagorako.','Errota lodienean. −0,5g erresistentzia gutxiagorako.',
'Mehea','Normala','Lodia','Crema','Zaporea','Indarra','Geroago baloratu','Balorazioa gorde',
'Barista modua','Itzali barista modua','Barista modua','{count} shot · {mins} min',
'Brewmie Premium','Brewmie zuretzat doitua.','Premium',
'Gehitu zure errota — gomendioak zure unitateetan.','Malguki eta auto tamperrak modeloan sartzen dira.','Gorde zure aleak. Aldatu poltsa, jarraitu non utzi zenuen.','Desblokeatu historia osoa eta joerak.','Konparatu shot bakoitza zure onenarekin.',
'Zure ekipamendua','Errota, tamperra, aleak. Gomendioak zure unitateetan.','Historia osoa','Shot bakoitza gordetzen da. Esportatu nahi duzunean.','Erreferentzia pertsonalak','Konparatu shot bakoitza zure onenarekin.',
'Brewmie soilik','$6.99','Lazy Sousekin pakete','$9.99','Dev: dev pill bidez desblokeatzen da. Ez da benetako erosketa.',
'Premium','Shot zaharrak gordeta daude. Historia osoa Premiumekin.','Desblokeatu erreferentzia pertsonalak Premiumekin.','Errota generikoa. Premiumek zureak doitzen ditu.','Eskuzko tampa. Premiumek malgukia eta automatikoa gehitzen ditu.','Erre maila ertaineko generikoa. Premiumek zure aleak jarraitzen ditu.',
'Konfigurazio morroia berriro abiarazi','Konfigurazio morroia','Jarraitu →',
'Hizkuntza','Pantailaren hizkuntza','Ohikoak','Beste hizkuntza batzuk','Brewmiek hizkuntza automatikoki detektatzen du. Aukeratu beste bat hemen. Ohiko zerrendatik kanpoko itzulpenak osatu gabe egon daitezke eta ingelesera itzul daitezke.','Azken aldiz','Irakurri pribatutasun politika osoa',
'Ikusi {count} guztiak','Shot guztiak ({count})','Editatu shota',
'Denbora','Bolumena','Zaporea','Indarra','Ezabatu','Shot hau ezabatu? Ezin da desegin.',
'Zure sweet spot-a','ehotzea','ratioa','zure {n} shot onenetatik','Erregistratu 85+ shot bat sweet spota ezartzeko.',
'Errekor pertsonala','Aste hau','Denbora leihoa','batezb. {score}','oraindik daturik ez','{count} egunez aktibo','CSV esportatu','Kontua ezabatzeko: chef@lazysous.app'],

'fa': ['ذخیره','بستن','لغو','قدرت‌گرفته از','شات در سراسر جهان','خانه',
'اولین شات را بکش.','شات {n}.','روز {n}.','آخرین شات: {score}. {tail}','عالی.','نزدیک.','یک تنظیم.','ریست و دوباره.','رسپی را تنظیم کن. مهمش را بکش.','ادامه بده. در حال یادگیریم.',
'روز {days} · هنوز در حال استراحت','روز {days} · در پنجره','روز {days} · زود استفاده کن','روز {days} · کهنه شد',
'در حال استراحت','در پنجره','زود استفاده کن','کهنه',
'{temp}°C · رطوبت {humidity}%','{temp}°C · رطوبت {humidity}%','{temp}°C · رطوبت {humidity}%',
'تجهیزات تو.','تجهیزات تو.','تجهیزات تو.','هر وقت بخواهی آماده‌ام.','دانه‌ها را برای تنظیم اضافه کن.','تجهیزات را تنظیم کن.','پنج دقیقه. شات‌های بهتر بعد.',
'{count} بخش باقیمانده.','{count} بخش باقیمانده.',
'هر شات ثبت می‌شود.','یکی بکش. شروع به ثبت می‌کنیم.','امتیازت، آسیابت، انحرافت.','{count} شات. ادامه بده.','{count} شات. ادامه بده.','{count} شات. میانگین ۵ تای آخر: {avg}.',
'یک ضربه. بدون رمز عبور.','ادامه با Meta','ادامه با GitHub','فقط یک نام مستعار. بدون رمز.','یک نام مستعار انتخاب کن.','به انتخاب توست. این تنها چیزی است که ذخیره می‌کنیم.','مثلاً billy_bean','ذخیره',
'کاهش {label} (دقیق)','افزایش {label} (دقیق)',
'بعد از اولین شات','درشت‌تر','۳ ثانیه طولانی. درشت‌تر آسیاب کن.','بکش. ثبت کن. می‌گوییم چه تغییر دهی.','بکش. ثبت کن. می‌گوییم دفعه بعد چه تغییر دهی.',
'{delta} {unit} کم','{delta} {unit} اضافه','نگه دار','هدف {value} {unit}',
'تغییر برای شات بعدی','نگهداری برای شات بعدی','این شات',
'رکورد شخصی. آرام بنوش.','+{delta} نسبت به قبلی. در حال صعود.','−{delta} نسبت به قبلی. ریست.','مانند قبلی. دست محکم.','اولین انجام شد. حالا یاد می‌گیریم.',
'توقف','ذخیره شات','در حال کشیدن','شات را ضبط کن','آماده شو',
'{seconds}ث کوتاه و {ml}میلی‌لیتر اضافه. ریزتر آسیاب کن.','{seconds}ث طولانی و {ml}میلی‌لیتر کم. درشت‌تر آسیاب کن.',
'{primary} آسیاب در ریزترین — دوز را افزایش بده.','{primary} آسیاب در درشت‌ترین — دوز را کاهش بده.',
'۳ شات ریزتر رفتی. ۰.۵+ گرم را امتحان کن.','۳ شات درشت‌تر رفتی. ۰.۵− گرم را امتحان کن.',
'آسیاب در ریزترین. ۰.۵+ گرم برای مقاومت بیشتر.','آسیاب در درشت‌ترین. ۰.۵− گرم برای مقاومت کمتر.',
'نازک','معمولی','غلیظ','کرما','طعم','قوت','بعداً امتیاز بده','ذخیره امتیاز',
'حالت باریستا','خاموش کردن حالت باریستا','حالت باریستا','{count} شات · {mins} دقیقه',
'Brewmie Premium','Brewmie تنظیم‌شده برای تو.','Premium',
'آسیابت را اضافه کن — توصیه‌ها در واحدهای تو.','تامپرهای فنری و خودکار وارد مدل می‌شوند.','دانه‌هایت را ذخیره کن. کیسه عوض کن، از همانجا ادامه بده.','تاریخچه کامل و روندها را باز کن.','هر شات را با بهترین خودت مقایسه کن.',
'تجهیزات تو','آسیاب، تامپر، دانه. توصیه‌ها در واحدهای تو.','تاریخچه کامل','هر شات ذخیره می‌شود. هر زمان خواستی صادر کن.','معیارهای شخصی','هر شات را با بهترین خودت مقایسه کن.',
'فقط Brewmie','$6.99','بسته با Lazy Sous','$9.99','Dev: از طریق dev pill باز می‌شود. خرید واقعی نیست.',
'Premium','شات‌های قدیمی ذخیره‌اند. تاریخچه کامل با Premium.','معیارهای شخصی را با Premium باز کن.','آسیاب عمومی. Premium محاسبات را برای تو تنظیم می‌کند.','تامپ دستی. Premium فنری و خودکار اضافه می‌کند.','رست متوسط عمومی. Premium دانه‌هایت را دنبال می‌کند.',
'اجرای دوباره راهنمای نصب','راهنمای نصب','ادامه →',
'زبان','زبان نمایش','رایج','زبان‌های دیگر','Brewmie زبانت را خودکار تشخیص می‌دهد. اینجا یکی دیگر انتخاب کن. ترجمه‌های خارج از فهرست رایج ممکن است ناقص باشند و به انگلیسی برگردند.','آخرین بار','خواندن کامل سیاست حریم خصوصی',
'مشاهده همه {count}','همه شات‌ها ({count})','ویرایش شات',
'زمان','حجم','طعم','قوت','حذف','این شات را حذف کنیم؟ قابل بازگشت نیست.',
'سوییت اسپات تو','آسیاب','نسبت','از {n} شات برتر تو','شاتی با ۸۵+ ثبت کن تا سوییت اسپات تنظیم شود.',
'رکورد شخصی','این هفته','بازه زمانی','میانگین {score}','هنوز داده‌ای نیست','{count} روز فعال','صادر کردن CSV','برای حذف حساب: chef@lazysous.app'],

'fi': ['Tallenna','Sulje','Peruuta','Toimii','shottia maailmanlaajuisesti','Etusivu',
'Vedä ensimmäinen.','Shotti {n}.','Päivä {n}.','Viime shotti: {score}. {tail}','Täydellinen.','Lähellä.','Yksi viritys.','Nollaa ja uudestaan.','Aseta resepti. Vedä se mikä merkitsee.','Jatka vetämistä. Opimme.',
'Päivä {days} · vielä lepää','Päivä {days} · ikkunassa','Päivä {days} · käytä pian','Päivä {days} · vanhentunut',
'Lepää','Ikkunassa','Käytä pian','Vanhentunut',
'{temp}°C · kosteus {humidity}%','{temp}°C · kosteus {humidity}%','{temp}°C · kosteus {humidity}%',
'Sinun setti.','Sinun setti.','Sinun setti.','Valmis kun olet.','Lisää pavut viritystä varten.','Aseta settisi.','Viisi minuuttia. Paremmat shotit jälkeen.',
'{count} osio jäljellä.','{count} osiota jäljellä.',
'Jokainen shotti, kirjattu.','Vedä yksi. Aloitamme kirjaamisen.','Pisteet, jauhatus, ajautuminen.','{count} shotti. Jatka.','{count} shottia. Jatka.','{count} shottia. 5-shottin keskiarvo {avg}.',
'Yksi näpäytys. Ei salasanoja.','Jatka Metan kanssa','Jatka GitHubin kanssa','Vain lempinimi. Ei salasanoja.','Valitse lempinimi.','Sinun valinta. Tämä on ainoa mitä tallennamme.','esim. billy_bean','Tallenna',
'Vähennä {label} (hieno)','Lisää {label} (hieno)',
'Ensimmäisen shotin jälkeen','Karkeampi','3s liian pitkä. Jauha karkeammaksi.','Vedä. Kirjaa. Kerromme mitä muuttaa.','Vedä. Kirjaa. Kerromme mitä muuttaa seuraavaksi.',
'{delta} {unit} liian vähän','{delta} {unit} liikaa','Pidä','tavoite {value} {unit}',
'Muuta seuraavaa shottia varten','Pidä seuraavaa shottia varten','Tämä shotti',
'Henkilökohtainen ennätys. Nauti hitaasti.','+{delta} edellisestä. Nousussa.','−{delta} edellisestä. Nollaa.','Sama kuin edellinen. Vakaa käsi.','Ensimmäinen tehty. Nyt opimme.',
'PYSÄYTÄ','TALLENNA SHOTTI','Vedetään','Kaappaa shotti','Valmistaudu',
'{seconds}s lyhyt ja {ml}ml liikaa. Jauha hienommaksi.','{seconds}s pitkä ja {ml}ml vajaa. Jauha karkeammaksi.',
'{primary} Mylly hienoimmillaan — nosta annosta.','{primary} Mylly karkeimmillaan — laske annosta.',
'3 shottia hienommin. Kokeile +0,5g.','3 shottia karkeammin. Kokeile −0,5g.',
'Mylly hienoimmillaan. +0,5g lisää vastusta.','Mylly karkeimmillaan. −0,5g vähemmän vastusta.',
'Ohut','Normaali','Paksu','Crema','Maku','Vahvuus','Arvioi myöhemmin','Tallenna arvio',
'Barista-tila','Sulje barista-tila','Barista-tila','{count} shottia · {mins} min',
'Brewmie Premium','Brewmie sinulle viritetty.','Premium',
'Lisää myllysi — suositukset omissa yksiköissäsi.','Jousi- ja autotamperit malliin mukaan.','Tallenna papusi. Vaihda pussia, jatka samasta.','Avaa täysi historia ja trendit.','Vertaa jokaista shottia parhaaseesi.',
'Sinun setti','Mylly, tamper, pavut. Suositukset yksiköissäsi.','Täysi historia','Jokainen shotti tallennettu. Vie milloin haluat.','Henkilökohtaiset ennätykset','Vertaa jokaista shottia parhaaseesi.',
'Vain Brewmie','$6.99','Paketti Lazy Sousin kanssa','$9.99','Dev: avaa dev pillin kautta. Ei oikea osto.',
'Premium','Vanhemmat shotit on tallennettu. Täysi historia Premiumilla.','Avaa henkilökohtaiset ennätykset Premiumilla.','Yleinen mylly. Premium kalibroi omaasi.','Manuaalinen tamp. Premium lisää jousen ja auton.','Yleinen keskipaahto. Premium seuraa papujasi.',
'Käynnistä asetusvelho uudelleen','Asetusvelho','Jatka →',
'Kieli','Näyttökieli','Yleiset','Muut kielet','Brewmie tunnistaa kielen automaattisesti. Valitse toinen täältä. Yleisten ulkopuoliset käännökset voivat olla epätäydellisiä ja palautuvat englantiin.','Viimeksi tehty','Lue koko tietosuojakäytäntö',
'Näytä kaikki {count}','Kaikki shotit ({count})','Muokkaa shottia',
'Aika','Tilavuus','Maku','Vahvuus','Poista','Poistetaanko tämä shotti? Ei voi peruuttaa.',
'Sinun sweet spot','jauhatus','suhde','{n} parhaastasi shotistasi','Kirjaa 85+ shotti asettaaksesi sweet spotin.',
'Henkilökohtainen ennätys','Tällä viikolla','Aikaikkuna','keskim. {score}','ei vielä dataa','Aktiivinen {count} päivää','Vie CSV','Tilin poisto: kirjoita chef@lazysous.app'],

'fil': ['I-save','Isara','Kanselahin','Pinapagana ng','shots sa buong mundo','Home',
'Hilain mo na ang una.','Shot {n}.','Araw {n}.','Huling shot: {score}. {tail}','Tama.','Malapit na.','Isa lang ang ayos.','I-reset at ulitin.','I-set ang recipe. Hilain ang importante.','Tuloy lang. Natututo kami.',
'Araw {days} · nagpapahinga pa','Araw {days} · sa window','Araw {days} · gamitin agad','Araw {days} · lipas na',
'Nagpapahinga','Sa window','Gamitin agad','Lipas na',
'{temp}°C · {humidity}% halumigmig','{temp}°C · {humidity}% halumigmig','{temp}°C · {humidity}% halumigmig',
'Ang gear mo.','Ang gear mo.','Ang gear mo.','Handa kahit kailan.','Magdagdag ng beans para makapag-dial in.','I-set up ang gear mo.','Limang minuto. Mas mahusay na shots pagkatapos.',
'May {count} section pa.','May {count} sections pa.',
'Bawat shot, naitala.','Hilain ang isa. Magsisimula na kami magtala.','Score, gilingan, drift mo.','{count} shot. Tuloy lang.','{count} shots. Tuloy lang.','{count} shots. 5-shot average {avg}.',
'Isang tap. Walang password.','Magpatuloy sa Meta','Magpatuloy sa GitHub','Nickname lang. Walang password.','Pumili ng nickname.','Bahala ka. Ito lang ang ina-save namin.','hal. billy_bean','I-save',
'Bawasan ang {label} (fine)','Dagdagan ang {label} (fine)',
'Pagkatapos ng unang shot','Mas magaspang','3s mahaba. Mas magaspang ang giling.','Hilain. I-log. Sasabihin namin kung ano babaguhin.','Hilain. I-log. Sasabihin namin kung ano babaguhin sa susunod.',
'{delta} {unit} kulang','{delta} {unit} sobra','I-tira na lang','target {value} {unit}',
'Baguhin para sa susunod na shot','Panatilihin para sa susunod na shot','Itong shot',
'Personal best. Inumin nang mabagal.','+{delta} kaysa nakaraan. Tumataas.','−{delta} kaysa nakaraan. I-reset.','Pareho sa nakaraan. Matatag na kamay.','Tapos na ang una. Ngayon, matututo na tayo.',
'TUMIGIL','I-SAVE ANG SHOT','Naghihila','Hulihin ang shot','Maghanda',
'{seconds}s maikli at {ml}ml sobra. Mas pinong giling.','{seconds}s mahaba at {ml}ml kulang. Mas magaspang ang giling.',
'{primary} Grinder sa pinakapino — dagdagan ang dose.','{primary} Grinder sa pinakamagaspang — bawasan ang dose.',
'3 shots mas pino. Subukan +0.5g.','3 shots mas magaspang. Subukan −0.5g.',
'Grinder sa pinakapino. +0.5g para sa dagdag na resistance.','Grinder sa pinakamagaspang. −0.5g para sa mas kaunting resistance.',
'Manipis','Normal','Makapal','Crema','Lasa','Lakas','I-rate later','I-save ang rating',
'Barista mode','I-off ang barista mode','Barista mode','{count} shots · {mins} min',
'Brewmie Premium','Brewmie na nakatutok sa\'yo.','Premium',
'Idagdag ang grinder mo — recommendations sa units mo.','Spring at auto tampers papasok sa model.','I-save ang beans mo. Magpalit ng bag, tuloy lang.','I-unlock ang buong history at trends.','Ihambing bawat shot sa best mo.',
'Ang gear mo','Grinder, tamper, beans. Recommendations sa units mo.','Buong history','Bawat shot na-save. Mag-export kahit kailan.','Personal benchmarks','Ihambing bawat shot sa best mo.',
'Brewmie lang','$6.99','Bundle sa Lazy Sous','$9.99','Dev: unlock sa pamamagitan ng dev pill. Hindi tunay na pagbili.',
'Premium','Mga lumang shots ay naka-save. Buong history sa Premium.','I-unlock ang personal benchmarks gamit ang Premium.','Generic grinder. Sinasaayos ng Premium para sa iyo.','Manual tamp. Nagdadagdag ang Premium ng spring at auto.','Generic medium roast. Tina-track ng Premium ang beans mo.',
'I-run muli ang setup wizard','Setup wizard','Magpatuloy →',
'Wika','Wika ng display','Karaniwan','Iba pang wika','Awtomatikong nakikilala ng Brewmie ang wika mo. Pumili ng iba dito. Pagsasalin sa labas ng karaniwang listahan ay maaaring hindi kumpleto at babalik sa Ingles.','Huling beses','Basahin ang buong privacy policy',
'Tingnan lahat ({count})','Lahat ng shots ({count})','I-edit ang shot',
'Oras','Volume','Lasa','Lakas','Tanggalin','Tanggalin itong shot? Hindi na maibabalik.',
'Ang sweet spot mo','giling','ratio','mula sa top {n} shots mo','Mag-log ng 85+ shot para masimulan ang sweet spot mo.',
'Personal best','Linggong ito','Time window','avg {score}','wala pang data','Active sa {count} araw','I-export CSV','Para mag-delete ng account, i-email ang chef@lazysous.app'],

'ga': ['Sábháil','Dún','Cealaigh','Á chumhachtú ag','seat ar fud an domhain','Baile',
'Tarraing do chéad cheann.','Seat {n}.','Lá {n}.','Seat deireanach: {score}. {tail}','Foirfe.','Beagán uait.','Tweak amháin.','Athshocraigh agus ar ais.','Socraigh an oideas. Tarraing an cheann tábhachtach.','Lean ag tarraingt. Táimid ag foghlaim.',
'Lá {days} · ag scíth fós','Lá {days} · san fhuinneog','Lá {days} · úsáid go luath','Lá {days} · sean',
'Ag scíth','San fhuinneog','Úsáid go luath','Sean',
'{temp}°C · {humidity}% taise','{temp}°C · {humidity}% taise','{temp}°C · {humidity}% taise',
'Do threalamh.','Do threalamh.','Do threalamh.','Réidh nuair atá tusa.','Cuir pónairí leis chun calabrú.','Socraigh do threalamh.','Cúig nóiméad. Seataí níos fearr ina dhiaidh.',
'{count} alt fágtha.','{count} alt fágtha.',
'Gach seat, taifeadta.','Tarraing ceann. Tosóimid ag taifeadadh.','Do scór, meilt, drift.','{count} seat. Lean ar aghaidh.','{count} seat. Lean ar aghaidh.','{count} seat. Meán 5: {avg}.',
'Tapáil amháin. Gan pasfhocail.','Lean le Meta','Lean le GitHub','Leasainm amháin. Gan pasfhocal.','Roghnaigh leasainm.','Mar is mian leat. Sin an t-aon rud a shábhálann muid.','m.sh. billy_bean','Sábháil',
'Laghdaigh {label} go mín','Méadaigh {label} go mín',
'Tar éis do chéad seat','Níos gairbhe','3s ró-fhada. Meilt níos gairbhe.','Tarraing. Logáil. Inseoidh muid duit cad atá le hathrú.','Tarraing. Logáil. Inseoidh muid duit cad atá le hathrú an chéad uair eile.',
'{delta} {unit} gearr','{delta} {unit} fada','Coinnigh','sprioc {value} {unit}',
'Athraigh don chéad seat eile','Coinnigh don chéad seat eile','An seat seo',
'Curiarracht phearsanta. Bain sult as go mall.','+{delta} ar an gceann deireanach. Ag ardú.','−{delta} ar an gceann deireanach. Athshocraigh.','Mar an gcéanna leis an gceann deireanach. Lámh dhaingean.','An chéad cheann déanta. Anois ag foghlaim.',
'STAD','SÁBHÁIL SEAT','Á tharraingt','Tóg an seat','Bí réidh',
'{seconds}s gearr agus {ml}ml ró-mhór. Meilt níos míne.','{seconds}s fada agus {ml}ml ró-bheag. Meilt níos gairbhe.',
'{primary} Muileann ar an gceann is míne — méadaigh an dáileog.','{primary} Muileann ar an gceann is gairbhe — laghdaigh an dáileog.',
'3 seat níos míne. Bain triail as +0.5g.','3 seat níos gairbhe. Bain triail as −0.5g.',
'Muileann ar an gceann is míne. +0.5g do friotaíocht níos mó.','Muileann ar an gceann is gairbhe. −0.5g do friotaíocht níos lú.',
'Tanaí','Gnách','Tiubh','Crema','Blas','Neart','Marcáil níos déanaí','Sábháil rátáil',
'Mód barista','Múch mód barista','Mód barista','{count} seat · {mins} nóim',
'Brewmie Premium','Brewmie ar leagan amach duit.','Premium',
'Cuir do mhuileann isteach — moltaí i d\'aonaid.','Téann tamperaí sprionga agus uathoibríocha isteach sa mhúnla.','Sábháil do phónairí. Athraigh mála, lean ar aghaidh.','Dícheangail stair iomlán agus treochtaí.','Cuir gach seat i gcomparáid le do cheann is fearr.',
'Do threalamh','Muileann, tamper, pónairí. Moltaí i d\'aonaid.','Stair iomlán','Sábháil gach seat. Easpórtáil aon uair.','Mírbhuncháis phearsanta','Cuir gach seat i gcomparáid le do cheann is fearr.',
'Brewmie amháin','$6.99','Beart le Lazy Sous','$9.99','Dev: dícheangail trí dev pill. Ní fíor-cheannach é.',
'Premium','Sábháilte na seataí níos sine. Stair iomlán le Premium.','Dícheangail Mírbhuncháis Phearsanta le Premium.','Muileann ginearálta. Calabraíonn Premium do do cheann féin.','Tamp de láimh. Cuireann Premium sprionga agus uathoibríoch leis.','Rósta meánach ginearálta. Leanann Premium do phónairí.',
'Athchasadh draoi socraithe','Draoi socraithe','Lean →',
'Teanga','Teanga taispeána','Coitianta','Teangacha eile','Brathann Brewmie do theanga go huathoibríoch. Roghnaigh ceann eile anseo. Aistriúcháin lasmuigh den liosta coitianta is féidir leo a bheith neamhiomlán agus dul ar ais go Béarla.','An uair dheireanach','Léigh an polasaí príobháideachais iomlán',
'Féach gach {count}','Gach seat ({count})','Cuir seat in eagar',
'Am','Toirt','Blas','Neart','Scrios','Scrios an seat seo? Ní féidir é a chealú.',
'Do sweet spot','meilt','cóimheas','as do {n} seat is fearr','Logáil seat 85+ chun do sweet spot a shocrú.',
'Curiarracht phearsanta','An tseachtain seo','Fuinneog ama','meán {score}','gan sonraí fós','{count} lá gníomhach','Easpórtáil CSV','Le cuntas a scriosadh, déan teagmháil le chef@lazysous.app'],
}


def set_nested(d, key, value):
    parts = key.split('.')
    cur = d
    for p in parts[:-1]:
        if p not in cur or not isinstance(cur[p], dict):
            cur[p] = {}
        cur = cur[p]
    cur[parts[-1]] = value


def main():
    assert len(KEYS) == 151, f'KEYS has {len(KEYS)} entries; expected 146'
    for locale, vals in LOCALES.items():
        if len(vals) != 151:
            print(f'  SKIP {locale}: {len(vals)} values, expected 151')
            continue
        path = TR / f'{locale}.json'
        existing = json.loads(path.read_text(encoding='utf-8'))
        for k, v in zip(KEYS, vals):
            set_nested(existing, k, v)
        path.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        print(f'{locale}: filled {len(vals)} keys')


if __name__ == '__main__':
    main()
