#!/usr/bin/env python3
"""Tier 2 batch C: ms, mt, my, ps, ro, rw, sd, si, sk, sw, ta, te, th, uk, ur."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TR = ROOT / 'public' / 'translations'

KEYS = [
    'common.save','common.close','common.cancel','footer.poweredBy','footer.shotsGlobally','header.home',
    'hero.brewFirst','hero.shotN','hero.dayN','hero.statusLastShot','hero.statusNailed','hero.statusClose',
    'hero.statusOneTweak','hero.statusKeepGoing','hero.statusReady','hero.statusKeepPulling',
    'hero.beanResting','hero.beanDay','hero.beanUseSoon','hero.beanStale',
    'hero.beanRestingShort','hero.beanDayShort','hero.beanUseSoonShort','hero.beanStaleShort',
    'hero.weatherHumid','hero.weatherDry','hero.weatherNeutral',
    'hero.setupYourKit','hero.setupKitOnFile','hero.setupAllSetBig','hero.setupAllSet','hero.setupAddBeans',
    'hero.setupEmpty','hero.setupEmptySub','hero.setupSectionsToGo','hero.setupSectionsToGoPlural',
    'hero.insightsBig','hero.insightsEmpty','hero.insightsEmptySub','hero.insightsCount','hero.insightsCountPlural','hero.insightsAvg',
    'auth.providerSub','auth.continueMeta','auth.continueGitHub','auth.privacyNote','auth.nicknameTitle','auth.nicknameSub','auth.nicknamePlaceholder','auth.nicknameSubmit',
    'brew.decreaseFine','brew.increaseFine','brew.coachPreviewBadge','brew.coachPreviewDirection','brew.coachPreviewReason','brew.coachPreviewCaption','brew.coachLine',
    'brew.outcomeShort','brew.outcomeLong','brew.holdAtTarget','brew.targetWas','brew.sectionChange','brew.sectionHold','brew.sectionShot',
    'brew.scoreBest','brew.scoreUp','brew.scoreDown','brew.scoreSame','brew.scoreFirst',
    'brew.stop','brew.saveShot','brew.timingRunning','brew.timingStopped','brew.countdownSub',
    'brew.reasonRanFastBoth','brew.reasonRanSlowBoth','brew.reasonGrindAtMin','brew.reasonGrindAtMax',
    'brew.doseTrendUp','brew.doseTrendDown','brew.doseGrindAtMin','brew.doseGrindAtMax',
    'crema.thin','crema.normal','crema.thick','rating.crema','rating.flavour','rating.strength','rating.later','rating.save',
    'barista.toggleOn','barista.toggleOff','barista.active','barista.sessionMeta',
    'premium.eyebrow','premium.title','premium.lockBadge','premium.triggerGrinder','premium.triggerTamper','premium.triggerBeans','premium.triggerHistory','premium.triggerBenchmarks',
    'premium.feature1Head','premium.feature1Sub','premium.feature2Head','premium.feature2Sub','premium.feature3Head','premium.feature3Sub',
    'premium.ctaBrewmie','premium.priceBrewmie','premium.ctaBundle','premium.priceBundle','premium.devNote',
    'tierLock.badge','tierLock.historyMore','tierLock.benchmarksLocked','tierLock.genericGrinder','tierLock.genericTamper','tierLock.genericBeans',
    'setup.profileCtaReset','setup.bannerEyebrow','setup.bannerCta',
    'setup.cardLanguage','setup.languageLabel','setup.languageMajor','setup.languageMore','setup.languageHint','setup.maintLastDone','setup.privacyPolicyLink',
    'insights.viewAll','insights.allShotsTitle','insights.editShot','insights.editTime','insights.editVolume','insights.editTaste','insights.editStrength',
    'insights.deleteShot','insights.confirmDeleteShot','insights.sweetSpotEyebrow','insights.bestGrindLabel','insights.ratioLabel','insights.fromNShots','insights.noTopShots',
    'insights.personalBest','insights.thisWeek','insights.timeWindow','insights.avgScore','insights.noShotsYet','insights.daysActive','insights.exportCsv','insights.deleteAccountEmail',
]

LOCALES = {
'ms': ['Simpan','Tutup','Batal','Dikuasakan oleh','shot di seluruh dunia','Laman utama',
'Tarik shot pertama anda.','Shot {n}.','Hari {n}.','Shot terakhir: {score}. {tail}','Tepat.','Hampir.','Satu pelarasan.','Tetapkan semula dan ulang.','Tetapkan resipi. Tarik yang penting.','Teruskan tarik. Kami sedang belajar.',
'Hari {days} · masih berehat','Hari {days} · dalam tetingkap','Hari {days} · guna segera','Hari {days} · sudah lapuk',
'Berehat','Dalam tetingkap','Guna segera','Lapuk',
'{temp}°C · kelembapan {humidity}%','{temp}°C · kelembapan {humidity}%','{temp}°C · kelembapan {humidity}%',
'Peralatan anda.','Peralatan anda.','Peralatan anda.','Sedia bila anda sedia.','Tambah biji untuk laras.','Sediakan peralatan anda.','Lima minit. Shot lebih baik selepasnya.',
'{count} bahagian lagi.','{count} bahagian lagi.',
'Setiap shot, direkod.','Tarik satu. Kami mula merekod.','Markah, kisaran, hanyutan anda.','{count} shot. Teruskan.','{count} shot. Teruskan.','{count} shot. Purata 5: {avg}.',
'Satu sentuh. Tiada kata laluan.','Teruskan dengan Meta','Teruskan dengan GitHub','Nama panggilan sahaja. Tiada kata laluan.','Pilih nama panggilan.','Terpulang. Itu sahaja yang kami simpan.','cth. billy_bean','Simpan',
'Kurangkan {label} (halus)','Tambah {label} (halus)','Selepas shot pertama','Lebih kasar','3s panjang. Kisar lebih kasar.','Tarik. Rekod. Kami beritahu apa nak ubah.','Tarik. Rekod. Kami beritahu apa nak ubah seterusnya.',
'{delta} {unit} pendek','{delta} {unit} lebih','Biarkan','sasaran {value} {unit}','Tukar untuk shot seterusnya','Kekalkan untuk shot seterusnya','Shot ini',
'Rekod peribadi. Hirup perlahan.','+{delta} dari sebelumnya. Menaik.','−{delta} dari sebelumnya. Tetapkan semula.','Sama dengan sebelumnya. Tangan tetap.','Pertama selesai. Sekarang belajar.',
'BERHENTI','SIMPAN SHOT','Tarik','Tangkap shot','Bersedia',
'{seconds}s pendek dan {ml}ml lebih. Kisar halus.','{seconds}s panjang dan {ml}ml kurang. Kisar kasar.',
'{primary} Pengisar pada paling halus — naikkan dos.','{primary} Pengisar pada paling kasar — kurangkan dos.',
'3 shot lebih halus. Cuba +0.5g.','3 shot lebih kasar. Cuba −0.5g.',
'Pengisar pada paling halus. +0.5g untuk lebih rintangan.','Pengisar pada paling kasar. −0.5g untuk kurang rintangan.',
'Nipis','Biasa','Tebal','Crema','Rasa','Kekuatan','Nilai kemudian','Simpan penilaian',
'Mod barista','Tutup mod barista','Mod barista','{count} shot · {mins} min',
'Brewmie Premium','Brewmie ditala untuk anda.','Premium',
'Tambah pengisar anda — cadangan dalam unit anda.','Tamper spring dan auto masuk ke model.','Simpan biji anda. Tukar beg, sambung dari tempat berhenti.','Buka sejarah penuh dan trend.','Bandingkan setiap shot dengan terbaik anda.',
'Peralatan anda','Pengisar, tamper, biji. Cadangan dalam unit anda.','Sejarah penuh','Setiap shot disimpan. Eksport bila-bila.','Penanda aras peribadi','Bandingkan setiap shot dengan terbaik anda.',
'Brewmie sahaja','$6.99','Bundle dengan Lazy Sous','$9.99','Dev: buka melalui dev pill. Bukan pembelian sebenar.',
'Premium','Shot lama disimpan. Sejarah penuh dengan Premium.','Buka penanda aras peribadi dengan Premium.','Pengisar generik. Premium tala kepada anda.','Tamp manual. Premium tambah spring dan auto.','Pemanggangan sederhana generik. Premium jejak biji anda.',
'Jalan semula bestari','Bestari','Teruskan →',
'Bahasa','Bahasa paparan','Biasa','Bahasa lain','Brewmie mengesan bahasa anda secara automatik. Pilih lain di sini. Terjemahan di luar biasa mungkin tidak lengkap dan kembali kepada bahasa Inggeris.','Kali terakhir','Baca dasar privasi penuh',
'Lihat semua ({count})','Semua shot ({count})','Edit shot','Masa','Isipadu','Rasa','Kekuatan','Padam','Padam shot ini? Tidak boleh dibatalkan.',
'Titik manis anda','kisaran','nisbah','dari {n} shot terbaik anda','Rekod shot 85+ untuk tetapkan titik manis.',
'Rekod peribadi','Minggu ini','Tetingkap masa','purata {score}','tiada data lagi','Aktif {count} hari','Eksport CSV','Untuk padam akaun, e-mel chef@lazysous.app'],

'mt': ['Issejvja','Agħlaq','Ikkanċella','Imħaddma minn','shots madwar id-dinja','Dar',
'Iġbed l-ewwel.','Shot {n}.','Jum {n}.','L-aħħar shot: {score}. {tail}','Perfett.','Qrib.','Aġġustament wieħed.','Erġa ibda.','Issettja r-riċetta. Iġbed dak li jgħodd.','Kompli iġbed. Qed nitgħallmu.',
'Jum {days} · għadu jistrieħ','Jum {days} · fit-tieqa','Jum {days} · uża dalwaqt','Jum {days} · skadut',
'Jistrieħ','Fit-tieqa','Uża dalwaqt','Skadut',
'{temp}°C · umdità {humidity}%','{temp}°C · umdità {humidity}%','{temp}°C · umdità {humidity}%',
'It-tagħmir tiegħek.','It-tagħmir tiegħek.','It-tagħmir tiegħek.','Lest meta inti.','Żid żrieragħ biex tikkalibra.','Issettja t-tagħmir tiegħek.','Ħames minuti. Shots aħjar wara.',
'{count} taqsima fadal.','{count} taqsimiet fadal.',
'Kull shot, irreġistrat.','Iġbed wieħed. Nibdew nirreġistraw.','L-iskor, it-tħin, id-drift tiegħek.','{count} shot. Kompli.','{count} shots. Kompli.','{count} shots. Medja ta\' 5: {avg}.',
'Tap wieħed. Bla password.','Kompli b\'Meta','Kompli b\'GitHub','Laqam biss. Bla password.','Agħżel laqam.','Tiegħek. Hu l-uniku ħaġa li nsalvaw.','eż. billy_bean','Issejvja',
'Naqqas {label} (fin)','Żid {label} (fin)','Wara l-ewwel shot tiegħek','Eħxen','3s twil. Itħan eħxen.','Iġbed. Irreġistra. Ngħidulek x\'tibdel.','Iġbed. Irreġistra. Ngħidulek x\'tibdel id-darba li jmiss.',
'{delta} {unit} qasir','{delta} {unit} twil','Żomm','mira {value} {unit}','Ibdel għax-shot li jmiss','Żomm għax-shot li jmiss','Dan ix-shot',
'Rekord personali. Doqq bil-mod.','+{delta} fuq ta\' qabel. Tielgħa.','−{delta} fuq ta\' qabel. Erġa ibda.','L-istess bħal ta\' qabel. Id soda.','L-ewwel sar. Issa nitgħallmu.',
'IEQAF','SALVA SHOT','Niġbed','Aqbad ix-shot','Lest',
'{seconds}s qasir u {ml}ml żejjed. Itħan oqsla.','{seconds}s twil u {ml}ml nieqes. Itħan eħxen.',
'{primary} Tħin fl-iktar fin — żid id-doża.','{primary} Tħin fl-iktar eħxen — naqqas id-doża.',
'3 shots oqsla. Ipprova +0.5g.','3 shots eħxen. Ipprova −0.5g.',
'Tħin fl-iktar fin. +0.5g għal aktar reżistenza.','Tħin fl-iktar eħxen. −0.5g għal anqas reżistenza.',
'Irqiqa','Normali','Ħoxna','Crema','Togħma','Saħħa','Ivvalwa wara','Salva valutazzjoni',
'Mod barista','Itfi mod barista','Mod barista','{count} shots · {mins} min',
'Brewmie Premium','Brewmie aġġustat għalik.','Premium',
'Żid it-tħin tiegħek — rakkomandazzjonijiet fl-unitajiet tiegħek.','Tampers spring u awtomatiċi fil-mudell.','Salva ż-żrieragħ tiegħek. Ibdel l-borża, kompli minn fejn waqaft.','Iftah l-istorja sħiħa u t-tendenzi.','Qabbel kull shot mal-aqwa tiegħek.',
'It-tagħmir tiegħek','Tħin, tamper, żrieragħ. Rakkomandazzjonijiet fl-unitajiet tiegħek.','Storja sħiħa','Kull shot salvat. Esporta meta trid.','Marki personali','Qabbel kull shot mal-aqwa tiegħek.',
'Brewmie biss','$6.99','Bundle ma\' Lazy Sous','$9.99','Dev: jinfetaħ b\'dev pill. Mhux xirja vera.',
'Premium','Shots qodma huma salvati. Storja sħiħa b\'Premium.','Iftah marki personali b\'Premium.','Tħin ġeneriku. Premium jikkalibra għal tiegħek.','Tamp manwali. Premium iżid spring u auto.','Inkaljat medju ġeneriku. Premium isegwi ż-żrieragħ tiegħek.',
'Erġa ibda l-wizard tas-setup','Setup','Kompli →',
'Lingwa','Lingwa tal-wirja','Komuni','Lingwi oħra','Brewmie jagħraf il-lingwa awtomatikament. Agħżel oħra hawn. Traduzzjonijiet barra mill-komuni jistgħu jkunu inkompleti u jirritornaw għall-Ingliż.','L-aħħar darba','Aqra l-politika tal-privatezza sħiħa',
'Ara l-{count} kollha','Ix-shots kollha ({count})','Editja shot','Ħin','Volum','Togħma','Saħħa','Ħassar','Tneħħi dan ix-shot? Ma jistax jiġi annullat.',
'Il-punt ħelu tiegħek','tħin','proporzjon','mill-aqwa {n} shots tiegħek','Irreġistra shot ta\' 85+ biex tissettja l-punt ħelu.',
'Rekord personali','Din il-ġimgħa','Tieqa ta\' ħin','medja {score}','għad m\'hemmx data','Attiv {count} ġranet','Esporta CSV','Biex tħassar l-account, ibgħat email lil chef@lazysous.app'],

'my': ['သိမ်းမည်','ပိတ်','ပယ်ဖျက်','အလုပ်လုပ်စေသူ','shot ကမ္ဘာတစ်ဝန်း','ပင်မ',
'ပထမတစ်ခုကို ဆွဲထုတ်ပါ။','Shot {n}။','နေ့ {n}။','နောက်ဆုံး shot: {score}။ {tail}','ပြည့်စုံ။','နီးနီး။','တစ်ခုပဲ ပြင်ရန်။','ပြန်စပါ။','Recipe သတ်မှတ်ပါ။ အရေးကြီးတာကို ဆွဲထုတ်ပါ။','ဆက်ဆွဲထုတ်ပါ။ ကျွန်ုပ်တို့ သင်ယူနေသည်။',
'နေ့ {days} · အနားယူနေဆဲ','နေ့ {days} · အကောင်းဆုံးအချိန်','နေ့ {days} · မကြာမီသုံးပါ','နေ့ {days} · ဟောင်းနေပြီ',
'အနားယူနေ','အကောင်းဆုံးအချိန်','မကြာမီသုံးပါ','ဟောင်းနေပြီ',
'{temp}°C · စိုထိုင်းဆ {humidity}%','{temp}°C · စိုထိုင်းဆ {humidity}%','{temp}°C · စိုထိုင်းဆ {humidity}%',
'သင့်ပစ္စည်း။','သင့်ပစ္စည်း။','သင့်ပစ္စည်း။','သင်အသင့်ဖြစ်လျှင်။','ချိန်ညှိရန် bean များ ထည့်ပါ။','သင့်ပစ္စည်းကို သတ်မှတ်ပါ။','၅ မိနစ်။ နောက်ပိုင်း shot များ ပိုကောင်းမည်။',
'အပိုင်း {count} ကျန်။','အပိုင်း {count} ကျန်။',
'Shot တိုင်းကို မှတ်တမ်းတင်သည်။','တစ်ခု ဆွဲထုတ်ပါ။ မှတ်တမ်းတင်စတင်မည်။','သင့်အမှတ်၊ ကြိတ်ခြင်း၊ လွဲချော်မှု။','Shot {count}။ ဆက်ပါ။','Shot {count}။ ဆက်ပါ။','Shot {count}။ ၅-shot ပျမ်းမျှ {avg}။',
'တစ်ချက်နှိပ်။ စကားဝှက်မလို။','Meta ဖြင့် ဆက်လုပ်ပါ','GitHub ဖြင့် ဆက်လုပ်ပါ','ခေါ်နာမည်သာ။ စကားဝှက်မရှိ။','ခေါ်နာမည် ရွေးပါ။','သင်ကြိုက်သလို။ ဤတစ်ခုသာ သိမ်းသည်။','ဥပမာ billy_bean','သိမ်းမည်',
'{label} ကို သေသပ်စွာ လျှော့','{label} ကို သေသပ်စွာ တိုး','ပထမ shot ပြီးနောက်','ပိုကြမ်း','၃ စက္ကန့် ရှည်သည်။ ပိုကြမ်းကြိတ်ပါ။','ဆွဲထုတ်ပါ။ မှတ်တမ်းတင်ပါ။ ဘာပြောင်းရမည်ကို ပြောမည်။','ဆွဲထုတ်ပါ။ မှတ်တမ်းတင်ပါ။ နောက်တစ်ခါ ဘာပြောင်းရမည်ကို ပြောမည်။',
'{delta} {unit} လို','{delta} {unit} ပို','ထားပါ','ပန်းတိုင် {value} {unit}','နောက် shot အတွက် ပြောင်းပါ','နောက် shot အတွက် ထားပါ','ဤ shot',
'ကိုယ်ပိုင်စံချိန်။ ဖြည်းဖြည်း သောက်ပါ။','ယခင်ထက် +{delta}။ တက်နေသည်။','ယခင်ထက် −{delta}။ ပြန်စပါ။','ယခင်အတိုင်း။ ခိုင်မြဲသော လက်။','ပထမ ပြီးပြီ။ ယခု သင်ယူမည်။',
'ရပ်ပါ','SHOT သိမ်းမည်','ဆွဲထုတ်နေ','Shot ဖမ်းပါ','အသင့်ဖြစ်ပါ',
'{seconds}s တို၊ {ml}ml ပိုသည်။ ပိုသိမ်မွေ့ ကြိတ်ပါ။','{seconds}s ရှည်၊ {ml}ml လိုသည်။ ပိုကြမ်း ကြိတ်ပါ။',
'{primary} ကြိတ်စက် အသိမ်ဆုံး — dose တိုးပါ။','{primary} ကြိတ်စက် အကြမ်းဆုံး — dose လျှော့ပါ။',
'Shot ၃ ခု ပိုသိမ်။ +0.5g စမ်းကြည့်ပါ။','Shot ၃ ခု ပိုကြမ်း။ −0.5g စမ်းကြည့်ပါ။',
'ကြိတ်စက် အသိမ်ဆုံး။ ခုခံမှု ပိုရရန် +0.5g။','ကြိတ်စက် အကြမ်းဆုံး။ ခုခံမှု လျှော့ရန် −0.5g။',
'ပါး','ပုံမှန်','ထူ','Crema','အရသာ','အရင်း','နောက်မှ အကဲဖြတ်','အကဲဖြတ်မှု သိမ်း',
'Barista mode','Barista mode ပိတ်','Barista mode','Shot {count} ခု · {mins} မိနစ်',
'Brewmie Premium','သင့်အတွက် Brewmie။','Premium',
'သင့် ကြိတ်စက်ကို ထည့်ပါ — အကြံပြုချက်များ သင့်ယူနစ်များဖြင့်။','Spring နှင့် auto tamper များ မော်ဒယ်ထဲသို့။','သင့် bean များ သိမ်းပါ။ အိတ်ပြောင်း၊ ရပ်ထားသည့်နေရာက ဆက်လုပ်ပါ။','သမိုင်းအပြည့်နှင့် ခေတ်ရေစီးကြောင်းများ ဖွင့်ပါ။','Shot တိုင်းကို သင့်အကောင်းဆုံးနှင့် နှိုင်းပါ။',
'သင့်ပစ္စည်း','ကြိတ်စက်၊ tamper၊ bean။ အကြံပြုချက်များ သင့်ယူနစ်များဖြင့်။','သမိုင်းအပြည့်','Shot တိုင်း သိမ်းသည်။ အချိန်တိုင်း export လုပ်ပါ။','ကိုယ်ပိုင် စံချိန်များ','Shot တိုင်းကို သင့်အကောင်းဆုံးနှင့် နှိုင်းပါ။',
'Brewmie တစ်ခုတည်း','$6.99','Lazy Sous နှင့် bundle','$9.99','Dev: dev pill ဖြင့် ဖွင့်သည်။ စစ်မှန်သော ဝယ်ယူမှု မဟုတ်။',
'Premium','Shot ဟောင်းများ သိမ်းထား။ Premium ဖြင့် သမိုင်းအပြည့်။','Premium ဖြင့် ကိုယ်ပိုင်စံချိန်များကို ဖွင့်ပါ။','ယေဘုယျ ကြိတ်စက်။ Premium က သင့်အတွက် ချိန်ညှိ။','လက်ဖြင့် tamp။ Premium က spring နှင့် auto ထည့်။','ယေဘုယျ အလယ်အလတ် ရှာထား။ Premium က သင့် bean များ ခြေရာခံ။',
'Setup wizard ပြန်စတင်','Setup','ဆက်လုပ်ပါ →',
'ဘာသာစကား','မြင်ကွင်း ဘာသာစကား','သာမန်','အခြား ဘာသာစကားများ','Brewmie က ဘာသာစကားကို အလိုအလျောက် သိရှိသည်။ ဤနေရာတွင် အခြားဘာသာစကား ရွေးပါ။ သာမန်အပြင်ဘက် ဘာသာပြန်ဆိုမှုများ မပြည့်စုံ၍ အင်္ဂလိပ်သို့ ပြန်နိုင်သည်။','နောက်ဆုံးတစ်ကြိမ်','ကိုယ်ရေးကာကွယ်မှု မူဝါဒ အပြည့်အစုံ ဖတ်ပါ',
'အားလုံး ({count}) ကို ကြည့်','Shot အားလုံး ({count})','Shot ပြင်','အချိန်','ပမာဏ','အရသာ','အရင်း','ဖျက်','ဤ shot ကို ဖျက်မလား။ ပြန်လည် မရရှိနိုင်။',
'သင့် sweet spot','ကြိတ်ခြင်း','အချိုး','သင့် ထိပ်တန်း shot {n} မှ','Sweet spot သတ်မှတ်ရန် 85+ shot မှတ်တမ်းတင်ပါ။',
'ကိုယ်ပိုင် အကောင်းဆုံး','ဤအပတ်','အချိန် ပြတင်းပေါက်','ပျမ်းမျှ {score}','ဒေတာ မရှိသေး','{count} ရက် တက်ကြွ','CSV export','Account ဖျက်ရန် chef@lazysous.app သို့ email'],

'ps': ['ساتل','بند','لغوه','رهبري شوی','شاټونه په نړۍ کې','کور',
'لومړی یې راوباسه.','شاټ {n}.','ورځ {n}.','وروستی شاټ: {score}. {tail}','بشپړ.','نږدې.','یو سمون.','بیا پیل.','ترکیب وټاکه. مهم یې راوباسه.','راوباسه. موږ زده کوو.',
'ورځ {days} · لاهم آرام کوي','ورځ {days} · په کړکۍ کې','ورځ {days} · ژر یې وکاروه','ورځ {days} · زاړه شوی',
'آرام کوي','په کړکۍ کې','ژر یې وکاروه','زاړه',
'{temp}°C · لمدوالی {humidity}%','{temp}°C · لمدوالی {humidity}%','{temp}°C · لمدوالی {humidity}%',
'ستا تجهیزات.','ستا تجهیزات.','ستا تجهیزات.','هرکله چې وغواړې.','د تنظیم لپاره دانې ورزیات کړه.','تجهیزات تنظیم کړه.','پنځه دقیقې. وروسته غوره شاټونه.',
'{count} برخه پاتې.','{count} برخې پاتې.',
'هر شاټ ثبت کیږي.','یو راوباسه. ثبتول پیل کوو.','ستا نمره، اوړل، انحراف.','{count} شاټ. دوام ورکړه.','{count} شاټونه. دوام ورکړه.','{count} شاټونه. د 5 منځنۍ {avg}.',
'یو ټک. د پاسورډ اړتیا نشته.','د Meta سره دوام','د GitHub سره دوام','یوازې لقب. د پاسورډ اړتیا نشته.','لقب وټاکه.','ستا خوښه. یوازې همدا ساتو.','مثلاً billy_bean','ساتل',
'{label} په باریکۍ کم کړه','{label} په باریکۍ زیات کړه','د لومړي شاټ وروسته','ډبل','3s اوږد. ډبله اوړه.','راوباسه. ثبت. د بدلون په اړه به ووایو.','راوباسه. ثبت. د راتلونکي ځل لپاره بدلون به ووایو.',
'{delta} {unit} لږ','{delta} {unit} ډېر','وساته','هدف {value} {unit}','د راتلونکي شاټ لپاره بدلون','د راتلونکي شاټ لپاره وساته','دا شاټ',
'شخصي ریکارډ. ورو یې وڅښه.','تېر څخه +{delta}. لوړېږي.','تېر څخه −{delta}. بیا پیل.','تېر په څېر. کلک لاس.','لومړی شو. اوس به زده کړو.',
'ودرول','شاټ ساتل','اوبه کوي','شاټ ونیسه','تیار اوسه',
'{seconds}s لنډ او {ml}ml ډېر. باریکه اوړه.','{seconds}s اوږد او {ml}ml لږ. ډبله اوړه.',
'{primary} اوړوونکی په ډېر باریک — ډوز زیات کړه.','{primary} اوړوونکی په ډېر ډبل — ډوز کم کړه.',
'3 شاټونه باریک شول. +0.5g هڅه وکړه.','3 شاټونه ډبل شول. −0.5g هڅه وکړه.',
'اوړوونکی په ډېر باریک. د ډېرې مقاومت لپاره +0.5g.','اوړوونکی په ډېر ډبل. د کم مقاومت لپاره −0.5g.',
'نازکه','عادي','ډبله','کریما','خوند','شدت','وروسته درجه ورکړه','درجه وساته',
'د باریستا حالت','د باریستا حالت بند','د باریستا حالت','{count} شاټونه · {mins} دقیقې',
'Brewmie Premium','ستا لپاره تنظیم شوی Brewmie.','Premium',
'خپل اوړوونکی ورزیات کړه — سپارښتنې ستا په واحدونو کې.','د سپرنګ او اوتو ټامپرونه په ماډل کې.','خپلې دانې وساتل. کڅوړه بدله کړه، له هغه ځایه چې پاتې وې.','بشپړ تاریخ او رجحانات پرانیستل.','هر شاټ د خپل غوره سره پرتله کړه.',
'ستا تجهیزات','اوړوونکی، ټامپر، دانې. سپارښتنې ستا په واحدونو کې.','بشپړ تاریخ','هر شاټ ساتل کیږي. هر وخت صادرول.','شخصي معیارونه','هر شاټ د خپل غوره سره پرتله کړه.',
'یوازې Brewmie','$6.99','د Lazy Sous سره بنډل','$9.99','Dev: د dev pill له لارې پرانیستل کیږي. اصلي پیرودنه نه ده.',
'Premium','زاړه شاټونه ساتل شوي. د Premium سره بشپړ تاریخ.','د Premium سره شخصي معیارونه پرانیستل.','عمومي اوړوونکی. Premium ستا لپاره عیارول کوي.','لاسي ټامپ. Premium سپرنګ او اوتو زیاتوي.','عمومي منځنی وریت. Premium ستا دانې تعقیبوي.',
'د تنظیم ویزارډ بیا پیل کړه','تنظیم','دوام →',
'ژبه','د ښودنې ژبه','عام','نورې ژبې','Brewmie ژبه په اتومات ډول پیژني. دلته بله وټاکه. د عام څخه بهر ژباړې نیمګړې وي او په انګلیسي بدلیږي.','وروستی ځل','بشپړه د محرمیت پالیسي ولولئ',
'ټول وګوره ({count})','ټول شاټونه ({count})','شاټ سم کړه','وخت','حجم','خوند','شدت','حذف','دا شاټ حذف کړه؟ بیرته نه راځي.',
'ستا خوږ ځای','اوړل','تناسب','ستا د غوره {n} شاټونو څخه','د خوږ ځای ټاکلو لپاره 85+ شاټ ثبت کړه.',
'شخصي غوره','دا اونۍ','د وخت کړکۍ','منځنۍ {score}','لاهم ډاټا نشته','{count} ورځې فعال','CSV صادرول','د حساب د لرې کولو لپاره chef@lazysous.app ته بریښنالیک واستوه'],

'ro': ['Salvează','Închide','Anulează','Susținut de','shot-uri la nivel mondial','Acasă',
'Trage primul.','Shot {n}.','Ziua {n}.','Ultimul shot: {score}. {tail}','Perfect.','Aproape.','O ajustare.','Resetare și iar.','Setează rețeta. Trage ce contează.','Continuă să tragi. Învățăm.',
'Ziua {days} · încă se odihnește','Ziua {days} · în fereastră','Ziua {days} · folosește în curând','Ziua {days} · expirat',
'Se odihnește','În fereastră','Folosește în curând','Expirat',
'{temp}°C · umiditate {humidity}%','{temp}°C · umiditate {humidity}%','{temp}°C · umiditate {humidity}%',
'Echipamentul tău.','Echipamentul tău.','Echipamentul tău.','Gata când ești tu.','Adaugă boabe pentru calibrare.','Setează echipamentul.','Cinci minute. Shot-uri mai bune după.',
'A rămas {count} secțiune.','Au rămas {count} secțiuni.',
'Fiecare shot, înregistrat.','Trage unul. Începem să înregistrăm.','Scorul, măcinarea, deriva ta.','{count} shot. Continuă.','{count} shot-uri. Continuă.','{count} shot-uri. Media a 5: {avg}.',
'O atingere. Fără parole.','Continuă cu Meta','Continuă cu GitHub','Doar o poreclă. Fără parole.','Alege o poreclă.','Cum vrei. Asta-i tot ce salvăm.','ex. billy_bean','Salvează',
'Reduce {label} (fin)','Mărește {label} (fin)','După primul shot','Mai grosier','3s prea lung. Macină mai grosier.','Trage. Înregistrează. Îți spunem ce să schimbi.','Trage. Înregistrează. Îți spunem ce să schimbi data viitoare.',
'{delta} {unit} scurt','{delta} {unit} lung','Păstrează','obiectiv {value} {unit}','Schimbă pentru următorul shot','Păstrează pentru următorul shot','Acest shot',
'Record personal. Savurează încet.','+{delta} față de anterior. Urcă.','−{delta} față de anterior. Resetare.','La fel ca anteriorul. Mână fermă.','Primul gata. Acum învățăm.',
'OPREȘTE','SALVEAZĂ SHOT','Tragere','Captează shot-ul','Pregătește-te',
'{seconds}s scurt și {ml}ml în plus. Macină mai fin.','{seconds}s lung și {ml}ml în minus. Macină mai grosier.',
'{primary} Râșnița pe cea mai fină — crește doza.','{primary} Râșnița pe cea mai grosieră — scade doza.',
'3 shot-uri mai fin. Încearcă +0,5g.','3 shot-uri mai grosier. Încearcă −0,5g.',
'Râșnița pe cea mai fină. +0,5g pentru mai multă rezistență.','Râșnița pe cea mai grosieră. −0,5g pentru mai puțină rezistență.',
'Subțire','Normală','Densă','Crema','Gust','Tărie','Evaluează mai târziu','Salvează evaluare',
'Mod barista','Oprește mod barista','Mod barista','{count} shot-uri · {mins} min',
'Brewmie Premium','Brewmie reglat pentru tine.','Premium',
'Adaugă râșnița — recomandări în unitățile tale.','Tamper-e cu arc și automate intră în model.','Salvează-ți boabele. Schimbă punga, continuă de unde ai rămas.','Deblochează istoricul complet și tendințele.','Compară fiecare shot cu cel mai bun al tău.',
'Echipamentul tău','Râșniță, tamper, boabe. Recomandări în unitățile tale.','Istoric complet','Fiecare shot salvat. Exportă oricând.','Repere personale','Compară fiecare shot cu cel mai bun al tău.',
'Doar Brewmie','$6.99','Pachet cu Lazy Sous','$9.99','Dev: se deblochează prin dev pill. Nu e cumpărare reală.',
'Premium','Shot-uri vechi sunt salvate. Istoric complet cu Premium.','Deblochează reperele personale cu Premium.','Râșniță generică. Premium calibrează pentru a ta.','Tamp manual. Premium adaugă arc și automat.','Prăjire medie generică. Premium urmărește boabele tale.',
'Reia asistentul de configurare','Asistent','Continuă →',
'Limba','Limba de afișare','Comune','Alte limbi','Brewmie detectează limba automat. Alege alta aici. Traducerile în afara celor comune pot fi incomplete și revin la engleză.','Ultima dată','Citește politica de confidențialitate completă',
'Vezi toate ({count})','Toate shot-urile ({count})','Editează shot','Timp','Volum','Gust','Tărie','Șterge','Ștergi acest shot? Nu se poate anula.',
'Sweet spot-ul tău','măcinare','raport','din cele {n} mai bune shot-uri ale tale','Înregistrează un shot 85+ pentru a seta sweet spot-ul.',
'Record personal','Săptămâna asta','Fereastra de timp','medie {score}','încă nu sunt date','Activ {count} zile','Exportă CSV','Pentru ștergerea contului trimite email la chef@lazysous.app'],

'rw': ['Bika','Funga','Kuraguza','Bishyigikiwe na','shot ku isi','Ahabanza',
'Saba uwa mbere.','Shot {n}.','Umunsi {n}.','Shot iheruka: {score}. {tail}','Nibyiza.','Hafi.','Kuringaniza kumwe.','Subiramo.','Shyiraho uburyo. Saba ibikenewe.','Komeza usabe. Turiga.',
'Umunsi {days} · iracyaruhukira','Umunsi {days} · mu idirishya','Umunsi {days} · gukoresha vuba','Umunsi {days} · birashaje',
'Iruhuka','Mu idirishya','Gukoresha vuba','Birashaje',
'{temp}°C · ubuhehere {humidity}%','{temp}°C · ubuhehere {humidity}%','{temp}°C · ubuhehere {humidity}%',
'Ibikoresho byawe.','Ibikoresho byawe.','Ibikoresho byawe.','Witeguye igihe ushaka.','Ongeraho imbuto kugira ngo uhuze.','Shyiraho ibikoresho byawe.','Iminota itanu. Shot nziza nyuma.',
'Igice {count} gisigaye.','Ibice {count} bisigaye.',
'Buri shot yandikwa.','Saba imwe. Tugiye gutangira kwandika.','Amanota yawe, isya, kuvana.','Shot {count}. Komeza.','Shot {count}. Komeza.','Shot {count}. Impuzandengo ya 5: {avg}.',
'Gukanda rimwe. Nta ijambo ryibanga.','Komeza na Meta','Komeza na GitHub','Izina ry\'ubwoba gusa. Nta ijambo ryibanga.','Hitamo izina ry\'ubwoba.','Ku bwawe. Ni cyo cyonyine duhuza.','urugero billy_bean','Bika',
'Gabanya {label} (gake)','Wongere {label} (gake)','Nyuma ya shot ya mbere','Cyiza','3s biraza. Sya cyiza.','Saba. Andika. Tuzakubwira icyo guhindura.','Saba. Andika. Tuzakubwira icyo guhindura ubutaha.',
'{delta} {unit} gake','{delta} {unit} byinshi','Bika','intego {value} {unit}','Hindura kuri shot ikurikira','Komeza kuri shot ikurikira','Iyi shot',
'Inyandiko bwite. Nywa buhoro.','+{delta} ku rwa nyuma. Birazamuka.','−{delta} ku rwa nyuma. Subiramo.','Bisa n\'urwa nyuma. Ukuboko gukomeye.','Iya mbere yarangiye. Ubu turiga.',
'HAGARARA','BIKA SHOT','Birashobora','Fata shot','Itegure',
'{seconds}s ngufi na {ml}ml byinshi. Sya gato gato.','{seconds}s biraza na {ml}ml bike. Sya cyiza.',
'{primary} Igisya kiri ku gato kose — wongere ingano.','{primary} Igisya kiri ku cyiza kose — gabanya ingano.',
'3 shots gake gake. Gerageza +0.5g.','3 shots cyiza cyiza. Gerageza −0.5g.',
'Igisya kiri ku gato kose. +0.5g kugira ngo kurushe.','Igisya kiri ku cyiza kose. −0.5g kugira ngo bikomeze.',
'Gato','Bisanzwe','Byinshi','Crema','Uburyohe','Imbaraga','Genera nyuma','Bika gusuzuma',
'Uburyo bwa barista','Hagarika uburyo bwa barista','Uburyo bwa barista','Shot {count} · {mins} min',
'Brewmie Premium','Brewmie yagenewe wewe.','Premium',
'Wongereho igisya cyawe — inama ziri muri unite zawe.','Tamper za sprink n\'iza auto zinjira mu cyitegererezo.','Bika imbuto zawe. Hindura agasakoshi, komeza aho wahagaritse.','Fungura amateka yose n\'uburyo.','Gereranya buri shot n\'iyawe nziza.',
'Ibikoresho byawe','Igisya, tamper, imbuto. Inama muri unite zawe.','Amateka yose','Buri shot ibikwa. Sohora igihe icyo aricyo cyose.','Ibipimo bya bwite','Gereranya buri shot n\'iyawe nziza.',
'Brewmie gusa','$6.99','Bundle na Lazy Sous','$9.99','Dev: birafungukira binyuze muri dev pill. Si urugomero rwa nyaba.',
'Premium','Shots za kera zibikwa. Amateka yose hamwe na Premium.','Fungura ibipimo bya bwite hamwe na Premium.','Igisya rusange. Premium ikuringaniza igisya cyawe.','Tamp y\'intoki. Premium yongera sprink na auto.','Iyoteshwa hagati rusange. Premium ikurikirana imbuto zawe.',
'Subira mu rwego rw\'isuzuma','Isuzuma','Komeza →',
'Ururimi','Ururimi rwo kugaragaza','Bisanzwe','Indi ndimi','Brewmie imenya ururimi rwawe yikora. Hitamo urundi hano. Ibyahinduwe bitari mu bisanzwe bishobora kuba bidakwiye gusubira mu Cyongereza.','Igihe cya nyuma','Soma politiki yose y\'amabanga',
'Reba byose ({count})','Shots zose ({count})','Hindura shot','Igihe','Ingano','Uburyohe','Imbaraga','Siba','Siba iyi shot? Ntibishobora gusubizwa.',
'Aho ushobora cyane','isya','igipimo','muri shots {n} zawe nziza','Andika shot ya 85+ kugira ngo ushyireho aho ushobora cyane.',
'Inyandiko bwite','Iyi cyumweru','Idirishya ry\'igihe','impuzandengo {score}','nta makuru aracyari','Igikora iminsi {count}','Sohora CSV','Kugira ngo usibe konti, ohereza email kuri chef@lazysous.app'],

'sd': ['محفوظ ڪريو','بند','منسوخ','هلائي رهيو آهي','شاٽ پوري دنيا ۾','گهر',
'پنهنجو پهريون ڪڍو.','شاٽ {n}.','ڏينهن {n}.','آخري شاٽ: {score}. {tail}','بلڪل.','ويجهو.','هڪ ترميم.','ٻيهر شروع.','رسيپي سيٽ ڪريو. اهم شيءَ ڪڍو.','ڪڍندا رهو. اسان سکي رهيا آهيون.',
'ڏينهن {days} · اڃا آرام ۾','ڏينهن {days} · بهترين ونڊو ۾','ڏينهن {days} · جلد استعمال ڪريو','ڏينهن {days} · پراڻو',
'آرام ۾','بهترين ونڊو ۾','جلد استعمال ڪريو','پراڻو',
'{temp}°C · رطوبت {humidity}%','{temp}°C · رطوبت {humidity}%','{temp}°C · رطوبت {humidity}%',
'توهان جو سامان.','توهان جو سامان.','توهان جو سامان.','جڏهن توهان تيار آهيو.','ايڊجسٽ ڪرڻ لاءِ ٻج شامل ڪريو.','پنهنجو سامان سيٽ ڪريو.','پنج منٽ. بعد ۾ بهتر شاٽ.',
'{count} حصو باقي.','{count} حصا باقي.',
'هر شاٽ رڪارڊ ٿيو.','هڪ ڪڍو. اسان رڪارڊنگ شروع ڪندا آهيون.','توهان جو اسڪور، پيهائي، ڊرفٽ.','{count} شاٽ. جاري رکو.','{count} شاٽ. جاري رکو.','{count} شاٽ. 5-شاٽ سراسري {avg}.',
'هڪ ٽَپَ. ڪو پاسورڊ نه.','Meta سان جاري رکو','GitHub سان جاري رکو','صرف نِڪ نالو. ڪو پاسورڊ نه.','نِڪ نالو چونڊيو.','توهان جي مرضي. صرف اهو محفوظ ٿيندو آهي.','مثال billy_bean','محفوظ',
'{label} گهٽايو (ٿوري)','{label} وڌايو (ٿوري)','پنهنجي پهرين شاٽ کان پوءِ','وڏو','3s ڊگهو. وڏو پيهو.','ڪڍو. لاگ ڪريو. ٻڌائينداسين ته ڇا تبديل ڪريو.','ڪڍو. لاگ ڪريو. ايندڙ ڀيري ٻڌائينداسين ته ڇا تبديل ڪريو.',
'{delta} {unit} ڪم','{delta} {unit} وڌيڪ','اهڙي ئي رکو','مقصد {value} {unit}','ايندڙ شاٽ لاءِ تبديل ڪريو','ايندڙ شاٽ لاءِ رکو','هي شاٽ',
'ذاتي رڪارڊ. ٿوري ٿوري چکو.','اڳئين کان +{delta}. اڀري رهيو آهي.','اڳئين کان −{delta}. ٻيهر شروع.','اڳئين وانگر. مضبوط هٿ.','پهريون ٿيو. هاڻي اسان سکنداسين.',
'بند',' شاٽ محفوظ','ڪڍي رهيو','شاٽ قبضو ڪريو','تيار ٿيو',
'{seconds}s ننڍو ۽ {ml}ml وڌيڪ. باريڪ پيهو.','{seconds}s ڊگهو ۽ {ml}ml گهٽ. وڏو پيهو.',
'{primary} پيهائيندڙ سڀ کان باريڪ — ڊوز وڌايو.','{primary} پيهائيندڙ سڀ کان وڏو — ڊوز گهٽايو.',
'3 شاٽ باريڪ. +0.5g ڪوشش ڪريو.','3 شاٽ وڏو. −0.5g ڪوشش ڪريو.',
'پيهائيندڙ سڀ کان باريڪ. وڌيڪ مزاحمت لاءِ +0.5g.','پيهائيندڙ سڀ کان وڏو. گهٽ مزاحمت لاءِ −0.5g.',
'پتلي','عام','ٿلهو','ڪريما','ذائقو','شدت','بعد ۾ ريٽ ڪريو','ريٽنگ محفوظ',
'بريسٽا موڊ','بريسٽا موڊ بند','بريسٽا موڊ','{count} شاٽ · {mins} منٽ',
'Brewmie Premium','توهان لاءِ ٺاهيل Brewmie.','Premium',
'پنهنجو پيهائيندڙ شامل ڪريو — سفارشون توهان جي يونٽن ۾.','اسپرنگ ۽ آٽو ٽيمپر ماڊل ۾ داخل.','پنهنجا ٻج محفوظ. ٿيلهو تبديل ڪريو، جتي ڇڏيو هو اتان جاري رکو.','مڪمل تاريخ ۽ رجحانن کي کوليو.','هر شاٽ کي پنهنجي بهترين سان مقابلو ڪريو.',
'توهان جو سامان','پيهائيندڙ، ٽيمپر، ٻج. سفارشون توهان جي يونٽن ۾.','مڪمل تاريخ','هر شاٽ محفوظ. ڪڏهن به ايڪسپورٽ.','ذاتي معيار','هر شاٽ کي پنهنجي بهترين سان مقابلو ڪريو.',
'صرف Brewmie','$6.99','Lazy Sous سان بنڊل','$9.99','Dev: dev pill ذريعي کوليو. حقيقي خريداري نه آهي.',
'Premium','پراڻا شاٽ محفوظ آهن. Premium سان مڪمل تاريخ.','Premium سان ذاتي معيار کوليو.','عام پيهائيندڙ. Premium توهان لاءِ ڪيليبر ڪندو آهي.','هٿيرو ٽيمپ. Premium اسپرنگ ۽ آٽو شامل ڪندو آهي.','عام وچ روسٽ. Premium توهان جا ٻج ٽريڪ ڪندو آهي.',
'سيٽ اپ وزرڊ ٻيهر هلايو','سيٽ اپ','جاري →',
'ٻولي','ڊسپلي ٻولي','عام','ٻيون ٻوليون','Brewmie ٻولي خودبخود سڃاڻي ٿو. هتي ٻي چونڊيو. عام کان ٻاهر ترجما اڻپورا ٿي سگهن ٿا ۽ انگريزي ڏانهن واپس وڃن ٿا.','آخري ڀيرو','مڪمل پرائيويسي پاليسي پڙهو',
'سڀ ({count}) ڏسو','سڀ شاٽ ({count})','شاٽ ايڊٽ','وقت','مقدار','ذائقو','شدت','ڊاهيو','هي شاٽ ڊاهيو؟ واپس نه ٿيندو.',
'توهان جو سويٽ اسپاٽ','پيهائي','تناسب','توهان جي مٿين {n} شاٽن مان','سويٽ اسپاٽ سيٽ ڪرڻ لاءِ 85+ شاٽ رڪارڊ ڪريو.',
'ذاتي بهترين','هن هفتي','وقت ونڊو','اوسط {score}','اڃا تائين ڊيٽا نه','{count} ڏينهن سرگرم','CSV ايڪسپورٽ','اڪائونٽ ڊاهڻ لاءِ chef@lazysous.app کي اي ميل ڪريو'],

'si': ['සුරකින්න','වසන්න','අවලංගු','බලය ලබා දෙන්නේ','shots ලොව පුරා','මුල් පිටුව',
'පළමුවැන්න ඇද්න්න.','Shot {n}.','දින {n}.','අවසන් shot: {score}. {tail}','පරිපූර්ණයි.','ආසන්න.','එක් සමාකරණයක්.','යළි පටන් ගන්න.','වට්ටෝරුව සකසන්න. වැදගත් එක ඇද්න්න.','දිගටම ඇද්න්න. අපි ඉගෙන ගන්නවා.',
'දින {days} · තවමත් විවේකය','දින {days} · කවුළුවේ','දින {days} · ඉක්මනින් භාවිතා කරන්න','දින {days} · පරණයි',
'විවේකය','කවුළුවේ','ඉක්මනින් භාවිතා','පරණයි',
'{temp}°C · ආර්ද්‍රතාවය {humidity}%','{temp}°C · ආර්ද්‍රතාවය {humidity}%','{temp}°C · ආර්ද්‍රතාවය {humidity}%',
'ඔබේ උපකරණ.','ඔබේ උපකරණ.','ඔබේ උපකරණ.','ඔබ සූදානම් විට.','සකස් කිරීමට බෝංචි එක් කරන්න.','ඔබේ උපකරණ සකසන්න.','මිනිත්තු පහක්. පසුව හොඳ shots.',
'{count} කොටසක් ඉතිරි.','{count} කොටස් ඉතිරි.',
'සෑම shot එකක්ම වාර්තා.','එකක් ඇද්න්න. අපි වාර්තා කිරීම ආරම්භ කරමු.','ඔබේ ලකුණු, ඇඹරුම, විසරණය.','{count} shot. දිගටම කරන්න.','{count} shots. දිගටම කරන්න.','{count} shots. 5-shot සාමාන්‍ය {avg}.',
'එක ස්පර්ශයක්. මුරපදයක් නැත.','Meta සමඟ දිගටම','GitHub සමඟ දිගටම','අන්වර්ථ නාමයක් පමණයි. මුරපදයක් නැත.','අන්වර්ථ නාමයක් තෝරන්න.','ඔබ කැමති අයුරින්. අපි ඉතිරි කරන්නේ එයම පමණයි.','උදා. billy_bean','සුරකින්න',
'{label} ස්වල්ප වශයෙන් අඩු','{label} ස්වල්ප වශයෙන් වැඩි','ඔබේ පළමු shot පසු','ඝන','3s දිගුයි. ඝන ලෙස ඇඹරෙන්න.','ඇද්න්න. වාර්තා කරන්න. වෙනස් කළ යුතු දේ අපි කියන්නෙමු.','ඇද්න්න. වාර්තා කරන්න. ඊළඟ වතාවේ වෙනස් කළ යුතු දේ අපි කියන්නෙමු.',
'{delta} {unit} අඩු','{delta} {unit} වැඩි','තබා ගන්න','ඉලක්කය {value} {unit}','ඊළඟ shot සඳහා වෙනස් කරන්න','ඊළඟ shot සඳහා තබා ගන්න','මෙම shot',
'පුද්ගලික වාර්තාව. සෙමින් භුක්ති විඳින්න.','පෙරට වඩා +{delta}. ඉහළට.','පෙරට වඩා −{delta}. යළි පටන් ගන්න.','පෙර හා සමානයි. ස්ථාවර අත.','පළමුවැන්න අවසන්. දැන් අපි ඉගෙන ගන්නවා.',
'නවත්වන්න','SHOT සුරකින්න','ඇදීම','Shot ග්‍රහණය','සූදානම් වන්න',
'{seconds}s කෙටි සහ {ml}ml වැඩි. සියුම් ලෙස ඇඹරෙන්න.','{seconds}s දිගු සහ {ml}ml අඩු. ඝන ලෙස ඇඹරෙන්න.',
'{primary} ඇඹරුම්කරුව සුළුම මට්ටමේ — මාත්‍රාව වැඩි කරන්න.','{primary} ඇඹරුම්කරුව ඝනම මට්ටමේ — මාත්‍රාව අඩු කරන්න.',
'3 shots සියුම්ව. +0.5g උත්සාහ කරන්න.','3 shots ඝන. −0.5g උත්සාහ කරන්න.',
'ඇඹරුම්කරුව සුළුම මට්ටමේ. වැඩි ප්‍රතිරෝධයක් සඳහා +0.5g.','ඇඹරුම්කරුව ඝනම මට්ටමේ. අඩු ප්‍රතිරෝධයක් සඳහා −0.5g.',
'තුනී','සාමාන්‍ය','ඝන','Crema','රසය','ශක්තිය','පසුව ශ්‍රේණිගත කරන්න','ශ්‍රේණිගත කිරීම සුරකින්න',
'Barista ආකාරය','Barista ආකාරය අක්‍රිය','Barista ආකාරය','{count} shots · {mins} මිනි',
'Brewmie Premium','ඔබට සකස් කළ Brewmie.','Premium',
'ඔබේ ඇඹරුම්කරුව එකතු කරන්න — නිර්දේශ ඔබේ ඒකකවලින්.','Spring සහ auto tampers ආකෘතියට ඇතුළත් වේ.','ඔබේ බෝංචි සුරකින්න. බෑගය මාරු කරන්න, නැවැත්වූ තැනින් දිගටම කරන්න.','සම්පූර්ණ ඉතිහාසය සහ ප්‍රවණතා අගුළු හරින්න.','සෑම shot එකක්ම ඔබේ හොඳම සමඟ සංසන්දනය කරන්න.',
'ඔබේ උපකරණ','ඇඹරුම්කරුව, tamper, බෝංචි. නිර්දේශ ඔබේ ඒකකවලින්.','සම්පූර්ණ ඉතිහාසය','සෑම shot එකක්ම සුරකින. ඕනෑම විටක නිර්යාත කරන්න.','පුද්ගලික මිම්ම','සෑම shot එකක්ම ඔබේ හොඳම සමඟ සංසන්දනය කරන්න.',
'Brewmie පමණයි','$6.99','Lazy Sous සමඟ bundle','$9.99','Dev: dev pill හරහා අගුළු හරිනවා. සැබෑ මිලදී ගැනීමක් නොවේ.',
'Premium','පැරණි shots සුරකින. Premium සමඟ සම්පූර්ණ ඉතිහාසය.','Premium සමඟ පුද්ගලික මිම්ම අගුළු හරින්න.','සාමාන්‍ය ඇඹරුම්කරුව. Premium ඔබට ගැළපේ.','අතින් tamp. Premium spring සහ auto එක් කරයි.','සාමාන්‍ය මධ්‍යම roast. Premium ඔබේ බෝංචි අනුගමනය කරයි.',
'සැකසුම් මාර්ගෝපදේශය නැවත','සැකසුම','දිගටම →',
'භාෂාව','පෙන්වීමේ භාෂාව','පොදු','වෙනත් භාෂා','Brewmie ඔබේ භාෂාව ස්වයංක්‍රීයව හඳුනා ගනී. මෙහි වෙනත් එකක් තෝරන්න. පොදු ලැයිස්තුවෙන් පිටත පරිවර්තන අසම්පූර්ණ විය හැකි අතර ඉංග්‍රීසියට ආපසු යයි.','අවසන් වරට','සම්පූර්ණ පෞද්ගලිකත්ව ප්‍රතිපත්තිය කියවන්න',
'සියල්ල ({count}) බලන්න','සියලුම shots ({count})','Shot සංස්කරණය','කාලය','පරිමාව','රසය','ශක්තිය','මකන්න','මෙම shot මකන්නද? ආපසු ලබා ගත නොහැක.',
'ඔබේ sweet spot','ඇඹරුම','අනුපාතය','ඔබේ ඉහළම {n} shots වලින්','Sweet spot සැකසීමට 85+ shot එකක් වාර්තා කරන්න.',
'පුද්ගලික හොඳම','මෙම සතියේ','කාල කවුළුව','සාම. {score}','තවම දත්ත නැත','{count} දින සක්‍රිය','CSV නිර්යාත','ගිණුම මැකීමට chef@lazysous.app වෙත email කරන්න'],

'sk': ['Uložiť','Zavrieť','Zrušiť','Poháňa','shotov celosvetovo','Domov',
'Vytiahni prvý.','Shot {n}.','Deň {n}.','Posledný shot: {score}. {tail}','Presne.','Blízko.','Jeden zásah.','Resetuj a znova.','Nastav recept. Vytiahni to dôležité.','Pokračuj. Učíme sa.',
'Deň {days} · ešte odpočíva','Deň {days} · v okne','Deň {days} · využi čoskoro','Deň {days} · prešiel',
'Odpočíva','V okne','Využi čoskoro','Prešiel',
'{temp}°C · vlhkosť {humidity}%','{temp}°C · vlhkosť {humidity}%','{temp}°C · vlhkosť {humidity}%',
'Tvoje vybavenie.','Tvoje vybavenie.','Tvoje vybavenie.','Pripravené keď ty.','Pridaj zrná na doladenie.','Nastav vybavenie.','Päť minút. Lepšie shoty potom.',
'Zostáva {count} sekcia.','Zostávajú {count} sekcie.',
'Každý shot zaznamenaný.','Vytiahni jeden. Začíname zaznamenávať.','Tvoje skóre, mletie, drift.','{count} shot. Pokračuj.','{count} shotov. Pokračuj.','{count} shotov. Priemer z 5: {avg}.',
'Jedno ťuknutie. Žiadne heslá.','Pokračovať s Meta','Pokračovať s GitHub','Len prezývka. Žiadne heslá.','Vyber prezývku.','Ako chceš. Toto je jediné čo ukladáme.','napr. billy_bean','Uložiť',
'Zníž {label} (jemne)','Zvýš {label} (jemne)','Po prvom shote','Hrubšie','3s dlhé. Mlet hrubšie.','Vytiahni. Zapíš. Povieme čo zmeniť.','Vytiahni. Zapíš. Povieme čo zmeniť nabudúce.',
'{delta} {unit} menej','{delta} {unit} viac','Nechaj','cieľ {value} {unit}','Zmeniť pre ďalší shot','Ponechať pre ďalší shot','Tento shot',
'Osobný rekord. Vychutnaj si ho.','+{delta} oproti minulému. Rastie.','−{delta} oproti minulému. Reset.','Rovnako ako minulý. Pevná ruka.','Prvý hotový. Teraz sa učíme.',
'STOP','ULOŽIŤ SHOT','Vyťahujem','Zachyť shot','Priprav sa',
'{seconds}s krátky a {ml}ml veľa. Mlet jemnejšie.','{seconds}s dlhý a {ml}ml málo. Mlet hrubšie.',
'{primary} Mlynček na najjemnejšom — zvýš dávku.','{primary} Mlynček na najhrubšom — zníž dávku.',
'3 shoty jemnejšie. Skús +0,5g.','3 shoty hrubšie. Skús −0,5g.',
'Mlynček na najjemnejšom. +0,5g pre väčší odpor.','Mlynček na najhrubšom. −0,5g pre menší odpor.',
'Tenká','Normálna','Hustá','Crema','Chuť','Intenzita','Ohodnotiť neskôr','Uložiť hodnotenie',
'Režim barista','Vypnúť režim barista','Režim barista','{count} shotov · {mins} min',
'Brewmie Premium','Brewmie naladený pre teba.','Premium',
'Pridaj mlynček — odporúčania v tvojich jednotkách.','Pružinové a auto tampery do modelu.','Ulož svoje zrná. Vymeň vrecko, pokračuj kde si bol.','Odomkni celú históriu a trendy.','Porovnaj každý shot s tvojim najlepším.',
'Tvoje vybavenie','Mlynček, tamper, zrná. Odporúčania v tvojich jednotkách.','Celá história','Každý shot uložený. Export kedykoľvek.','Osobné rekordy','Porovnaj každý shot s tvojim najlepším.',
'Len Brewmie','$6.99','Balíček s Lazy Sous','$9.99','Dev: odomykanie cez dev pill. Nie je to skutočný nákup.',
'Premium','Staršie shoty sú uložené. Celá história s Premium.','Odomkni osobné rekordy s Premium.','Generický mlynček. Premium ladí pre tvoj.','Manuálny tamp. Premium pridá pružinový a auto.','Generické stredné praženie. Premium sleduje tvoje zrná.',
'Spustiť sprievodcu znova','Sprievodca','Pokračovať →',
'Jazyk','Jazyk zobrazenia','Bežné','Ďalšie jazyky','Brewmie deteguje jazyk automaticky. Vyber tu iný. Preklady mimo bežný zoznam môžu byť neúplné a vrátia sa k angličtine.','Naposledy','Prečítaj celé zásady ochrany',
'Zobraziť všetkých {count}','Všetky shoty ({count})','Upraviť shot','Čas','Objem','Chuť','Intenzita','Vymazať','Vymazať tento shot? Nedá sa vrátiť.',
'Tvoj sweet spot','mletie','pomer','z tvojich {n} najlepších shotov','Zaznamenaj shot s 85+ pre nastavenie sweet spotu.',
'Osobný rekord','Tento týždeň','Časové okno','priem. {score}','zatiaľ bez dát','Aktívny {count} dní','Exportovať CSV','Pre vymazanie účtu napíš chef@lazysous.app'],

'sw': ['Hifadhi','Funga','Ghairi','Inaendeshwa na','shot ulimwenguni','Nyumbani',
'Toa wa kwanza.','Shot {n}.','Siku {n}.','Shot ya mwisho: {score}. {tail}','Sahihi.','Karibu.','Marekebisho moja.','Anza upya.','Weka kichocheo. Toa muhimu.','Endelea kutoa. Tunajifunza.',
'Siku {days} · bado inapumzika','Siku {days} · ndani ya dirisha','Siku {days} · tumia mapema','Siku {days} · ya zamani',
'Inapumzika','Ndani ya dirisha','Tumia mapema','Ya zamani',
'{temp}°C · unyevu {humidity}%','{temp}°C · unyevu {humidity}%','{temp}°C · unyevu {humidity}%',
'Vifaa vyako.','Vifaa vyako.','Vifaa vyako.','Tayari unapokuwa.','Ongeza maharagwe ili kurekebisha.','Weka vifaa vyako.','Dakika tano. Shot bora baadaye.',
'Sehemu {count} imebaki.','Sehemu {count} zimebaki.',
'Kila shot inarekodi.','Toa moja. Tunaanza kurekodi.','Alama yako, kusaga, kuyumba.','Shot {count}. Endelea.','Shot {count}. Endelea.','Shot {count}. Wastani wa 5: {avg}.',
'Mguso mmoja. Hakuna nenosiri.','Endelea na Meta','Endelea na GitHub','Jina la utani tu. Hakuna nenosiri.','Chagua jina la utani.','Kama unavyotaka. Hiyo tu tunahifadhi.','mfano billy_bean','Hifadhi',
'Punguza {label} (kidogo)','Ongeza {label} (kidogo)','Baada ya shot ya kwanza','Mzima','Sekunde 3 ndefu. Saga mzima.','Toa. Rekodi. Tutakuambia cha kubadilisha.','Toa. Rekodi. Tutakuambia cha kubadilisha wakati ujao.',
'{delta} {unit} pungufu','{delta} {unit} zaidi','Hifadhi','lengo {value} {unit}','Badilisha kwa shot ifuatayo','Hifadhi kwa shot ifuatayo','Shot hii',
'Rekodi binafsi. Onja polepole.','+{delta} kuliko ya nyuma. Inapanda.','−{delta} kuliko ya nyuma. Anza upya.','Sawa na ya nyuma. Mkono thabiti.','Wa kwanza umekwisha. Sasa tunajifunza.',
'SIMAMA','HIFADHI SHOT','Inatoa','Nasa shot','Kuwa tayari',
'Sekunde {seconds} fupi na {ml}ml zaidi. Saga laini.','Sekunde {seconds} ndefu na {ml}ml pungufu. Saga mzima.',
'{primary} Kisagaji kwenye laini zaidi — ongeza kipimo.','{primary} Kisagaji kwenye mzima zaidi — punguza kipimo.',
'Shot 3 laini. Jaribu +0.5g.','Shot 3 mzima. Jaribu −0.5g.',
'Kisagaji kwenye laini zaidi. +0.5g kwa upinzani zaidi.','Kisagaji kwenye mzima zaidi. −0.5g kwa upinzani mdogo.',
'Nyembamba','Kawaida','Nene','Crema','Ladha','Nguvu','Tathmini baadaye','Hifadhi tathmini',
'Hali ya barista','Zima hali ya barista','Hali ya barista','Shot {count} · dakika {mins}',
'Brewmie Premium','Brewmie iliyoboreshwa kwako.','Premium',
'Ongeza kisagaji chako — mapendekezo katika vipimo vyako.','Tamper za spring na otomatiki zinaingia kwenye modeli.','Hifadhi maharagwe yako. Badilisha mfuko, endelea ulipoachia.','Fungua historia kamili na mwenendo.','Linganisha kila shot na bora yako.',
'Vifaa vyako','Kisagaji, tamper, maharagwe. Mapendekezo katika vipimo vyako.','Historia kamili','Kila shot inahifadhiwa. Hamisha wakati wowote.','Vigezo binafsi','Linganisha kila shot na bora yako.',
'Brewmie tu','$6.99','Pakiti pamoja na Lazy Sous','$9.99','Dev: kufunguliwa kwa dev pill. Si ununuzi halisi.',
'Premium','Shot za zamani zimehifadhiwa. Historia kamili na Premium.','Fungua vigezo binafsi na Premium.','Kisagaji cha jumla. Premium hurekebisha kwako.','Tamp ya mkono. Premium huongeza spring na otomatiki.','Roast ya kati ya jumla. Premium hufuatilia maharagwe yako.',
'Endesha mwongozo wa kuweka tena','Mwongozo','Endelea →',
'Lugha','Lugha ya kuonyesha','Za kawaida','Lugha nyingine','Brewmie hutambua lugha kiotomatiki. Chagua nyingine hapa. Tafsiri nje ya za kawaida zinaweza kuwa hazijakamilika na kurudi kwa Kiingereza.','Mwisho','Soma sera kamili ya faragha',
'Tazama zote ({count})','Shot zote ({count})','Hariri shot','Wakati','Kiasi','Ladha','Nguvu','Futa','Futa shot hii? Haiwezi kutendwa upya.',
'Sehemu yako tamu','kusaga','uwiano','kutoka kwa shot {n} bora zako','Rekodi shot ya 85+ kuweka sehemu tamu.',
'Rekodi binafsi','Wiki hii','Dirisha la wakati','wastani {score}','hakuna data bado','{count} siku za kazi','Hamisha CSV','Kufuta akaunti, tuma barua pepe kwa chef@lazysous.app'],

'ta': ['சேமி','மூடு','ரத்து','இயக்குபவர்','shots உலகெங்கும்','முகப்பு',
'முதலாவதை இழு.','Shot {n}.','நாள் {n}.','கடைசி shot: {score}. {tail}','சரியாக.','அருகில்.','ஒரு சீர்படுத்தல்.','மீண்டும் தொடங்கு.','செய்முறையை அமை. முக்கியமானதை இழு.','இழுத்துக்கொண்டே இரு. நாங்கள் கற்கிறோம்.',
'நாள் {days} · இன்னும் ஓய்வு','நாள் {days} · சிறந்த சாளரத்தில்','நாள் {days} · விரைவில் பயன்படுத்து','நாள் {days} · பழையது',
'ஓய்வு','சிறந்த சாளரத்தில்','விரைவில் பயன்படுத்து','பழையது',
'{temp}°C · ஈரப்பதம் {humidity}%','{temp}°C · ஈரப்பதம் {humidity}%','{temp}°C · ஈரப்பதம் {humidity}%',
'உன் சாதனங்கள்.','உன் சாதனங்கள்.','உன் சாதனங்கள்.','நீ தயாராக இருக்கும்போது.','டயல்-இன் செய்ய பீன்ஸ் சேர்.','உன் சாதனங்களை அமை.','ஐந்து நிமிடம். பின்னர் சிறந்த shots.',
'{count} பிரிவு மீதம்.','{count} பிரிவுகள் மீதம்.',
'ஒவ்வொரு shot-ம் பதிவு.','ஒன்றை இழு. பதிவை தொடங்குகிறோம்.','உன் மதிப்பெண், அரவை, விலகல்.','{count} shot. தொடரவும்.','{count} shots. தொடரவும்.','{count} shots. 5-shot சராசரி {avg}.',
'ஒரே தொடுதல். கடவுச்சொல் இல்லை.','Meta உடன் தொடரவும்','GitHub உடன் தொடரவும்','புனைபெயர் மட்டும். கடவுச்சொல் இல்லை.','புனைபெயரை தேர்வு செய்.','உன் விருப்பம். அதை மட்டும்தான் சேமிக்கிறோம்.','எ.கா. billy_bean','சேமி',
'{label} நுட்பமாக குறை','{label} நுட்பமாக அதிகரி','உன் முதல் shot க்கு பிறகு','கரடுமுரடாக','3s நீளம். கரடுமுரடாக அரை.','இழு. பதிவு செய். எதை மாற்ற வேண்டுமென்று சொல்வோம்.','இழு. பதிவு செய். அடுத்த முறை எதை மாற்ற வேண்டுமென்று சொல்வோம்.',
'{delta} {unit} குறைவு','{delta} {unit} அதிகம்','அப்படியே வை','இலக்கு {value} {unit}','அடுத்த shot க்கு மாற்று','அடுத்த shot க்கு வை','இந்த shot',
'தனிப்பட்ட சாதனை. மெதுவாக ருசி.','முந்தைய shot-ஐ விட +{delta}. ஏறுகிறது.','முந்தைய shot-ஐ விட −{delta}. மீண்டும் தொடங்கு.','முந்தையதைப் போல. திட கை.','முதலாவது முடிந்தது. இப்போது கற்போம்.',
'நிறுத்து','SHOT-ஐ சேமி','இழுக்கிறது','Shot-ஐ பிடிக்கவும்','தயாராகவும்',
'{seconds}s குறைவு மற்றும் {ml}ml அதிகம். நுட்பமாக அரை.','{seconds}s நீளம் மற்றும் {ml}ml குறைவு. கரடுமுரடாக அரை.',
'{primary} ஆரம்பம் மிக நுட்பமான — டோஸ் அதிகரி.','{primary} ஆரம்பம் மிக கரடுமுரடான — டோஸ் குறை.',
'3 shots நுட்பமாக. +0.5g முயற்சி.','3 shots கரடுமுரடாக. −0.5g முயற்சி.',
'ஆரம்பம் மிக நுட்பமான. மேலும் எதிர்ப்பிற்கு +0.5g.','ஆரம்பம் மிக கரடுமுரடான. குறைவான எதிர்ப்பிற்கு −0.5g.',
'மெல்லிய','சாதாரண','அடர்த்தியான','Crema','சுவை','வலிமை','பின்னர் மதிப்பீடு','மதிப்பீட்டை சேமி',
'பாரிஸ்டா முறை','பாரிஸ்டா முறை அணை','பாரிஸ்டா முறை','{count} shots · {mins} நிமி',
'Brewmie Premium','உனக்காக சீரமைக்கப்பட்ட Brewmie.','Premium',
'உன் ஆரம்பத்தை சேர் — பரிந்துரைகள் உன் அலகுகளில்.','Spring மற்றும் auto tampers மாதிரியில் சேரும்.','உன் பீன்ஸ் சேமி. பை மாற்று, விட்டிட்ட இடத்திலிருந்து தொடரவும்.','முழு வரலாறு மற்றும் போக்குகளை திறக்கவும்.','ஒவ்வொரு shot-ஐயும் உன் சிறந்ததுடன் ஒப்பிடு.',
'உன் சாதனங்கள்','ஆரம்பம், tamper, பீன்ஸ். பரிந்துரைகள் உன் அலகுகளில்.','முழு வரலாறு','ஒவ்வொரு shot-ம் சேமிக்கப்படும். எப்போது வேண்டுமானாலும் ஏற்றுமதி.','தனிப்பட்ட அளவீடுகள்','ஒவ்வொரு shot-ஐயும் உன் சிறந்ததுடன் ஒப்பிடு.',
'Brewmie மட்டும்','$6.99','Lazy Sous பண்டில்','$9.99','Dev: dev pill வழியாக திறக்கப்படுகிறது. உண்மையான வாங்குதல் அல்ல.',
'Premium','பழைய shots சேமிக்கப்பட்டுள்ளன. Premium உடன் முழு வரலாறு.','Premium உடன் தனிப்பட்ட அளவீடுகளை திறக்கவும்.','பொதுவான ஆரம்பம். Premium உனக்காக சீரமைக்கிறது.','கைமுறை tamp. Premium spring மற்றும் auto சேர்க்கிறது.','பொதுவான நடுத்தர வறுத்தல். Premium உன் பீன்ஸ்-ஐ கண்காணிக்கிறது.',
'அமைப்பு உதவியாளர் மீண்டும்','அமைப்பு','தொடரவும் →',
'மொழி','காட்சி மொழி','பொதுவான','மற்ற மொழிகள்','Brewmie மொழியை தானாக கண்டறிகிறது. வேறொன்றை இங்கே தேர்வு செய். பொதுவான பட்டியலுக்கு வெளியே மொழிபெயர்ப்புகள் முழுமையற்றதாக இருக்கலாம் மற்றும் ஆங்கிலத்திற்கு திரும்பும்.','கடைசி முறை','முழு தனியுரிமை கொள்கையை படிக்கவும்',
'அனைத்தையும் காண்க ({count})','அனைத்து shots ({count})','Shot-ஐ திருத்து','நேரம்','அளவு','சுவை','வலிமை','நீக்கு','இந்த shot-ஐ நீக்கவா? மீண்டும் கொண்டு வர முடியாது.',
'உன் sweet spot','அரவை','விகிதம்','உன் சிறந்த {n} shots-ல் இருந்து','Sweet spot-ஐ அமைக்க 85+ shot பதிவு செய்.',
'தனிப்பட்ட சிறந்தது','இந்த வாரம்','நேர சாளரம்','சராசரி {score}','இன்னும் தரவு இல்லை','{count} நாட்கள் செயலில்','CSV ஏற்றுமதி','கணக்கை அழிக்க chef@lazysous.app-க்கு மின்னஞ்சல் அனுப்பு'],

'te': ['సేవ్','మూసివేయి','రద్దు','ఆధారం','shots ప్రపంచవ్యాప్తంగా','హోమ్',
'మొదటిది లాగండి.','Shot {n}.','రోజు {n}.','చివరి shot: {score}. {tail}','సరిగ్గా.','దగ్గర.','ఒక సర్దుబాటు.','మళ్లీ ప్రారంభించు.','రెసిపీ సెట్ చేయండి. ముఖ్యమైనది లాగండి.','లాగుతూ ఉండండి. మేము నేర్చుకుంటున్నాము.',
'రోజు {days} · ఇంకా విశ్రాంతి','రోజు {days} · ఉత్తమ విండోలో','రోజు {days} · త్వరగా వాడండి','రోజు {days} · పాత',
'విశ్రాంతి','ఉత్తమ విండోలో','త్వరగా వాడండి','పాత',
'{temp}°C · తేమ {humidity}%','{temp}°C · తేమ {humidity}%','{temp}°C · తేమ {humidity}%',
'మీ పరికరం.','మీ పరికరం.','మీ పరికరం.','మీరు సిద్ధంగా ఉన్నప్పుడు.','సర్దుబాటు చేయడానికి బీన్స్ జోడించండి.','మీ పరికరాన్ని సెట్ చేయండి.','ఐదు నిమిషాలు. తర్వాత మెరుగైన shots.',
'{count} విభాగం మిగిలింది.','{count} విభాగాలు మిగిలాయి.',
'ప్రతి shot రికార్డ్.','ఒకటి లాగండి. రికార్డ్ ప్రారంభిస్తాము.','మీ స్కోర్, గ్రైండింగ్, డ్రిఫ్ట్.','{count} shot. కొనసాగించండి.','{count} shots. కొనసాగించండి.','{count} shots. 5-shot సగటు {avg}.',
'ఒక తాకుడు. పాస్‌వర్డ్ లేదు.','Meta తో కొనసాగించండి','GitHub తో కొనసాగించండి','మారుపేరు మాత్రమే. పాస్‌వర్డ్ లేదు.','మారుపేరును ఎంచుకోండి.','మీ ఇష్టం. ఇది మాత్రమే సేవ్ చేస్తాము.','ఉదా. billy_bean','సేవ్',
'{label} తగ్గించండి (ఫైన్)','{label} పెంచండి (ఫైన్)','మీ మొదటి shot తర్వాత','మరింత ముతక','3s పొడవైన. ముతకగా గ్రైండ్ చేయండి.','లాగండి. లాగ్ చేయండి. ఏమి మార్చాలో చెబుతాము.','లాగండి. లాగ్ చేయండి. తరువాతిసారి ఏమి మార్చాలో చెబుతాము.',
'{delta} {unit} తక్కువ','{delta} {unit} ఎక్కువ','అలాగే ఉంచండి','లక్ష్యం {value} {unit}','తదుపరి shot కోసం మార్చండి','తదుపరి shot కోసం ఉంచండి','ఈ shot',
'వ్యక్తిగత రికార్డ్. మెల్లగా ఆస్వాదించండి.','మునుపటి కంటే +{delta}. పెరుగుతోంది.','మునుపటి కంటే −{delta}. రీసెట్.','మునుపటి వలె. స్థిరమైన చేయి.','మొదటిది అయింది. ఇప్పుడు నేర్చుకుందాం.',
'ఆపండి','SHOT సేవ్','లాగుతోంది','Shot క్యాప్చర్ చేయండి','సిద్ధంగా ఉండండి',
'{seconds}s చిన్నది మరియు {ml}ml ఎక్కువ. ఫైన్‌గా గ్రైండ్ చేయండి.','{seconds}s పొడవైన మరియు {ml}ml తక్కువ. ముతకగా గ్రైండ్ చేయండి.',
'{primary} గ్రైండర్ అత్యంత ఫైన్‌లో — డోస్ పెంచండి.','{primary} గ్రైండర్ అత్యంత ముతకలో — డోస్ తగ్గించండి.',
'3 shots ఫైన్. +0.5g ప్రయత్నించండి.','3 shots ముతక. −0.5g ప్రయత్నించండి.',
'గ్రైండర్ అత్యంత ఫైన్‌లో. ఎక్కువ రెసిస్టెన్స్ కోసం +0.5g.','గ్రైండర్ అత్యంత ముతకలో. తక్కువ రెసిస్టెన్స్ కోసం −0.5g.',
'సన్నని','సాధారణ','దట్టమైన','Crema','రుచి','బలం','తరువాత రేట్ చేయండి','రేటింగ్ సేవ్',
'బరిస్తా మోడ్','బరిస్తా మోడ్ ఆఫ్','బరిస్తా మోడ్','{count} shots · {mins} నిమిషాలు',
'Brewmie Premium','మీకు ట్యూన్ చేసిన Brewmie.','Premium',
'మీ గ్రైండర్‌ను జోడించండి — సిఫార్సులు మీ యూనిట్‌లలో.','Spring మరియు auto tampers మోడల్‌లోకి.','మీ బీన్స్‌ను సేవ్ చేయండి. బ్యాగ్ మార్చండి, వదిలిన చోటు నుండి కొనసాగండి.','పూర్తి చరిత్ర మరియు ట్రెండ్‌లను అన్‌లాక్.','ప్రతి shot ను మీ ఉత్తమమైన దానితో పోల్చండి.',
'మీ పరికరం','గ్రైండర్, tamper, బీన్స్. సిఫార్సులు మీ యూనిట్‌లలో.','పూర్తి చరిత్ర','ప్రతి shot సేవ్. ఎప్పుడైనా ఎగుమతి.','వ్యక్తిగత బెంచ్‌మార్క్‌లు','ప్రతి shot ను మీ ఉత్తమమైన దానితో పోల్చండి.',
'Brewmie మాత్రమే','$6.99','Lazy Sous బండిల్','$9.99','Dev: dev pill ద్వారా అన్‌లాక్. నిజమైన కొనుగోలు కాదు.',
'Premium','పాత shots సేవ్ చేయబడ్డాయి. Premium తో పూర్తి చరిత్ర.','Premium తో వ్యక్తిగత బెంచ్‌మార్క్‌లను అన్‌లాక్.','సాధారణ గ్రైండర్. Premium మీ కోసం క్యాలిబ్రేట్.','మాన్యువల్ tamp. Premium spring మరియు auto జోడిస్తుంది.','సాధారణ మీడియం రోస్ట్. Premium మీ బీన్స్‌ను ట్రాక్.',
'సెటప్ విజార్డ్ మళ్లీ','సెటప్','కొనసాగించండి →',
'భాష','ప్రదర్శన భాష','సాధారణం','ఇతర భాషలు','Brewmie భాషను ఆటోమేటిక్‌గా గుర్తిస్తుంది. ఇక్కడ మరొకటి ఎంచుకోండి. సాధారణం వెలుపల అనువాదాలు అసంపూర్ణంగా ఉండవచ్చు మరియు ఆంగ్లానికి తిరిగి వస్తాయి.','చివరి సారి','పూర్తి గోప్యతా విధానం చదవండి',
'అన్నీ చూడండి ({count})','అన్ని shots ({count})','Shot ను సవరించండి','సమయం','పరిమాణం','రుచి','బలం','తొలగించండి','ఈ shot ను తొలగించాలా? రద్దు చేయలేరు.',
'మీ sweet spot','గ్రైండ్','నిష్పత్తి','మీ టాప్ {n} shots నుండి','Sweet spot సెట్ చేయడానికి 85+ shot రికార్డ్.',
'వ్యక్తిగత ఉత్తమ','ఈ వారం','సమయ విండో','సగటు {score}','ఇంకా డేటా లేదు','{count} రోజులు చురుకుగా','CSV ఎగుమతి','ఖాతాను తొలగించడానికి chef@lazysous.app కు ఇమెయిల్'],

'th': ['บันทึก','ปิด','ยกเลิก','ขับเคลื่อนโดย','ช็อตทั่วโลก','หน้าหลัก',
'ดึงช็อตแรก','ช็อต {n}','วันที่ {n}','ช็อตล่าสุด: {score}. {tail}','พอดี','ใกล้แล้ว','ปรับเล็กน้อย','รีเซ็ตและเริ่มใหม่','ตั้งค่าสูตร ดึงสิ่งที่สำคัญ','ดึงต่อไป เรากำลังเรียนรู้',
'วัน {days} · ยังพักอยู่','วัน {days} · ในหน้าต่าง','วัน {days} · ใช้เร็วๆ นี้','วัน {days} · เก่าแล้ว',
'พักอยู่','ในหน้าต่าง','ใช้เร็วๆ นี้','เก่าแล้ว',
'{temp}°C · ความชื้น {humidity}%','{temp}°C · ความชื้น {humidity}%','{temp}°C · ความชื้น {humidity}%',
'อุปกรณ์ของคุณ','อุปกรณ์ของคุณ','อุปกรณ์ของคุณ','พร้อมเมื่อคุณพร้อม','เพิ่มเมล็ดเพื่อปรับ','ตั้งค่าอุปกรณ์ของคุณ','ห้านาที ช็อตดีขึ้นหลังจากนั้น',
'เหลือ {count} ส่วน','เหลือ {count} ส่วน',
'ทุกช็อตถูกบันทึก','ดึงหนึ่งช็อต เริ่มบันทึก','คะแนน บด การเบี่ยงเบนของคุณ','{count} ช็อต ต่อไป','{count} ช็อต ต่อไป','{count} ช็อต ค่าเฉลี่ย 5 ช็อต {avg}',
'แตะครั้งเดียว ไม่ต้องรหัสผ่าน','ดำเนินการต่อด้วย Meta','ดำเนินการต่อด้วย GitHub','แค่ชื่อเล่น ไม่ต้องรหัสผ่าน','เลือกชื่อเล่น','ตามใจคุณ เราเก็บแค่นี้','เช่น billy_bean','บันทึก',
'ลด {label} (ละเอียด)','เพิ่ม {label} (ละเอียด)','หลังช็อตแรก','หยาบขึ้น','ยาว 3 วินาที บดหยาบขึ้น','ดึง บันทึก จะบอกสิ่งที่ต้องเปลี่ยน','ดึง บันทึก จะบอกสิ่งที่ต้องเปลี่ยนคราวหน้า',
'{delta} {unit} น้อยไป','{delta} {unit} มากไป','คงไว้','เป้าหมาย {value} {unit}','เปลี่ยนสำหรับช็อตถัดไป','คงไว้สำหรับช็อตถัดไป','ช็อตนี้',
'สถิติส่วนตัว จิบช้าๆ','+{delta} จากครั้งก่อน กำลังขึ้น','−{delta} จากครั้งก่อน รีเซ็ต','เหมือนครั้งก่อน มือนิ่ง','ครั้งแรกเสร็จ ตอนนี้เรียนรู้',
'หยุด','บันทึกช็อต','กำลังดึง','บันทึกช็อต','เตรียมตัว',
'{seconds} วินาทีสั้น และ {ml}ml มากไป บดละเอียดขึ้น','{seconds} วินาทียาว และ {ml}ml น้อยไป บดหยาบขึ้น',
'{primary} เครื่องบดละเอียดสุด — เพิ่มโดส','{primary} เครื่องบดหยาบสุด — ลดโดส',
'3 ช็อตละเอียดขึ้น ลอง +0.5g','3 ช็อตหยาบขึ้น ลอง −0.5g',
'เครื่องบดละเอียดสุด +0.5g เพื่อต้านทานมากขึ้น','เครื่องบดหยาบสุด −0.5g เพื่อต้านทานน้อยลง',
'บาง','ปกติ','หนา','ครีมา','รสชาติ','ความเข้ม','ให้คะแนนภายหลัง','บันทึกคะแนน',
'โหมดบาริสต้า','ปิดโหมดบาริสต้า','โหมดบาริสต้า','{count} ช็อต · {mins} นาที',
'Brewmie Premium','Brewmie ปรับให้คุณ','Premium',
'เพิ่มเครื่องบด คำแนะนำในหน่วยของคุณ','Tamper สปริงและออโต้เข้าโมเดล','บันทึกเมล็ดของคุณ เปลี่ยนถุง ต่อจากที่ค้างไว้','ปลดล็อกประวัติทั้งหมดและเทรนด์','เปรียบเทียบทุกช็อตกับสถิติของคุณ',
'อุปกรณ์ของคุณ','เครื่องบด tamper เมล็ด คำแนะนำในหน่วยของคุณ','ประวัติทั้งหมด','ทุกช็อตถูกบันทึก ส่งออกเมื่อใดก็ได้','เกณฑ์ส่วนตัว','เปรียบเทียบทุกช็อตกับสถิติของคุณ',
'Brewmie เท่านั้น','$6.99','ชุดกับ Lazy Sous','$9.99','Dev: ปลดล็อกผ่าน dev pill ไม่ใช่ซื้อจริง',
'Premium','ช็อตเก่าถูกบันทึก ประวัติทั้งหมดด้วย Premium','ปลดล็อกเกณฑ์ส่วนตัวด้วย Premium','เครื่องบดทั่วไป Premium ปรับให้คุณ','Tamp แบบมือ Premium เพิ่มสปริงและออโต้','คั่วกลางทั่วไป Premium ติดตามเมล็ดของคุณ',
'รันตัวช่วยตั้งค่าใหม่','ตัวช่วยตั้งค่า','ดำเนินการต่อ →',
'ภาษา','ภาษาแสดงผล','ทั่วไป','ภาษาอื่น','Brewmie ตรวจจับภาษาอัตโนมัติ เลือกอื่นที่นี่ การแปลนอกรายการทั่วไปอาจไม่สมบูรณ์และกลับเป็นภาษาอังกฤษ','ครั้งล่าสุด','อ่านนโยบายความเป็นส่วนตัวฉบับเต็ม',
'ดูทั้งหมด ({count})','ช็อตทั้งหมด ({count})','แก้ไขช็อต','เวลา','ปริมาตร','รสชาติ','ความเข้ม','ลบ','ลบช็อตนี้? ไม่สามารถย้อนกลับได้',
'จุดที่ดีของคุณ','การบด','อัตราส่วน','จาก {n} ช็อตที่ดีที่สุด','บันทึกช็อต 85+ เพื่อตั้งจุดที่ดี',
'สถิติส่วนตัว','สัปดาห์นี้','หน้าต่างเวลา','เฉลี่ย {score}','ยังไม่มีข้อมูล','ใช้งาน {count} วัน','ส่งออก CSV','ลบบัญชี อีเมลที่ chef@lazysous.app'],

'uk': ['Зберегти','Закрити','Скасувати','Працює на','шотів у світі','Головна',
'Витягни перший.','Шот {n}.','День {n}.','Останній шот: {score}. {tail}','Влучно.','Близько.','Одне налаштування.','Скинь і знову.','Налаштуй рецепт. Витягни важливе.','Продовжуй витягувати. Ми вчимося.',
'День {days} · ще відпочиває','День {days} · у вікні','День {days} · використай скоро','День {days} · застарілий',
'Відпочиває','У вікні','Використай скоро','Застарілий',
'{temp}°C · вологість {humidity}%','{temp}°C · вологість {humidity}%','{temp}°C · вологість {humidity}%',
'Твоє обладнання.','Твоє обладнання.','Твоє обладнання.','Готово коли ти готовий.','Додай зерна для налаштування.','Налаштуй обладнання.','П\'ять хвилин. Кращі шоти після.',
'Залишилася {count} секція.','Залишилося {count} секцій.',
'Кожен шот записаний.','Витягни один. Починаємо записувати.','Твій бал, помел, дрейф.','{count} шот. Продовжуй.','{count} шотів. Продовжуй.','{count} шотів. Середнє з 5: {avg}.',
'Один дотик. Без паролів.','Продовжити з Meta','Продовжити з GitHub','Лише нікнейм. Без паролів.','Вибери нікнейм.','Як хочеш. Це єдине що зберігаємо.','напр. billy_bean','Зберегти',
'Зменш {label} (тонко)','Збільш {label} (тонко)','Після першого шота','Грубше','3с задовго. Мели грубше.','Витягни. Запиши. Скажемо що змінити.','Витягни. Запиши. Скажемо що змінити далі.',
'{delta} {unit} мало','{delta} {unit} багато','Залиш','ціль {value} {unit}','Зміни для наступного шота','Залиш для наступного шота','Цей шот',
'Особистий рекорд. Смакуй повільно.','+{delta} до попереднього. Росте.','−{delta} до попереднього. Скинь.','Як попередній. Тверда рука.','Перший зроблено. Тепер вчимося.',
'СТОП','ЗБЕРЕГТИ ШОТ','Витягується','Зафіксуй шот','Підготуйся',
'{seconds}с короткий і {ml}мл забагато. Мели тонше.','{seconds}с задовго і {ml}мл недостатньо. Мели грубше.',
'{primary} Млинок на найтоншому — підвищ дозу.','{primary} Млинок на найгрубшому — знизь дозу.',
'3 шоти тонше. Спробуй +0,5г.','3 шоти грубше. Спробуй −0,5г.',
'Млинок на найтоншому. +0,5г для більшого опору.','Млинок на найгрубшому. −0,5г для меншого опору.',
'Тонка','Звичайна','Густа','Крема','Смак','Міцність','Оцінити пізніше','Зберегти оцінку',
'Режим бариста','Вимкнути режим бариста','Режим бариста','{count} шотів · {mins} хв',
'Brewmie Premium','Brewmie налаштований під тебе.','Premium',
'Додай млинок — рекомендації в твоїх одиницях.','Пружинні та авто темпери в модель.','Збережи свої зерна. Зміни пакет, продовжуй звідки зупинився.','Розблокуй всю історію та тренди.','Порівнюй кожен шот зі своїм найкращим.',
'Твоє обладнання','Млинок, темпер, зерна. Рекомендації в твоїх одиницях.','Вся історія','Кожен шот збережено. Експортуй коли захочеш.','Особисті рекорди','Порівнюй кожен шот зі своїм найкращим.',
'Лише Brewmie','$6.99','Пакет з Lazy Sous','$9.99','Dev: розблокування через dev pill. Не справжня покупка.',
'Premium','Старіші шоти збережено. Вся історія з Premium.','Розблокуй особисті рекорди з Premium.','Загальний млинок. Premium налаштовує під твій.','Ручний темп. Premium додає пружинний та авто.','Загальна середня обсмажка. Premium стежить за твоїми зернами.',
'Перезапустити майстер','Майстер','Продовжити →',
'Мова','Мова інтерфейсу','Поширені','Інші мови','Brewmie виявляє мову автоматично. Вибери іншу тут. Переклади поза поширеним списком можуть бути неповними і повертаються до англійської.','Останній раз','Прочитати повну політику конфіденційності',
'Показати всі ({count})','Всі шоти ({count})','Редагувати шот','Час','Об\'єм','Смак','Міцність','Видалити','Видалити цей шот? Не можна скасувати.',
'Твій sweet spot','помел','співвідношення','з твоїх {n} найкращих шотів','Запиши шот з 85+ щоб задати sweet spot.',
'Особистий рекорд','Цей тиждень','Часове вікно','середнє {score}','поки немає даних','Активний {count} днів','Експорт CSV','Для видалення акаунта пиши chef@lazysous.app'],

'ur': ['محفوظ کریں','بند','منسوخ','چلتا ہے','دنیا بھر میں شاٹس','گھر',
'پہلا کھینچو۔','شاٹ {n}۔','دن {n}۔','آخری شاٹ: {score}۔ {tail}','بالکل ٹھیک۔','قریب۔','ایک ایڈجسٹمنٹ۔','ری سیٹ اور دوبارہ۔','ترکیب سیٹ کرو۔ اہم کو کھینچو۔','کھینچتے رہو۔ ہم سیکھ رہے ہیں۔',
'دن {days} · ابھی آرام میں','دن {days} · بہترین ونڈو میں','دن {days} · جلد استعمال کریں','دن {days} · پرانا',
'آرام میں','بہترین ونڈو میں','جلد استعمال','پرانا',
'{temp}°C · نمی {humidity}%','{temp}°C · نمی {humidity}%','{temp}°C · نمی {humidity}%',
'آپ کا سامان۔','آپ کا سامان۔','آپ کا سامان۔','جب آپ تیار ہوں۔','ٹیون کرنے کے لیے بینز شامل کریں۔','اپنا سامان سیٹ کریں۔','پانچ منٹ۔ بعد میں بہتر شاٹس۔',
'{count} حصہ باقی۔','{count} حصے باقی۔',
'ہر شاٹ ریکارڈ ہوتا ہے۔','ایک کھینچو۔ ہم ریکارڈنگ شروع کریں۔','آپ کا اسکور، گرائنڈ، ڈرفٹ۔','{count} شاٹ۔ جاری رکھیں۔','{count} شاٹس۔ جاری رکھیں۔','{count} شاٹس۔ 5-شاٹ اوسط {avg}۔',
'ایک ٹیپ۔ پاس ورڈ نہیں۔','Meta کے ساتھ جاری','GitHub کے ساتھ جاری','صرف عرفی نام۔ پاس ورڈ نہیں۔','عرفی نام چنیں۔','آپ کی مرضی۔ صرف یہی محفوظ ہوتا ہے۔','مثلاً billy_bean','محفوظ',
'{label} باریک کریں (نازک)','{label} بڑھائیں (نازک)','آپ کے پہلے شاٹ کے بعد','موٹا','3s لمبا۔ موٹا پیسیں۔','کھینچو۔ لاگ کریں۔ بتائیں گے کیا بدلنا ہے۔','کھینچو۔ لاگ کریں۔ اگلی بار کیا بدلنا ہے۔',
'{delta} {unit} کم','{delta} {unit} زیادہ','ویسا ہی رکھیں','ہدف {value} {unit}','اگلے شاٹ کے لیے بدلیں','اگلے شاٹ کے لیے رکھیں','یہ شاٹ',
'ذاتی ریکارڈ۔ آہستہ پیئیں۔','پچھلے سے +{delta}۔ اوپر۔','پچھلے سے −{delta}۔ ری سیٹ۔','پچھلے جیسا۔ مضبوط ہاتھ۔','پہلا ہو گیا۔ اب سیکھیں۔',
'روکیں','شاٹ محفوظ کریں','کھینچ رہا ہے','شاٹ پکڑیں','تیار ہو جائیں',
'{seconds}s چھوٹا اور {ml}ml زیادہ۔ باریک پیسیں۔','{seconds}s لمبا اور {ml}ml کم۔ موٹا پیسیں۔',
'{primary} گرائنڈر سب سے باریک — ڈوز بڑھائیں۔','{primary} گرائنڈر سب سے موٹا — ڈوز کم کریں۔',
'3 شاٹس باریک۔ +0.5g آزمائیں۔','3 شاٹس موٹا۔ −0.5g آزمائیں۔',
'گرائنڈر سب سے باریک۔ زیادہ مزاحمت کے لیے +0.5g۔','گرائنڈر سب سے موٹا۔ کم مزاحمت کے لیے −0.5g۔',
'پتلی','معمولی','گاڑھی','کریما','ذائقہ','شدت','بعد میں ریٹ کریں','ریٹنگ محفوظ',
'باریستا موڈ','باریستا موڈ بند','باریستا موڈ','{count} شاٹس · {mins} منٹ',
'Brewmie Premium','آپ کے لیے ٹیون شدہ Brewmie۔','Premium',
'اپنا گرائنڈر شامل کریں — تجاویز آپ کی یونٹس میں۔','اسپرنگ اور آٹو ٹیمپرز ماڈل میں۔','اپنی بینز محفوظ کریں۔ بیگ بدلیں، جہاں چھوڑا تھا وہاں سے۔','مکمل تاریخ اور رجحانات کھولیں۔','ہر شاٹ کا اپنے بہترین سے موازنہ کریں۔',
'آپ کا سامان','گرائنڈر، ٹیمپر، بینز۔ تجاویز آپ کی یونٹس میں۔','مکمل تاریخ','ہر شاٹ محفوظ۔ کبھی بھی برآمد کریں۔','ذاتی معیارات','ہر شاٹ کا اپنے بہترین سے موازنہ کریں۔',
'صرف Brewmie','$6.99','Lazy Sous بنڈل','$9.99','Dev: dev pill سے کھلتا ہے۔ حقیقی خریداری نہیں۔',
'Premium','پرانے شاٹس محفوظ ہیں۔ Premium کے ساتھ مکمل تاریخ۔','Premium کے ساتھ ذاتی معیارات کھولیں۔','عام گرائنڈر۔ Premium آپ کے لیے کیلیبریٹ کرتا ہے۔','دستی ٹیمپ۔ Premium اسپرنگ اور آٹو شامل کرتا ہے۔','عام میڈیم روسٹ۔ Premium آپ کی بینز ٹریک کرتا ہے۔',
'سیٹ اپ وزرڈ دوبارہ چلائیں','سیٹ اپ','جاری رکھیں →',
'زبان','ڈسپلے زبان','عام','دوسری زبانیں','Brewmie زبان خودکار طور پر پہچانتا ہے۔ یہاں دوسری چنیں۔ عام سے باہر کے ترجمے نامکمل ہو سکتے ہیں اور انگریزی پر واپس آتے ہیں۔','آخری بار','مکمل پرائیویسی پالیسی پڑھیں',
'تمام ({count}) دیکھیں','تمام شاٹس ({count})','شاٹ ایڈٹ','وقت','حجم','ذائقہ','شدت','حذف','اس شاٹ کو حذف کریں؟ واپس نہیں ہو گا۔',
'آپ کا سویٹ اسپاٹ','گرائنڈ','تناسب','آپ کے ٹاپ {n} شاٹس سے','سویٹ اسپاٹ سیٹ کرنے کے لیے 85+ شاٹ ریکارڈ۔',
'ذاتی بہترین','اس ہفتے','وقت ونڈو','اوسط {score}','ابھی ڈیٹا نہیں','{count} دن فعال','CSV برآمد','اکاؤنٹ حذف کرنے کے لیے chef@lazysous.app کو ای میل'],
}


def set_nested(d, key, value):
    parts = key.split('.')
    cur = d
    for p in parts[:-1]:
        if p not in cur or not isinstance(cur[p], dict):
            cur[p] = {}
        cur = cur[p]
    cur[parts[-1]] = value


def main():
    assert len(KEYS) == 151
    for locale, vals in LOCALES.items():
        if len(vals) != 151:
            print(f'  SKIP {locale}: {len(vals)} values, expected 151')
            continue
        path = TR / f'{locale}.json'
        existing = json.loads(path.read_text(encoding='utf-8'))
        for k, v in zip(KEYS, vals):
            set_nested(existing, k, v)
        path.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        print(f'{locale}: filled {len(vals)} keys')


if __name__ == '__main__':
    main()
