#!/usr/bin/env python3
"""Tier 2 batch B: gl, gu, ha, he, hr, hu, hy, ka, kk, km, kn, ml, mn, mr."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TR = ROOT / 'public' / 'translations'

KEYS = [
    'common.save','common.close','common.cancel','footer.poweredBy','footer.shotsGlobally','header.home',
    'hero.brewFirst','hero.shotN','hero.dayN','hero.statusLastShot','hero.statusNailed','hero.statusClose',
    'hero.statusOneTweak','hero.statusKeepGoing','hero.statusReady','hero.statusKeepPulling',
    'hero.beanResting','hero.beanDay','hero.beanUseSoon','hero.beanStale',
    'hero.beanRestingShort','hero.beanDayShort','hero.beanUseSoonShort','hero.beanStaleShort',
    'hero.weatherHumid','hero.weatherDry','hero.weatherNeutral',
    'hero.setupYourKit','hero.setupKitOnFile','hero.setupAllSetBig','hero.setupAllSet','hero.setupAddBeans',
    'hero.setupEmpty','hero.setupEmptySub','hero.setupSectionsToGo','hero.setupSectionsToGoPlural',
    'hero.insightsBig','hero.insightsEmpty','hero.insightsEmptySub','hero.insightsCount','hero.insightsCountPlural','hero.insightsAvg',
    'auth.providerSub','auth.continueMeta','auth.continueGitHub','auth.privacyNote','auth.nicknameTitle','auth.nicknameSub','auth.nicknamePlaceholder','auth.nicknameSubmit',
    'brew.decreaseFine','brew.increaseFine','brew.coachPreviewBadge','brew.coachPreviewDirection','brew.coachPreviewReason','brew.coachPreviewCaption','brew.coachLine',
    'brew.outcomeShort','brew.outcomeLong','brew.holdAtTarget','brew.targetWas','brew.sectionChange','brew.sectionHold','brew.sectionShot',
    'brew.scoreBest','brew.scoreUp','brew.scoreDown','brew.scoreSame','brew.scoreFirst',
    'brew.stop','brew.saveShot','brew.timingRunning','brew.timingStopped','brew.countdownSub',
    'brew.reasonRanFastBoth','brew.reasonRanSlowBoth','brew.reasonGrindAtMin','brew.reasonGrindAtMax',
    'brew.doseTrendUp','brew.doseTrendDown','brew.doseGrindAtMin','brew.doseGrindAtMax',
    'crema.thin','crema.normal','crema.thick','rating.crema','rating.flavour','rating.strength','rating.later','rating.save',
    'barista.toggleOn','barista.toggleOff','barista.active','barista.sessionMeta',
    'premium.eyebrow','premium.title','premium.lockBadge','premium.triggerGrinder','premium.triggerTamper','premium.triggerBeans','premium.triggerHistory','premium.triggerBenchmarks',
    'premium.feature1Head','premium.feature1Sub','premium.feature2Head','premium.feature2Sub','premium.feature3Head','premium.feature3Sub',
    'premium.ctaBrewmie','premium.priceBrewmie','premium.ctaBundle','premium.priceBundle','premium.devNote',
    'tierLock.badge','tierLock.historyMore','tierLock.benchmarksLocked','tierLock.genericGrinder','tierLock.genericTamper','tierLock.genericBeans',
    'setup.profileCtaReset','setup.bannerEyebrow','setup.bannerCta',
    'setup.cardLanguage','setup.languageLabel','setup.languageMajor','setup.languageMore','setup.languageHint','setup.maintLastDone','setup.privacyPolicyLink',
    'insights.viewAll','insights.allShotsTitle','insights.editShot','insights.editTime','insights.editVolume','insights.editTaste','insights.editStrength',
    'insights.deleteShot','insights.confirmDeleteShot','insights.sweetSpotEyebrow','insights.bestGrindLabel','insights.ratioLabel','insights.fromNShots','insights.noTopShots',
    'insights.personalBest','insights.thisWeek','insights.timeWindow','insights.avgScore','insights.noShotsYet','insights.daysActive','insights.exportCsv','insights.deleteAccountEmail',
]

LOCALES = {
'gl': ['Gardar','Pechar','Cancelar','Impulsado por','shots polo mundo','Inicio',
'Saca o primeiro.','Shot {n}.','Día {n}.','Último shot: {score}. {tail}','Cravado.','Cerca.','Un axuste.','Reinicia e outra.','Pon a receita. Saca o importante.','Sigue. Aprendemos.',
'Día {days} · aínda repousando','Día {days} · na xanela','Día {days} · úsao pronto','Día {days} · pasado',
'Repousando','Na xanela','Úsao pronto','Pasado',
'{temp}°C · {humidity}% humidade','{temp}°C · {humidity}% humidade','{temp}°C · {humidity}% humidade',
'O teu equipamento.','O teu equipamento.','O teu equipamento.','Listo cando queiras.','Engade grans para axustar.','Configura o equipamento.','Cinco minutos. Mellores shots despois.',
'Queda {count} sección.','Quedan {count} seccións.',
'Cada shot, rexistrado.','Saca un. Comezamos a rexistrar.','A túa puntuación, moaxe, deriva.','{count} shot. Continúa.','{count} shots. Continúa.','{count} shots. Media de 5: {avg}.',
'Un toque. Sen contrasinais.','Continuar con Meta','Continuar con GitHub','Só un alcume. Sen contrasinais.','Escolle un alcume.','Como queiras. É o único que gardamos.','p.ex. billy_bean','Gardar',
'Diminuír {label} (fino)','Aumentar {label} (fino)','Tras o teu primeiro shot','Máis groso','3s longo. Máis groso.','Saca. Rexistra. Dicímosche que cambiar.','Saca. Rexistra. Dicímosche que cambiar despois.',
'{delta} {unit} curto','{delta} {unit} longo','Mantén','obxectivo {value} {unit}','Cambia para o próximo shot','Mantén para o próximo shot','Este shot',
'Récord persoal. Sabórea amodo.','+{delta} sobre o anterior. Subindo.','−{delta} sobre o anterior. Reinicia.','Igual que o anterior. Man firme.','Primeiro feito. Agora aprendemos.',
'PARAR','GARDAR SHOT','Extraendo','Captura o shot','Prepárate',
'{seconds}s curto e {ml}ml de máis. Máis fino.','{seconds}s longo e {ml}ml de menos. Máis groso.',
'{primary} Muíño no mínimo — sobe a dose.','{primary} Muíño no máximo — baixa a dose.',
'3 shots máis fino. Proba +0,5g.','3 shots máis groso. Proba −0,5g.',
'Muíño no mínimo. +0,5g para máis resistencia.','Muíño no máximo. −0,5g para menos resistencia.',
'Fina','Normal','Espesa','Crema','Sabor','Intensidade','Valorar despois','Gardar valoración',
'Modo barista','Apagar modo barista','Modo barista','{count} shots · {mins} min',
'Brewmie Premium','Brewmie axustado para ti.','Premium',
'Engade o teu muíño — recomendacións nas túas unidades.','Os tampers de resorte e automáticos súmanse ao modelo.','Garda os teus grans. Cambia de bolsa, continúa.','Desbloquea o historial completo e tendencias.','Compara cada shot co teu mellor.',
'O teu equipamento','Muíño, tamper, grans. Recomendacións nas túas unidades.','Historial completo','Cada shot gardado. Exporta cando queiras.','Récords persoais','Compara cada shot co teu mellor.',
'Só Brewmie','$6.99','Paquete con Lazy Sous','$9.99','Dev: desbloqueo polo dev pill. Non é compra real.',
'Premium','Os shots antigos están gardados. Historial completo con Premium.','Desbloquea Récords persoais con Premium.','Muíño xenérico. Premium calibra para o teu.','Tamp manual. Premium engade resorte e automático.','Torrado medio xenérico. Premium segue os teus grans.',
'Reiniciar asistente','Asistente','Continuar →',
'Idioma','Idioma de pantalla','Comúns','Outros idiomas','Brewmie detecta o teu idioma. Escolle outro aquí. As traducións fóra dos comúns poden estar incompletas e volver ao inglés.','Última vez','Ler política de privacidade',
'Ver os {count}','Todos os shots ({count})','Editar shot','Tempo','Volume','Sabor','Intensidade','Eliminar','Eliminar este shot? Non se pode desfacer.',
'O teu sweet spot','moaxe','ratio','dos teus {n} mellores shots','Rexistra un shot 85+ para fixar o teu sweet spot.',
'Récord persoal','Esta semana','Xanela de tempo','media {score}','sen datos aínda','Activo {count} días','Exportar CSV','Para borrar conta: chef@lazysous.app'],

'gu': ['સાચવો','બંધ','રદ','થી સંચાલિત','શોટ વૈશ્વિક રીતે','હોમ',
'પ્રથમ કાઢો.','શોટ {n}.','દિવસ {n}.','છેલ્લો શોટ: {score}. {tail}','સંપૂર્ણ.','નજીક.','એક ફેરફાર.','રીસેટ કરી ફરી.','રેસિપી સેટ કરો. જરૂરી કાઢો.','કાઢતા રહો. અમે શીખીએ છીએ.',
'દિવસ {days} · હજુ આરામ','દિવસ {days} · શ્રેષ્ઠ વિન્ડોમાં','દિવસ {days} · જલદી વાપરો','દિવસ {days} · જૂનું',
'આરામ','શ્રેષ્ઠ વિન્ડોમાં','જલદી વાપરો','જૂનું',
'{temp}°C · {humidity}% ભેજ','{temp}°C · {humidity}% ભેજ','{temp}°C · {humidity}% ભેજ',
'તમારા સાધનો.','તમારા સાધનો.','તમારા સાધનો.','જ્યારે તૈયાર.','સેટ કરવા બીન ઉમેરો.','તમારા સાધનો સેટ કરો.','પાંચ મિનિટ. પછી વધુ સારા શોટ.',
'{count} વિભાગ બાકી.','{count} વિભાગ બાકી.',
'દરેક શોટ રેકોર્ડ.','એક કાઢો. અમે ટ્રેક કરવાનું શરૂ.','તમારો સ્કોર, ગ્રાઈન્ડ, ડ્રિફ્ટ.','{count} શોટ. ચાલુ રાખો.','{count} શોટ. ચાલુ રાખો.','{count} શોટ. 5-શોટ સરેરાશ {avg}.',
'એક ટેપ. પાસવર્ડ નહીં.','Meta સાથે ચાલુ','GitHub સાથે ચાલુ','માત્ર નિકનેમ. પાસવર્ડ નહીં.','નિકનેમ પસંદ કરો.','તમારી મરજી. એ જ સાચવીએ છીએ.','જેમ કે billy_bean','સાચવો',
'{label} ઘટાડો (બારીક)','{label} વધારો (બારીક)','પ્રથમ શોટ પછી','જાડું','3s લાંબું. જાડું પીસો.','કાઢો. લોગ કરો. શું બદલવું તે કહીશું.','કાઢો. લોગ કરો. આગળ શું બદલવું તે કહીશું.',
'{delta} {unit} ઓછું','{delta} {unit} વધારે','જેવું છે રાખો','લક્ષ્ય {value} {unit}','આગલા શોટ માટે બદલો','આગલા શોટ માટે રાખો','આ શોટ',
'વ્યક્તિગત રેકોર્ડ. ધીમે માણો.','પાછલા કરતા +{delta}. વધી રહ્યું.','પાછલા કરતા −{delta}. રીસેટ.','પાછલા જેવું. સ્થિર હાથ.','પ્રથમ થયું. હવે શીખીએ.',
'રોકો','શોટ સાચવો','કાઢી રહ્યું','શોટ કેપ્ચર','તૈયાર',
'{seconds}s ટૂંકું અને {ml}ml વધુ. બારીક પીસો.','{seconds}s લાંબું અને {ml}ml ઓછું. જાડું પીસો.',
'{primary} ગ્રાઇન્ડર સૌથી બારીક — ડોઝ વધારો.','{primary} ગ્રાઇન્ડર સૌથી જાડું — ડોઝ ઘટાડો.',
'3 શોટ બારીક. +0.5g અજમાવો.','3 શોટ જાડું. −0.5g અજમાવો.',
'ગ્રાઇન્ડર સૌથી બારીક. +0.5g વધુ પ્રતિરોધ.','ગ્રાઇન્ડર સૌથી જાડું. −0.5g ઓછો પ્રતિરોધ.',
'પાતળું','સામાન્ય','ઘટ્ટ','ક્રીમા','સ્વાદ','તીવ્રતા','પછી રેટ','રેટિંગ સાચવો',
'બરિસ્ટા મોડ','બરિસ્ટા મોડ બંધ','બરિસ્ટા મોડ','{count} શોટ · {mins} મિનિટ',
'Brewmie Premium','તમારા માટે ટ્યૂન્ડ Brewmie.','Premium',
'ગ્રાઇન્ડર ઉમેરો — સૂચનો તમારા એકમમાં.','સ્પ્રિંગ અને ઓટો ટેમ્પર મોડેલમાં.','બીન સાચવો. બેગ બદલો, જ્યાંથી છોડ્યું ત્યાંથી.','સંપૂર્ણ ઇતિહાસ અને ટ્રેન્ડ.','દરેક શોટની તુલના તમારા શ્રેષ્ઠ સાથે.',
'તમારા સાધનો','ગ્રાઇન્ડર, ટેમ્પર, બીન. સૂચનો તમારા એકમમાં.','સંપૂર્ણ ઇતિહાસ','દરેક શોટ સચવાય. ગમે ત્યારે એક્સપોર્ટ.','વ્યક્તિગત માપદંડ','દરેક શોટની તુલના તમારા શ્રેષ્ઠ સાથે.',
'માત્ર Brewmie','$6.99','Lazy Sous બંડલ','$9.99','Dev: dev pill થી અનલોક. વાસ્તવિક ખરીદી નથી.',
'Premium','જૂના શોટ સચવાય છે. Premium સાથે સંપૂર્ણ ઇતિહાસ.','Premium સાથે વ્યક્તિગત માપદંડ અનલોક.','સામાન્ય ગ્રાઇન્ડર. Premium તમારા માટે કેલિબ્રેટ.','મેન્યુઅલ ટેમ્પ. Premium સ્પ્રિંગ અને ઓટો ઉમેરે.','સામાન્ય મધ્યમ રોસ્ટ. Premium તમારા બીન ટ્રેક કરે.',
'સેટઅપ વિઝાર્ડ ફરી','સેટઅપ','ચાલુ →',
'ભાષા','ડિસ્પ્લે ભાષા','સામાન્ય','અન્ય ભાષાઓ','Brewmie ભાષા આપોઆપ શોધે. અન્ય પસંદ કરો. સામાન્ય બહારના અનુવાદ અધૂરા હોઈ શકે, અંગ્રેજીમાં પાછા.','છેલ્લે','સંપૂર્ણ ગોપનીયતા નીતિ વાંચો',
'બધા {count} જુઓ','બધા શોટ ({count})','શોટ સંપાદિત','સમય','માત્રા','સ્વાદ','તીવ્રતા','કાઢો','આ શોટ કાઢો? પાછું નહીં.',
'તમારો સ્વીટ સ્પોટ','ગ્રાઇન્ડ','રેશિયો','તમારા ટોપ {n} શોટમાંથી','સ્વીટ સ્પોટ સેટ કરવા 85+ શોટ રેકોર્ડ કરો.',
'વ્યક્તિગત શ્રેષ્ઠ','આ અઠવાડિયે','સમય વિન્ડો','સરેરાશ {score}','હજુ ડેટા નથી','{count} દિવસ સક્રિય','CSV એક્સપોર્ટ','એકાઉન્ટ કાઢવા chef@lazysous.app પર ઇમેઇલ'],

'ha': ['Ajiye','Rufe','Soke','Wanda yake samarwa','shot a duniya','Gida',
'Ja na farko.','Shot {n}.','Rana {n}.','Shot na ƙarshe: {score}. {tail}','Cikakke.','Kusa.','Daidaitawa ɗaya.','Sake farawa.','Saita girke-girke. Ja abin da yake muhimmanci.','Ci gaba da ja. Muna koyo.',
'Rana {days} · har yana hutu','Rana {days} · cikin tagar','Rana {days} · yi amfani da shi nan da nan','Rana {days} · ya wuce',
'Yana hutu','Cikin tagar','Yi amfani nan da nan','Ya wuce',
'{temp}°C · danshi {humidity}%','{temp}°C · danshi {humidity}%','{temp}°C · danshi {humidity}%',
'Kayanka.','Kayanka.','Kayanka.','A shirye duk lokacin da kake.','Ƙara wake don daidaitawa.','Saita kayanka.','Mintuna biyar. Shot mafi kyau bayan.',
'Sashe {count} ya rage.','Sassan {count} sun rage.',
'Kowane shot, an yi rikodi.','Ja ɗaya. Muna fara rikodi.','Makinka, niƙa, sauya.','Shot {count}. Ci gaba.','Shot {count}. Ci gaba.','Shot {count}. Matsakaicin 5: {avg}.',
'Taɓawa ɗaya. Babu kalmar sirri.','Ci gaba da Meta','Ci gaba da GitHub','Ƙaramin suna kawai. Babu kalmar sirri.','Zaɓi ƙaramin suna.','A gareka. Wannan kawai muke ajiyewa.','misali billy_bean','Ajiye',
'Rage {label} (mai laushi)','Ƙara {label} (mai laushi)','Bayan shot na farko','Mai kauri','3s tsayi. Niƙa mai kauri.','Ja. Rikodi. Za mu faɗa abin da za a canza.','Ja. Rikodi. Za mu faɗa abin da za a canza na gaba.',
'{delta} {unit} ƙaranci','{delta} {unit} yawa','Bar haka','manufa {value} {unit}','Canja don shot na gaba','Bar shi don shot na gaba','Wannan shot',
'Mafi kyawun kanka. Ka ji daɗinsa sannu sannu.','+{delta} bisa na ƙarshe. Yana hawa.','−{delta} bisa na ƙarshe. Sake farawa.','Daidai da na ƙarshe. Hannu mai tabbas.','Na farko ya tafi. Yanzu mu koya.',
'TSAYA','AJIYE SHOT','Yana ja','Kama shot ɗin','Ka shirya',
'{seconds}s gajere kuma {ml}ml yawa. Niƙa mai laushi.','{seconds}s tsayi kuma {ml}ml ƙaranci. Niƙa mai kauri.',
'{primary} Niƙa a mafi laushi — ƙara kashi.','{primary} Niƙa a mafi kauri — rage kashi.',
'Shot 3 mafi laushi. Gwada +0.5g.','Shot 3 mafi kauri. Gwada −0.5g.',
'Niƙa a mafi laushi. +0.5g don ƙarin juriya.','Niƙa a mafi kauri. −0.5g don ƙarancin juriya.',
'Sirara','Na yau da kullum','Mai kauri','Crema','Dandano','Ƙarfi','Kima daga baya','Ajiye kima',
'Yanayin barista','Kashe yanayin barista','Yanayin barista','Shot {count} · {mins} mintuna',
'Brewmie Premium','Brewmie da aka daidaita gareka.','Premium',
'Ƙara niƙanka — shawarwari a cikin sashinka.','Tamper na spring da auto suna shiga samfurin.','Ajiye wakenka. Canja jaka, ci gaba inda ka tsaya.','Buɗe cikakken tarihi da yanayi.','Kwatanta kowane shot da mafi kyawunka.',
'Kayanka','Niƙa, tamper, wake. Shawarwari a cikin sashinka.','Cikakken tarihi','Kowane shot an ajiye. Fitarwa kowane lokaci.','Maƙalattai na kai','Kwatanta kowane shot da mafi kyawunka.',
'Brewmie kawai','$6.99','Saka tare da Lazy Sous','$9.99','Dev: buɗewa ta dev pill. Ba ainihin saye ba.',
'Premium','Tsofaffin shots an ajiye su. Cikakken tarihi tare da Premium.','Buɗe maƙalattai na kai tare da Premium.','Niƙa na gama-gari. Premium ya daidaita zuwa naka.','Tamp na hannu. Premium yana ƙara spring da auto.','Soyayyen matsakaici na gama-gari. Premium yana bin wakenka.',
'Sake gudanar da mai jagora','Mai jagora','Ci gaba →',
'Harshe','Harshen nuni','Wadanda aka saba','Sauran harsuna','Brewmie yana gano harshe ta atomatik. Zaɓi wani a nan. Fassarori da suka wuce wadanda aka saba na iya zama marasa cikawa kuma su koma turanci.','Lokaci na ƙarshe','Karanta cikakkiyar manufar sirri',
'Duba duka ({count})','Dukan shots ({count})','Gyara shot','Lokaci','Yawan','Dandano','Ƙarfi','Sharewa','Sharar wannan shot? Ba zai komo ba.',
'Madaidaicin maki naka','niƙa','rabo','daga shot {n} mafi kyaunka','Yi rikodin shot 85+ don saita maki naka.',
'Mafi kyawun kanka','Wannan mako','Tagar lokaci','matsakaici {score}','babu bayanai tukuna','Aiki kwanaki {count}','Fitar CSV','Don share asusu, aika imel zuwa chef@lazysous.app'],

'he': ['שמור','סגור','בטל','מופעל על ידי','שוטים בעולם','בית',
'תוציא את הראשון.','שוט {n}.','יום {n}.','שוט אחרון: {score}. {tail}','בול.','קרוב.','כיוון אחד.','אפס והתחל מחדש.','קבע את המתכון. תוציא את החשוב.','המשך לחלץ. אנחנו לומדים.',
'יום {days} · עוד נח','יום {days} · בחלון','יום {days} · השתמש בקרוב','יום {days} · ישן',
'נח','בחלון','השתמש בקרוב','ישן',
'{temp}°C · לחות {humidity}%','{temp}°C · לחות {humidity}%','{temp}°C · לחות {humidity}%',
'הציוד שלך.','הציוד שלך.','הציוד שלך.','מוכן מתי שאתה.','הוסף פולים לכיול.','הגדר את הציוד שלך.','חמש דקות. שוטים טובים יותר אחרי.',
'נשאר חלק {count}.','נשארו {count} חלקים.',
'כל שוט מתועד.','תוציא אחד. מתחילים לתעד.','הציון שלך, הטחינה, הסחיפה.','{count} שוט. המשך.','{count} שוטים. המשך.','{count} שוטים. ממוצע 5: {avg}.',
'הקשה אחת. בלי סיסמאות.','המשך עם Meta','המשך עם GitHub','רק כינוי. בלי סיסמאות.','בחר כינוי.','הבחירה שלך. זה כל מה שאנחנו שומרים.','למשל billy_bean','שמור',
'הפחת {label} (עדין)','הוסף {label} (עדין)','אחרי השוט הראשון','גס יותר','3s ארוך. תטחן גס יותר.','חלץ. תעד. נגיד מה לשנות.','חלץ. תעד. נגיד מה לשנות בפעם הבאה.',
'{delta} {unit} פחות','{delta} {unit} יותר','שמור','יעד {value} {unit}','שנה לשוט הבא','שמור לשוט הבא','שוט זה',
'שיא אישי. תיהנה לאט.','+{delta} מהקודם. עולים.','−{delta} מהקודם. אפס.','כמו הקודם. יד יציבה.','הראשון מאחורינו. עכשיו לומדים.',
'עצור','שמור שוט','מחלץ','תעד את השוט','התכונן',
'{seconds}s קצר ו-{ml}ml יותר. תטחן עדין יותר.','{seconds}s ארוך ו-{ml}ml פחות. תטחן גס יותר.',
'{primary} מטחנה במצב הכי עדין — הגדל מנה.','{primary} מטחנה במצב הכי גס — הקטן מנה.',
'3 שוטים עדינים יותר. נסה +0.5g.','3 שוטים גסים יותר. נסה −0.5g.',
'מטחנה במצב הכי עדין. +0.5g להתנגדות נוספת.','מטחנה במצב הכי גס. −0.5g לפחות התנגדות.',
'דקה','רגילה','עבה','קרמה','טעם','עוצמה','דרג מאוחר יותר','שמור דירוג',
'מצב ברמן','כבה מצב ברמן','מצב ברמן','{count} שוטים · {mins} דק׳',
'Brewmie Premium','Brewmie מכוון אליך.','Premium',
'הוסף את המטחנה — המלצות ביחידות שלך.','טמפרים קפיציים ואוטומטיים נכנסים למודל.','שמור את הפולים שלך. החלף שקית, המשך משם.','פתח היסטוריה מלאה ומגמות.','השווה כל שוט לטוב ביותר שלך.',
'הציוד שלך','מטחנה, טמפר, פולים. המלצות ביחידות שלך.','היסטוריה מלאה','כל שוט נשמר. ייצא מתי שתרצה.','אמות מידה אישיות','השווה כל שוט לטוב ביותר שלך.',
'Brewmie בלבד','$6.99','חבילה עם Lazy Sous','$9.99','Dev: שחרור דרך dev pill. לא רכישה אמיתית.',
'Premium','שוטים ישנים שמורים. היסטוריה מלאה עם Premium.','פתח אמות מידה אישיות עם Premium.','מטחנה כללית. Premium מכייל לשלך.','טמפ ידני. Premium מוסיף קפיצי ואוטומטי.','קליה בינונית כללית. Premium עוקב אחרי הפולים שלך.',
'הפעל מחדש את אשף ההגדרה','אשף הגדרה','המשך →',
'שפה','שפת תצוגה','נפוצות','שפות אחרות','Brewmie מזהה את השפה אוטומטית. בחר אחרת כאן. תרגומים מחוץ לרשימת הנפוצות עשויים להיות חלקיים ויחזרו לאנגלית.','בפעם האחרונה','קרא את מדיניות הפרטיות',
'הצג את כל {count}','כל השוטים ({count})','ערוך שוט','זמן','נפח','טעם','עוצמה','מחק','למחוק את השוט הזה? לא ניתן לבטל.',
'נקודת המתיקות שלך','טחינה','יחס','מ-{n} השוטים הטובים שלך','תעד שוט 85+ כדי לקבוע את נקודת המתיקות.',
'שיא אישי','השבוע','חלון זמן','ממוצע {score}','אין עדיין נתונים','פעיל {count} ימים','ייצא CSV','למחיקת חשבון, שלח לchef@lazysous.app'],

'hr': ['Spremi','Zatvori','Otkaži','Pokreće','shotova globalno','Početna',
'Povuci prvi.','Shot {n}.','Dan {n}.','Zadnji shot: {score}. {tail}','Pogođeno.','Blizu.','Jedan tweak.','Resetiraj i opet.','Postavi recept. Povuci ono što je važno.','Nastavi povlačiti. Učimo.',
'Dan {days} · još se odmara','Dan {days} · u prozoru','Dan {days} · iskoristi uskoro','Dan {days} · zastario',
'Odmara se','U prozoru','Iskoristi uskoro','Zastario',
'{temp}°C · {humidity}% vlažnosti','{temp}°C · {humidity}% vlažnosti','{temp}°C · {humidity}% vlažnosti',
'Tvoja oprema.','Tvoja oprema.','Tvoja oprema.','Spreman kad si ti.','Dodaj zrna za podešavanje.','Postavi svoju opremu.','Pet minuta. Bolji shotovi nakon.',
'Ostala {count} sekcija.','Ostalo {count} sekcija.',
'Svaki shot, zabilježen.','Povuci jedan. Počinjemo bilježiti.','Tvoj rezultat, mljevenje, otklon.','{count} shot. Nastavi.','{count} shotova. Nastavi.','{count} shotova. Prosjek 5: {avg}.',
'Jedan dodir. Bez lozinki.','Nastavi s Meta','Nastavi s GitHub','Samo nadimak. Bez lozinki.','Odaberi nadimak.','Tvoja stvar. Jedino što čuvamo.','npr. billy_bean','Spremi',
'Smanji {label} (fino)','Povećaj {label} (fino)','Nakon prvog shota','Krupnije','3s dugo. Melji krupnije.','Povuci. Zabilježi. Reći ćemo što promijeniti.','Povuci. Zabilježi. Reći ćemo što promijeniti sljedeći put.',
'{delta} {unit} kraće','{delta} {unit} dulje','Zadrži','cilj {value} {unit}','Promijeni za sljedeći shot','Zadrži za sljedeći shot','Ovaj shot',
'Osobni rekord. Uživaj polako.','+{delta} na prethodni. Raste.','−{delta} na prethodni. Resetiraj.','Isto kao prethodni. Sigurna ruka.','Prvi gotov. Sad učimo.',
'STOP','SPREMI SHOT','Povlačenje','Zabilježi shot','Pripremi se',
'{seconds}s kratko i {ml}ml viška. Melji finije.','{seconds}s dugo i {ml}ml manjka. Melji krupnije.',
'{primary} Mlinac na najfinijem — povisi dozu.','{primary} Mlinac na najkrupnijem — smanji dozu.',
'3 shota finije. Probaj +0,5g.','3 shota krupnije. Probaj −0,5g.',
'Mlinac na najfinijem. +0,5g za veći otpor.','Mlinac na najkrupnijem. −0,5g za manji otpor.',
'Tanka','Normalna','Gusta','Crema','Okus','Jačina','Ocijeni kasnije','Spremi ocjenu',
'Barista način','Isključi barista način','Barista način','{count} shotova · {mins} min',
'Brewmie Premium','Brewmie podešen za tebe.','Premium',
'Dodaj mlinac — preporuke u tvojim jedinicama.','Pružinski i auto tamperi ulaze u model.','Spremi svoja zrna. Promijeni vrećicu, nastavi gdje si stao.','Otključaj cijelu povijest i trendove.','Usporedi svaki shot s tvojim najboljim.',
'Tvoja oprema','Mlinac, tamper, zrna. Preporuke u tvojim jedinicama.','Cijela povijest','Svaki shot spremljen. Izvoz bilo kada.','Osobni rekordi','Usporedi svaki shot s tvojim najboljim.',
'Samo Brewmie','$6.99','Paket s Lazy Sous','$9.99','Dev: otključavanje preko dev pill. Nije pravi kupnja.',
'Premium','Stariji shotovi su spremljeni. Cijela povijest s Premium.','Otključaj osobne rekorde s Premium.','Generički mlinac. Premium kalibrira za tvoj.','Ručno tampanje. Premium dodaje pružinski i auto.','Generička srednja prženost. Premium prati tvoja zrna.',
'Ponovo pokreni čarobnjak','Čarobnjak','Nastavi →',
'Jezik','Jezik prikaza','Uobičajeni','Drugi jezici','Brewmie automatski otkriva jezik. Odaberi drugi ovdje. Prijevodi izvan uobičajenih mogu biti nepotpuni i vraćaju se na engleski.','Zadnji put','Pročitaj cjelovita pravila privatnosti',
'Prikaži svih {count}','Svi shotovi ({count})','Uredi shot','Vrijeme','Volumen','Okus','Jačina','Obriši','Obrisati ovaj shot? Ne može se vratiti.',
'Tvoj sweet spot','mljevenje','omjer','iz tvojih {n} najboljih shotova','Zabilježi shot s 85+ za postavljanje sweet spota.',
'Osobni rekord','Ovaj tjedan','Vremenski prozor','prosjek {score}','još bez podataka','Aktivan {count} dana','Izvoz CSV','Za brisanje računa piši chef@lazysous.app'],

'hu': ['Mentés','Bezárás','Mégse','Üzemelteti','shot világszerte','Kezdőlap',
'Húzd az elsőt.','Shot {n}.','Nap {n}.','Utolsó shot: {score}. {tail}','Telibe.','Közel.','Egy igazítás.','Reset és újra.','Állítsd be a receptet. Húzd a lényeget.','Folytasd. Tanulunk.',
'{days}. nap · még pihen','{days}. nap · az ablakban','{days}. nap · használd hamar','{days}. nap · elavult',
'Pihen','Az ablakban','Használd hamar','Elavult',
'{temp}°C · {humidity}% páratartalom','{temp}°C · {humidity}% páratartalom','{temp}°C · {humidity}% páratartalom',
'A felszerelésed.','A felszerelésed.','A felszerelésed.','Kész mikor te.','Adj hozzá babot a beállításhoz.','Állítsd be a felszerelést.','Öt perc. Utána jobb shotok.',
'{count} szakasz hátra.','{count} szakasz hátra.',
'Minden shot rögzítve.','Húzz egyet. Elkezdjük rögzíteni.','Pontszámod, őrlésed, sodródásod.','{count} shot. Folytasd.','{count} shot. Folytasd.','{count} shot. 5-shot átlag {avg}.',
'Egy érintés. Nincs jelszó.','Folytatás Metával','Folytatás GitHubbal','Csak becenév. Nincs jelszó.','Válassz becenevet.','Rajtad áll. Csak ezt mentjük el.','pl. billy_bean','Mentés',
'{label} csökkentése (finom)','{label} növelése (finom)','Az első shot után','Durvább','3s hosszú. Őröld durvábbra.','Húzd. Naplózd. Megmondjuk mit változtass.','Húzd. Naplózd. Megmondjuk mit változtass legközelebb.',
'{delta} {unit} kevés','{delta} {unit} sok','Tartsd','cél {value} {unit}','Változtasd a következő shothoz','Tartsd a következő shothoz','Ez a shot',
'Személyes csúcs. Élvezd lassan.','+{delta} az előzőhöz. Emelkedik.','−{delta} az előzőhöz. Reset.','Ugyanannyi mint előző. Biztos kéz.','Első megvolt. Most tanulunk.',
'STOP','SHOT MENTÉSE','Húzás','Rögzítsd a shotot','Készülj',
'{seconds}s rövid és {ml}ml sok. Őröld finomabbra.','{seconds}s hosszú és {ml}ml kevés. Őröld durvábbra.',
'{primary} Daráló a legfinomabban — emeld a dózist.','{primary} Daráló a legdurvábban — csökkentsd a dózist.',
'3 shot finomabb. Próbáld +0,5g.','3 shot durvább. Próbáld −0,5g.',
'Daráló a legfinomabban. +0,5g több ellenállásért.','Daráló a legdurvábban. −0,5g kevesebb ellenállásért.',
'Vékony','Normál','Vastag','Crema','Íz','Erősség','Értékelés később','Értékelés mentése',
'Barista mód','Barista mód ki','Barista mód','{count} shot · {mins} perc',
'Brewmie Premium','Brewmie hangolva rád.','Premium',
'Add hozzá a darálót — javaslatok a te egységeidben.','Rugós és automata tamperek a modellbe.','Mentsd a babokat. Csomag váltás, folytatás onnan.','Nyisd ki a teljes történetet és trendeket.','Hasonlítsd minden shotot a saját legjobbadhoz.',
'A felszerelésed','Daráló, tamper, bab. Javaslatok a te egységeidben.','Teljes történet','Minden shot mentve. Exportálj bármikor.','Személyes mérföldkövek','Hasonlítsd minden shotot a saját legjobbadhoz.',
'Csak Brewmie','$6.99','Csomag a Lazy Sous-szal','$9.99','Dev: dev pillel nyitható. Nem valós vásárlás.',
'Premium','Régebbi shotok mentve. Teljes történet Premiummal.','Nyisd ki a személyes mérföldköveket Premiummal.','Általános daráló. A Premium a tiédhez kalibrál.','Kézi tamp. A Premium hozzáadja a rugóst és automatát.','Általános közepes pörkölés. A Premium követi a babjaidat.',
'Telepítő varázsló újrafuttatása','Telepítő','Tovább →',
'Nyelv','Megjelenítési nyelv','Gyakori','Más nyelvek','A Brewmie automatikusan érzékeli a nyelvet. Itt válassz másikat. A gyakorin kívüli fordítások hiányosak lehetnek és angolra esnek vissza.','Utoljára','Olvasd el a teljes adatvédelmi nyilatkozatot',
'Mind ({count})','Összes shot ({count})','Shot szerkesztése','Idő','Térfogat','Íz','Erősség','Törlés','Törölni ezt a shotot? Nem visszavonható.',
'A sweet spotod','őrlés','arány','a legjobb {n} shotodból','85+ shotot naplózz a sweet spot beállításához.',
'Személyes csúcs','Ezen a héten','Időablak','átl. {score}','még nincs adat','Aktív {count} napja','CSV export','Fiók törléséhez írj a chef@lazysous.app-ra'],

'hy': ['Պահպանել','Փակել','Չեղարկել','Աշխատում է','շոթ ողջ աշխարհում','Գլխավոր',
'Քաշիր առաջինը։','Շոթ {n}։','Օր {n}։','Վերջին շոթ՝ {score}։ {tail}','Կատարյալ։','Մոտ։','Մեկ կարգավորում։','Վերամեկնարկ։','Կարգավորիր բաղադրատոմսը։ Քաշիր կարևորը։','Շարունակիր քաշել։ Մենք սովորում ենք։',
'Օր {days} · դեռ հանգստանում է','Օր {days} · պատուհանում','Օր {days} · օգտագործիր շուտով','Օր {days} · հնացած',
'Հանգստանում է','Պատուհանում','Օգտագործիր շուտով','Հնացած',
'{temp}°C · խոնավություն {humidity}%','{temp}°C · խոնավություն {humidity}%','{temp}°C · խոնավություն {humidity}%',
'Քո սարքավորումը։','Քո սարքավորումը։','Քո սարքավորումը։','Պատրաստ երբ դու։','Ավելացրու հատիկներ կարգավորման համար։','Կարգավորիր սարքավորումդ։','Հինգ րոպե։ Հետո ավելի լավ շոթեր։',
'{count} բաժին մնաց։','{count} բաժին մնաց։',
'Յուրաքանչյուր շոթ՝ արձանագրված։','Քաշիր մեկը։ Սկսում ենք արձանագրել։','Քո միավորը, աղալը, շեղումը։','{count} շոթ։ Շարունակիր։','{count} շոթ։ Շարունակիր։','{count} շոթ։ 5-ի միջին {avg}։',
'Մեկ հպում։ Առանց գաղտնաբառերի։','Շարունակել Meta-ով','Շարունակել GitHub-ով','Միայն մականուն։ Առանց գաղտնաբառերի։','Ընտրիր մականուն։','Քո ընտրությունն է։ Միակ բանն է, որ պահում ենք։','օր. billy_bean','Պահպանել',
'Նվազեցրու {label}-ը (նուրբ)','Ավելացրու {label}-ը (նուրբ)','Քո առաջին շոթից հետո','Ավելի կոպիտ','3s երկար։ Աղա ավելի կոպիտ։','Քաշիր։ Արձանագրիր։ Կասենք ինչ փոխել։','Քաշիր։ Արձանագրիր։ Կասենք ինչ փոխել հաջորդ անգամ։',
'{delta} {unit} պակաս','{delta} {unit} ավել','Պահպանիր','նպատակ {value} {unit}','Փոխիր հաջորդ շոթի համար','Պահպանիր հաջորդ շոթի համար','Այս շոթը',
'Անձնական ռեկորդ։ Վայելիր կամաց։','+{delta} նախորդից։ Բարձրանում է։','−{delta} նախորդից։ Վերամեկնարկ։','Նույնն ինչ նախորդը։ Հաստատուն ձեռք։','Առաջինը պատրաստ է։ Հիմա սովորում ենք։',
'ԿԱՆԳՆԵՑՆԵԼ','ՊԱՀՊԱՆԵԼ ՇՈԹԸ','Քաշում է','Գրավիր շոթը','Պատրաստվիր',
'{seconds}s կարճ և {ml}ml ավել։ Աղա ավելի նուրբ։','{seconds}s երկար և {ml}ml պակաս։ Աղա ավելի կոպիտ։',
'{primary} Աղացը նուրբին — ավելացրու դոզան։','{primary} Աղացը կոպիտին — նվազեցրու դոզան։',
'3 շոթ ավելի նուրբ։ Փորձիր +0.5գ։','3 շոթ ավելի կոպիտ։ Փորձիր −0.5գ։',
'Աղացը նուրբին։ +0.5գ ավելի դիմադրության համար։','Աղացը կոպիտին։ −0.5գ պակաս դիմադրության համար։',
'Բարակ','Սովորական','Թանձր','Կրեմա','Համ','Ուժ','Գնահատել ավելի ուշ','Պահպանել գնահատականը',
'Բարիստա ռեժիմ','Անջատել բարիստա ռեժիմը','Բարիստա ռեժիմ','{count} շոթ · {mins} րոպե',
'Brewmie Premium','Brewmie կարգավորված քեզ համար։','Premium',
'Ավելացրու քո աղացը — առաջարկները քո միավորներով։','Զսպանակային և ավտո թամպերները մտնում են մոդելի մեջ։','Պահպանիր հատիկներդ։ Փոխիր փաթեթը, շարունակիր այնտեղից։','Բացիր ամբողջ պատմությունը և միտումները։','Համեմատիր յուրաքանչյուր շոթ քո լավագույնի հետ։',
'Քո սարքավորումը','Աղաց, թամպեր, հատիկներ։ Առաջարկներ քո միավորներով։','Ամբողջ պատմություն','Յուրաքանչյուր շոթ պահպանված։ Արտահանիր ցանկացած ժամանակ։','Անձնական չափանիշներ','Համեմատիր յուրաքանչյուր շոթ քո լավագույնի հետ։',
'Միայն Brewmie','$6.99','Փաթեթ Lazy Sous-ի հետ','$9.99','Dev՝ բացվում է dev pill-ով։ Իրական գնում չէ։',
'Premium','Հին շոթերը պահպանված են։ Ամբողջ պատմություն Premium-ի հետ։','Բացիր անձնական չափանիշները Premium-ով։','Ընդհանուր աղաց։ Premium-ը կարգավորում է քո աղացին։','Ձեռքով թամպ։ Premium-ը ավելացնում է զսպանակային և ավտո։','Ընդհանուր միջին թխած։ Premium-ը հետևում է հատիկներիդ։',
'Վերագործարկել կարգավորման հրաշագործը','Հրաշագործ','Շարունակել →',
'Լեզու','Ցուցադրման լեզու','Տարածված','Այլ լեզուներ','Brewmie-ն ինքնաբերաբար հայտնաբերում է լեզուն։ Ընտրիր այստեղ։ Տարածվածներից դուրս թարգմանությունները կարող են անկատար լինել և վերադառնալ անգլերենին։','Վերջին անգամ','Կարդա ամբողջ գաղտնիության քաղաքականությունը',
'Տես բոլորը ({count})','Բոլոր շոթերը ({count})','Խմբագրել շոթը','Ժամանակ','Ծավալ','Համ','Ուժ','Ջնջել','Ջնջե՞լ այս շոթը։ Հնարավոր չէ վերականգնել։',
'Քո քաղցր կետը','աղալ','հարաբերակցություն','քո {n} լավագույն շոթերից','Արձանագրիր 85+ շոթ՝ քաղցր կետը սահմանելու համար։',
'Անձնական ռեկորդ','Այս շաբաթ','Ժամանակի պատուհան','միջին {score}','դեռ տվյալներ չկան','Ակտիվ {count} օր','Արտահանել CSV','Հաշիվը ջնջելու համար գրեք chef@lazysous.app'],

'ka': ['შენახვა','დახურვა','გაუქმება','იკვებება','შოტი მსოფლიოში','მთავარი',
'გამოწურე პირველი.','შოტი {n}.','დღე {n}.','ბოლო შოტი: {score}. {tail}','ზუსტი.','ახლოს.','ერთი მცირე ცვლილება.','დაარესეტე და თავიდან.','დააყენე რეცეპტი. გამოწურე მთავარი.','გააგრძელე გამოწურვა. ვსწავლობთ.',
'დღე {days} · ჯერ ისვენებს','დღე {days} · სარკმელში','დღე {days} · მალე გამოიყენე','დღე {days} · გადავადებული',
'ისვენებს','სარკმელში','მალე გამოიყენე','გადავადებული',
'{temp}°C · ტენიანობა {humidity}%','{temp}°C · ტენიანობა {humidity}%','{temp}°C · ტენიანობა {humidity}%',
'შენი აღჭურვილობა.','შენი აღჭურვილობა.','შენი აღჭურვილობა.','მზად ნებისმიერ დროს.','დაამატე მარცვლები კალიბრაციისთვის.','დააყენე აღჭურვილობა.','ხუთი წუთი. შემდეგ უკეთესი შოტები.',
'{count} განყოფილება დარჩა.','{count} განყოფილება დარჩა.',
'ყველა შოტი ჩაწერილია.','გამოწურე ერთი. ვიწყებთ ჩაწერას.','შენი ქულა, დაფქვა, გადახრა.','{count} შოტი. გააგრძელე.','{count} შოტი. გააგრძელე.','{count} შოტი. 5-ის საშუალო {avg}.',
'ერთი შეხება. პაროლების გარეშე.','გააგრძელე Meta-ით','გააგრძელე GitHub-ით','მხოლოდ მეტსახელი. პაროლების გარეშე.','აირჩიე მეტსახელი.','შენი არჩევანი. ერთადერთი, რასაც ვინახავთ.','მაგ. billy_bean','შენახვა',
'შეამცირე {label} (ნაზად)','გაზარდე {label} (ნაზად)','შენი პირველი შოტის შემდეგ','უფრო უხეში','3წ გრძელი. დაფქვი უფრო უხეშად.','გამოწურე. ჩაწერე. გეტყვით რა შეცვალო.','გამოწურე. ჩაწერე. გეტყვით რა შეცვალო შემდეგ ჯერზე.',
'{delta} {unit} ნაკლები','{delta} {unit} მეტი','დატოვე','სამიზნე {value} {unit}','შეცვალე შემდეგი შოტისთვის','დატოვე შემდეგი შოტისთვის','ეს შოტი',
'პერსონალური რეკორდი. დატკბი ნელა.','+{delta} წინაზე. იზრდება.','−{delta} წინაზე. დაარესეტე.','იგივე რაც წინა. მტკიცე ხელი.','პირველი მზად. ახლა ვსწავლობთ.',
'შეჩერება','შოტის შენახვა','გამოწურვა','დააფიქსირე შოტი','მოემზადე',
'{seconds}წ მოკლე და {ml}მლ მეტი. დაფქვი უფრო წვრილად.','{seconds}წ გრძელი და {ml}მლ ნაკლები. დაფქვი უფრო უხეშად.',
'{primary} საფქვავი წვრილზე — გაზარდე დოზა.','{primary} საფქვავი უხეშზე — შეამცირე დოზა.',
'3 შოტი უფრო წვრილად. სცადე +0.5გ.','3 შოტი უფრო უხეშად. სცადე −0.5გ.',
'საფქვავი წვრილზე. +0.5გ მეტი წინააღმდეგობისთვის.','საფქვავი უხეშზე. −0.5გ ნაკლები წინააღმდეგობისთვის.',
'თხელი','ნორმალური','სქელი','კრემა','გემო','სიძლიერე','შეფასე მოგვიანებით','შეფასების შენახვა',
'ბარისტას რეჟიმი','ბარისტას რეჟიმის გამორთვა','ბარისტას რეჟიმი','{count} შოტი · {mins} წთ',
'Brewmie Premium','Brewmie შენთვის მორგებული.','Premium',
'დაამატე საფქვავი — რეკომენდაციები შენს ერთეულებში.','ზამბარიანი და ავტო ტამპერები შედის მოდელში.','შეინახე მარცვლები. ცვალე ტომარა, გააგრძელე იქედან.','გახსენი სრული ისტორია და ტენდენციები.','შეადარე ყველა შოტი შენს საუკეთესოს.',
'შენი აღჭურვილობა','საფქვავი, ტამპერი, მარცვლები. რეკომენდაციები შენს ერთეულებში.','სრული ისტორია','ყველა შოტი შენახული. ექსპორტი ნებისმიერ დროს.','პერსონალური ეტალონები','შეადარე ყველა შოტი შენს საუკეთესოს.',
'მხოლოდ Brewmie','$6.99','კომპლექტი Lazy Sous-თან','$9.99','Dev: გახსნა dev pill-ით. ნამდვილი შესყიდვა არ არის.',
'Premium','ძველი შოტები შენახულია. სრული ისტორია Premium-ით.','გახსენი პერსონალური ეტალონები Premium-ით.','ზოგადი საფქვავი. Premium აკალიბრებს შენთვის.','ხელით ტამპი. Premium ამატებს ზამბარიანს და ავტოს.','ზოგადი საშუალო შემწვარი. Premium თვალყურს ადევნებს მარცვლებს.',
'დაყენების ოსტატის თავიდან გაშვება','ოსტატი','გააგრძელე →',
'ენა','ჩვენების ენა','გავრცელებული','სხვა ენები','Brewmie ენას ავტომატურად ამოიცნობს. აქ აირჩიე სხვა. გავრცელებულის გარეთ თარგმანი შეიძლება არასრული იყოს და ინგლისურს დაუბრუნდეს.','ბოლოს გაკეთებული','წაიკითხე კონფიდენციალურობის სრული პოლიტიკა',
'ნახე ყველა ({count})','ყველა შოტი ({count})','შოტის რედაქტირება','დრო','მოცულობა','გემო','სიძლიერე','წაშლა','წავშალოთ ეს შოტი? დაბრუნება შეუძლებელია.',
'შენი sweet spot','დაფქვა','კოეფიციენტი','შენი ტოპ {n} შოტიდან','აქცი 85+ შოტი sweet spot-ის დასაყენებლად.',
'პერსონალური რეკორდი','ამ კვირაში','დროის ფანჯარა','საშ. {score}','მონაცემები ჯერ არ არის','აქტიური {count} დღე','CSV ექსპორტი','ანგარიშის წასაშლელად მისწერე chef@lazysous.app'],

'kk': ['Сақтау','Жабу','Бас тарту','Қозғаушы','шот әлем бойынша','Басты бет',
'Бірінші тарт.','Шот {n}.','{n}-ші күн.','Соңғы шот: {score}. {tail}','Дәл.','Жақын.','Бір жонеу.','Қайтадан баста.','Рецептті орнат. Маңыздыны тарт.','Тартуды жалғастыр. Үйренеміз.',
'{days}-ші күн · әлі дем алуда','{days}-ші күн · терезеде','{days}-ші күн · тез пайдалан','{days}-ші күн · ескірген',
'Дем алуда','Терезеде','Тез пайдалан','Ескірген',
'{temp}°C · ылғал {humidity}%','{temp}°C · ылғал {humidity}%','{temp}°C · ылғал {humidity}%',
'Сенің жабдығың.','Сенің жабдығың.','Сенің жабдығың.','Дайын болған кезде.','Реттеу үшін дән қос.','Жабдықты орнат.','Бес минут. Кейін жақсы шот.',
'{count} бөлім қалды.','{count} бөлім қалды.',
'Әр шот жазылады.','Біреуін тарт. Жазуды бастаймыз.','Сенің ұпайың, тартуың, ауытқуың.','{count} шот. Жалғастыр.','{count} шот. Жалғастыр.','{count} шот. 5-тің ортасы {avg}.',
'Бір түрту. Құпиясөз жоқ.','Meta-мен жалғастыру','GitHub-пен жалғастыру','Тек лақап ат. Құпиясөз жоқ.','Лақап ат таңда.','Қалауыңша. Тек осыны сақтаймыз.','мысалы billy_bean','Сақтау',
'{label}-ні нәзік азайт','{label}-ні нәзік арттыр','Бірінші шоттан кейін','Дөрекілеу','3с ұзын. Дөрекілеу тарт.','Тарт. Жаз. Не өзгертуді айтамыз.','Тарт. Жаз. Келесі жолы не өзгертуді айтамыз.',
'{delta} {unit} аз','{delta} {unit} көп','Сол күйде','мақсат {value} {unit}','Келесі шот үшін өзгерт','Келесі шот үшін сақта','Бұл шот',
'Жеке рекорд. Жайлап ішіп шық.','Алдыңғыдан +{delta}. Көтерілуде.','Алдыңғыдан −{delta}. Қайтадан баста.','Алдыңғыдай. Берік қол.','Біріншісі бітті. Енді үйренеміз.',
'ТОҚТАТ','ШОТТЫ САҚТА','Тартуда','Шотты түсір','Дайын бол',
'{seconds}с қысқа және {ml}мл артық. Жіңішкерек тарт.','{seconds}с ұзын және {ml}мл аз. Дөрекілеу тарт.',
'{primary} Тартқыш ең жіңішкеде — мөлшерді арттыр.','{primary} Тартқыш ең дөрекіде — мөлшерді азайт.',
'3 шот жіңішкерек болды. +0,5г сынап көр.','3 шот дөрекілеу болды. −0,5г сынап көр.',
'Тартқыш ең жіңішкеде. +0,5г көбірек қарсылық үшін.','Тартқыш ең дөрекіде. −0,5г аздау қарсылық үшін.',
'Жұқа','Қалыпты','Қою','Крема','Дәм','Қаттылық','Кейінірек бағала','Бағалауды сақта',
'Бариста режимі','Бариста режимін өшір','Бариста режимі','{count} шот · {mins} мин',
'Brewmie Premium','Brewmie саған бапталған.','Premium',
'Тартқышты қос — ұсыныстар сенің бірліктеріңде.','Серіппелі және авто тампер модельге кіреді.','Дәндеріңді сақта. Қапты ауыстыр, қалдырған жерден жалғастыр.','Толық тарихты және үрдістерді аш.','Әр шотты өзіңнің үздіктіңмен салыстыр.',
'Сенің жабдығың','Тартқыш, тампер, дәндер. Ұсыныстар сенің бірліктеріңде.','Толық тарих','Әр шот сақталады. Қалаған кезде экспорттай аласың.','Жеке көрсеткіштер','Әр шотты өзіңнің үздіктіңмен салыстыр.',
'Тек Brewmie','$6.99','Lazy Sous-пен пакет','$9.99','Dev: dev pill арқылы ашылады. Шын сатып алу емес.',
'Premium','Ескі шоттар сақталған. Толық тарих Premium-мен.','Premium-мен жеке көрсеткіштерді аш.','Жалпы тартқыш. Premium сенікіне бапталады.','Қолмен тампинг. Premium серіппелі және авто қосады.','Жалпы орташа қуыру. Premium дәндеріңді бақылайды.',
'Орнату шеберін қайта іске қос','Шебер','Жалғастыру →',
'Тіл','Көрсету тілі','Жиі','Басқа тілдер','Brewmie тілді автоматты табады. Басқасын осы жерден таңда. Жиіден тыс аудармалар толық болмауы мүмкін, ағылшынға қайтады.','Соңғы рет','Толық құпиялылық саясатын оқы',
'Барлық {count} көрсету','Барлық шоттар ({count})','Шотты өңде','Уақыт','Көлем','Дәм','Қаттылық','Жою','Бұл шотты жою? Қайтару мүмкін емес.',
'Сенің ең үздік нүктең','тарту','қатынас','{n} ең үздік шоттан','Ең үздік нүктені орнату үшін 85+ шот жаз.',
'Жеке рекорд','Осы аптада','Уақыт терезесі','орт. {score}','деректер әлі жоқ','{count} күн белсенді','CSV экспорт','Аккаунтты жою үшін chef@lazysous.app'],

'km': ['រក្សាទុក','បិទ','បោះបង់','ដំណើរការដោយ','shot ទូទាំងពិភពលោក','ដើម',
'ដក​ដំបូង។','Shot {n}។','ថ្ងៃ {n}។','Shot ចុងក្រោយ៖ {score}។ {tail}','គឺ​ហ្នឹង។','ជិត។','កែតម្រូវ​មួយ។','កំណត់​ឡើងវិញ។','កំណត់​រូបមន្ត។ ដក​អ្វី​សំខាន់។','បន្ត​ដក។ យើង​កំពុង​រៀន។',
'ថ្ងៃ {days} · នៅ​សម្រាក','ថ្ងៃ {days} · ក្នុង​បង្អួច','ថ្ងៃ {days} · ប្រើ​ឆាប់ៗ','ថ្ងៃ {days} · ហួស​ហើយ',
'សម្រាក','ក្នុង​បង្អួច','ប្រើ​ឆាប់ៗ','ហួស',
'{temp}°C · សំណើម {humidity}%','{temp}°C · សំណើម {humidity}%','{temp}°C · សំណើម {humidity}%',
'បរិក្ខារ​អ្នក។','បរិក្ខារ​អ្នក។','បរិក្ខារ​អ្នក។','រួចរាល់​ពេល​អ្នក​ត្រៀម។','បន្ថែម​គ្រាប់​ដើម្បី​កែ។','កំណត់​បរិក្ខារ​អ្នក។','៥ នាទី។ Shot ប្រសើរ​បន្ទាប់។',
'នៅ​សល់​ {count} ផ្នែក។','នៅ​សល់ {count} ផ្នែក។',
'រាល់ shot ត្រូវ​បាន​កត់ត្រា។','ដក​មួយ។ ចាប់ផ្តើម​កត់ត្រា។','ពិន្ទុ ការ​កិន ការ​បំលាស់ប្ដូរ​អ្នក។','{count} shot។ បន្ត។','{count} shot។ បន្ត។','{count} shot។ មធ្យម​៥៖ {avg}។',
'មួយ​ដង។ គ្មាន​ពាក្យ​សម្ងាត់។','បន្ត​ជាមួយ Meta','បន្ត​ជាមួយ GitHub','ឈ្មោះ​ហៅក្រៅ​តែ។ គ្មាន​ពាក្យ​សម្ងាត់។','ជ្រើស​ឈ្មោះ​ហៅក្រៅ។','តាម​អ្នក។ យើង​រក្សា​តែ​នេះ។','ឧ. billy_bean','រក្សាទុក',
'បន្ថយ {label} (ល្អិត)','បន្ថែម {label} (ល្អិត)','បន្ទាប់​ពី shot ដំបូង','គ្រាប់​ធំ','3s យូរ។ កិន​គ្រាប់​ធំ។','ដក។ កត់ត្រា។ យើង​នឹង​ប្រាប់​អ្វី​ត្រូវ​ផ្លាស់ប្ដូរ។','ដក។ កត់ត្រា។ យើង​នឹង​ប្រាប់​អ្វី​ត្រូវ​ផ្លាស់ប្ដូរ​លើក​ក្រោយ។',
'{delta} {unit} ខ្វះ','{delta} {unit} លើស','រក្សា','គោលដៅ {value} {unit}','ផ្លាស់ប្ដូរ​សម្រាប់ shot បន្ទាប់','រក្សា​សម្រាប់ shot បន្ទាប់','Shot នេះ',
'កំណត់ត្រា​ផ្ទាល់ខ្លួន។ ភ្លក់​យឺតៗ។','+{delta} ពី​មុន។ កំពុង​កើនឡើង។','−{delta} ពី​មុន។ កំណត់​ឡើងវិញ។','ដូច​មុន។ ដៃ​មាំ។','ដំបូង​រួច​ហើយ។ ឥឡូវ​យើង​រៀន។',
'បញ្ឈប់','រក្សា Shot','កំពុង​ដក','កត់ត្រា Shot','ត្រៀម​ខ្លួន',
'{seconds}s ខ្លី និង {ml}ml លើស។ កិន​ល្អិត។','{seconds}s យូរ និង {ml}ml ខ្វះ។ កិន​គ្រាប់​ធំ។',
'{primary} ម៉ាស៊ីន​កិន​នៅ​ល្អិត​បំផុត — បន្ថែម​បរិមាណ។','{primary} ម៉ាស៊ីន​កិន​នៅ​គ្រាប់​ធំ​បំផុត — បន្ថយ​បរិមាណ។',
'៣ shot ល្អិត​ជាង។ សាកល្បង +0.5g។','៣ shot គ្រាប់​ធំ​ជាង។ សាកល្បង −0.5g។',
'ម៉ាស៊ីន​កិន​នៅ​ល្អិត​បំផុត។ +0.5g សម្រាប់​ការ​ទប់​ច្រើន។','ម៉ាស៊ីន​កិន​នៅ​គ្រាប់​ធំ​បំផុត។ −0.5g សម្រាប់​ការ​ទប់​តិច។',
'ស្ដើង','ធម្មតា','ក្រាស់','Crema','រសជាតិ','កម្លាំង','វាយ​តម្លៃ​ពេល​ក្រោយ','រក្សា​ការ​វាយ​តម្លៃ',
'របៀប Barista','បិទ​របៀប Barista','របៀប Barista','{count} shot · {mins} នាទី',
'Brewmie Premium','Brewmie ត្រូវ​បាន​លៃ​សម្រាប់​អ្នក។','Premium',
'បន្ថែម​ម៉ាស៊ីន​កិន — អនុសាសន៍​ក្នុង​ឯកតា​អ្នក។','Tamper ស្ព្រីង និង​ស្វ័យប្រវត្តិ​ចូល​គំរូ។','រក្សា​គ្រាប់​អ្នក។ ប្ដូរ​កញ្ចប់ បន្ត​ពី​ដែល​ឈប់។','ដោះសោ​ប្រវត្តិ​ពេញ និង​និន្នាការ។','ប្រៀបធៀប​រាល់ shot នឹង​អ្នក​ល្អ​បំផុត។',
'បរិក្ខារ​អ្នក','ម៉ាស៊ីន​កិន tamper គ្រាប់។ អនុសាសន៍​ក្នុង​ឯកតា​អ្នក។','ប្រវត្តិ​ពេញ','រាល់ shot រក្សា។ នាំចេញ​នៅ​ពេល​ណា​ក៏​បាន។','ស្តង់ដារ​ផ្ទាល់ខ្លួន','ប្រៀបធៀប​រាល់ shot នឹង​អ្នក​ល្អ​បំផុត។',
'Brewmie តែ​ប៉ុណ្ណោះ','$6.99','កញ្ចប់​ជាមួយ Lazy Sous','$9.99','Dev៖ ដោះសោ​តាម dev pill។ មិន​មែន​ការ​ទិញ​ពិត​ទេ។',
'Premium','Shot ចាស់​ត្រូវ​បាន​រក្សា។ ប្រវត្តិ​ពេញ​ជាមួយ Premium។','ដោះសោ​ស្តង់ដារ​ផ្ទាល់ខ្លួន​ជាមួយ Premium។','ម៉ាស៊ីន​កិន​ទូទៅ។ Premium កែ​សម្រាប់​អ្នក។','Tamp ដោយ​ដៃ។ Premium បន្ថែម​ស្ព្រីង និង​ស្វ័យប្រវត្តិ។','Roast មធ្យម​ទូទៅ។ Premium តាមដាន​គ្រាប់​អ្នក។',
'រត់​ឧបករណ៍​ជំនួយ​សា​ឡើងវិញ','ឧបករណ៍​ជំនួយ','បន្ត →',
'ភាសា','ភាសា​បង្ហាញ','ធម្មតា','ភាសា​ផ្សេង','Brewmie រក​ភាសា​ដោយ​ស្វ័យប្រវត្តិ។ ជ្រើស​ផ្សេង​ទីនេះ។ ការ​បកប្រែ​ក្រៅ​ពី​ធម្មតា​អាច​មិន​ពេញលេញ និង​ត្រឡប់​ទៅ​អង់គ្លេស។','លើក​ចុង​ក្រោយ','អាន​គោល​ការណ៍​ឯកជន​ភាព​ពេញ',
'មើល​ទាំងអស់ ({count})','រាល់ shot ({count})','កែ Shot','ពេលវេលា','បរិមាណ','រសជាតិ','កម្លាំង','លុប','លុប shot នេះ? មិន​អាច​សង​វិញ។',
'Sweet spot អ្នក','ការ​កិន','អត្រា','ពី shot ល្អ​បំផុត {n} របស់​អ្នក','កត់ត្រា shot 85+ ដើម្បី​កំណត់ sweet spot។',
'កំណត់ត្រា​ផ្ទាល់​ខ្លួន','សប្តាហ៍​នេះ','បង្អួច​ពេលវេលា','មធ្យម {score}','មិនទាន់​មាន​ទិន្នន័យ','សកម្ម {count} ថ្ងៃ','នាំចេញ CSV','ដើម្បី​លុប​គណនី សូម​សរសេរ​ទៅ chef@lazysous.app'],

'kn': ['ಉಳಿಸಿ','ಮುಚ್ಚಿ','ರದ್ದು','ಒದಗಿಸಿದ್ದು','ಶಾಟ್‌ಗಳು ಜಗತ್ತಿನಲ್ಲಿ','ಮುಖಪುಟ',
'ಮೊದಲನ್ನು ಎಳೆಯಿರಿ.','ಶಾಟ್ {n}.','ದಿನ {n}.','ಕೊನೆಯ ಶಾಟ್: {score}. {tail}','ನಿಖರ.','ಹತ್ತಿರ.','ಒಂದು ಸರಿಪಡಿಸುವಿಕೆ.','ರೀಸೆಟ್ ಮಾಡಿ ಮತ್ತೆ.','ರೆಸಿಪಿ ಹೊಂದಿಸಿ. ಮುಖ್ಯವಾದದನ್ನು ಎಳೆಯಿರಿ.','ಎಳೆಯುತ್ತಲೇ ಇರಿ. ನಾವು ಕಲಿಯುತ್ತಿದ್ದೇವೆ.',
'ದಿನ {days} · ಇನ್ನೂ ವಿಶ್ರಾಂತಿ','ದಿನ {days} · ಶ್ರೇಷ್ಠ ವಿಂಡೋದಲ್ಲಿ','ದಿನ {days} · ಬೇಗ ಬಳಸಿ','ದಿನ {days} · ಹಳೆಯದು',
'ವಿಶ್ರಾಂತಿ','ಶ್ರೇಷ್ಠ ವಿಂಡೋದಲ್ಲಿ','ಬೇಗ ಬಳಸಿ','ಹಳೆಯದು',
'{temp}°C · ಆರ್ದ್ರತೆ {humidity}%','{temp}°C · ಆರ್ದ್ರತೆ {humidity}%','{temp}°C · ಆರ್ದ್ರತೆ {humidity}%',
'ನಿಮ್ಮ ಸಲಕರಣೆ.','ನಿಮ್ಮ ಸಲಕರಣೆ.','ನಿಮ್ಮ ಸಲಕರಣೆ.','ನೀವು ಸಿದ್ಧವಾದಾಗ.','ಡಯಲ್-ಇನ್ ಮಾಡಲು ಬೀಜಗಳನ್ನು ಸೇರಿಸಿ.','ನಿಮ್ಮ ಸಲಕರಣೆ ಹೊಂದಿಸಿ.','ಐದು ನಿಮಿಷ. ನಂತರ ಉತ್ತಮ ಶಾಟ್.',
'{count} ವಿಭಾಗ ಬಾಕಿ.','{count} ವಿಭಾಗ ಬಾಕಿ.',
'ಪ್ರತಿ ಶಾಟ್ ದಾಖಲಿಸಲಾಗಿದೆ.','ಒಂದು ಎಳೆಯಿರಿ. ದಾಖಲಿಸಲು ಪ್ರಾರಂಭಿಸುತ್ತೇವೆ.','ನಿಮ್ಮ ಸ್ಕೋರ್, ಗ್ರೈಂಡ್, ಡ್ರಿಫ್ಟ್.','{count} ಶಾಟ್. ಮುಂದುವರಿಸಿ.','{count} ಶಾಟ್. ಮುಂದುವರಿಸಿ.','{count} ಶಾಟ್. 5-ಶಾಟ್ ಸರಾಸರಿ {avg}.',
'ಒಂದು ಸ್ಪರ್ಶ. ಪಾಸ್‌ವರ್ಡ್ ಇಲ್ಲ.','Meta ಮೂಲಕ ಮುಂದುವರಿಸಿ','GitHub ಮೂಲಕ ಮುಂದುವರಿಸಿ','ಕೇವಲ ಅಡ್ಡಹೆಸರು. ಪಾಸ್‌ವರ್ಡ್ ಇಲ್ಲ.','ಅಡ್ಡಹೆಸರು ಆಯ್ಕೆಮಾಡಿ.','ನಿಮ್ಮ ಆಯ್ಕೆ. ಇದನ್ನು ಮಾತ್ರ ಉಳಿಸುತ್ತೇವೆ.','ಉದಾ. billy_bean','ಉಳಿಸಿ',
'{label} ಕಡಿಮೆ ಮಾಡಿ (ಸೂಕ್ಷ್ಮ)','{label} ಹೆಚ್ಚಿಸಿ (ಸೂಕ್ಷ್ಮ)','ಮೊದಲ ಶಾಟ್ ನಂತರ','ಒರಟು','3s ಹೆಚ್ಚು. ಒರಟಾಗಿ ರುಬ್ಬಿ.','ಎಳೆಯಿರಿ. ಲಾಗ್ ಮಾಡಿ. ಏನು ಬದಲಾಯಿಸಬೇಕೆಂದು ಹೇಳುತ್ತೇವೆ.','ಎಳೆಯಿರಿ. ಲಾಗ್ ಮಾಡಿ. ಮುಂದೆ ಏನು ಬದಲಾಯಿಸಬೇಕೆಂದು ಹೇಳುತ್ತೇವೆ.',
'{delta} {unit} ಕಡಿಮೆ','{delta} {unit} ಹೆಚ್ಚು','ಇಡಿ','ಗುರಿ {value} {unit}','ಮುಂದಿನ ಶಾಟ್‌ಗಾಗಿ ಬದಲಾಯಿಸಿ','ಮುಂದಿನ ಶಾಟ್‌ಗಾಗಿ ಇಡಿ','ಈ ಶಾಟ್',
'ವೈಯಕ್ತಿಕ ದಾಖಲೆ. ನಿಧಾನವಾಗಿ ಸವಿಯಿರಿ.','ಹಿಂದಿನದಕ್ಕಿಂತ +{delta}. ಏರುತ್ತಿದೆ.','ಹಿಂದಿನದಕ್ಕಿಂತ −{delta}. ರೀಸೆಟ್.','ಹಿಂದಿನಂತೆಯೇ. ಸ್ಥಿರ ಕೈ.','ಮೊದಲನೆಯದು ಮುಗಿಯಿತು. ಈಗ ಕಲಿಯೋಣ.',
'ನಿಲ್ಲಿಸಿ','ಶಾಟ್ ಉಳಿಸಿ','ಎಳೆಯುತ್ತಿದೆ','ಶಾಟ್ ಹಿಡಿಯಿರಿ','ಸಿದ್ಧರಾಗಿ',
'{seconds}s ಕಡಿಮೆ ಮತ್ತು {ml}ml ಹೆಚ್ಚು. ಸೂಕ್ಷ್ಮವಾಗಿ ರುಬ್ಬಿ.','{seconds}s ಹೆಚ್ಚು ಮತ್ತು {ml}ml ಕಡಿಮೆ. ಒರಟಾಗಿ ರುಬ್ಬಿ.',
'{primary} ಗ್ರೈಂಡರ್ ಅತ್ಯಂತ ಸೂಕ್ಷ್ಮ — ಡೋಸ್ ಹೆಚ್ಚಿಸಿ.','{primary} ಗ್ರೈಂಡರ್ ಅತ್ಯಂತ ಒರಟು — ಡೋಸ್ ಕಡಿಮೆ ಮಾಡಿ.',
'3 ಶಾಟ್ ಸೂಕ್ಷ್ಮ. +0.5g ಪ್ರಯತ್ನಿಸಿ.','3 ಶಾಟ್ ಒರಟು. −0.5g ಪ್ರಯತ್ನಿಸಿ.',
'ಗ್ರೈಂಡರ್ ಅತ್ಯಂತ ಸೂಕ್ಷ್ಮ. +0.5g ಹೆಚ್ಚಿನ ಪ್ರತಿರೋಧಕ್ಕೆ.','ಗ್ರೈಂಡರ್ ಅತ್ಯಂತ ಒರಟು. −0.5g ಕಡಿಮೆ ಪ್ರತಿರೋಧಕ್ಕೆ.',
'ತೆಳು','ಸಾಮಾನ್ಯ','ದಪ್ಪ','ಕ್ರೆಮಾ','ರುಚಿ','ಶಕ್ತಿ','ನಂತರ ರೇಟ್ ಮಾಡಿ','ರೇಟಿಂಗ್ ಉಳಿಸಿ',
'ಬರಿಸ್ಟಾ ಮೋಡ್','ಬರಿಸ್ಟಾ ಮೋಡ್ ಆಫ್','ಬರಿಸ್ಟಾ ಮೋಡ್','{count} ಶಾಟ್ · {mins} ನಿಮಿಷ',
'Brewmie Premium','ನಿಮಗಾಗಿ ಟ್ಯೂನ್ ಮಾಡಿದ Brewmie.','Premium',
'ಗ್ರೈಂಡರ್ ಸೇರಿಸಿ — ಶಿಫಾರಸುಗಳು ನಿಮ್ಮ ಯೂನಿಟ್‌ಗಳಲ್ಲಿ.','ಸ್ಪ್ರಿಂಗ್ ಮತ್ತು ಆಟೋ ಟ್ಯಾಂಪರ್‌ಗಳು ಮಾದರಿಗೆ ಸೇರುತ್ತವೆ.','ನಿಮ್ಮ ಬೀಜಗಳನ್ನು ಉಳಿಸಿ. ಬ್ಯಾಗ್ ಬದಲಿಸಿ, ಎಲ್ಲಿ ಬಿಟ್ಟಿದ್ದೀರೋ ಅಲ್ಲಿಂದ.','ಸಂಪೂರ್ಣ ಇತಿಹಾಸ ಮತ್ತು ಪ್ರವೃತ್ತಿ ಅನ್‌ಲಾಕ್ ಮಾಡಿ.','ಪ್ರತಿ ಶಾಟ್ ಅನ್ನು ನಿಮ್ಮ ಉತ್ತಮದೊಂದಿಗೆ ಹೋಲಿಸಿ.',
'ನಿಮ್ಮ ಸಲಕರಣೆ','ಗ್ರೈಂಡರ್, ಟ್ಯಾಂಪರ್, ಬೀಜಗಳು. ಶಿಫಾರಸುಗಳು ನಿಮ್ಮ ಯೂನಿಟ್‌ಗಳಲ್ಲಿ.','ಸಂಪೂರ್ಣ ಇತಿಹಾಸ','ಪ್ರತಿ ಶಾಟ್ ಉಳಿಯುತ್ತದೆ. ಬೇಕಾದಾಗ ಎಕ್ಸ್‌ಪೋರ್ಟ್.','ವೈಯಕ್ತಿಕ ಮಾನದಂಡಗಳು','ಪ್ರತಿ ಶಾಟ್ ಅನ್ನು ನಿಮ್ಮ ಉತ್ತಮದೊಂದಿಗೆ ಹೋಲಿಸಿ.',
'Brewmie ಮಾತ್ರ','$6.99','Lazy Sous ಬಂಡಲ್','$9.99','Dev: dev pill ಮೂಲಕ ಅನ್‌ಲಾಕ್. ನಿಜವಾದ ಖರೀದಿ ಅಲ್ಲ.',
'Premium','ಹಳೆಯ ಶಾಟ್ ಉಳಿದಿವೆ. Premium ನೊಂದಿಗೆ ಸಂಪೂರ್ಣ ಇತಿಹಾಸ.','Premium ನೊಂದಿಗೆ ವೈಯಕ್ತಿಕ ಮಾನದಂಡಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ.','ಸಾಮಾನ್ಯ ಗ್ರೈಂಡರ್. Premium ನಿಮಗೆ ಕ್ಯಾಲಿಬ್ರೇಟ್.','ಮ್ಯಾನ್ಯುಯಲ್ ಟ್ಯಾಂಪ್. Premium ಸ್ಪ್ರಿಂಗ್ ಮತ್ತು ಆಟೋ ಸೇರಿಸುತ್ತದೆ.','ಸಾಮಾನ್ಯ ಮಧ್ಯಮ ಹುರಿತ. Premium ನಿಮ್ಮ ಬೀಜಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡುತ್ತದೆ.',
'ಸೆಟಪ್ ವಿಜಾರ್ಡ್ ಮತ್ತೆ ರನ್','ಸೆಟಪ್','ಮುಂದುವರಿಸಿ →',
'ಭಾಷೆ','ಪ್ರದರ್ಶನ ಭಾಷೆ','ಸಾಮಾನ್ಯ','ಇತರ ಭಾಷೆಗಳು','Brewmie ಭಾಷೆಯನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪತ್ತೆ ಮಾಡುತ್ತದೆ. ಬೇರೆಯದನ್ನು ಇಲ್ಲಿ ಆಯ್ಕೆಮಾಡಿ. ಸಾಮಾನ್ಯದ ಹೊರಗಿನ ಭಾಷಾಂತರಗಳು ಅಪೂರ್ಣವಾಗಿರಬಹುದು ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ಗೆ ಮರಳುತ್ತವೆ.','ಕೊನೆಯ ಬಾರಿ','ಸಂಪೂರ್ಣ ಗೌಪ್ಯತಾ ನೀತಿ ಓದಿ',
'ಎಲ್ಲ ({count}) ನೋಡಿ','ಎಲ್ಲ ಶಾಟ್ ({count})','ಶಾಟ್ ಸಂಪಾದಿಸಿ','ಸಮಯ','ಪರಿಮಾಣ','ರುಚಿ','ಶಕ್ತಿ','ಅಳಿಸಿ','ಈ ಶಾಟ್ ಅಳಿಸಬೇಕೇ? ಹಿಂತಿರುಗಿಸಲಾಗದು.',
'ನಿಮ್ಮ ಸ್ವೀಟ್ ಸ್ಪಾಟ್','ಗ್ರೈಂಡ್','ಅನುಪಾತ','ನಿಮ್ಮ ಟಾಪ್ {n} ಶಾಟ್ ಗಳಿಂದ','ಸ್ವೀಟ್ ಸ್ಪಾಟ್ ಹೊಂದಿಸಲು 85+ ಶಾಟ್ ದಾಖಲಿಸಿ.',
'ವೈಯಕ್ತಿಕ ಶ್ರೇಷ್ಠ','ಈ ವಾರ','ಸಮಯ ವಿಂಡೋ','ಸರಾಸರಿ {score}','ಇನ್ನೂ ಡೇಟಾ ಇಲ್ಲ','{count} ದಿನ ಸಕ್ರಿಯ','CSV ಎಕ್ಸ್‌ಪೋರ್ಟ್','ಖಾತೆ ಅಳಿಸಲು chef@lazysous.app ಗೆ ಇಮೇಲ್'],

'ml': ['സേവ് ചെയ്യുക','അടയ്ക്കുക','റദ്ദാക്കുക','നൽകുന്നു','ഷോട്ടുകൾ ലോകത്ത്','ഹോം',
'ആദ്യത്തെത് വലിക്കുക.','ഷോട്ട് {n}.','ദിവസം {n}.','അവസാന ഷോട്ട്: {score}. {tail}','ശരി.','അടുത്ത്.','ഒരു ക്രമീകരണം.','റീസെറ്റ് ചെയ്ത് വീണ്ടും.','റെസിപ്പി സജ്ജമാക്കുക. പ്രധാനപ്പെട്ടത് വലിക്കുക.','വലിച്ചുകൊണ്ടിരിക്കുക. ഞങ്ങൾ പഠിക്കുന്നു.',
'ദിവസം {days} · ഇപ്പോഴും വിശ്രമത്തിൽ','ദിവസം {days} · മികച്ച വിൻഡോയിൽ','ദിവസം {days} · ഉടൻ ഉപയോഗിക്കുക','ദിവസം {days} · പഴയത്',
'വിശ്രമത്തിൽ','മികച്ച വിൻഡോയിൽ','ഉടൻ ഉപയോഗിക്കുക','പഴയത്',
'{temp}°C · ഈർപ്പം {humidity}%','{temp}°C · ഈർപ്പം {humidity}%','{temp}°C · ഈർപ്പം {humidity}%',
'നിങ്ങളുടെ ഉപകരണം.','നിങ്ങളുടെ ഉപകരണം.','നിങ്ങളുടെ ഉപകരണം.','നിങ്ങൾ തയ്യാറാകുമ്പോൾ.','ഡയൽ ഇൻ ചെയ്യാൻ ബീൻസ് ചേർക്കുക.','നിങ്ങളുടെ ഉപകരണം സജ്ജമാക്കുക.','അഞ്ച് മിനിറ്റ്. ശേഷം മികച്ച ഷോട്ടുകൾ.',
'{count} വിഭാഗം ബാക്കി.','{count} വിഭാഗങ്ങൾ ബാക്കി.',
'ഓരോ ഷോട്ടും രേഖപ്പെടുത്തിയിരിക്കുന്നു.','ഒന്ന് വലിക്കുക. ട്രാക്കിംഗ് ആരംഭിക്കാം.','നിങ്ങളുടെ സ്കോർ, ഗ്രൈൻഡ്, ഡ്രിഫ്റ്റ്.','{count} ഷോട്ട്. തുടരുക.','{count} ഷോട്ടുകൾ. തുടരുക.','{count} ഷോട്ടുകൾ. 5-ഷോട്ട് ശരാശരി {avg}.',
'ഒറ്റ ടാപ്പ്. പാസ്‌വേഡില്ല.','Meta ഉപയോഗിച്ച് തുടരുക','GitHub ഉപയോഗിച്ച് തുടരുക','വിളിപ്പേര് മാത്രം. പാസ്‌വേഡില്ല.','ഒരു വിളിപ്പേര് തിരഞ്ഞെടുക്കുക.','നിങ്ങളുടെ തിരഞ്ഞെടുപ്പ്. ഇതുമാത്രമേ സേവ് ചെയ്യൂ.','ഉദാ. billy_bean','സേവ്',
'{label} കുറയ്ക്കുക (സൂക്ഷ്മം)','{label} കൂട്ടുക (സൂക്ഷ്മം)','നിങ്ങളുടെ ആദ്യ ഷോട്ടിന് ശേഷം','പരുക്കൻ','3s നീളം. പരുക്കനായി പൊടിക്കുക.','വലിക്കുക. ലോഗ് ചെയ്യുക. എന്ത് മാറ്റണമെന്ന് പറയാം.','വലിക്കുക. ലോഗ് ചെയ്യുക. അടുത്ത തവണ എന്ത് മാറ്റണമെന്ന് പറയാം.',
'{delta} {unit} കുറവ്','{delta} {unit} കൂടുതൽ','സൂക്ഷിക്കുക','ലക്ഷ്യം {value} {unit}','അടുത്ത ഷോട്ടിന് മാറ്റം','അടുത്ത ഷോട്ടിന് സൂക്ഷിക്കുക','ഈ ഷോട്ട്',
'വ്യക്തിഗത റെക്കോർഡ്. പതുക്കെ ആസ്വദിക്കുക.','മുമ്പത്തേക്കാൾ +{delta}. ഉയരുന്നു.','മുമ്പത്തേക്കാൾ −{delta}. റീസെറ്റ്.','മുമ്പത്തേത് പോലെ. ഉറച്ച കൈ.','ആദ്യത്തേത് ചെയ്തു. ഇപ്പോൾ പഠിക്കാം.',
'നിർത്തുക','ഷോട്ട് സേവ്','വലിക്കുന്നു','ഷോട്ട് ക്യാപ്ചർ','തയ്യാറാകുക',
'{seconds}s കുറവ് {ml}ml കൂടുതൽ. സൂക്ഷ്മമായി പൊടിക്കുക.','{seconds}s കൂടുതൽ {ml}ml കുറവ്. പരുക്കനായി പൊടിക്കുക.',
'{primary} ഗ്രൈൻഡർ ഏറ്റവും സൂക്ഷ്മത്തിൽ — ഡോസ് കൂട്ടുക.','{primary} ഗ്രൈൻഡർ ഏറ്റവും പരുക്കനിൽ — ഡോസ് കുറയ്ക്കുക.',
'3 ഷോട്ട് സൂക്ഷ്മം. +0.5g പരീക്ഷിക്കുക.','3 ഷോട്ട് പരുക്കൻ. −0.5g പരീക്ഷിക്കുക.',
'ഗ്രൈൻഡർ ഏറ്റവും സൂക്ഷ്മത്തിൽ. കൂടുതൽ പ്രതിരോധത്തിന് +0.5g.','ഗ്രൈൻഡർ ഏറ്റവും പരുക്കനിൽ. കുറവ് പ്രതിരോധത്തിന് −0.5g.',
'നേർത്ത','സാധാരണ','കട്ടി','ക്രീമ','രുചി','ശക്തി','പിന്നീട് റേറ്റ് ചെയ്യുക','റേറ്റിംഗ് സേവ്',
'ബരിസ്റ്റ മോഡ്','ബരിസ്റ്റ മോഡ് ഓഫ്','ബരിസ്റ്റ മോഡ്','{count} ഷോട്ടുകൾ · {mins} മിനിറ്റ്',
'Brewmie Premium','നിങ്ങൾക്കായി ട്യൂൺ ചെയ്ത Brewmie.','Premium',
'നിങ്ങളുടെ ഗ്രൈൻഡർ ചേർക്കുക — ശുപാർശകൾ നിങ്ങളുടെ യൂണിറ്റിൽ.','സ്പ്രിംഗ്, ഓട്ടോ ടാമ്പറുകൾ മോഡലിലേക്ക്.','നിങ്ങളുടെ ബീൻസ് സൂക്ഷിക്കുക. ബാഗ് മാറ്റി, അവിടെ നിന്ന് തുടരുക.','മുഴുവൻ ചരിത്രവും ട്രെൻഡുകളും അൺലോക്ക്.','എല്ലാ ഷോട്ടും നിങ്ങളുടെ മികച്ചതുമായി താരതമ്യം.',
'നിങ്ങളുടെ ഉപകരണം','ഗ്രൈൻഡർ, ടാമ്പർ, ബീൻസ്. ശുപാർശകൾ നിങ്ങളുടെ യൂണിറ്റിൽ.','മുഴുവൻ ചരിത്രം','ഓരോ ഷോട്ടും സേവ്. എപ്പോൾ വേണമെങ്കിലും എക്സ്പോർട്ട്.','വ്യക്തിഗത ബെഞ്ച്മാർക്കുകൾ','എല്ലാ ഷോട്ടും നിങ്ങളുടെ മികച്ചതുമായി താരതമ്യം.',
'Brewmie മാത്രം','$6.99','Lazy Sous ബണ്ടിൽ','$9.99','Dev: dev pill വഴി അൺലോക്ക്. യഥാർത്ഥ വാങ്ങലല്ല.',
'Premium','പഴയ ഷോട്ടുകൾ സേവ് ചെയ്തിരിക്കുന്നു. Premium-നൊപ്പം മുഴുവൻ ചരിത്രം.','Premium-നൊപ്പം വ്യക്തിഗത ബെഞ്ച്മാർക്കുകൾ അൺലോക്ക്.','പൊതുവായ ഗ്രൈൻഡർ. Premium നിങ്ങൾക്കായി കാലിബ്രേറ്റ്.','മാനുവൽ ടാമ്പ്. Premium സ്പ്രിംഗ്, ഓട്ടോ ചേർക്കും.','പൊതുവായ മധ്യമം റോസ്റ്റ്. Premium നിങ്ങളുടെ ബീൻസ് ട്രാക്ക്.',
'സെറ്റപ്പ് വിസാർഡ് വീണ്ടും','സെറ്റപ്പ്','തുടരുക →',
'ഭാഷ','ഡിസ്പ്ലേ ഭാഷ','സാധാരണ','മറ്റ് ഭാഷകൾ','Brewmie ഭാഷ സ്വയം കണ്ടെത്തുന്നു. ഇവിടെ വേറൊന്ന് തിരഞ്ഞെടുക്കുക. സാധാരണത്തിന് പുറത്തുള്ള പരിഭാഷകൾ അപൂർണ്ണമാകാം, ഇംഗ്ലീഷിലേക്ക് മടങ്ങാം.','കഴിഞ്ഞ തവണ','മുഴുവൻ സ്വകാര്യതാ നയം വായിക്കുക',
'എല്ലാം ({count}) കാണുക','എല്ലാ ഷോട്ടുകൾ ({count})','ഷോട്ട് എഡിറ്റ്','സമയം','വ്യാപ്തം','രുചി','ശക്തി','ഇല്ലാതാക്കുക','ഈ ഷോട്ട് ഇല്ലാതാക്കണോ? പുനഃസ്ഥാപിക്കാനാവില്ല.',
'നിങ്ങളുടെ സ്വീറ്റ് സ്പോട്ട്','ഗ്രൈൻഡ്','അനുപാതം','നിങ്ങളുടെ ടോപ് {n} ഷോട്ടുകളിൽ നിന്ന്','സ്വീറ്റ് സ്പോട്ട് സജ്ജമാക്കാൻ 85+ ഷോട്ട് ലോഗ് ചെയ്യുക.',
'വ്യക്തിഗത മികച്ചത്','ഈ ആഴ്ച','സമയ വിൻഡോ','ശരാശരി {score}','ഡാറ്റ ഇല്ല','{count} ദിവസം സജീവം','CSV എക്സ്പോർട്ട്','അക്കൗണ്ട് ഡിലീറ്റ് ചെയ്യാൻ chef@lazysous.app ലേക്ക് ഇമെയിൽ'],

'mn': ['Хадгалах','Хаах','Цуцлах','Тэжээдэг','шот дэлхий даяар','Нүүр',
'Эхнийхээ татаач.','Шот {n}.','Өдөр {n}.','Сүүлийн шот: {score}. {tail}','Цогцолбор.','Ойрхон.','Нэг тохируулга.','Шинээр эхэл.','Жороо тохируул. Чухлыг нь татаач.','Үргэлжлүүл татах. Бид сурч байна.',
'Өдөр {days} · одоо ч амарч байна','Өдөр {days} · цонхонд','Өдөр {days} · удахгүй хэрэглээрэй','Өдөр {days} · хуучирсан',
'Амарч байна','Цонхонд','Удахгүй хэрэглээрэй','Хуучирсан',
'{temp}°C · чийг {humidity}%','{temp}°C · чийг {humidity}%','{temp}°C · чийг {humidity}%',
'Чиний тоног.','Чиний тоног.','Чиний тоног.','Бэлэн болсон үед.','Тохируулахын тулд буурцаг нэм.','Тоногоо тохируул.','Таван минут. Дараа нь илүү сайн шот.',
'{count} хэсэг үлдсэн.','{count} хэсэг үлдсэн.',
'Шот бүрийг бүртгэдэг.','Нэгийг нь татаач. Бүртгэж эхэлнэ.','Чиний оноо, тээрэмдэлт, хазайлт.','{count} шот. Үргэлжлүүл.','{count} шот. Үргэлжлүүл.','{count} шот. 5-ийн дундаж {avg}.',
'Нэг товшилт. Нууц үг үгүй.','Meta-р үргэлжлүүлэх','GitHub-р үргэлжлүүлэх','Зөвхөн хочин нэр. Нууц үг үгүй.','Хочин нэр сонгох.','Чинийх. Үүнийг л хадгална.','жнь billy_bean','Хадгалах',
'{label}-г бага зэрэг бууруул','{label}-г бага зэрэг нэмэгдүүл','Эхний шотын дараа','Илүү бүдүүн','3с урт. Бүдүүн тээрэмд.','Татаач. Бүртгэ. Юу солихыг хэлнэ.','Татаач. Бүртгэ. Дараагийн удаа юу солихыг хэлнэ.',
'{delta} {unit} дутуу','{delta} {unit} илүү','Үлдээ','зорилго {value} {unit}','Дараагийн шотод солих','Дараагийн шотод үлдээ','Энэ шот',
'Хувийн рекорд. Удаан амт.','Өмнөхөөс +{delta}. Өсөж байна.','Өмнөхөөс −{delta}. Шинэчлэх.','Өмнөхтэй адил. Тогтвортой гар.','Эхнийх дууссан. Одоо сурна.',
'ЗОГСООХ','ШОТЫГ ХАДГАЛАХ','Татаж байна','Шотыг бүртгэ','Бэлэн бай',
'{seconds}с богино, {ml}мл илүү. Жижигрүү тээрэмд.','{seconds}с урт, {ml}мл дутуу. Бүдүүн тээрэмд.',
'{primary} Тээрэм хамгийн жижигт — тунг нэмэгдүүл.','{primary} Тээрэм хамгийн бүдүүнд — тунг бууруул.',
'3 шот жижигрэв. +0.5г оролд.','3 шот бүдүүлэв. −0.5г оролд.',
'Тээрэм хамгийн жижигт. Эсэргүүцэл нэмэхэд +0.5г.','Тээрэм хамгийн бүдүүнд. Эсэргүүцэл багасахад −0.5г.',
'Нимгэн','Энгийн','Зузаан','Крема','Амт','Хүч','Дараа үнэлэх','Үнэлгээ хадгалах',
'Барист горим','Барист горимыг унтраах','Барист горим','{count} шот · {mins} мин',
'Brewmie Premium','Brewmie чинийхээр.','Premium',
'Тээрмээ нэм — зөвлөмж чиний нэгжээр.','Пүрш ба авто тампер моделд орно.','Буурцагаа хадгал. Цүнхээ соль, тэндээсээ үргэлжлүүл.','Бүтэн түүх, чиг хандлагыг нээ.','Шот тус бүрийг хамгийн сайнтайгаа харьцуул.',
'Чиний тоног','Тээрэм, тампер, буурцаг. Зөвлөмж чиний нэгжээр.','Бүтэн түүх','Шот бүр хадгалагдана. Хүссэн үедээ экспортлох.','Хувийн жишиг','Шот тус бүрийг хамгийн сайнтайгаа харьцуул.',
'Зөвхөн Brewmie','$6.99','Lazy Sous-тай багц','$9.99','Dev: dev pill-ээр нээгдэнэ. Жинхэнэ худалдан авалт биш.',
'Premium','Хуучин шотууд хадгалагдсан. Premium-тэй бүтэн түүх.','Premium-тэй хувийн жишгүүдийг нээ.','Ерөнхий тээрэм. Premium чиньхээр тохируулна.','Гар тампер. Premium пүрш, авто нэмнэ.','Ерөнхий дунд шарсан. Premium буурцагуудыг хянана.',
'Тохиргооны зөвлөхийг дахин','Тохиргооны зөвлөх','Үргэлжлүүлэх →',
'Хэл','Дэлгэцийн хэл','Түгээмэл','Бусад хэлүүд','Brewmie хэлийг автоматаар таних. Энд өөр сонго. Түгээмэлээс гадуурх орчуулга бүрэн биш байж болох ба англиар буцна.','Сүүлийн удаа','Бүрэн нууцлалын бодлогыг унш',
'Бүгдийг ({count}) харах','Бүх шот ({count})','Шот засах','Хугацаа','Эзлэхүүн','Амт','Хүч','Устгах','Энэ шотыг устгах уу? Буцаах боломжгүй.',
'Чиний сайн цэг','тээрэмдэлт','харьцаа','хамгийн сайн {n} шотоос','85+ шот бүртгэж сайн цэгээ тогтоо.',
'Хувийн дээд амжилт','Энэ долоо хоног','Хугацааны цонх','дундж. {score}','өгөгдөл алга','{count} өдөр идэвхтэй','CSV экспорт','Бүртгэлийг устгах: chef@lazysous.app'],

'mr': ['जतन करा','बंद करा','रद्द','समर्थक','शॉट जागतिक स्तरावर','मुख्यपृष्ठ',
'पहिला ओढा.','शॉट {n}.','दिवस {n}.','शेवटचा शॉट: {score}. {tail}','अचूक.','जवळ.','एक समायोजन.','रीसेट करा आणि पुन्हा.','कृती सेट करा. महत्त्वाचे ओढा.','ओढत राहा. आम्ही शिकत आहोत.',
'दिवस {days} · अजून विश्रांती','दिवस {days} · खिडकीत','दिवस {days} · लवकर वापरा','दिवस {days} · जुने',
'विश्रांती','खिडकीत','लवकर वापरा','जुने',
'{temp}°C · आर्द्रता {humidity}%','{temp}°C · आर्द्रता {humidity}%','{temp}°C · आर्द्रता {humidity}%',
'तुमचे साधन.','तुमचे साधन.','तुमचे साधन.','तुम्ही तयार झालात की.','डायल इन करण्यासाठी बीन्स जोडा.','तुमचे साधन सेट करा.','पाच मिनिटे. नंतर चांगले शॉट.',
'{count} विभाग बाकी.','{count} विभाग बाकी.',
'प्रत्येक शॉट नोंदविला.','एक ओढा. आम्ही नोंदवायला सुरुवात करतो.','तुमचा स्कोअर, ग्राइंड, ड्रिफ्ट.','{count} शॉट. सुरू ठेवा.','{count} शॉट. सुरू ठेवा.','{count} शॉट. 5-शॉट सरासरी {avg}.',
'एक टॅप. पासवर्ड नाही.','Meta सह सुरू','GitHub सह सुरू','फक्त टोपणनाव. पासवर्ड नाही.','टोपणनाव निवडा.','तुमच्या मर्जीचे. हेच फक्त जतन करतो.','उदा. billy_bean','जतन करा',
'{label} कमी करा (बारीक)','{label} वाढवा (बारीक)','तुमच्या पहिल्या शॉटनंतर','जाडसर','3s जास्त. जाडसर दळा.','ओढा. नोंद. काय बदलायचे ते सांगू.','ओढा. नोंद. पुढच्या वेळी काय बदलायचे ते सांगू.',
'{delta} {unit} कमी','{delta} {unit} जास्त','तसेच ठेवा','लक्ष्य {value} {unit}','पुढच्या शॉटसाठी बदला','पुढच्या शॉटसाठी ठेवा','हा शॉट',
'वैयक्तिक विक्रम. हळू चाखा.','मागच्यापेक्षा +{delta}. वाढत आहे.','मागच्यापेक्षा −{delta}. रीसेट.','मागच्यासारखे. स्थिर हात.','पहिला झाला. आता शिकू.',
'थांबवा','शॉट जतन','ओढत आहे','शॉट कॅप्चर करा','तयार व्हा',
'{seconds}s कमी आणि {ml}ml जास्त. बारीक दळा.','{seconds}s जास्त आणि {ml}ml कमी. जाडसर दळा.',
'{primary} ग्राइंडर सर्वात बारीक — डोस वाढवा.','{primary} ग्राइंडर सर्वात जाडसर — डोस कमी करा.',
'3 शॉट अधिक बारीक. +0.5g वापरून पहा.','3 शॉट अधिक जाडसर. −0.5g वापरून पहा.',
'ग्राइंडर सर्वात बारीक. अधिक प्रतिकारासाठी +0.5g.','ग्राइंडर सर्वात जाडसर. कमी प्रतिकारासाठी −0.5g.',
'पातळ','सामान्य','दाट','क्रेमा','चव','तीव्रता','नंतर रेट','रेटिंग जतन',
'बरिस्ता मोड','बरिस्ता मोड बंद','बरिस्ता मोड','{count} शॉट · {mins} मिनिटे',
'Brewmie Premium','तुमच्यासाठी ट्यून केलेले Brewmie.','Premium',
'ग्राइंडर जोडा — शिफारसी तुमच्या युनिटमध्ये.','स्प्रिंग आणि ऑटो टॅम्पर मॉडेलमध्ये.','तुमच्या बीन्स जतन करा. पिशवी बदला, सोडलेल्या जागेपासून पुढे.','संपूर्ण इतिहास आणि ट्रेंड अनलॉक.','प्रत्येक शॉट तुमच्या सर्वोत्तमशी तुलना.',
'तुमचे साधन','ग्राइंडर, टॅम्पर, बीन्स. शिफारसी तुमच्या युनिटमध्ये.','संपूर्ण इतिहास','प्रत्येक शॉट जतन. कधीही निर्यात.','वैयक्तिक मापदंड','प्रत्येक शॉट तुमच्या सर्वोत्तमशी तुलना.',
'फक्त Brewmie','$6.99','Lazy Sous बंडल','$9.99','Dev: dev pill द्वारे अनलॉक. खरी खरेदी नाही.',
'Premium','जुने शॉट जतन. Premium सह संपूर्ण इतिहास.','Premium सह वैयक्तिक मापदंड अनलॉक.','सामान्य ग्राइंडर. Premium तुमच्यासाठी कॅलिब्रेट.','मॅन्युअल टॅम्प. Premium स्प्रिंग आणि ऑटो जोडते.','सामान्य मध्यम भाजणी. Premium तुमच्या बीन्सचा मागोवा घेते.',
'सेटअप विझार्ड पुन्हा चालवा','सेटअप','सुरू ठेवा →',
'भाषा','प्रदर्शन भाषा','सामान्य','इतर भाषा','Brewmie भाषा आपोआप ओळखते. दुसरी इथे निवडा. सामान्यबाहेरील भाषांतर अपूर्ण असू शकते आणि इंग्रजीत परत येते.','शेवटची वेळ','संपूर्ण गोपनीयता धोरण वाचा',
'सर्व ({count}) पहा','सर्व शॉट ({count})','शॉट संपादित','वेळ','खंड','चव','तीव्रता','हटवा','हा शॉट हटवायचा? परत मिळणार नाही.',
'तुमचा स्वीट स्पॉट','ग्राइंड','गुणोत्तर','तुमच्या टॉप {n} शॉटमधून','स्वीट स्पॉट सेट करण्यासाठी 85+ शॉट नोंद करा.',
'वैयक्तिक सर्वोत्तम','या आठवड्यात','वेळ खिडकी','सरासरी {score}','डेटा नाही','{count} दिवस सक्रिय','CSV निर्यात','खाते हटवण्यासाठी chef@lazysous.app ला ईमेल'],
}


def set_nested(d, key, value):
    parts = key.split('.')
    cur = d
    for p in parts[:-1]:
        if p not in cur or not isinstance(cur[p], dict):
            cur[p] = {}
        cur = cur[p]
    cur[parts[-1]] = value


def main():
    assert len(KEYS) == 151, f'KEYS has {len(KEYS)} entries'
    for locale, vals in LOCALES.items():
        if len(vals) != 151:
            print(f'  SKIP {locale}: {len(vals)} values, expected 151')
            continue
        path = TR / f'{locale}.json'
        existing = json.loads(path.read_text(encoding='utf-8'))
        for k, v in zip(KEYS, vals):
            set_nested(existing, k, v)
        path.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        print(f'{locale}: filled {len(vals)} keys')


if __name__ == '__main__':
    main()
